### ISSUE TITLE
charts text content not support emoji display

### ISSUE THREAD

**Issue by lly7690** [syncfusion/flutter-widgets#1017]
charts' text content not support emoji display,for example:
<img width="499" alt="image" src="https://user-images.githubusercontent.com/17976067/209921177-bf9633c8-3c56-4d75-b641-85f00cb690df.png">

**Comment by Yuvaraj-Gajaraj** [comment]
Hi,



Your requirement can be achieved with the help of the [axisLabelFormatter](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/axisLabelFormatter.html) callback in the [ChartAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis-class.html), which helps you to modify the axis label text. Here you can give the Unicode character of your emoji instead of text. We have shared the code snippet and sample below for your reference. Also shared the Unicode value of all the emoji below.



Reference link for emoji: https://en.wikipedia.org/wiki/Emoji#Unicode_blocks



Code snippet:
```dart
SfCartesianChart(
  primaryXAxis: CategoryAxis(
    axisLabelFormatter: (args) {
      return ChartAxisLabel(
          String.fromCharCode(int.parse('1F601', radix: 16)),
          args.textStyle);
    },
  ),
)
```
Screenshot:

![image](https://user-images.githubusercontent.com/61863686/210069306-0d3b6ed6-a4b9-4738-b4d0-645ad3ab0a88.png)

Sample: 
[i427424.zip](https://github.com/syncfusion/flutter-widgets/files/10324622/i427424.zip)

**Comment by lly7690** [comment]
Thank you for your reply,but our project is based on flutter sdk 2.5.3 now,can't use your new version yet,we will try it on our next flutter sdk update.:)
