### ISSUE TITLE
[SFRadialGauge][BUG] Needle pointer is not shown

### ISSUE THREAD

**Issue by alihabbash** [syncfusion/flutter-widgets#102]
It's a **bug** that happens when the gauge animation set to true and the value of the pointer is equal to minimum
for example, this is what happens when the value is set to -20 and the animation is true:

![Screenshot_1609262895](https://user-images.githubusercontent.com/17434665/103302803-2d4d4100-4a0d-11eb-9d05-0b1c2516cd79.png)

when I set the value of the pointer to -19.9 or when I set the animation to false the needle shown is expected:

![Screenshot_1609263508](https://user-images.githubusercontent.com/17434665/103302928-743b3680-4a0d-11eb-8f8b-2ad8d11a1f3f.png)

It seems that the bug is appeared when the value of the pointer <= minimum and the animation is activated

**Comment by SriramKiranSenthilkumar** [comment]
Hi @alihabbash,

Greetings from Syncfusion. We have analyzed your scenario with the provided information at our end and we are able to replicate the reported issue regarding the needle pointer is not showing when the value is lesser than or equal to minimum axis value. We will consider this as a bug and will include the fix for the reported issue in our upcoming weekly patch release which is expected to be rolled out by the 2nd week of January. We will update you once the release is rolled and we appreciate your patience until then.

Regards,
Sriram Kiran

**Comment by Dharanipalani** [comment]
Hi @alihabbash,

We are happy to inform you that the reported issue has been fixed in our latest version **v18.4.34**. Now the needle pointer will be visible when its value is lesser or equal to the axis minimum value. Please upgrade our gauges to the latest version from the following link.

Latest version:  [https://pub.dev/packages/syncfusion_flutter_gauges/versions/18.4.34](url)

Thanks,
Dharanitharan. P
