### ISSUE TITLE
I can't update the view of month view when I use cellbuilder.

### ISSUE THREAD

**Issue by 2e2ee95304418f96** [syncfusion/flutter-widgets#1026]
When I use cellBuilder to custom the cell, I want to update the cell view with GetX when data changed, but the view didn't change .I am sure that the view was triggerred to change.But nothing happen. But when I call the method "set selectionDate" , the view changed correctly. Is that my problem?

**Comment by MuniappanSubramanian** [comment]
We have analyzed your requirements and implemented the Flutter Calendar using **GetX**. We created the class UpdateData by extending the **GetXController** and then had the method **updateItem** inside this class. You should wrap your widget in the **GetBuilder** widget if you want to access the method in the UpdateData class. We generated the data for the calendar appointments in this updateItem method, and then, instead of calling **setState**, we just called **update()**, which will update the Flutter calendar. 

We have achieved this in the button click, when you tapped the update button it will call the updateItem method and will refresh the calendar with appointment data.  

`onPressed: () {   
 final controller = Get.put(UpdateData());    
controller.updateItem();    
// Assigned the data source    
dataSource = controller.calendarData;
},` 

We have prepared a sample for the same, please find the attached sample.
[calendar.zip](https://github.com/syncfusion/flutter-widgets/files/10389668/calendar.zip)
