### ISSUE TITLE
Treemap tooltip position customizablity? 

### ISSUE THREAD

**Issue by 0x0-14** [syncfusion/flutter-widgets#1029]

**Comment by LokeshPalani** [comment]
Hi @0x0-14,

You can achieve your requirement by using the [tooltipSettings](https://pub.dev/documentation/syncfusion_flutter_treemap/latest/treemap/SfTreemap/tooltipSettings.html) property in the [SfTreemap](https://pub.dev/documentation/syncfusion_flutter_treemap/latest/treemap/SfTreemap-class.html). This allows you to customize the appearance of the tooltip. We have shared user guide documentation for your reference.

UG,

https://help.syncfusion.com/flutter/treemap/tooltip#tooltip-for-the-tiles

If the provided solution does not satisfy your requirement, we kindly request that you share more detailed information, including screenshots or screen recordings, so that we can assist you more effectively.


Regards,
Lokesh.
