### ISSUE TITLE
Paginated DataGrid with GridWidgetColumn problem!

### ISSUE THREAD

**Issue by svsno1** [syncfusion/flutter-widgets#103]
Hi,

I has a DataGridSource data that containing a bool column.
This is my cellBuilder: (BuildContext context, GridColumn column, int rowIndex) {
                          if (rowIndex >= 0) {
                            final value = data.paginatedData[rowIndex][column.mappingName];
                            return Checkbox(value: value);
                          } else
                            return null;
                        }

It works correctly if I don't sort the data.
When I sort the data on the other column, the bool column doesn't change because the data.paginatedData contains unsorted data.
I know the sorted data is stored in _effectiveDataSource, but it's a private variable.

How can I use the GridWidgetColumn base on its value.

Thanks!

**Comment by NeelakandanKannan** [comment]
Hi @svsno1 ,

Thanks for contacting Syncfusion support.

If you want set the values for widgets based on the currently sorted order, you have to use the **DataGridSource[index]** indexer instead of the datasource collection which you set in dataSource property of DataGridSource. DataGrid provides the inner sorted list collection in the DataGridSource[index] indexer. 

The below example shows how to load image for widgets based from DataGridSource[index].

```dart
@override

  Widget build(BuildContext context) {

    return Scaffold(

        appBar: AppBar(title: Text('Syncfusion Flutter DataGrid')),

        body: SfDataGrid(

            allowSorting: true,

            source: _employeeDataSource,

            columnWidthMode: ColumnWidthMode.auto,

            cellBuilder:

                (BuildContext context, GridColumn column, int rowIndex) {

              return Container(

                padding: const EdgeInsets.all(3),

                child: _employeeDataSource[rowIndex].dealer,

              );

            },

            columns: _columns));

  }
```

You can also refer the below forum,
https://www.syncfusion.com/forums/159317/images-dont-move-when-other-columns-are-sorted

**Comment by svsno1** [comment]
Thanks so much!
