### ISSUE TITLE
[syncfusion_flutter_charts] Breaking SplineSeries line on empty points

### ISSUE THREAD

**Issue by Ilya-Vys** [syncfusion/flutter-widgets#1043]
I need to break SplineSeries line on empty values. DateTimeCategoryAxis cuts off that interval, but i need to show it. EmptyPointSettings color also doesn't change empty values line color( i tried to set it as transparent to hide). Is there any way to achieve it?

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @Ilya-Vys,

Your requirement can be achieved with the help of the [pointColorMapper](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianChartPoint/pointColorMapper.html) property in the [SplineSeries](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SplineSeries-class.html). Here you can set the [emptyPointSettings](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianSeries/emptyPointSettings.html) mode to [average](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/EmptyPointMode.html) and then map the color value for the point based on the value. If the y-value is null, assign the desired empty point color; otherwise, set it to null. This will work as you expect. We have shared the code snippet and sample below for your reference.

**Note:** If you have an x value as null, then the point won't display in the chart and the empty point mode will not work.

Code snippet:
```dart
SplineSeries<ChartSampleData, DateTime>(
  dataSource: chartData!,
  pointColorMapper: (ChartSampleData sales, _) =>
      sales.y == null ? Colors.red : null,
  emptyPointSettings: EmptyPointSettings(mode: EmptyPointMode.average),
  xValueMapper: (ChartSampleData sales, _) => sales.x,
  yValueMapper: (ChartSampleData sales, _) => sales.y,
),
```

Screenshot:

![image](https://user-images.githubusercontent.com/61863686/214020585-aca4b687-cc5b-45fa-a955-2e75db3fd600.png)





If the above-shared solution does not meet your requirements then, please share more information on your requirement in detail, along with screenshots or screen recordings. This will help us assist you in a better way.

**Comment by Ilya-Vys** [comment]
Thank's a lot, that solution works))
