### ISSUE TITLE
A4 paper size not working

### ISSUE THREAD

**Issue by ahmadbintariq4u** [syncfusion/flutter-widgets#1054]
I'm trying to set the paper size to a4 with the default code, but every paper size is working except papera4 and I'm using office 2016 professional

**Comment by irfanajaffer** [comment]
We have checked the reported issue with the provided details on our end, and it working properly on our end. 

code snippet used on our end:
`//Create a new PDF documentation
PdfDocument document = PdfDocument();

//Set the page size
document.pageSettings.size = PdfPageSize.a4;

//Draw the text by adding page to the document
document.pages.add().graphics.drawString(
    'Hello World!!!', PdfStandardFont(PdfFontFamily.helvetica, 27),
    brush: PdfBrushes.mediumVioletRed,
    bounds: const Rect.fromLTWH(170, 100, 0, 0));

//Save and dispose the PDF document
File('Output.pdf').writeAsBytes(await document.save());
document.dispose();`

can you please confirm whether you have used the same code on your end? we request you to share the output pdf and the simple sample to reporduce the issue. So that we can assist with you further in this

**Comment by ahmadbintariq4u** [comment]
Thanks for you efforts.
