### ISSUE TITLE
[syncfusion_flutter_calendar] Missing special 2-day span case.

### ISSUE THREAD

**Issue by pauldemarco** [syncfusion/flutter-widgets#106]
The following are Google Calendar screenshots.

I'm assuming this is the goal for syncfusion flutter calendar as well.

The calendar treats an appointment date range 3 different ways:

### Single day:

<img src="https://user-images.githubusercontent.com/16725750/103826572-16c66b80-5045-11eb-8023-3456d19639e7.png" width="300">

### Spans 2 days (note it only shows on the first day):
<img src="https://user-images.githubusercontent.com/16725750/103826621-28a80e80-5045-11eb-8210-11aa56310b51.png" width="300">

### Spans more than 2 days:
<img src="https://user-images.githubusercontent.com/16725750/103826640-3362a380-5045-11eb-94d6-543e02ae1f53.png" width="300">

At the moment, syncfusion splits the 2-day span into two slots, one for each day, which is not compliant with the above Google Calendar screenshot.
I'd like to propose a feature request to add this by default or with a boolean option _showRolloverOnFirstDayOnly_ in `scheduleViewSettings`

**Comment by Indumathi1195R** [comment]
Hi,

Based on the provided information, we have checked the mentioned issue “**Two-day span appointment in two slots in Flutter calendar**”. As per the calendar implementation, we will show the span appointment in two slots, when the appointment timing is less than 24hr (But on different dates). Because the **startTime** and **endTime** dates of the appointment are different, so we will show the appointment in two slots. Also, we will improve the behavior of span appointments in the schedule view to show **startTime** and **endTime** values.

On the web, the Google calendar also shows the span appointment of the schedule view in two slots. Please find the web google calendar Image also.
 
<img width="576" alt="Screenshot (66)" src="https://user-images.githubusercontent.com/54974849/103880300-f2c76080-50fe-11eb-93d5-28948251ae94.png">

We hope that this helps you. Please let us know if you need further assistance. If possible, can you please share more details about your requested feature, it would be helpful for us to analyze and log the Feature request.

Regards,
Indumathi R

**Comment by pauldemarco** [comment]
The screenshots I posted are from the Google Calendar app. So while the web might show a 2 day span as 2 slots, perhaps the mobile version should comply with the Google Calendar app and show one?

**Comment by Indumathi1195R** [comment]
Hi,

As mentioned in our previous update as per implementation the spanned appointment cannot split into 2 appointments as Case 2. We will consider displaying the span appointment details as improvement like start time and end time value with the span appointment in schedule view. We will improve this behavior in any of our upcoming releases and let you know once the release rolled out. We appreciate your patience until then.

You can track the status of this report through the following feedback link,

**Feedback link:**
https://www.syncfusion.com/feedback/21292/improvements-in-the-schedule-view-span-appointments-of-the-flutter-event-calendar

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
