### ISSUE TITLE
pdf_xfdf_document.dart:38:35: Error: The argument type 'String?' can't be assigned to the parameter type 'Object' because 'String?' is nullable and 'Object' isn't.

### ISSUE THREAD

**Issue by connectganeshs** [syncfusion/flutter-widgets#1074]
![Screenshot 2023-02-06 at 3 28 46 PM](https://user-images.githubusercontent.com/57519624/216942198-7770e5e9-fcb6-447c-8f25-98591d4c83e1.png)
Attached image, where  builder.attribute('href', _pdfFilePath); accepts String and Object but the _pdfFilePath has been declared as String? which is causing issue while building on iOS.

**Comment by Hieu86355** [comment]
> ![Screenshot 2023-02-06 at 3 28 46 PM](https://user-images.githubusercontent.com/57519624/216942198-7770e5e9-fcb6-447c-8f25-98591d4c83e1.png) Attached image, where builder.attribute('href', _pdfFilePath); accepts String and Object but the _pdfFilePath has been declared as String? which is causing issue while building on iOS.

I have the same issue on iOS devices. Did you have any ideas?

**Comment by VivekMakwana24** [comment]
Any update on this issue?

**Comment by irfanajaffer** [comment]
<html>
<body>
<p dir="auto" style="box-sizing: border-box; margin-top: 0px !important; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">We found that the problem is due to the older version of the<span style="box-sizing: border-box;"> </span><a href="https://pub.dev/packages/xml/versions" rel="nofollow" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none;">xml</a><span style="box-sizing: border-box;"> </span>package being referred to in your project. Recently, the<span style="box-sizing: border-box;"> </span><a href="https://pub.dev/documentation/xml/latest/xml/XmlBuilder/attribute.html" rel="nofollow" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none;">XmlBuilder</a><span style="box-sizing: border-box;"> </span>attribute value API has been updated from non-nullable to nullable type; you can refer to the following API reference for further details.</p><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br style="box-sizing: border-box;"></p>

Xml package version 6.2.0 | Xml package version 6.2.2
-- | --
https://pub.dev/documentation/xml/6.2.0/xml/XmlBuilder/attribute.html | https://pub.dev/documentation/xml/latest/xml/XmlBuilder/attribute.html

<p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br style="box-sizing: border-box;"></p><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">So, we request you to update your pub cache by using the following command to resolve the issue.</p><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span style="box-sizing: border-box;">dart pub cache add xml<span style="box-sizing: border-box;"> </span></span><span style="box-sizing: border-box;">--version</span><span style="box-sizing: border-box;"><span style="box-sizing: border-box;"> </span></span><span style="box-sizing: border-box;">"6.2.2"</span></p><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br style="box-sizing: border-box;"></p><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px !important; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">You can refer<span style="box-sizing: border-box;"> </span><a href="https://dart.dev/tools/pub/cmd/pub-cache" rel="nofollow" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none;">https://dart.dev/tools/pub/cmd/pub-cache</a><span style="box-sizing: border-box;"> </span>for more details</p>
</body>
</html>

**Comment by connectganeshs** [comment]
> We found that the problem is due to the older version of the [xml](https://pub.dev/packages/xml/versions) package being referred to in your project. Recently, the [XmlBuilder](https://pub.dev/documentation/xml/latest/xml/XmlBuilder/attribute.html) attribute value API has been updated from non-nullable to nullable type; you can refer to the following API reference for further details.
> 
> Xml package version 6.2.0	Xml package version 6.2.2
> https://pub.dev/documentation/xml/6.2.0/xml/XmlBuilder/attribute.html	https://pub.dev/documentation/xml/latest/xml/XmlBuilder/attribute.html
> So, we request you to update your pub cache by using the following command to resolve the issue.
> 
> dart pub cache add xml --version "6.2.2"
> 
> You can refer https://dart.dev/tools/pub/cmd/pub-cache for more details

This worked @irfanajaffer, thank you so much.

**Comment by alwangk** [comment]
> We found that the problem is due to the older version of the [xml](https://pub.dev/packages/xml/versions) package being referred to in your project. Recently, the [XmlBuilder](https://pub.dev/documentation/xml/latest/xml/XmlBuilder/attribute.html) attribute value API has been updated from non-nullable to nullable type; you can refer to the following API reference for further details.
> 
> Xml package version 6.2.0	Xml package version 6.2.2
> https://pub.dev/documentation/xml/6.2.0/xml/XmlBuilder/attribute.html	https://pub.dev/documentation/xml/latest/xml/XmlBuilder/attribute.html
> So, we request you to update your pub cache by using the following command to resolve the issue.
> 
> dart pub cache add xml --version "6.2.2"
> 
> You can refer https://dart.dev/tools/pub/cmd/pub-cache for more details

Still not work on me with latest syncfusion_flutter_pdfviewer: ^20.4.49 on Flutter 3.7.1  :(

**Comment by akiratfli** [comment]
I encounter this issue also. I add `xml: 6.2.2` to pubspec.yaml resolved

**Comment by alwangk** [comment]
> > > We found that the problem is due to the older version of the [xml](https://pub.dev/packages/xml/versions) package being referred to in your project. Recently, the [XmlBuilder](https://pub.dev/documentation/xml/latest/xml/XmlBuilder/attribute.html) attribute value API has been updated from non-nullable to nullable type; you can refer to the following API reference for further details.
> > > Xml package version 6.2.0	Xml package version 6.2.2
> > > https://pub.dev/documentation/xml/6.2.0/xml/XmlBuilder/attribute.html	https://pub.dev/documentation/xml/latest/xml/XmlBuilder/attribute.html
> > > So, we request you to update your pub cache by using the following command to resolve the issue.
> > > dart pub cache add xml --version "6.2.2"
> > > You can refer [https://dart.dev/tools/pub/cmd/pub-cache for](https://dart.dev/tools/pub/cmd/pub-cache%C2%A0for) more details
> > 
> > 
> > Still not work on me with latest syncfusion_flutter_pdfviewer: ^20.4.49 on Flutter 3.7.1 :(
> 
> I followed following steps:
> 
> 1. flutter clean
> 2. in iOS directory : pod deintegrate
> 3. flutter pub get
> 4. dart pub cache repair
> 5. dart pub cache add xml --version "6.2.2"
> 6. in iOS directory: pod install
> 7. flutter run
> 
> if above dint help, then try removing all the dependancies from .yaml file and run `flutter pub get` and then add all the dependencies run `flutter pub get` again.
> 
> hope this helps.

Thank for the reply. I have try those, but still the same.

Working with downgrading version to 20.3.59 as https://github.com/syncfusion/flutter-widgets/issues/1069#issuecomment-1418514942

**Comment by dwikyhardi** [comment]
> I encounter this issue also. I add `xml: 6.2.2` to pubspec.yaml resolved

resolved my issues

**Comment by connectganeshs** [comment]
Closing the issue as adding `xml: 6.2.2` in yaml or if you have dependancy on older version of xml then run `dart pub cache add xml --version "6.2.2"`
