### ISSUE TITLE
Filter all the rows instead of rows available in a page

### ISSUE THREAD

**Issue by ledjoncili** [syncfusion/flutter-widgets#1084]
By default, the rows on a page are filtered.  If I would like to filter something which is on second page, I have to navigate to second page.
This is already implemented for sorting https://help.syncfusion.com/flutter/datagrid/paging#sort-all-the-rows-instead-of-rows-available-in-a-page. It would be a good idea to have it as well for filtering

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @ledjoncili,

If you wish to apply filtering to the entire DataGrid instead of just the current page, avoid overriding the **handlePageChange** method at the sample level, as you would do for sorting the whole data. Instead, ensure that you have access to all rows in the DataGrid, which will allow you to filter rows from the entire collection rather than just the current page.

However, if you decide to load data on a per-page basis, sorting or filtering can only be applied to the current page. This is the current behavior of the DataGrid. I have attached a simple sample for your reference. Please check it out

[sample](https://github.com/syncfusion/flutter-widgets/files/10782748/sample.zip)


Regards,
Tamilarasan
