### ISSUE TITLE
[SfCircularChart] Black arrow on tooltip template does not disappear

### ISSUE THREAD

**Issue by LuisCampos97** [syncfusion/flutter-widgets#111]
In the tooltip template, a black arrow does not disappear:
![image](https://user-images.githubusercontent.com/33434500/103927277-09c37e00-5112-11eb-8456-f3fc734cd9ee.png)

```dart
TooltipBehavior tooltip = TooltipBehavior(
        enable: true,
        shouldAlwaysShow: true,
        builder: (dynamic data, dynamic point, dynamic series, int pointIndex,
            int seriesIndex) {
          return Container(
              decoration: BoxDecoration(
                  color: Colors.white, borderRadius: BorderRadius.circular(4)),
              padding: EdgeInsets.symmetric(vertical: 4, horizontal: 6),
              child: Text("€ ${data.y}", style: TextStyle(fontSize: 18)));
        });
```

Can you help me remove that black arrow?

Thank you.
Luís

**Comment by Dharanipalani** [comment]
Hi @LuisCampos97,
 
We have analyzed your scenario and we would like to let you know that the arrow in the tooltip template will be appeared by default similar to the normal tooltip and this is our default behavior. If you wish to change the color of the arrow, you can specify using the **color** property in the **tooltipBehavior**. So, give color as white to make the tooltip template arrow white instead of black. Here we give the modified code snippet of yours here.

`TooltipBehavior tooltip =   TooltipBehavior(color: Colors.white);`

Screenshot: 
![image](https://user-images.githubusercontent.com/19763272/104017434-1ca38480-51de-11eb-9b2b-a4ddf362bcfe.png)

Kindly revert us if you need further assistance.

Thanks, 
Dharanitharan. P

**Comment by LuisCampos97** [comment]
Ok thank you!
