### ISSUE TITLE
SfCartesianChart tooltipBehavior canShowMarker not working

### ISSUE THREAD

**Issue by millie-molly** [syncfusion/flutter-widgets#1110]
canShowMarker does not disappear

**Comment by LavanyaGowtham2021** [comment]
We tried to replicate the reported issue regarding ‘[canShowMarker ](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TooltipBehavior/canShowMarker.html)property is not working’ at our end. Unfortunately, we are not able to reproduce the reported issue as we are not exactly sure in what scenario the issue is replicating. So, we kindly request you to share us with more information on your requirement in detail along with screenshots/screenrecordings or try to replicate the reported issue in the below attached test sample and revert us so that it will help us assist you in a better way.

Screenshot:
<img width="369" alt="image" src="https://user-images.githubusercontent.com/82077349/223072174-505f3651-cbe8-42ac-93d7-7f9071e03f82.png">
[github_1110.zip](https://github.com/syncfusion/flutter-widgets/files/10896487/github_1110.zip)

**Comment by millie-molly** [comment]
oh i thought that mark on the tooltip gonna disappear. 
then what is the mark?
<img width="369" alt="marker" src="https://user-images.githubusercontent.com/93499150/223288886-e73d0e82-892b-464f-a0d7-c1d0b8009f80.png">

**Comment by Yuvaraj-Gajaraj** [comment]
This is not a marker of the tooltip, it is actually an arrow of the tooltip and it is pointing to the data point, and it cannot be hidden. However, if you want to hide this arrow, you can achieve it with the help of the [builder](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TooltipBehavior/builder.html) and [opacity](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TooltipBehavior/opacity.html) properties in the tooltip. When the opacity is set to 0, it applies to the default tooltip and hides the arrow, and the builder helps you to render a custom tooltip instead of the default. We have included a code snippet below for your reference.



Code snippet:
```dart
tooltipBehavior: TooltipBehavior(
  enable: true,
  opacity: 0,
  builder: (data, point, series, pointIndex, seriesIndex) {
    return Container(
      decoration: BoxDecoration(
        color: Colors.black,
        borderRadius: BorderRadius.circular(5),
      ),
      child: Padding(
        padding: const EdgeInsets.all(8.0),
        child: Text(
          '${point!.y}',
          style: const TextStyle(color: Colors.white),
        ),
      ),
    );
  },
),
```

Screenshot:
<img src='https://user-images.githubusercontent.com/61863686/223703978-676862a1-a40f-4a78-aaeb-981ad74f376c.png' width = 200px/>

**Comment by millie-molly** [comment]
amazing! thanks
