### ISSUE TITLE
[syncfusion_flutter_charts] Waviness of the line

### ISSUE THREAD

**Issue by Ilya-Vys** [syncfusion/flutter-widgets#1111]
I have values ​​going down a strict value per minute. But LineSeries looks little waving. Is it possible to make it strict?
![Screenshot 2023-03-03 at 14 35 16](https://user-images.githubusercontent.com/66084736/222710445-bd2a10ec-3fe1-4361-af62-a478db918d67.png)

**Comment by Yuvaraj-Gajaraj** [comment]
We have tried to reproduce the reported issue that is the line series is waving when there are data points on the x-axis for a minute, but we were unable to replicate the issue on our end. Therefore, we kindly request that you provide us with more information in detail, along with screenshots or screen recordings, so that we can assist you in a better way. 

We have also shared the sample below for your reference, please try to reproduce the issue in that sample and get back to us.

Screenshot:
<img src='https://user-images.githubusercontent.com/61863686/223445732-4bf8c2de-cef6-4a39-9b4a-3d6fe18a7b4b.png' width=200px/>



Sample: 
[i444143.zip](https://github.com/syncfusion/flutter-widgets/files/10910164/i444143.zip)

**Comment by Ilya-Vys** [comment]
Thanks for your answer. It was my bad based on wrong double values rounding.
