### ISSUE TITLE
Line Chart show timing

### ISSUE THREAD

**Issue by tuceturan** [syncfusion/flutter-widgets#1112]
I use Line chart and I have 6 line data each line has  8200 data
Is showing slowly and when ı zoom is too slow How can I fix? or any suggestion for that?

![Screenshot_20230303-150649 1](https://user-images.githubusercontent.com/47599661/222716399-42ced054-1fff-4d00-a615-fcf3a853def8.jpg)

**Comment by LavanyaGowtham2021** [comment]
The following are the key points that can be used to boost the performance of the chart when there is a need to plot high volume data.

- Load and store the required data points in the initState method itself, and then set the data points to the chart series. 
- Use [NumericAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/NumericAxis-class.html) or [DateTimeAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeAxis/DateTimeAxis.html) instead of [CategoryAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CategoryAxis/CategoryAxis.html). 
- When there are large number of points to load in line series, you can use [FastLineSeries](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/FastLineSeries-class.html) series instead of [LineSeries](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/LineSeries-class.html).
- Instead of enabling data markers and labels when there are large number of data points, you can use [Trackball](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/trackballBehavior.html) to view the point information.
- Set series [animationDuration](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianSeries/animationDuration.html) as 0 to disable the animation while loading large number of data points.
- Use [updateDataSource](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeriesController/updateDataSource.html) method while updating dynamic data points instead of calling setState. For more details refer ug -  https://help.syncfusion.com/flutter/cartesian-charts/methods#updatedatasource.
- Use On-demand loading while rendering large data points, it can be used to load more data to the chart when the visible range reaches the end on dragging in the chart.  https://help.syncfusion.com/flutter/cartesian-charts/on-demand-loading
