### ISSUE TITLE
[syncfusion_flutter_datagrid] Possible to change resize behavior for ColumnWidthMode.fill?

### ISSUE THREAD

**Issue by socramm9** [syncfusion/flutter-widgets#1120]
https://user-images.githubusercontent.com/52098754/224024991-6060597e-68f9-4cf9-ac0b-f12a3935ca8d.mov

I understand why it happens but I am afraid that some user my find this behaviour weird.

The "File name" column is set to `ColumnWidthMode.fill` and by resizing the "Size" column the "File name" column is also resized. 
Personally I think this does't feel natural.

The Grid from [mui.com](mui.com) has a more natural feel to it. Here an example sandbox:
https://codesandbox.io/s/columnsizinggrid-demo-mui-x-forked-fdhyn0?file=/demo.tsx

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @socramm9,

Based on the information you provided, it appears that you have set the **ColumnWidthMode** to '**fill**' for the column named ''**File name**''. Could you please confirm if you have set any other **ColumnWidthMode** values in either **SfDataGrid.columWidthMode** or **GridColumn.columnWidthMode** for other columns? **Additionally, it would be helpful if you could provide more information on the expected behavior**. To further assist you, please provide your DataGrid configuration so that we can investigate and provide an appropriate solution.

Regards,
Tamilarasan
