### ISSUE TITLE
Squared selection with custom cellBuilder in SfDateRangePicker

### ISSUE THREAD

**Issue by PawlikMichal25** [syncfusion/flutter-widgets#1121]
Hello,

I need to increase height of individual cells in `SfDateRangePicker`. If you know a better way how to do this, then please let me know, but I tried to use custom `cellBuilder`. The problem is that once I used it the selection stopped working correctly - the corners aren't rounded.
```dart

  @override
  Widget build(BuildContext context) {
    return SfDateRangePicker(
      ....
      cellBuilder: (context, details) {
        return Container(
          height: 40,
          alignment: Alignment.center,
          child: Text(details.date.toString()),
        );
      },
    );
  }
```
How can I use custom `cellBuilder` but still have nice, rounded corners in selection?

How it looks:
![Screenshot_20230310-100755](https://user-images.githubusercontent.com/15315707/224308543-8fd710fc-4eac-4a96-b718-bf18f3df708c.png)

How I expect it to look:
![Screenshot_20230310-100810](https://user-images.githubusercontent.com/15315707/224308643-29db6910-7877-47e4-bb14-c80ece537353.png)

**Comment by MuniappanSubramanian** [comment]
@PawlikMichal25 

**#Regarding I need to increase the height of individual cells**
The current implementation of the Flutter Calendar does not have support to increase the height of individual cells.

**#Regarding SelectionShape circle does not apply while using the cell builder support.**
The current implementation of the Flutter Calendar does not have circle selection shape support for cell builder. It is an expected behavior for a flutter calendar with a cell builder.
