### ISSUE TITLE
Error: Type 'PanAxis' not fou nd.   final PanAxis panAxis;

### ISSUE THREAD

**Issue by dghub-founder** [syncfusion/flutter-widgets#1136]
syncfusion_flutter_core-20.4.54/lib/src/widgets/interactive_scroll_viewer.dart:59:9: Error: Type 'PanAxis' not fou
nd.
  final PanAxis panAxis;

how to fix this error.
I need syncfusion_flutter_core old version.

**Comment by Yuvaraj-Gajaraj** [comment]
The reported issue is caused by a recent upgrade to the Flutter version. In previous versions, the alignPanAxis property was a Boolean, but in version 3.7.0, it was changed to an enum type. To resolve this issue, upgrade the Flutter SDK to version 3.7.0, as all the Syncfusion Flutter packages have been updated to this version. The framework breaking change PR can be found below for your reference.



https://github.com/flutter/flutter/pull/109014/commits/1c6f20c8b3dc8e10258a626d401161db2942ddca
