### ISSUE TITLE
[syncfusion_flutter_pdfviewer] Error: Type 'PanAxis' not found.....

### ISSUE THREAD

**Issue by Imesh7** [syncfusion/flutter-widgets#1163]
```
: Error: Type 'PanAxis' not found.
../…/widgets/interactive_scroll_viewer.dart:59
  final PanAxis panAxis;
        ^^^^^^^

: Error: Undefined name 'PanAxis'.
../…/widgets/interactive_scroll_viewer.dart:15
      this.panAxis = PanAxis.free,
                     ^^^^^^^
: Error: Method 'readState' cannot be called on 'PageStorageBucket?' because it is potentially null.
../…/src/pdfviewer.dart:1057
- 'PageStorageBucket' is from 'package:flutter/src/widgets/page_storage.dart' ('../../../../fvm/versions/3.3.10/packages/flutter/lib/src/widgets/page_storage.dart').
package:flutter/…/widgets/page_storage.dart:1
Try calling using ?. instead.
      final dynamic offset = PageStorage.of(context).readState(context);
                                                     ^^^^^^^^^

: Error: Method 'readState' cannot be called on 'PageStorageBucket?' because it is potentially null.
../…/src/pdfviewer.dart:1061
- 'PageStorageBucket' is from 'package:flutter/src/widgets/page_storage.dart' ('../../../../fvm/versions/3.3.10/packages/flutter/lib/src/widgets/page_storage.dart').
package:flutter/…/widgets/page_storage.dart:1

Try calling using ?. instead.
          .readState(context, identifier: 'zoomLevel_${widget.key}');
           ^^^^^^^^^
: Error: Method 'writeState' cannot be called on 'PageStorageBucket?' because it is potentially null.
../…/src/pdfviewer.dart:3305
- 'PageStorageBucket' is from 'package:flutter/src/widgets/page_storage.dart' ('../../../../3.3.10/packages/flutter/lib/src/widgets/page_storage.dart').
package:flutter/…/widgets/page_storage.dart:1
Try calling using ?. instead.
          PageStorage.of(context).writeState(
                                  ^^^^^^^^^^

: Error: Method 'writeState' cannot be called on 'PageStorageBucket?' because it is potentially null.
../…/src/pdfviewer.dart:3333
- 'PageStorageBucket' is from 'package:flutter/src/widgets/page_storage.dart' ('../../../../fvm/versions/3.3.10/packages/flutter/lib/src/widgets/page_storage.dart').
package:flutter/…/widgets/page_storage.dart:1
Try calling using ?. instead.
          PageStorage.of(context).writeState(
                                  ^^^^^^^^^^

: Error: 'PanAxis' isn't a type.
../…/widgets/interactive_scroll_viewer.dart:59
  final PanAxis panAxis;

        ^^^^^^^
: Error: No named parameter with the name 'panAxis'.
../…/widgets/interactive_scroll_viewer.dart:299
        panAxis: widget.panAxis,
        ^^^^^^^
: Context: Found this candidate, but the arguments don't match.
../…/widgets/interactive_viewer.dart:61
  InteractiveViewer({
  ^^^^^^^^^^^^^^^^^
```
  
  
 got above mentioned issue. 
 I am using latest version of this package([syncfusion_flutter_pdfviewer: ^21.1.39](https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/21.1.39)).
  Checked with flutter version - 3.3.10

I thinks error occurs in flutter - syncfusion_flutter_core 20.4.54

**Comment by deepika134** [comment]
@Imesh7 , Kindly clear the pub cache and run the **flutter pub upgrade** command for upgrading all the packages to the latest version. syncfusion_flutter_core is the dependency package of syncfusion_flutter_pdfviewer please make sure the latest version of syncfusion_flutter_core is referred in your application.

**Comment by vaibhiarora03** [comment]
@deepika134 I am also getting the same error.

`
Running Gradle task 'assembleDebug'...
../../flutter_sdk/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-21.1.37/lib/src/widgets/interactive_scroll_viewer.dart:59:9: Error: Type 'PanAxis' not found.
  final PanAxis panAxis;
        ^^^^^^^
../../flutter_sdk/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-21.1.37/lib/src/widgets/interactive_scroll_viewer.dart:15:22: Error: Undefined name 'PanAxis'.
      this.panAxis = PanAxis.free,
                     ^^^^^^^
../../flutter_sdk/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_pdfviewer-21.1.37/lib/src/pdfviewer.dart:1055:54: Error: Method 'readState' cannot be called on 'PageStorageBucket?' because it is potentially null.
 - 'PageStorageBucket' is from 'package:flutter/src/widgets/page_storage.dart' ('../../flutter_sdk/flutter/packages/flutter/lib/src/widgets/page_storage.dart').
Try calling using ?. instead.
      final dynamic offset = PageStorage.of(context).readState(context);
                                                     ^^^^^^^^^
../../flutter_sdk/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_pdfviewer-21.1.37/lib/src/pdfviewer.dart:1059:12: Error: Method 'readState' cannot be called on 'PageStorageBucket?' because it is potentially null.
 - 'PageStorageBucket' is from 'package:flutter/src/widgets/page_storage.dart' ('../../flutter_sdk/flutter/packages/flutter/lib/src/widgets/page_storage.dart').
Try calling using ?. instead.
          .readState(context, identifier: 'zoomLevel_${widget.key}');
           ^^^^^^^^^
../../flutter_sdk/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_pdfviewer-21.1.37/lib/src/pdfviewer.dart:3299:35: Error: Method 'writeState' cannot be called on 'PageStorageBucket?' because it is potentially null.
 - 'PageStorageBucket' is from 'package:flutter/src/widgets/page_storage.dart' ('../../flutter_sdk/flutter/packages/flutter/lib/src/widgets/page_storage.dart').
Try calling using ?. instead.
          PageStorage.of(context).writeState(
                                  ^^^^^^^^^^
../../flutter_sdk/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_pdfviewer-21.1.37/lib/src/pdfviewer.dart:3327:35: Error: Method 'writeState' cannot be called on 'PageStorageBucket?' because it is potentially null.
 - 'PageStorageBucket' is from 'package:flutter/src/widgets/page_storage.dart' ('../../flutter_sdk/flutter/packages/flutter/lib/src/widgets/page_storage.dart').
Try calling using ?. instead.
          PageStorage.of(context).writeState(
                                  ^^^^^^^^^^
../../flutter_sdk/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-21.1.37/lib/src/widgets/interactive_scroll_viewer.dart:59:9: Error: 'PanAxis' isn't a type.
  final PanAxis panAxis;
        ^^^^^^^
../../flutter_sdk/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-21.1.37/lib/src/widgets/interactive_scroll_viewer.dart:299:9: Error: No named parameter with the name 'panAxis'.
        panAxis: widget.panAxis,
        ^^^^^^^
../../flutter_sdk/flutter/packages/flutter/lib/src/widgets/interactive_viewer.dart:61:3: Context: Found this candidate, but the arguments don't match.
  InteractiveViewer({
  ^^^^^^^^^^^^^^^^^


FAILURE: Build failed with an exception.

* Where:
Script '/Users/imac/flutter_sdk/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1159

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/imac/flutter_sdk/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 54s
Exception: Gradle task assembleDebug failed with exit code 1
`

`syncfusion_flutter_core : 21.1.39`
`syncfusion_flutter_pdfviewer : 21.1.39`

`
Flutter (Channel stable, 3.3.10, on macOS 12.6.2 21G320 darwin-x64, locale en-US)
    • Flutter version 3.3.10 on channel stable at /Users/imac/flutter_sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (4 months ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0
`

**Comment by vaibhiarora03** [comment]
Somehow it worked by downgrading all the packages. 

```
syncfusion_flutter_core: 20.3.59
syncfusion_flutter_pdf: 20.3.59
syncfusion_flutter_pdfviewer: 20.3.59
```

**Comment by deepika134** [comment]
Hi @vaibhiarora03 , The reported issue is caused by a upgradation of the Flutter. In previous versions, the alignPanAxis property was a Boolean, but in version 3.7.0, it was changed to an Enum type. To resolve this issue, upgrade the Flutter SDK to the latest version and also upgrade the latest Syncfusion package version.
