### ISSUE TITLE
[syncfusion_flutter_pdf] After Form PDF save - not shown in App, but when I open PDF on my mac 

### ISSUE THREAD

**Issue by marcoheine** [syncfusion/flutter-widgets#1170]
I work with editable PDFs. I fill in the fields, save it and want to open (OpenFile.open();) it in the app (iOS simulator). But the saved fields are not shown filled, they are empty.
If I go to the directory on my Mac where the app saves the PDF and open this file with Adobe, then these documents are filled out.
What's the mistake?

Here is my code:

`
import 'package:flutter/material.dart';
import 'dart:io';
import 'package:xxx/AppConstant.dart';
import 'package:xxx/app_data/screen/common/standardScaffold.dart';
import 'package:open_file_plus/open_file_plus.dart';
import 'package:syncfusion_flutter_pdf/pdf.dart';
import 'package:path_provider/path_provider.dart';

class EditPdf extends StatefulWidget {
  File pdfDocument;

  EditPdf(this.pdfDocument);

  @override
  State<EditPdf> createState() => _EditPdfState();
}

class _EditPdfState extends State<EditPdf> with WidgetsBindingObserver {
  Widget PdfEditForm = SizedBox();
  Map fields = {};

  @override
  void initState() {
    super.initState();
    generateEditForm();
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return StandardScaffold(SingleChildScrollView(child: Column(children: [
          PdfEditForm,
        ],)),
      floatingActionButton: FloatingActionButton(
        onPressed: () async {
          await savePdfForm();
          print(widget.pdfDocument.path);
          OpenFile.open(widget.pdfDocument.path);
        },
        backgroundColor: colorPrimary,
        child: const Icon(Icons.remove_red_eye, color: Colors.white),
      ),
      backButtonAlertDialog: true,
      topBarTitle: 'PDF bearbeiten',
    );
  }

  savePdfForm() async {
    final PdfDocument document = PdfDocument(inputBytes: widget.pdfDocument.readAsBytesSync());

    PdfForm form = document.form;

    for (int i = 0; i < document.form.fields.count; i++) {
      PdfField field = document.form.fields[i];

      if (field is PdfTextBoxField) {
        if (fields[i] != null) {
          if (fields[i]['value'] != null) {
            field.text = fields[i]['value'];
          }
        }
      } else if (field is PdfRadioButtonListField && field.selectedIndex != 1) {
        if (fields[i] != null) {
          if (fields[i]['value'] != null) {
            field.selectedValue = fields[i]['value'];
          }
        }
      } else if (field is PdfCheckBoxField) {
        if (fields[i] != null) {
          if (fields[i]['value'] != null) {
            field.isChecked = fields[i]['value'];
          }
        }
      } else if (field is PdfComboBoxField) {
        if (fields[i] != null) {
          if (fields[i]['value'] != null) {
            field.selectedValue = fields[i]['value'];
          }
        }
      } else if (field is PdfSignatureField) {

      }
    }

    var dir = await getApplicationDocumentsDirectory();

    File(widget.pdfDocument.path).writeAsBytesSync(await document.save());
    document.dispose();
  }

  generateEditForm() async {
    List<Widget> list = <Widget>[];

    final PdfDocument document = PdfDocument(inputBytes: widget.pdfDocument.readAsBytesSync());

    for (int i = 0; i < document.form.fields.count; i++) {
      PdfField field = document.form.fields[i];

      if (fields[i] == null) {
        fields[i] = {};
      }

      if (field is PdfTextBoxField) {
        if (1 == 1) {
          list.add(TextField(
            decoration: InputDecoration(
              labelText: field.name, //babel text
              hintText: field.tooltip, //hint textiocn
              hintStyle: TextStyle(fontSize: 18), //hint text style
              labelStyle: TextStyle(fontSize: 13), //label style
            ),
            onChanged: (String value) {
              fields[i]['value'] = value;
            },
          ));
          list.add(SizedBox(height: 15.0));
        }
      } else if (field is PdfRadioButtonListField && field.selectedIndex != 1) {
        list.add(Text(field.name!));

        List<RadioListTile> radioList = <RadioListTile>[];
        for (int j = 0; j < field.items.count; j++) {
          PdfRadioButtonListItem item = field.items[j];

          radioList.add(RadioListTile<String>(
            title: Text(item.value),
            value: item.value,
            groupValue:  fields[i]['value'] ?? null,
            onChanged: (String? value) {
              setState(() {
                fields[i]['value'] = value;
                generateEditForm();
              });
            },
          ));
        }
        list.add(Column(children: radioList));
        list.add(SizedBox(height: 15.0));
      } else if (field is PdfCheckBoxField) {
        if (fields[i]['value'] == null) {
          fields[i]['value'] = field.isChecked;
        }
        list.add(CheckboxListTile(
          title: Text(field.name!),
          value: fields[i]['value'],
          onChanged: (bool? value) {
            setState(() {
              fields[i]['value'] = value;
              generateEditForm();
            });
          },
        ));
        list.add(SizedBox(height: 15.0));
      } else if (field is PdfListBoxField) {
        List<DropdownMenuItem<String>> dropdownList = <DropdownMenuItem<String>>[];

        dropdownList.add(DropdownMenuItem(
          child: Text("--- auswählen --"),
          value: "",
        ));

        for (int j = 0; j < field.items.count; j++) {
          PdfListFieldItem item = field.items[j];

          dropdownList.add(DropdownMenuItem(
            child: Text(item.text),
            value: item.text,
          ));
        }

        list.add(DropdownButtonFormField<String>(
          decoration: InputDecoration(
            labelText: field.name,
            hintText: field.tooltip,
            hintStyle: TextStyle(fontSize: 18),
            labelStyle: TextStyle(fontSize: 13),
          ),
          items: dropdownList,
          value: fields[i]['value'],
          onChanged: (String? value) {
            setState(() {
              fields[i]['value'] = value;
              generateEditForm();
            });
          },
        ));
      } else if (field is PdfComboBoxField) {

        List<DropdownMenuItem<String>> dropdownList = <DropdownMenuItem<String>>[];

        dropdownList.add(DropdownMenuItem(
          child: Text("--- auswählen --"),
          value: "",
        ));

        for (int j = 0; j < field.items.count; j++) {
          PdfListFieldItem item = field.items[j];

          dropdownList.add(DropdownMenuItem(
            child: Text(item.text),
            value: item.text,
          ));
        }

        list.add(DropdownButtonFormField<String>(
          decoration: InputDecoration(
            labelText: field.name,
            hintText: field.tooltip,
            hintStyle: TextStyle(fontSize: 18),
            labelStyle: TextStyle(fontSize: 13),
          ),
          items: dropdownList,
          value: fields[i]['value'],
          onChanged: (String? value) {
            setState(() {
              fields[i]['value'] = value;
              generateEditForm();
            });
          },
        ));

      } else if (field is PdfSignatureField) {
        print("PdfSignatureField");
        print(field.name);
        print(field.tooltip);
      }
    }

    setState(() {
      PdfEditForm = Column(children: list);
    });
  }

}

`

**Comment by irfanajaffer** [comment]
<html>
<body>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(0, 0, 0); font-family: Heebo, &quot;open sans&quot;, sans-serif, -apple-system, BlinkMacSystemFont; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">We suggest using the below API to create an appearance for the required fields to view on mobile applications.</p>

form.setDefaultAppearance(false);
--


<p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(0, 0, 0); font-family: Heebo, &quot;open sans&quot;, sans-serif, -apple-system, BlinkMacSystemFont; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br style="box-sizing: border-box;"></p><p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(0, 0, 0); font-family: Heebo, &quot;open sans&quot;, sans-serif, -apple-system, BlinkMacSystemFont; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Follow the below links for more information:</p><p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(0, 0, 0); font-family: Heebo, &quot;open sans&quot;, sans-serif, -apple-system, BlinkMacSystemFont; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span style="box-sizing: border-box;"><a classname="e-rte-anchor" href="https://help.syncfusion.com/flutter/pdf/working-with-forms#set-appearance-to-the-pdf-form-fields" target="_blank" style="box-sizing: border-box; color: rgb(5, 101, 255); text-decoration: none; background-color: transparent; user-select: auto;">https://help.syncfusion.com/flutter/pdf/working-with-forms#set-appearance-to-the-pdf-form-fields</a></span></p><p style="box-sizing: border-box; margin: 0px; color: rgb(0, 0, 0); font-family: Heebo, &quot;open sans&quot;, sans-serif, -apple-system, BlinkMacSystemFont; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span style="box-sizing: border-box;"></span><br style="box-sizing: border-box;"><span style="box-sizing: border-box;">If still you are facing an issue, we request you share the required input document with us. So that we can assist with you further in this. <br style="box-sizing: border-box;"></span></p>
</body>
</html>

**Comment by marcoheine** [comment]
@irfanajaffer 

Thanks! This is working now!

But I have problems with PdfComboBoxField and PdfListBoxField.
After saving and opening the PDF, everything in PdfComboBoxField and PdfListBoxField is in Unicode hexadecimal. Could you help again, please?

<img width="514" alt="image" src="https://user-images.githubusercontent.com/10060379/232821993-61bea29b-43a9-4a1e-b155-0e54326a6a0c.png">

**Comment by irfanajaffer** [comment]
The fix for the reported issue " Preservation issue occurs after modifying the form fields in the PDF document" has been included in our weekly release v21.2.4.

Kindly use the following link to refer to our latest package,

https://pub.dev/packages/syncfusion_flutter_pdf/versions
