### ISSUE TITLE
[syncfusion_flutter_xlsio] Creating a Table with a single column fails.

### ISSUE THREAD

**Issue by lukaszciastko** [syncfusion/flutter-widgets#1174]
The following code should create a Table with a single column:

```Dart
    final workbook = Workbook();
    final sheet = workbook.worksheets[0]..name = 'Sheet1';

    sheet.getRangeByName('A1').setText('Fruits');
    sheet.getRangeByName('A2').setText('banana');
    sheet.getRangeByName('A3').setText('Cherry');
    sheet.getRangeByName('A4').setText('Banana');

    sheet.tableCollection.create('Table1', sheet.getRangeByName('A1:A4'));
```

However, it results in an exception:

<img width="372" alt="Screenshot 2023-04-24 at 12 26 59" src="https://user-images.githubusercontent.com/964414/233900178-7e28de18-3ffb-4a15-82ce-ad0039b621a5.png">

As soon as I add another column, everything works as expected.

I'm using syncfusion_flutter_xlsio version 21.1.41.

**Comment by Kurmitha4004** [comment]
We have included the fix for the issue The file is corrupted when creating a table with a single column in Flutter XlsIO in our weekly NuGet release version 21.2.6. Kindly upgrade your Syncfusion packages to this version and let us know if the issue is resolved.



Latest NuGet Package: https://pub.dev/packages/syncfusion_flutter_xlsio/versions/21.2.6
