### ISSUE TITLE
[syncfusion_flutter_xlsio] Referencing Tables from another Sheet doesn't work.

### ISSUE THREAD

**Issue by lukaszciastko** [syncfusion/flutter-widgets#1175]
In the following code, I am trying to SUM numbers from Sheet1 and display the sum in Sheet2:

```Dart
    final workbook = Workbook();
    final sheet = workbook.worksheets[0]..name = 'Sheet1';

    sheet.getRangeByName('A1').setText('Odd');
    sheet.getRangeByName('A2').setNumber(1);
    sheet.getRangeByName('A3').setNumber(3);

    sheet.getRangeByName('B1').setText('Even');
    sheet.getRangeByName('B2').setNumber(2);
    sheet.getRangeByName('B3').setNumber(4);

    sheet.tableCollection.create('Numbers', sheet.getRangeByName('A1:B3'));

    final sheet2 = workbook.worksheets.addWithName('Sheet2');
    sheet2.enableSheetCalculations();

    sheet2.getRangeByName('A1').setText('Odd Sum');
    sheet2.getRangeByName('A2').setFormula('=SUM(Sheet1!Numbers[Odd])');
```

This results in an error:

![Uploading Screenshot 2023-04-24 at 12.42.26.png…]()

On the contrary, when I reference the column by its range name, everything works as expected:

```Dart
    sheet2.getRangeByName('A1').setText('Odd Sum');
    sheet2.getRangeByName('A2').setFormula('=SUM(Sheet1!A1)');
```

I'm using syncfusion_flutter_xlsio version 21.1.41.

**Comment by Kurmitha4004** [comment]
We have included the fix for the issue The file is corrupted while referring the table named range to formula in Flutter XlsIO in our weekly NuGet release version 21.2.6. Kindly upgrade your Syncfusion packages to this version and let us know if the issue is resolved.



Latest NuGet Package: https://pub.dev/packages/syncfusion_flutter_xlsio/versions/21.2.6
