### ISSUE TITLE
[syncfusion_flutter_maps] MapShapeLayer Zooming & Panning is not smooth for World Map in App [Android/iOS]

### ISSUE THREAD

**Issue by souvik-dw** [syncfusion/flutter-widgets#118]
Hi, 
I am developing an App where I am showing maps with MapShapeLayer. I am getting issues with zooming and panning is not smooth for the world map.
It's working fine with a single state map but not with a large world map.

Following are the details:
Flutter: 1.22.5
syncfusion_flutter_maps: 18.4.34

**Comment by LakshmiRadhaKrishnan** [comment]
Hi, 
 
Thanks for contacting us. 
 
While loading larger shapes, there is a performance degrade during interaction. We have already reported this to the Flutter and waiting for their response. 
 
However, if you group the shapes using continent instead of country, you may get an improved performance. 

![image](https://user-images.githubusercontent.com/47354659/105327462-ea8a1d80-5bf4-11eb-93b3-5856b42385d2.png)

For this, you need to set the shapeDataField as 'continent' instead of 'name'. 

**Code snippet:**
MapShapeSource _dataSource; 

@override
void initState() {
  _dataSource = MapShapeSource.asset(
    'assets/world_map.json',
    shapeDataField: 'continent',
  );
  super.initState();
} 

However, the shapes will be grouped based on the continents. Hence, data labels, selection, legend, color mapping etc. will work based on the continent. Could you please check whether this will satisfy your requirement? If not, we kindly request you to provide more details about your requirement. 
 
Regards, 
Lakshmi R.

**Comment by souvik-dw** [comment]
Hi @LakshmiRadhaKrishnan,

Thanks for your reply. 

I want to show countries and use a label, color, tooltip depending on the data. So, shapes based on the continent will not work.

Is there any ETA for this to resolve or any workaround?

**Comment by LakshmiRadhaKrishnan** [comment]
Hi Souvik,  
  
We have checked the possibilities but currently we don’t have a workaround to improve the performance. As we mentioned in our earlier updates, the performance will be improved as soon as the mentioned issue is resolved in the framework.  
  
You can follow up the issue in the below link.  
  
https://github.com/flutter/flutter/issues/72718    
  
We will also update in our release notes once it is resolved from our side.   
  
Regards,  
Lakshmi R.
