### ISSUE TITLE
sortIconColor / filterIconColor, but only when is in use

### ISSUE THREAD

**Issue by fehernyul** [syncfusion/flutter-widgets#1196]
Hi,

Can I do somehow that I want to assign a custom color to the sort/filter icons but only when the current column was sorted/filtered?
After then I would like to see a "normal" sort/filter icon-color and a "used" sort/filter icon-color.
For example when the column is not sorted, then sorticon-color is Colors.black54 and he icon should be Colors.red on the column where there is sorting.

Thanks,
Gabor

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @fehernyul,

The DataGrid currently supports setting the color of the sort icon and filter icon through the [SfDataGridThemeData.sortIconColor](https://pub.dev/documentation/syncfusion_flutter_core/latest/theme/SfDataGridThemeData/sortIconColor.html) and [SfDataGridThemeData.filterIconColor](https://pub.dev/documentation/syncfusion_flutter_core/latest/theme/SfDataGridThemeData/filterIconColor.html) properties, respectively. However, these colors are applied to all states of the icons: ascending, descending, and non-sort order icons, filtered and unfiltered.

Please note that currently, the DataGrid does not provide the capability to change the color of the filter and sort icons only when a specific column is sorted or filtered. The color settings will be applied globally to all respective icons in the DataGrid.

However, there is a possible workaround that you can utilize to achieve your specific requirement. Instead of relying on the default icons provided by the DataGrid, you can set your own custom icons with the desired colors for each state through the **[SfDataGridThemeData.sortIcon](https://pub.dev/documentation/syncfusion_flutter_core/latest/theme/SfDataGridThemeData/sortIcon.html)** and  **[SfDataGridThemeData.filterIcon](https://pub.dev/documentation/syncfusion_flutter_core/latest/theme/SfDataGridThemeData/filterIcon.html)**. By doing so, you can have more control over the appearance of the icons based on the sorting and filtering states. 

We have already provided detailed information on how to set the sort and filter icon in the user guide. Please refer to the provided document for step-by-step instructions. 

Sort Icon Documentation: https://help.syncfusion.com/flutter/datagrid/sorting#set-a-custom-sorting-icon 

Filter Icon Documentation: https://help.syncfusion.com/flutter/datagrid/filtering#set-a-custom-filter-icon 

Regards,
Tamilarasan

**Comment by ashok-kuvaraja** [comment]
Hi @fehernyul,

We suspect that the reported problem has been resolved at your end. Please let us know if you have any further queries on this. We are happy to help you.

Regards, 
Ashok K
