### ISSUE TITLE
How to add custom value to the filtering UI

### ISSUE THREAD

**Issue by fehernyul** [syncfusion/flutter-widgets#1197]
Hi,

Can I insert a customer value/override these elements/change String values to a custom-object in this filtering UI?

![image](https://github.com/syncfusion/flutter-widgets/assets/25593792/08327ba5-27de-4c06-8fcf-5c2cebcc8a44)

Thanks,
Gabor

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @fehernyul,

As of now, the DataGrid displays the options in the checkbox filter based on the values provided in the DataGridSource for the respective column. It doesn't have built-in support for manually loading options in the checkbox filter.

To better understand your requirement and provide an appropriate solution, please provide more detailed information about your use case. Specifically, we would like to know how you want to change the string values to custom objects in the filtering UI. This information will assist us in evaluating your requirements and suggesting potential solutions.

Regards,
Tamilarasan

**Comment by Tamilarasan-Paranthaman** [comment]
@fehernyul, thank you for providing us with detailed information.


**Regarding: Problem (dbValue vs displayedText)**

As mentioned earlier, DataGrid currently does not have built-in support to load custom items in the checkbox options. However, based on the details you provided, it seems that you are trying to change the displayed value for a specific column, such as showing the **customerName** in the filter pop-up menu for the **customerID** column.

To achieve this, we have a possible workaround for you. You can modify the data type of the customerID cell in the Order class to be an object type. Then, in the **buildRow** method of your DataGridSource, you can set the appropriate value that should be displayed for the customerID in the DataGrid.

In order to show the customer's name in the filter popup for the corresponding column, you can override the toString() method in the Order class. By returning the customerName value when the **toString()** method is called, you can achieve the desired behavior.

We have prepared a sample that demonstrates this approach. In the sample, we have set the customerID as an object type and displayed it in the DataGrid, while the customerName is shown in the filter popup menu. Please note that this approach is only applicable to string types. Below is the relevant code snippet for your reference:

```dart
class EmployeeDataSource extends DataGridSource {

EmployeeDataSource(List<Order> orders) {
    buildDataGridRows(orders);
  }

  List<DataGridRow> datagridRow = [];

  @override
  List<DataGridRow> get rows => datagridRow;

  void buildDataGridRows(List<Order> orders) {
    datagridRow = orders
        .map<DataGridRow>((order) => DataGridRow(cells: [
              DataGridCell<int>(columnName: 'productId', value: order.productId),
              DataGridCell<String>(columnName: 'productName', value: order.productName),
              DataGridCell<Order>(columnName: 'customerID', value: order),
              DataGridCell<String>(columnName: 'country', value: order.country),
            ]))
        .toList();
  }

  @override
  DataGridRowAdapter buildRow(DataGridRow row) {
    return DataGridRowAdapter(
        cells: row.getCells().map<Widget>((dataGridCell) {
      return dataGridCell.columnName == 'customerID'
          ? Container(
              alignment: Alignment.center,
              padding: const EdgeInsets.symmetric(horizontal: 8.0),
              child: Text(dataGridCell.value.customerID),
            )
          : Container(
              alignment: Alignment.center,
              padding: const EdgeInsets.symmetric(horizontal: 8.0),
              child: Text(dataGridCell.value.toString()),
            );
    }).toList());
  }
}

```

**In Order class:**

```dart


class Order {
  final int productId;
  final String productName;
  final String customerName;
  final String customerID;
  final String orderID;
  final String country;
  final String color;

  Order({
    required this.productId,
    required this.productName,
    required this.customerName,
    required this.customerID,
    required this.orderID,
    required this.country,
    required this.color,
  });

  @override
  String toString() {
    return customerName;
  }
}

List<Order> orders = [
  Order(
    productId: 10001,
    productName: 'Chevrolet Corvette',
    customerName: 'John Doe',
    customerID: 'C001',
    orderID: 'O001',
    country: 'Argentina',
    color: 'Red',
  ),
  Order(
    productId: 10002,
    productName: 'Ford Mustang',
    customerName: 'Jane Smith',
    customerID: 'C002',
    orderID: 'O002',
    country: 'Austria',
    color: 'Blue',
  ),
  
…

  Order(
    productId: 10020,
    productName: 'Dodge Challenger',
    customerName: 'Liam Young',
    customerID: 'C020',
    orderID: 'O020',
    country: 'Switzerland',
    color: 'Maroon',
  ),
];

```
**Sample Link: [datagrid-sample](https://github.com/syncfusion/flutter-widgets/files/11507746/sample.zip)**



https://github.com/syncfusion/flutter-widgets/assets/93904422/01b16d29-5219-4bad-9938-cb751d422850



Please review the attached sample and let us know if it meets your requirements. If you have any further questions or need additional assistance, please let us know.

**Regarding: Problem (async loading filter values)**

Based on the information provided, it appears that you are inquiring about the possibility of implementing async loading for the performance of the checkbox filter. We would like to inform you that we have already implemented a solution using **[ListView.builder](https://api.flutter.dev/flutter/widgets/ListView/ListView.builder.html)**. This approach ensures that the options tiles in the checkbox are created on demand, rather than loading the entire list of values upfront. This optimized implementation ensures that the builder is only called for the children that are actually visible, thereby improving performance. Therefore, even if you have thousands of records, the performance will not be adversely affected. 

If we have misunderstood your query, could you please provide us with more details or clarify your request? This will help us better understand your requirements and provide you with an accurate and appropriate response.

Regards,
Tamilarasan

**Comment by fehernyul** [comment]
@Tamilarasan-Paranthaman 

First of all, thank you for your exhaustive answer.
But your answer didn't solve any of the problems.

I will try to describe them in a more practical way.

- CUSTOMER table, 2-column van: CUSTOMER_ID, CUSTOMER_NAME. It has 27,000 customers.
- ORDERS table, 3 column van: ORDER_ID, CUSTOMER_ID, PRODUCT_ID. This includes 1.7 million orders.
- PRODUCT table, 2-column van: PRODUCT_ID, PRODUCT_NAME. There are 20,000 products in it.

I want to display the first 10 records of the ORDERS table.

SQL: 

```
Select ORDERS.ORDER_ID, ORDERS.CUSTOMER_ID, ORDERS.PRODUCT_ID, CUSTOMER.CUSTOMER_NAME, PRODUCT.PRODUCT_NAME 
from ORDERS inner join PRODUCT on ORDERS.PRODUCT_ID = PRODUCT.PRODUCT_ID
inner join CUSTOMER on CUSTOMER.CUSTOMER_ID=ORDERS.CUSTOMER_ID
OFFSET 10 ROWS FETCH NEXT 10 ROWS ONLY;
```

```
ORDER_ID  CUSTOMER_ID   PRODUCT_ID   CUSTOMER_NAME   PRODUCT_NAME
O_ID_01 | CUS_1       | PROD_23    | GEORGE M.     | OPEL         |
O_ID_02 | CUS_1       | PROD_34    | GEORGE M.     | PORSCHE      |
O_ID_03 | CUS_1       | PROD_11    | GEORGE M.     | AUDI         |
O_ID_04 | CUS_1       | PROD_04    | GEORGE M.     | TOYOTA       |
O_ID_05 | CUS_1       | PROD_07    | GEORGE M.     | FORD         |
O_ID_06 | CUS_1       | PROD_12    | GEORGE M.     | VW           |
O_ID_07 | CUS_1       | PROD_44    | GEORGE M.     | MAZDA        |
O_ID_08 | CUS_2       | PROD_11    | JANET J.      | AUDI         |
O_ID_09 | CUS_2       | PROD_12    | JANET J.      | VW           |
O_ID_10 | CUS_2       | PROD_07    | JANET J.      | FORD         |

```
I don't want to display the PRODUCT_ID and CUSTOMER_ID values, I just pass them to flutter as data so that it knows that there is not a simple text that needs to be displayed, but a (text + ID) pair.
There are only 3 columns displayed: ORDER_ID, CUSTOMER_NAME, PRODUCT_NAME.

The goal is that when you want to filter e.g. by product, you should not be able to choose from these 10 elements but from all 20.000, or 
if you want to filter by customer, then it should not be only GEORGE or JANET, but all 27.000 customers.

Because of there are many records in the CUSTOMER and PRODUCT tables, this is only possible in a dynamic drop-down list, i.e. a drop-down list in which you can also filter.

For example: if the user wants to select CUSTOMER, which starts with "ZID", then the SELECT of the drop down list looks like this:

`Select * from CUSTOMER where CUSTOMER_NAME like "ZID%" OFFSET 100 ROWS FETCH NEXT 100 ROWS ONLY;`
there are a lot of customers starting with "ZID", I only ask for 100 of them.

When you select the desired customer, e.g. "ZIDONE ZENO", you will return your CUSTOMER_ID (CUS_24312) and ORDERS SELECT will be as follows:

```
Select ORDERS.ORDER_ID, ORDERS.CUSTOMER_ID, ORDERS.PRODUCT_ID, CUSTOMER.CUSTOMER_NAME, PRODUCT.PRODUCT_NAME 
from ORDERS inner join PRODUCT on ORDERS.PRODUCT_ID = PRODUCT.PRODUCT_ID
inner join CUSTOMER on CUSTOMER.CUSTOMER_ID=ORDERS.CUSTOMER_ID
WHERE ORDERS.CUSTOMER_ID = 'CUS_24312'
OFFSET 10 ROWS FETCH NEXT 10 ROWS ONLY;
```

```
ORDER_ID  CUSTOMER_ID        PRODUCT_ID   CUSTOMER_NAME     PRODUCT_NAME
O_ID_2312 | CUS_24312       | PROD_07    | ZIDONE ZENO     | FORD       |
O_ID_2341 | CUS_24312       | PROD_44    | ZIDONE ZENO     | MAZDA      |
O_ID_3241 | CUS_24312       | PROD_99    | ZIDONE ZENO     | TESLA      |
O_ID_9954 | CUS_24312       | PROD_04    | ZIDONE ZENO     | TOYOTA     |
```

A solution would be if there were not only 3 types of AdvancedFilterType but also a fourth one which is dbValueAndDispText.

```
/// Determines how the filter comparison should behave.
enum AdvancedFilterType {
  /// Specifies that the filtering options should be available based on string
  /// comparison.
  text,

  /// Specifies that the filtering options should be available based on numeric
  /// values.
  numeric,

  /// Specifies that the filtering options should be available based on date
  /// values.
  date,
	
	/// Specifies that the filtering options should be available based on db+display text values

	dbValueAndDispText
}
```

```
class DbValueAndDispText {
  dynamic dbValue;
  String dispText;
}
```

If this value is not simple text, numeric or date but dbValueAndDispText, then an externally specified widget would appear in the filter, e.g.: dropdown_search
https://pub.dev/packages/dropdown_search, which would return an ID (e.g.: CUS_24312) and the filtering would be based on this.

https://github.com/syncfusion/flutter-widgets/assets/25593792/d18cd681-d8e4-4e1d-b6a4-7d229c8adc8e


Regards,
Gabor

**Comment by Trung15010802** [comment]
What if we need to pass another object Order to another DataGridCell but with diffrent toString() property to filter?


```
  void buildDataGridRows(List<Order> orders) {
    datagridRow = orders
        .map<DataGridRow>((order) => DataGridRow(cells: [
              DataGridCell<int>(columnName: 'productId', value: order.productId),
              DataGridCell<String>(columnName: 'productName', value: order.productName),
              DataGridCell<Order>(columnName: 'customerID', value: order),
              DataGridCell<String>(columnName: 'country', value: order.country),
            ]))
        .toList();
  }
```

**Comment by Tamilarasan-Paranthaman** [comment]
@fehernyul,

Thank you for providing detailed information about your requirements. It appears that you are looking to load all unique items in the checkbox asynchronously. We have already logged a feature request for this functionality.

Feature Request: [Support to load unique items in filter popup menu asynchronously in Flutter | Feedback Portal (syncfusion.com)](https://www.syncfusion.com/feedback/38552/support-to-load-unique-items-in-filter-popup-menu-asynchronously)

We believe that implementing this feature request will meet your needs effectively. With the proposed feature, you will be able to load unique items not only from the items loaded in the DataGrid but also from external sources. You can then call the API to fetch the details and display them in the checkbox list.

Could you please review this approach and confirm whether it aligns with your requirements? Your feedback will help us ensure that we address your needs appropriately.

**Comment by ashok-kuvaraja** [comment]
Hi @fehernyul,

We are closing this issue. You can follow up on the issue using the provided feedback link. If you need further assistance, kindly reopen this issue. We are always happy to help you.

Regards,
Ashok K
