### ISSUE TITLE
SfCartesianChart + ColumnSeries + negative and positive value at same point + animation issue

### ISSUE THREAD

**Issue by vishaldhaduk9986** [syncfusion/flutter-widgets#120]
I am using SfCartesianChart with ColumnSeries and at same point both value like one is negative and one is positive.So I am facing issue of animation when click on button and change graph data.

Like in year we have 12 months.

month 1 => 4 , -2
month 2 => 6 , -3
and rest of months value is 0 (month 3 => 0, 0 , .... , month 12=> 0, 0)

So when I changed the graph data based on button click then also animating month 3 data with month 1 , 2 and others, while month 3 have 0 values so it should not animate.

Notes : when I am trying with only positive or only negative for all 12 months then. it's work.But when I am trying with both positive and negative then facing animation issue.Also need to display all 12 bars.

**Comment by Dharanipalani** [comment]
Hi @Vishaldhaduk9986,

Thanks for using our Syncfusion flutter charts. We can able to replicate your reported bug at our end and we regret the inconvenience. The fix will be included in the patch release which is expected to be rolled out on 2nd Feb 2021. Please be patience until then.

Thanks,
Dharanitharan. P

**Comment by Dharanipalani** [comment]
Hi @vishaldhaduk9986,
 
Thanks for being patience and we are happy to inform you that the reported issue has been fixed in our latest version **v18.4.41.** Now the animation will work correctly for the column charts. Please upgrade our chart package to the latest version from the following link.
 
Latest version:  [https://pub.dev/packages/syncfusion_flutter_charts/versions/18.4.41 ](url)
 
Thanks,
Dharanitharan. P
