### ISSUE TITLE
SfCartesianChart  Expected a value of type 'num?', but got one of type 'String'

### ISSUE THREAD

**Issue by hevan** [syncfusion/flutter-widgets#1202]
Expected a value of type 'num?', but got one of type 'String'
Center(
                    child: Container(
                        child: SfCartesianChart(
                          series: <ColumnSeries<_FinanceChartData, String>>[
                            ColumnSeries<_FinanceChartData, String>(
                              // Binding the chartData to the dataSource of the bar series.
                              dataSource: chartData,
                              xValueMapper: (_FinanceChartData sales, _) => sales.title,
                              yValueMapper: (_FinanceChartData sales, _) => sales.amount
                            ),
                          ],
                        ),
                    )
                ),

**Comment by LokeshPalani** [comment]
Hi @hevan,

We have validated your code snippets, and it appears that you have used string values in the 'x' values. By default, the [primaryXAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/primaryXAxis.html) is a [NumericAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/NumericAxis-class.html), which is why you encountered this error.

You can achieve your requirement by changing the [primaryXAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/primaryXAxis.html) to [CategoryAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CategoryAxis-class.html) in the [SfCartesianChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart-class.html). We have shared a code snippet for your reference. Please inform us if you require any additional assistance.

Code snippet:

```
SfCartesianChart(
            primaryXAxis: CategoryAxis(),
            primaryYAxis: NumericAxis(),
 )
```

Regards,
Lokesh.
