### ISSUE TITLE
Member not found: EdgeInsets.fromViewPadding.double keyPadHeight = EdgeInsets.fromViewPadding()

### ISSUE THREAD

**Issue by eebrahimjoy** [syncfusion/flutter-widgets#1216]
syncfusion_flutter_pdfviewer: ^21.2.6
 Flutter- 3.7.6, on macOS 13.2.1 22D68 darwin-arm64

**Comment by andfaraway** [comment]
use syncfusion_flutter_pdfviewer: ^21.2.3, it's work

**Comment by viveklodh** [comment]
i think you need to upgrade your flutter and upgrade your pub file

**Comment by deepika134** [comment]
The reported issue is caused by a recent upgrade to the Flutter version. To resolve this issue, upgrade the Flutter SDK to the latest version [3.10.0] and also upgrade the latest Syncfusion package version [21.2.6].

PdfViewer package: https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/21.2.6

Flutter SDK: https://storage.googleapis.com/flutter_infra_release/releases/stable/windows/flutter_windows_3.10.0-stable.zip
