### ISSUE TITLE
SplineAreaChart area side is wrong

### ISSUE THREAD

**Issue by tuceturan** [syncfusion/flutter-widgets#1230]
Hello I want to use  SplineAreaSeries
 My grap values like that ı created with Fl_chart
![image](https://github.com/syncfusion/flutter-widgets/assets/47599661/783752ca-662b-45a8-b600-33662f8438fb)

User when select logaritmich ı changed values this table I changed SfChartesianChart SplineAreaSeries are show other side 
![Screenshot_20230531_164805](https://github.com/syncfusion/flutter-widgets/assets/47599661/6848eba1-a487-4608-8b75-ad6bf4674feb)

I tried LogarithmicAxis also but didn't change 
can you help

**Comment by natrayansf** [comment]
We have reviewed your inquiry and were able to identify and replicate the reported issue regarding the 'SplineAreaSeries rendering on the opposite side when using the logarithmic axis'. As a result, we have created a bug report in our feedback portal. We plan to address this issue and implement the changes in our first weekly patch release after the Volume 2 main release. This is scheduled to be released by the end of this month. We will provide you with an update once the release is rolled out. Thank you for your patience. You can also track the progress of the bug through the feedback link provided below.

FR Link - https://www.syncfusion.com/feedback/44232/spline-series-is-not-rendering-while-using-with-log-axis

**Comment by BPraveenBalu** [comment]
We have forwarded the reported issue to the development team, and they have confirmed that it is not a bug but rather one of the behaviors of a logarithmic axis. The value of the first data point is 1, which means that the logarithm of 1 is 0. If decimal data points less than 1, such as 0.1 or 0.01, are used, they will result in negative values on the logarithmic axis. This is because the logarithm of 0.1 is -1, and the logarithm of 0.01 is -2. This behavior in spline area series is an expected behavior.

To illustrate, if negative data points are given for a numeric axis, the same output will be rendered for an area type series. Furthermore, we have verified this behavior using Microsoft Excel, and the logarithmic axis in Excel produces results similar to those in our charts when decimal values less than 1 are used. For reference, we have attached the output of a logarithmic axis in Excel.

Excel output for logarithmic axis with area series:

<img width="960" alt="output in excel for spline area series issue" src="https://github.com/syncfusion/flutter-widgets/assets/125338497/b873ae95-95cc-4f09-b4a9-ea14feede53a">
