### ISSUE TITLE
HTML to PDF

### ISSUE THREAD

**Issue by PRQAE** [syncfusion/flutter-widgets#1234]
Hi, 

is it possible to convert an HTML file to pdf? 

I have a ready-made HTML template form, and I have a flutter page as a form filling, I want to take the data after filling the form and compile it with the HTML template and convert it to PDF.

is it possible to do that?

**Comment by irfanajaffer** [comment]
We don't have support for converting HTML to PDF in Flutter, and it is only supported in .NET. You can use a .NET Core web API to convert the html file to pdf. It is important to ensure that the input HTML string or template can be saved and opened correctly in a browser. If the HTML displays properly in a browser, the resulting PDF file will be generated properly. Because, Our Blink converter internally makes use of chromium executable in headless mode for converting HTML to PDF. It will preserve the PDF document like how the input HTML is displayed in chromium-based web browsers (chrome print preview).

Please find the below UG link
https://help.syncfusion.com/file-formats/pdf/convert-html-to-pdf/net-core
https://help.syncfusion.com/file-formats/pdf/convert-html-to-pdf/features#html-string-to-pdf

Please find the below KB link
https://support.syncfusion.com/kb/article/7530/how-to-convert-html-to-pdf-in-asp-net-core-windows

Please refer the below blogs
https://www.syncfusion.com/blogs/post/generate-dynamic-pdf-reports-from-html-template-using-csharp.aspx
