### ISSUE TITLE
upgrade to Dart 3.x

### ISSUE THREAD

**Issue by fehernyul** [syncfusion/flutter-widgets#1244]
Hi,

Please upgrade to Dart 3.x

```
environment:
  sdk: '>=3.0.0 <4.0.0'

```
https://dart.dev/resources/dart-3-migration

Problems e.g.:
![image](https://github.com/syncfusion/flutter-widgets/assets/25593792/4e304e74-31be-4320-acbe-c1a79408c62c)

![image](https://github.com/syncfusion/flutter-widgets/assets/25593792/1dc08718-ea2a-40af-94c0-00fdbee841f6)

Regards,
Gabor

**Comment by LokeshPalani** [comment]
Hi,

Thank you for your suggestion. We will check compatibility with both 2.17 and 3.0 through testing and provide an update soon.

Regards,
Lokesh.

**Comment by Yuvaraj-Gajaraj** [comment]
We have checked your SDK version compatibility issue, but the issue didn't get reproduced at our end. Because in all our controls environment SDK version specifies from 2.17.0 to 4.0.0. So, it will take the dart version between 2.17.0 to 4.0.0. If you have a lower version of [Syncfusion](https://pub.dev/publishers/syncfusion.com/packages) package please upgrade it to the latest version, it will help you to resolve the issue.



If you still have the same issue please share more information regarding the package name and version you are using then please try to share the sample to reproduce the issue, it will be more helpful to us to provide a solution sooner.

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket with requested details to proceed further on this.
