### ISSUE TITLE
FEATURE REQUEST: Code Generation

### ISSUE THREAD

**Issue by Arpit1496** [syncfusion/flutter-widgets#1249]
Can we have code generation to convert Datagrids to SYncfusion Charts Directly using decorators ?

**Comment by LokeshPalani** [comment]
Hi @Arpit1496,

Currently, we do not have direct support to convert the [SfDataGrid](https://pub.dev/documentation/syncfusion_flutter_datagrid/latest/datagrid/SfDataGrid-class.html) into [SfCartesianChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/SfCartesianChart.html). Because, the [SfDataGrid](https://pub.dev/documentation/syncfusion_flutter_datagrid/latest/datagrid/SfDataGrid-class.html) contains multiple rows and columns, while the [SfCartesianChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/SfCartesianChart.html) only requires x and y data to render the chart. We kindly request you to provide us with more detailed information about the purpose of converting the [SfDataGrid](https://pub.dev/documentation/syncfusion_flutter_datagrid/latest/datagrid/SfDataGrid-class.html) into the [SfCartesianChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/SfCartesianChart.html) directly using decorators. This information will help us better assist you, and we will provide sample if you want. Please let us know if you require any further assistance.

Regards,
Lokesh.
