### ISSUE TITLE
Flutter syncfusion DataGridview Multiple Issue

### ISSUE THREAD

**Issue by abdulrehmananwar** [syncfusion/flutter-widgets#1264]
Video Attached
1-TextField onSubmitted i call submitCell(); now when i tap to other cell existing cell still showing focus. 
2- After Resize Screen on Horizontal Scroll  Headers remain fixed only and Row are move on Horizontal Scroll 

https://github.com/syncfusion/flutter-widgets/assets/62530396/dd61c1f1-cc72-4afd-a9bc-76933ae7d9bc

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @abdulrehmananwar,

**Regarding: TextField onSubmitted i call submitCell(); now when i tap to other cell existing cell still showing focus.**

We have thoroughly tested the attached sample and found that it functions correctly without any issues. If you are still experiencing the same problem, we kindly ask you to modify the provided sample in order to reproduce the issue accurately. Additionally, please provide us with any additional details or steps to replicate the problem. By doing so, you will greatly assist us in conducting a more in-depth investigation and promptly providing you with an appropriate solution.

**Sample: [datagrid-simple-sample](https://github.com/syncfusion/flutter-widgets/files/11849012/sample.zip)**


**Regarding: After Resize Screen on Horizontal Scroll Headers remain fixed only and Row are move on Horizontal Scroll.**

We have already identified the issue you reported and have successfully addressed it in the latest DataGrid package version 22.1.34. To resolve the issue on your end, we recommend updating your DataGrid package to the latest version. By doing so, you will have the fix implemented and should no longer encounter the problem you reported.

Regards,
Tamilarasan

**Comment by ashok-kuvaraja** [comment]
Hi @abdulrehmananwar,

We suspect that the reported problem has been resolved in the DataGrid package version 22.1.34. We are closing this issue. Please let us know if you have any further queries on this. We are happy to help you.

Regards, 
Ashok K
