### ISSUE TITLE
Wrong tangents with DateTime and cardinal curve

### ISSUE THREAD

**Issue by BananaHemic** [syncfusion/flutter-widgets#127]
First off, I just want to say that I love your graphing functions. They're gorgeous, fast, and easy to integrate.

I am having an issue with SplineSeries when the splineType is cadinal and the X axis is datetime.
![image](https://user-images.githubusercontent.com/11369260/106069664-c5dfeb00-60b7-11eb-8458-686823080131.png)

Looking into it, it appears that the tangent calculation in _getCardinalSpline is calculating huge numbers, beyond the range where double is likely accurate. I believe that the system may be turning datetime into microseconds, when milliseconds would most likely be appropriate.

**Comment by Dharanipalani** [comment]
Hi @BananaHemic, 

Greetings from Syncfusion. We have analyzed the reported scenario at our end and unfortunately, we are unable to replicate the issue. We would like to let you know that, we will calculate the control points for spline type series based on spline type to render the curve. The curve will differ for different spline types and we couldn't suspect your reported issue with cardinal spline type. So, if you share your data source, it will help us in further analysis and we will provide the solution at the earliest. 

Thanks, 
Dharanitharan. P

**Comment by Dharanipalani** [comment]
Hi @BananaHemic,
 
Thanks for the information. We can replicate the reported issue at our end from your given data source. This will be resolved in our weekly patch release which is expected to be rolled out on 9th February 2021. We appreciate your patience until then.

Thanks,
Dharanitharan. P

**Comment by BananaHemic** [comment]
Thank you for promptly addressing this

**Comment by Dharanipalani** [comment]
Hi @BananaHemic,

Thanks for being patience. We are happy to inform you that your reported issue has been fixed in our latest version **v18.4.42**. Now, the spline series for cardinal type with date-time axis renders properly, and to resolve the issue please upgrade to our latest version from the following link.

Latest Version: [https://pub.dev/packages/syncfusion_flutter_charts/versions/18.4.42](url)

Kindly revert us if you need any further assistance.

Thanks,
Dharanitharan. P
