### ISSUE TITLE
Multiple line series plotting in a not ascending and weird way on x axis.

### ISSUE THREAD

**Issue by corteXnzt** [syncfusion/flutter-widgets#1280]
I have weird outputs that I can't fix. Already explored all the APIs on your manuals.
1. Y axis labels will be gone (do not displays) if I include the Y axis title.
2. The first graph data is drawn with descending x (white one) while it should be like graphdata 2 and 3 (cause of the values).
3. The x axis labels are also numbered in weird way. It should start on zero and  blue dash line should plot before the pink one since it has lower value but instead plotted further. Behavior of x axis should be the same as how the Y axis display its value. 
TIA

Here is my test data:
```
List<_GraphData> graphData2 = [
    _GraphData(2.37, 0.0),
    _GraphData(0.0, 43.4),
  ];
  List<_GraphData> graphData3 = [
    _GraphData(2.88, 0.0),
    _GraphData(0.0, 35.71),
  ];
  List<_GraphData> graphData4 = [
    _GraphData(2.56, 0.0),
    _GraphData(0.0, 40.13),
  ];
1

```

Here is the part of the code:
```
SfCartesianChart(
  // Initialize category axis
    primaryXAxis: CategoryAxis(
      title: AxisTitle(text: 'Velocity(m/s)'),
    ),
    // primaryYAxis: CategoryAxis(
    //   title: AxisTitle(text: 'Force(N/kg)'),
    // ),
    series: <LineSeries<_GraphData, double>>[
      LineSeries(
          dataSource: graphData2,
          color: Colors.white,
          xValueMapper: (_GraphData values, _) => double.parse(values.x.toStringAsFixed(2)),
          yValueMapper: (_GraphData values, _) => double.parse(values.y.toStringAsFixed(2)),
      ),
      // for 30 degrees fvp
      LineSeries(
          dataSource: graphData3,
          dashArray: const <double>[6,6],
          color: Colors.pink,
          xValueMapper: (_GraphData values, _) => double.parse(values.x.toStringAsFixed(2)),
          yValueMapper: (_GraphData values, _) => double.parse(values.y.toStringAsFixed(2)),
      ),
      // for 90 degrees fvp
      LineSeries(
          dataSource: graphData4,
          dashArray: const <double>[10,6],
          color: Colors.blue,
          xValueMapper: (_GraphData values, _) => double.parse(values.x.toStringAsFixed(2)),
          yValueMapper: (_GraphData values, _) => double.parse(values.y.toStringAsFixed(2)),
      )
    ],
  ),
```

![IMG_20230627_152419](https://github.com/syncfusion/flutter-widgets/assets/49268713/9fb0ccc9-4c01-4624-b336-b14de2c3ca3f)

**Comment by sfHariHaraSudhan** [comment]
Hi @corteXnzt,

We have analyzed your query and investigated with the provided configuration in the simple sample. 

**Query 1: Y axis labels will be gone (do not displays) if I include the Y axis title.**

Here you have given the [primaryYAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/primaryYAxis.html) as [CategoryAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CategoryAxis-class.html). But In [SfCartesianChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart-class.html), the vertical Y Axis will always be in [NumericAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/NumericAxis-class.html). So, to display both the axis title and the axis labels in Y Axis, Use [NumericAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/NumericAxis-class.html) as [primaryYAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/primaryYAxis.html) and it will fix that issue.

**Query 2: The first graph data is drawn with descending x (white one) while it should be like graphdata 2 and 3 (cause of the values).
Query 3: The x axis labels are also numbered in weird way. It should start on zero and blue dash line should plot before the pink one since it has lower value but instead plotted further.**

For the above two queries, it will be fixed if you use [primaryXAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/primaryXAxis.html) as [NumericAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/NumericAxis-class.html) instead of [CategoryAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CategoryAxis-class.html).

Because, In [CategoryAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CategoryAxis-class.html) and [DateTimeCategoryAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeCategoryAxis-class.html), the axis labels will be rendered based on the index of the data points given. 

In [NumericAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/NumericAxis-class.html), the axis labels will be rendered based on the visible range and visible interval. So, In order to plot the blue dash line before the pink dash line and also to render the while graph properly, you can use [NumericAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/NumericAxis-class.html) for your use case.

Kindly review the code snippet below:
```
SfCartesianChart(
  primaryXAxis: NumericAxis(
    title: AxisTitle(text: 'Velocity(m/s)'),
  ),
  primaryYAxis: NumericAxis(
    title: AxisTitle(text: 'Force(N/kg)'),
  ),
  series: <LineSeries<_GraphData, double>>[
    LineSeries(
      dataSource: graphData2,
      color: Colors.amberAccent,
      xValueMapper: (_GraphData values, _) =>
          double.parse(values.x.toStringAsFixed(2)),
      yValueMapper: (_GraphData values, _) =>
          double.parse(values.y.toStringAsFixed(2)),
    ),
    LineSeries(
      dataSource: graphData3,
      dashArray: const <double>[6, 6],
      color: Colors.pink,
      xValueMapper: (_GraphData values, _) =>
          double.parse(values.x.toStringAsFixed(2)),
      yValueMapper: (_GraphData values, _) =>
          double.parse(values.y.toStringAsFixed(2)),
    ),
    LineSeries(
      dataSource: graphData4,
      dashArray: const <double>[10, 6],
      color: Colors.blue,
      xValueMapper: (_GraphData values, _) =>
          double.parse(values.x.toStringAsFixed(2)),
      yValueMapper: (_GraphData values, _) =>
          double.parse(values.y.toStringAsFixed(2)),
    )
  ],
),
```

Snapshot:
![image](https://github.com/syncfusion/flutter-widgets/assets/105288122/dcc4f31b-a691-483d-8816-e2ae83cf0575)

Also shared the User Guide regarding the axis in the [SfCartesianChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart-class.html) below for your reference. 
UG: https://help.syncfusion.com/flutter/cartesian-charts/axis-types.

Regards,
Hari Hara Sudhan. K
