### ISSUE TITLE
[radial-bar-chart] Minimum value to appear in Radial bar Chart

### ISSUE THREAD

**Issue by mdmota** [syncfusion/flutter-widgets#1295]
I'm using radial-bar-chart and the max value is 100%.
It's just starting to color the graph when the value is greater than or equal to 5.8%. How do I make the graph put from 1%?

**Comment by sfHariHaraSudhan** [comment]
Hi @mdmota,

We have analyzed your query, and to understand the mentioned requirement better, we need some clarification. We recommend you share any snapshot, basic outline, or code snippet regarding your query.

With that additional information, it will be helpful for us to provide best possible solution from our end.

Regards,
Hari Hara Sudhan. K

**Comment by mdmota** [comment]
Attached is the image of the graph. As you can see, when the value is low the graph does not color, when the value is greater than 5.8% the colored part starts to appear. I would like it to appear from 1%.
![Screenshot_20230712_065744](https://github.com/syncfusion/flutter-widgets/assets/21266037/fdb355a7-d195-4404-b727-484e70697db4)

`SfCircularChart(
          title: ChartTitle(text: isCardView ? '' : ''),
          margin: EdgeInsets.all(0),
          /// To enable the legend for radial bar.
          legend: Legend(
            position: LegendPosition.bottom,
              isVisible: false,
              iconHeight: 20,
              iconWidth: 20,
              overflowMode: LegendItemOverflowMode.wrap),
          tooltipBehavior: TooltipBehavior(enable: true, format: 'point.y %', decimalPlaces: 2, duration: 3000),
          series: _getRadialBarSeries()
        ),`

`List<RadialBarSeries<ChartData, String>> _getRadialBarSeries() {
    final List<ChartData> chartData = <ChartData>[
      ChartData(
          x: '${Format.doubleToString(val1)}/${Format.doubleToString(val2)}',
          y: val2! > 0 ? val1!/val2!*100: 0,
          text: _getTextFormat(),
          xValue: null,
          pointColor: AppTheme.roxoDonut),

    ];
    final List<RadialBarSeries<ChartData, String>> list =
    <RadialBarSeries<ChartData, String>>[
      RadialBarSeries<ChartData, String>(
          animationDuration: 200,
          pointRadiusMapper: (ChartData data, _) => data.xValue,
          maximumValue: 100,
          radius: '100%',
          gap: '1%',
          innerRadius: '69%',
          dataSource: chartData,
          cornerStyle: CornerStyle.bothCurve,
          xValueMapper: (ChartData data, _) => data.x,
          yValueMapper: (ChartData data, _) => data.y,
          pointColorMapper: (ChartData data, _) => data.pointColor,
          dataLabelMapper: (ChartData data, _) => data.text,
          dataLabelSettings: DataLabelSettings(isVisible: false))
    ];
    return list;`

**Comment by sfHariHaraSudhan** [comment]
Hi @mdmota,

We have analyzed your query and the mentioned behavior is replicated from our end with the provided code snippet. When the value falls below 5.8, the curves on both sides of the radial bar are not rendered due to limited available space when the [corner style](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CircularSeries/cornerStyle.html) is given as [bothCurve](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CornerStyle.html#bothCurve). While the color of the radial bar is displayed correctly, it requires sufficient space for the curves to be rendered.

To render the color of the radial bar at the minimum value, you can utilize the [corner style](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CircularSeries/cornerStyle.html) as [bothFlat](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CornerStyle.html#bothFlat) instead of [bothCurve](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CornerStyle.html#bothCurve) in the [RadialBar series](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/RadialBarSeries-class.html) of the [SfCircularChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCircularChart-class.html). If you have further queries, please get back to us.

Snapshot:
![image](https://github.com/syncfusion/flutter-widgets/assets/105288122/4a16dcc4-8d53-4ab2-bc7b-af8f2bef41f7)

Regards,
Hari Hara Sudhan. K
