### ISSUE TITLE
selected serie remains selected on chart rebuild

### ISSUE THREAD

**Issue by temirfe** [syncfusion/flutter-widgets#131]
On tapping a bar makes it selected (SelectionBehavior), but when chart is rebuilt (other data is given) then the bar that matches pointIndex of previous chart it becomes selected.
Also throwing error: `RangeError (index): Invalid value: Not in inclusive range 0..3: 21`
previous data has 22 items, new has 4.

**Comment by Dharanipalani** [comment]
Hi @temirfe,

Thanks for the interest in our Flutter charts. We have replicated your reported scenario at our end, and we regret the inconvenience. We will resolve this in the weekly patch release which is expected to be rolled out on 16th February 2021. We appreciate your patience until then.

Thanks,  
Dharanitharan. P

**Comment by Dharanipalani** [comment]
Hi Temirfe,

We regret the inconvenience. Due to some technical glitches, we are unable to include the fix in this weekly patch release. We will include the fix in the next weekly patch release which is expected to be rolled out on 23rd February 2021. We appreciate your patience until then.


Thanks,
Dharanitharan. P

**Comment by Dharanipalani** [comment]
Hi Temirfe,

We are glad to inform you that the reported issue has been resolved in our latest version **v18.4.44**. Now the selection will not throw any exception and to resolve this kindly upgrade our chart package to the latest version from the below link.

Latest version: https://pub.dev/packages/syncfusion_flutter_charts/versions/18.4.44

Thanks,
Dharanitharan. P
