### ISSUE TITLE
[syncfusion_flutter_calendar] Unable to Display Localized Dates in timeline day view

### ISSUE THREAD

**Issue by amirbahrawy** [syncfusion/flutter-widgets#1315]
I've been using the syncfusion_flutter_calendar package in my project to display a calendar with events. However, I noticed that the date formatting does not take into account the locale, which could lead to inconsistencies when displaying dates in different regions like this.

![Simulator Screen Shot - iPad Air (5th generation) - 2023-07-31 at 10 26 15](https://github.com/syncfusion/flutter-widgets/assets/38887148/fce52fae-ac0c-4aa2-9524-ba32483cc4be)

In the syncfusion_flutter_calendar package, the dateText is formatted using the DateFormat class without any specified locale, resulting in dates being displayed in a single, fixed format.

To address this limitation and provide a more user-friendly experience for users from different regions, I made the following modification:
```
final String dateText = DateFormat(timeSlotViewSettings.dateFormat, locale).format(currentDate); 
```
I have already tested this modification in my forked repository, and it works as expected. However, I believe it would be beneficial to include this enhancement in the official syncfusion_flutter_calendar package so that all users can benefit from localized date formatting.

**Comment by Abdelazeem777** [comment]
I am facing the same Bug here. 😔

And when I tried to edit this line as described above the issue was gone 🎉

FilePath: syncfusion_flutter_calendar/lib/src/calendar/views/timeline_view.dart
Line: 1244

before:
`final String dateText = DateFormat(timeSlotViewSettings.dateFormat).format(currentDate);`

After:
`final String dateText = DateFormat(timeSlotViewSettings.dateFormat,locale).format(currentDate);`

Please Fix this **BUG ASAP**

**Comment by IndumathiR-1995** [comment]
Hi Team,

We have already improved the behavior of the localization to numeric values (Numbers will not localized based on locale) and included the improvement in our September 5, 2023 weekly nuget release. Kindly update the latest version for this improvement.

Regards,
Indumathi R
