### ISSUE TITLE
[PDF] Pagination not working for tables that take more space than a single space

### ISSUE THREAD

**Issue by Wizzel1** [syncfusion/flutter-widgets#1332]
I am printing multiple tables with varying row heights below each other and the pagination does not seem to work: 

<img width="855" alt="Bildschirmfoto 2023-08-08 um 16 20 03" src="https://github.com/syncfusion/flutter-widgets/assets/43343510/418ed864-94e1-44a2-9219-f447daf74b89">

Is there a way to reliably paginate the rows?

**Comment by Wizzel1** [comment]
Can anyone please take a look at this?

**Comment by chinnumuniyappan** [comment]
Hi @Wizzel1 ,

We have created a sample application to draw multiple PDFGrid and it's drawn properly, we suspect that the problem may occur due to providing the pagination height to the next grid while drawing it. You can refer to the following code example and sample further details. 

    PdfGrid grid = await createPdfGrid();

    //Draw the grid to the page of the PDF document
    PdfLayoutResult? result = grid.draw(
        page: page,
        bounds: Rect.fromLTWH(0, 0, page.getClientSize().width, 0),
        format: PdfLayoutFormat(layoutType: PdfLayoutType.paginate));

    //Draw the second grid based on the result of the first grid
    PdfGrid grid2 = await createPdfGrid();
    result = grid2.draw(
        page: result!.page,
        bounds: Rect.fromLTWH(
            0, result.bounds.bottom + 10, page.getClientSize().width, 0),
        format: PdfLayoutFormat(layoutType: PdfLayoutType.paginate));

    //Draw the third grid based on the result of the second grid
    PdfGrid grid3 = await createPdfGrid();
    result = grid3.draw(
        page: result!.page,
        bounds: Rect.fromLTWH(
            0, result.bounds.bottom + 10, page.getClientSize().width, 0),
        format: PdfLayoutFormat(layoutType: PdfLayoutType.paginate));

You can refer to the complete sample [pdf_sample.zip](https://github.com/syncfusion/flutter-widgets/files/12661160/pdf_sample.zip) and [UG documentation](https://help.syncfusion.com/flutter/pdf/working-with-tables#adding-multiple-tables) for further details. 

Regards, 
Chinnu M

**Comment by Wizzel1** [comment]
Yes, it is working now. THanks
