### ISSUE TITLE
[syncfusion_flutter_datagrid] Scroll performance decreases significantly when using vertical grid lines

### ISSUE THREAD

**Issue by peer-f** [syncfusion/flutter-widgets#1337]
We have noticed that when using `gridLinesVisibility: GridLinesVisibility.both` the scroll performance in our web app gets so bad that it makes the data grid unusable. When disabling the vertical grid lines by going back to to horizontal grid lines the scroll performance improves significantly. 

I've tested this using release builds of our web app with different amounts of data such as 10, 25 or 50 data sets. Decreasing the amount of data shown didn't improve the scrolling issues we've experienced using vertical grid lines.

This is the code for our data grid:
```
SfDataGridTheme(
              data: SfDataGridThemeData(
                brightness: Brightness.light,
                gridLineColor: context.color.gray.shade500,
                gridLineStrokeWidth: 1,
                headerColor: context.color.orange,
              ),
              child: SfDataGrid(
                source: UserDataSource(
                  users: state.users,
                ),
                //gridLinesVisibility: GridLinesVisibility.both,
                //headerGridLinesVisibility: GridLinesVisibility.both,
                columnWidthMode: ColumnWidthMode.fill,
                onCellTap: (details) => print(details.rowColumnIndex),
                columns: [
                  GridColumn(
                    columnName: 'id',
                    label: Container(
                      padding: const EdgeInsets.symmetric(horizontal: 16.0),
                      alignment: Alignment.centerLeft,
                      child: const Text(
                        'ID',
                        overflow: TextOverflow.ellipsis,
                      ),
                    ),
                  ),
                  GridColumn(
                    columnName: 'firstName',
                    label: Container(
                      padding: const EdgeInsets.symmetric(horizontal: 16.0),
                      alignment: Alignment.centerLeft,
                      child: const Text(
                        'First name',
                        overflow: TextOverflow.ellipsis,
                      ),
                    ),
                  ),
                  GridColumn(
                    columnName: 'middleName',
                    label: Container(
                      padding: const EdgeInsets.symmetric(horizontal: 16.0),
                      alignment: Alignment.centerLeft,
                      child: const Text(
                        'Middle name',
                        overflow: TextOverflow.ellipsis,
                      ),
                    ),
                  ),
                  GridColumn(
                    columnName: 'lastName',
                    label: Container(
                      padding: const EdgeInsets.symmetric(horizontal: 16.0),
                      alignment: Alignment.centerLeft,
                      child: const Text(
                        'Last name',
                        overflow: TextOverflow.ellipsis,
                      ),
                    ),
                  ),
                  GridColumn(
                    columnName: 'email',
                    label: Container(
                      padding: const EdgeInsets.symmetric(horizontal: 16.0),
                      alignment: Alignment.centerLeft,
                      child: const Text(
                        'E-Mail',
                        overflow: TextOverflow.ellipsis,
                      ),
                    ),
                  ),
                  GridColumn(
                    columnName: 'mobileNumber',
                    label: Container(
                      padding: const EdgeInsets.symmetric(horizontal: 16.0),
                      alignment: Alignment.centerLeft,
                      child: const Text(
                        'Mobile number',
                        overflow: TextOverflow.ellipsis,
                      ),
                    ),
                  ),
                  GridColumn(
                    columnName: 'mobileVerified',
                    label: Container(
                      padding: const EdgeInsets.symmetric(horizontal: 16.0),
                      alignment: Alignment.centerLeft,
                      child: const Text(
                        'Mobile verified',
                        overflow: TextOverflow.ellipsis,
                      ),
                    ),
                  ),
                  GridColumn(
                    columnName: 'createdAt',
                    label: Container(
                      padding: const EdgeInsets.symmetric(horizontal: 16.0),
                      alignment: Alignment.centerLeft,
                      child: const Text(
                        'Created at',
                        overflow: TextOverflow.ellipsis,
                      ),
                    ),
                  ),
                  GridColumn(
                    columnName: 'updatedAt',
                    label: Container(
                      padding: const EdgeInsets.symmetric(horizontal: 16.0),
                      alignment: Alignment.centerLeft,
                      child: const Text(
                        'Updated at',
                        overflow: TextOverflow.ellipsis,
                      ),
                    ),
                  ),
                  GridColumn(
                    columnName: 'lastOnline',
                    label: Container(
                      padding: const EdgeInsets.symmetric(horizontal: 16.0),
                      alignment: Alignment.centerLeft,
                      child: const Text(
                        'Last online',
                        overflow: TextOverflow.ellipsis,
                      ),
                    ),
                  ),
                ],
              ),
            )

```

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @peer-f,

Based on the provided DataGrid configuration, we have prepared a simple sample and conducted comprehensive testing (release and debug modes) using the latest DataGrid version **22.2.8** and Flutter stable SDK **3.10.6**. We are pleased to inform you that the sample operates seamlessly without any scrolling performance concerns, even when vertical grid lines are enabled. We have tested it on the web platform using a Windows machine.

**Sample Link: [Sample](https://github.com/syncfusion/flutter-widgets/files/12343970/Sample.zip)**



https://github.com/syncfusion/flutter-widgets/assets/93904422/0fb06e19-eccc-4d0d-b377-bb420c5265b7



In order to gain deeper insight into the issue, we kindly request you to assess the attached sample on your own system. If you come across the same issue during your testing, kindly share the details of the device and platform where the sample was tested. Furthermore, any additional pertinent information about this issue would be greatly appreciated. This will help us investigate the problem and provide a timely solution.

Regards,
Tamilarasan

**Comment by Tamilarasan-Paranthaman** [comment]
@peer-f,

We have conducted extensive testing by enabling filtering in the sample provided in the previous response. Additionally, we evaluated the scrolling performance in the sample browser filtering sample on our end. During our testing, we did not encounter any scrolling issues in either of these samples.

Our testing was conducted using the most recent DataGrid version **23.1.39** and the latest Flutter stable version **3.13.6**, running on a MacBook Pro equipped with an Intel Core i5 processor. In our prior experiences, we encountered scrolling issues within Flutter versions **3.7** and **3.9**. These issues were successfully replicated in a simple sample. We promptly reported this matter to the framework and the framework team has confirmed the issue and subsequently addressed it. Specifically, this issue was identified as specific to the macOS web platform. For more comprehensive information regarding this resolved issue, please refer to the link provided below.

Reported Issue: https://github.com/flutter/flutter/issues/123204 

If you are currently using an older version of the Flutter SDK, we recommend upgrading to the latest Flutter version to determine if the issue persists. If you continue to experience the same scrolling performance issue with the latest version, we kindly request that you investigate the sample on other platforms, such as **`Windows`** and **`macOS desktop`** platforms. 

If the issue persists across multiple platforms, please share the output of the "flutter doctor" command for further analysis. Additionally, if possible, provide the sample in which you are encountering the issue. Alternatively, you can make the necessary modifications to the attached sample to reproduce the issue, enabling us to conduct a thorough examination and provide an appropriate solution to address the issue effectively. 

If you have recorded a video demonstrating the performance issue you've encountered, could you please share the video reference with us? This visual reference will aid in our understanding of the problem and assist us in identifying potential solutions more effectively.

**Comment by FarjanaParveen** [comment]
Hi @peer-f ,

We are suspect that the reported problem has been resolved at your end. Please let us know if you have any further queries on this. We are happy to help you.

Regards,
Farjana Parveen A
