### ISSUE TITLE
[syncfusion_flutter_datagrid] unexpected positionning of loadMoreView Widget 

### ISSUE THREAD

**Issue by chedwin41** [syncfusion/flutter-widgets#1352]
Hello, 

# Description:
I'm currently working on implementing a clean and dynamic infinite scrolling feature for my app using the Syncfusion Flutter DataGrid component. However, I've encountered an issue that needs addressing.

# Problem:
The theme I'm using is dynamic, which means I won't always have control over the background color of the page where the DataGrid is placed. Despite this, I want to display a circular progress indicator at the end of the datagrid when it's in the loading state.

The current implementation forces me to provide a background color and decorations to the loadMoreViewWidget so that it doesn't appear transparent. It seems to create a stack, positioning the loadMoreViewWidget in front of the DataGrid. This can be problematic when I don't know the background color of the page and want to maintain a clean and seamless user interface.

current display (quite ugly and i am force to know datagrid background color):
![image](https://github.com/syncfusion/flutter-widgets/assets/85499098/397c4cdb-f61d-47ed-8f3d-b09cd513fb7c)

first option now: putting a transparent background color but still ugly.
![image](https://github.com/syncfusion/flutter-widgets/assets/85499098/cba1e5e7-4ebe-4b13-b8af-ee2b90050b7e)

# Desired Solution:
I propose a more flexible and intuitive solution. Instead of the current implementation, I suggest placing the DataGrid and the loadMoreViewWidget in a row layout, with the DataGrid above and the loadMoreViewWidget below. This approach would make more sense and provide greater flexibility in accommodating various background colors and maintaining a clean and cohesive user interface.

**Comment by Tamilarasan-Paranthaman** [comment]
Hi,

Currently, in accordance with the structure of the DataGrid, the loadMoreView widget is positioned above the DataGrid at the end. However, achieving your desired outcome is still possible through the implementation of a workaround.

By utilizing the **SfDataGrid.footer** property, you can incorporate a SizedBox widget at the end of DataGrid. This positioning allows the loadMoreView widget to load just above the footer, rather than hovering over the DataGridRows. Furthermore, the flexibility to customize the footer's height according to your specifications is provided by the **SfDataGrid.footerHeight** property.

To provide you with a better understanding, we have included a code snippet and a demonstration video for your reference. Kindly review the provided sample for more comprehensive details of this solution.

```dart

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Syncfusion Flutter DataGrid')),
      body: SfDataGrid(
        source: _employeeDataSource,
        columnWidthMode: ColumnWidthMode.fill,
        columns: getColumns,
        footerHeight: 70,
        footer: const SizedBox.shrink(),
        loadMoreViewBuilder: (BuildContext context, LoadMoreRows loadMoreRows) {
          Future<String> loadRows() async {
            await loadMoreRows();
            return Future<String>.value('Completed');
          }

          return FutureBuilder<String>(
            initialData: 'loading',
            future: loadRows(),
            builder: (context, snapShot) {
              if (snapShot.data == 'loading') {
                return Container(
                    height: 60.0,
                    width: double.infinity,
                    alignment: Alignment.center,
                    child: const CircularProgressIndicator());
              } else {
                return SizedBox.fromSize(size: Size.zero);
              }
            },
          );
        },
      ),
    );
  }

```
**Sample Link: [Sample](https://github.com/syncfusion/flutter-widgets/files/12430541/sample.zip)**


https://github.com/syncfusion/flutter-widgets/assets/93904422/1ec75a8c-61d5-4dbd-9e0b-717457c202b9



Regards,
Tamilarasan

**Comment by chedwin41** [comment]
Hello,

Thanks for the answer and for the workaround. It totally fits my needs.
