### ISSUE TITLE
[syncfusion_flutter_charts: 22.2.10]Exception has occurred. StateError (Bad state: No element)

### ISSUE THREAD

**Issue by kevinxxq** [syncfusion/flutter-widgets#1356]
Hi There,
An error prompted when I update data,  the screenshot is enclosed:
![image](https://github.com/syncfusion/flutter-widgets/assets/55800697/c7183999-fd5c-455a-9842-b18c41d0cd44)

I hope below codes will help you figure out what happened:
```
  final seriesThickness = <ChartSeries<ThicknessChartData, int>>[];

    seriesThickness.clear();

    if (mainLineData.isNotEmpty) {
      var mainLine = LineSeries<ThicknessChartData, int>(
        dataSource: mainLineData,
        xValueMapper: (ThicknessChartData data, _) => data.x,
        yValueMapper: (ThicknessChartData data, _) => data.thickness,
        name: 'Main',
        color: mainColor,
      );

      seriesThickness.add(mainLine);
    }

    if (compareLineData.isNotEmpty) {
      var compareLine = LineSeries<ThicknessChartData, int>(
        dataSource: compareLineData,
        xValueMapper: (ThicknessChartData data, _) => data.x,
        yValueMapper: (ThicknessChartData data, _) => data.thickness,
        name: 'Compare',
        color: compareColor,
      );

      seriesThickness.add(compareLine);
    }
```
    
    The error took place when one of them(mainLine,compareLine) is empty.

Thank you.

**Comment by sfHariHaraSudhan** [comment]
Hi @kevinxxq,

From the provided code snippet, we understand that you need to render two series and display the trackball while updating the data points. We have prepared a simple sample to replicate the mentioned exception with two [Line Series](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/LineSeries-class.html) and by using the [TrackballBehavior.show](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TrackballBehavior/show.html) method to render the trackball and updating the data points using the [updateDataSource](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeriesController/updateDataSource.html) method. However, we are unable to replicate the mentioned exception based on the provided code snippet.

The mentioned exception occurs when attempting to access an element from a collection list that does not contain any elements. This usually happens when trying to retrieve an element at a specific index from an empty list. Therefore, we suspect that you may be calling the [TrackballBehavior.show](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TrackballBehavior/show.html) method before rendering the series itself or with an empty list.

Kindly refer the code snippet below:
```
class _DashBoardChartState extends State<DashBoardChart> {
  final seriesThickness = <ChartSeries<ThicknessChartData, int>>[];
  List<ThicknessChartData> mainLineData = [];
  List<ThicknessChartData> compareLineData = [];
  late TrackballBehavior _trackballBehavior;
  ChartSeriesController? mainLineController;
  ChartSeriesController? compareLineController;

  int mainCount = 100;
  int compareCount = 100;
  late Random random;

  @override
  void initState() {
    random = Random();
    // mainLineData = [
    //   ThicknessChartData(10, 70),
    //   ThicknessChartData(20, 30),
    //   ThicknessChartData(30, 60),
    //   ThicknessChartData(40, 90),
    //   ThicknessChartData(50, 40),
    //   ThicknessChartData(60, 20),
    //   ThicknessChartData(70, 40),
    //   ThicknessChartData(80, 10),
    //   ThicknessChartData(90, 80),
    //   ThicknessChartData(100, 50),
    // ];
    compareLineData = [
      ThicknessChartData(10, 60),
      ThicknessChartData(20, 40),
      ThicknessChartData(30, 30),
      ThicknessChartData(40, 20),
      ThicknessChartData(50, 80),
      ThicknessChartData(60, 90),
      ThicknessChartData(70, 50),
      ThicknessChartData(80, 30),
      ThicknessChartData(90, 70),
      ThicknessChartData(100, 20),
    ];

    _trackballBehavior = TrackballBehavior(
      enable: true,
    );
    super.initState();
  }

  void updateDataPoints(Timer timer) {
    _trackballBehavior.show(50, 40, 'point');
    mainCount = mainCount + 10;
    mainLineData.add(
      ThicknessChartData(
        mainCount,
        random.nextInt(100),
      ),
    );

    mainLineController!.updateDataSource(
      addedDataIndex: mainLineData.length - 1,
    );

    compareCount = compareCount + 10;
    compareLineData.add(
      ThicknessChartData(
        compareCount,
        random.nextInt(100),
      ),
    );
    compareLineController!.updateDataSource(
      addedDataIndex: compareLineData.length - 1,
    );
  }

  @override
  Widget build(BuildContext context) {
    Timer.periodic(const Duration(milliseconds: 200), updateDataPoints);
    seriesThickness.clear();

    final LineSeries<ThicknessChartData, int> mainLine =
        LineSeries<ThicknessChartData, int>(
      dataSource: mainLineData,
      xValueMapper: (ThicknessChartData data, _) => data.x,
      yValueMapper: (ThicknessChartData data, _) => data.y,
      onRendererCreated: (controller) {
        mainLineController = controller;
      },
    );

    seriesThickness.add(mainLine);

    if (compareLineData.isNotEmpty) {
      final LineSeries<ThicknessChartData, int> compareLine =
          LineSeries<ThicknessChartData, int>(
        dataSource: compareLineData,
        xValueMapper: (ThicknessChartData data, _) => data.x,
        yValueMapper: (ThicknessChartData data, _) => data.y,
        onRendererCreated: (controller) {
          compareLineController = controller;
        },
      );

      seriesThickness.add(compareLine);
    }
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: SfCartesianChart(
          primaryXAxis: NumericAxis(),
          primaryYAxis: NumericAxis(),
          series: seriesThickness,
          trackballBehavior: _trackballBehavior,
        ),
      ),
    );
  }
}
```
We recommend that you share a detailed code snippet that shows where the [TrackballBehavior.show](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TrackballBehavior/show.html) method is called and how the data points are updated using the [updateDataSource](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeriesController/updateDataSource.html) method or setState with the respective use case. Additionally, please modify the attached sample below to reproduce the mentioned behavior on your end. With those additional details, it will be very useful for us to provide the best possible solution from our end.

Regards,
Hari Hara Sudhan. K.
[495793.zip](https://github.com/syncfusion/flutter-widgets/files/12453467/495793.zip)
