### ISSUE TITLE
syncfusion_flutter_datagrid First selected all check box, click on the next page, found that the state has not been selected

### ISSUE THREAD

**Issue by hardgit** [syncfusion/flutter-widgets#1378]
Author Hello, I found a problem when using your plugin, maybe my usage is wrong

syncfusion_flutter_datagrid^22.2.11, 
when I click to select all the checkboxes, I click Next Page, and the checkbox state is not selected.
What should I do, please? Looking forward to your reply.

 code
![image](https://github.com/syncfusion/flutter-widgets/assets/31436497/b07b3e1a-955a-473a-a750-703c6b5e2a30)

video

https://github.com/syncfusion/flutter-widgets/assets/31436497/09b99468-405e-4eb1-958c-b5a9f862c69b

The other question is how do we get rid of this? Or how to customize?
![image](https://github.com/syncfusion/flutter-widgets/assets/31436497/1dd89a71-3b35-4e42-9115-5934555a4b24)

**Comment by hardgit** [comment]
Selecting All means selecting all items, including the checkboxes on the next page

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @hardgit,

**Regarding: When I click to select all the checkboxes, I click Next Page, and the checkbox state is not selected.**

Could you please provide us with more details regarding your requirements? Specifically, we would like to know whether you are loading all the rows into the DataGrid during the initial loading phase or if you are dynamically building the rows for each page by overriding the **`handlePageChange`** method in your sample. Additionally, kindly share more information about your use case and the specific requirements you are aiming to fulfill. 

**Regarding: The other question is how do we get rid of this? Or how to customize?**

Currently, the DataGrid does not offer support for customizing or removing the page details label.

Regards,
Tamilarasan

**Comment by hardgit** [comment]
> 
Hello, the functionality I want to achieve is that when I click the "Select All" button in the header, both the checkboxes and the rows should be selected. However, when I click on the next page, they are not selected, and when I return to the previous page, the previously selected items lose their selection status, as shown in the attached video. Additionally, I also need to retrieve the bean objects that I have already selected. Here is my code. Please take a look.
[23971641.zip](https://github.com/syncfusion/flutter-widgets/files/12546769/23971641.zip)

**Comment by hardgit** [comment]
In addition, concerning the DataGrid Page Details label, I would like to display it in another language because it doesn't blend well with the rest of the text. I hope we can enhance this small feature.

**Comment by Tamilarasan-Paranthaman** [comment]
@hardgit,

In the provided sample, you have chosen to construct rows exclusively for the corresponding page by overriding the **`handlePageChange`** method. This approach involves retrieving the rows selected on the current page and subsequently setting those rows within the `DataGridController.selectedRows` when navigating back to that page. It's important to note that this strategy may encounter limitations when used in scenarios where rows are exclusively built for the current page through `handlePageChange`. This is because the newly constructed rows (hash codes) differ from the previous ones.

In such cases, alternative approaches should be considered. For instance, instead of storing entire selected rows, you can capture the index of the selected rows on the current page and subsequently set the rows by retrieving them using their respective indices. Additionally, you can identify unique values for the rows, such as customer or product IDs or names, to manage row selection.

For your reference, please review the following code snippet and attached sample, which demonstrates the approach of obtaining selected row indices and setting rows based on those indices. This method can provide a more effective solution for your scenario.

```dart
Map<String, List<int>> selectedRowsCollection = {};      


 SizedBox(
            height: 60,
            child: SfDataPager(
              pageCount: ((_employees.length / _rowsPerPage).ceil()).toDouble(),
              direction: Axis.horizontal,
              delegate: _employeeDataSource,
              controller: _dataPagerController,
              onPageNavigationStart: (int pageIndex) {
                List<int> selectedRowsIndex = [];
                for (var row in _dataGridController.selectedRows) {
                  int index = _employeeDataSource.effectiveRows.indexOf(row);
                  selectedRowsIndex.add(index);
                }
                selectedRowsCollection[_dataPagerController.selectedPageIndex
                    .toString()] = selectedRowsIndex;
              },
              onPageNavigationEnd: (int pageIndex) {
                if (selectedRowsCollection.containsKey('$pageIndex') &&
                    selectedRowsCollection['$pageIndex'] != null &&
                    selectedRowsCollection['$pageIndex']!.isNotEmpty) {
                  List<DataGridRow> selectedRows = [];
                  for (var index in selectedRowsCollection['$pageIndex']!) {
                    selectedRows.add(_employeeDataSource.effectiveRows[index]);
                  }
                  _dataGridController.selectedRows = selectedRows;
                }
              },
            ),
          ),

```

**Sample Link: https://www.syncfusion.com/downloads/support/directtrac/general/ze/sample1498037644** 


**Regarding**: I would like to display it in another language because it doesn't blend well with the rest of the text.

We have already implemented localization support for this static label to facilitate its translation into your preferred language. You can achieve this by configuring the `MaterialApp.locale` property to correspond with the desired locale. 

As illustrated in the attached sample, we have set the application's locale to Chinese. You can reference the provided sample for guidance on implementing this localization feature in your own application.

```dart
import 'package:flutter/material.dart';
import 'package:syncfusion_flutter_datagrid/datagrid.dart';
import 'package:syncfusion_localizations/syncfusion_localizations.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

void main() {
  runApp(MaterialApp(
      localizationsDelegates: const [
        GlobalMaterialLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        SfGlobalLocalizations.delegate
      ],
      supportedLocales: const [
        Locale('zh'),
        Locale('ar'),
        Locale('fr'),
      ],
      locale: const Locale('zh'),
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const SfDataGridDemo()));
}

class SfDataGridDemo extends StatefulWidget {
  const SfDataGridDemo({Key? key}) : super(key: key);

  @override
  SfDataGridDemoState createState() => SfDataGridDemoState();
}

```

https://github.com/syncfusion/flutter-widgets/assets/93904422/94852fde-760e-4409-9cd6-7f286f40fee3

**Comment by hardgit** [comment]
Hello! @Tamilarasan-Paranthaman Thank you very much for your help. However, I found that I didn't receive the callback listener when I clicked on the checkbox. This prevents me from promptly retrieving the selected rows from the user. I can get the index of the row that the user clicked on using onCellTap, but I can't get the listener when I click on the checkbox. Can you provide a responsive listener?

**Comment by Tamilarasan-Paranthaman** [comment]
@hardgit,

The **`onCellTap`** callback is triggered when you tap on DataGrid row cells. If you tap on a checkbox within the grid, the tap event is intercepted and handled by the `Checkbox` itself, leading to the appropriate selection or deselection process. Consequently, in such cases, the `onCellTap` event is not propagated to the DataGrid.

To meet your requirements in this scenario, we recommend using the **`onSelectionChanged`** callback. This callback is invoked after a row is selected, providing the selected rows. Within this callback, you can easily identify the row indices from the `DataGridSource.effectiveRows' collection. For a more detailed implementation, please refer to the following code snippet.

```dart
SizedBox(
            height: constraints.maxHeight - dataPagerHeight,
            child: SfDataGrid(
              source: _employeeDataSource,
              controller: _dataGridController,
              onSelectionChanged: (addedRows, removedRows) {
                List<int> addedRowIndexes = addedRows
                    .map(
                        (row) => _employeeDataSource.effectiveRows.indexOf(row))
                    .toList();
                for (var index in addedRowIndexes) {
                  // The header row is not considered here
                  // since the header row is not part of the
                  // effective rows collection
                  print(index);
                }
              },
              selectionMode: SelectionMode.multiple,
              navigationMode: GridNavigationMode.row,
              showCheckboxColumn: true,
              columnWidthMode: ColumnWidthMode.fill,
              columns: getColumns,
            ),
          ),

```

**Comment by hardgit** [comment]
Thank you very much for your assistance. You can close this issue now.
