### ISSUE TITLE
Null check operator used on a null value syncfusion_flutter_charts/src/circular_chart/base/circular_area.dart

### ISSUE THREAD

**Issue by mdmota** [syncfusion/flutter-widgets#1387]
[stack.txt](https://github.com/syncfusion/flutter-widgets/files/12566440/stack.txt)
syncfusion_flutter_charts: ^22.2.11
I'm getting several errors similar to this in Firebase Crashlytics

CircularArea._performPointerMove
io.flutter.plugins.firebase.crashlytics.FlutterError - Null check operator used on a null value. Error thrown Instance of 'ErrorDescription'.
package:syncfusion_flutter_charts/src/circular_chart/base/circular_area.dart:149

**Comment by sfHariHaraSudhan** [comment]
Hi @mdmota,

We suspect that the mentioned exception might occurs while using the [onChartTouchInteractionMove](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCircularChart/onChartTouchInteractionMove.html) callback in the [SfCircularChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCircularChart-class.html) but Unfortunately, we are unable to replicate the mentioned exception based on the provided call stack. We have tried to replicate the mentioned exception using  [onChartTouchInteractionMove](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCircularChart/onChartTouchInteractionMove.html) callback in [Doughnut Series](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DoughnutSeries-class.html), [Pie Series](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/PieSeries-class.html) and [RadialBar Series](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/RadialBarSeries-class.html) with and without data points. 

However, we recommend you share code snippet or sample to reproduce the mentioned exception and it will be very useful for us to provide the best possible solution from our end.

Regards,
Hari Hara Sudhan. K.

**Comment by sfHariHaraSudhan** [comment]
Hi @mdmota,

From the provided query, we understand that you are using multiple graphs, therefore we have also checked with multiple [SfCircularChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCircularChart-class.html) using the [onChartTouchInteractionMove](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCircularChart/onChartTouchInteractionMove.html) callback to replicate the mentioned exception. Unfortunately, we are unable to replicate the mentioned exception from our end. 

We require some clarifications in specific, regarding the below mentioned points.

1. To ensure that the mentioned exception is due to the [onChartTouchInteractionMove](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCircularChart/onChartTouchInteractionMove.html) callback only, we need to know whether you are using the [onChartTouchInteractionMove](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCircularChart/onChartTouchInteractionMove.html) callback in your application or not.
2. If the [onChartTouchInteractionMove](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCircularChart/onChartTouchInteractionMove.html) callback is used, then we need to know the use case or purpose of using that callback and in which graph it is used. 
3. Also, we recommend you share the code snippet of the particular graph alone in which the [onChartTouchInteractionMove](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCircularChart/onChartTouchInteractionMove.html) callback is used.
4. If possible, share any recording or snapshot regarding when and where the exception occurs in your application with a detailed explanation.

With that additional information, it will be very useful for us to replicate the mentioned exception and to provide the best possible from our end.

Regards,
Hari Hara Sudhan. K.

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket with requested details, if you still face an issue with latest version.
