### ISSUE TITLE
Issues with rendering and layout of SfCartesianChart in flutter

### ISSUE THREAD

**Issue by harsuu942** [syncfusion/flutter-widgets#1407]
I'm encountering multiple issues with the rendering and layout of SfCartesianChart in my application. I have implemented charts for both the Stocks and Crypto sections, but the charts are looking messy and not displaying the data as expected.

Specific Problems:

The charts in both the Stocks and Crypto sections are looking cluttered and not displaying data clearly.
The layout of the charts is not visually pleasing, and I would like to improve the aesthetics.
I'm using SfCartesianChart with a DateTimeCategoryAxis for the X-axis and NumericAxis for the Y-axis and and for series I have using SplineSeries that series xValueMapper having datetime format value and yValueMapper having percentageChange that need to be display.
For individual index I have using  HiloOpenCloseSeries to rendering individual chart

Expected Behavior:
I expect the charts to:

Display the data for Dow Jones, Nasdaq, and S&P clearly in the Stocks section.
Display data for cryptocurrencies clearly in the Crypto section.
Have a visually appealing and organized layout.

Actual Behavior:
The charts are currently not meeting the above expectations. They are cluttered and don't provide a clear representation of the data.

**Are there any best practices or tips for rendering multiple charts in a single view using SfCartesianChart?
How can I improve the layout and visual appeal of the charts?
Is there a recommended way to handle multiple charts for different data series, like Dow Jones, Nasdaq, and S&P, in a single view?**

I have attached a screen shot for rending layout and also shared dummy payload as well

![WhatsApp Image 2023-09-03 at 6 16 09 PM](https://github.com/syncfusion/flutter-widgets/assets/17287262/ce03b9a3-1bf3-4f2b-a012-b54de8fc2f9f)
![WhatsApp Image 2023-09-08 at 12 28 45 AM](https://github.com/syncfusion/flutter-widgets/assets/17287262/ef583fb3-aa47-4980-8037-5f9bc1a55329)

[crypto.txt](https://github.com/syncfusion/flutter-widgets/files/12652700/crypto.txt)

**Comment by sfHariHaraSudhan** [comment]
Hi @harsuu942,

We have analyzed your query and attempted to replicate the behavior you mentioned using the provided JSON data. Unfortunately, we were unable to replicate the behavior. However, we would like to inform you that you can avoid this behavior and improve the performance of the chart by following the suggestions below.

1. Based on the provided JSON data, it seems that the collapsed rendering of series with one another is caused by the non-linear data points. The data points given to the [DateTimeCategoryAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeCategoryAxis-class.html) are linear in descending order, but the data points of the high, low, open, close, and percentageChange values are not in a linear manner. To avoid this behavior, you can try using the [sortingOrder](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianSeries/sortingOrder.html) property and [sortFieldValueMapper](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianSeries/sortFieldValueMapper.html) property to sort the given data points. I have shared the User Guide documentation link for your reference on the sorting feature - https://help.syncfusion.com/flutter/cartesian-charts/series-customization#sorting.
2. You can also use the [DateTimeAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeAxis-class.html) to render a large number of data points instead of the [DateTimeCategoryAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeCategoryAxis-class.html). This will render the data points in a consecutive manner and improve the performance of the chart.
3. Furthermore, you can use the [axes](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/axes.html) property to render multiple axes based on your requirements for each series with different data sources in a single chart. This will ensure that the chart looks neat and provides better clarity. I have shared the User Guide documentation link for your reference on multiple axes - https://help.syncfusion.com/flutter/cartesian-charts/axis-customization#multiple-axes.

If you continue to experience the mentioned behavior even after trying the suggestions provided above, we recommend that you share a sample in a runnable state or a code snippet for both the stock chart and crypto chart, along with a detailed explanation on how to reproduce the behavior. Additionally, provide the JSON data points for both the crypto chart and stock chart, along with any recordings of the chart rendering. This additional information will be very helpful for us to provide the best possible solution.

Regards,
Hari Hara Sudhan. K.

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket with requested details, if you still face an issue with latest version.
