### ISSUE TITLE
Incorrect Axis Label Interval

### ISSUE THREAD

**Issue by MishaCM** [syncfusion/flutter-widgets#1409]
primaryXAxis: NumericAxis(
                  title: AxisTitle(text: 'Question No.'),
                  interval: 1,
                  decimalPlaces: 0,
                  enableAutoIntervalOnZooming: false),
                  
When the no. of values in the axis exceeds 10, the interval becomes 2 instead of 1 as specified in the NumericAxis(). 
And if the length exceeds 30, the interval automatically becomes 3 for the values >20.

![Screenshot_20230919_145424](https://github.com/syncfusion/flutter-widgets/assets/97153112/1745e57e-c980-4300-be2b-9533ec5be35c)

Here, the interval given is 1, but it becomes 2 for after 10.

Expected Output:
Nee the same interval for the axis even when the no. of values exceeds 10. Or provide the same interval.

**Comment by sfHariHaraSudhan** [comment]
Hi @MishaCM,

Based on the provided snapshot, we understand that the axis labels on the x-axis are getting hidden when they collide with each other labels and this is because the default value of the [labelIntersectAction](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/labelIntersectAction.html) property is [AxisLabelIntersectAction.hide](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/AxisLabelIntersectAction.html). As the tick line is rendered properly for each specified [interval](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/interval.html), the interval property of the x-axis is functioning correctly, and we recommend that you set the [labelIntersectAction](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/labelIntersectAction.html) property as [AxisLabelIntersectAction.none](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/AxisLabelIntersectAction.html) to render all the axis labels visible even if they collided with each other or to any other types based on your requirement.

We have shared the UserGuide Documentation and Sample Browser links below for your reference regarding the smart axis labels feature.

UG : https://help.syncfusion.com/flutter/cartesian-charts/axis-customization#smart-axis-labels.
SB : https://flutter.syncfusion.com/#/cartesian-charts/axis-features/handling-labels-collision.

If you have further queries, please get back to us.

Regards,
Hari Hara Sudhan. K.
