### ISSUE TITLE
HiloSeries chart dot issue while scrolling and padding between line and dataLabelSettings

### ISSUE THREAD

**Issue by anis-mansuri** [syncfusion/flutter-widgets#1414]
I'm using HiloSeries
I get this dot when I scroll the graph. If I don't use DataLabelSettings then dots are not coming.
How can I connect a round Container with the line, I need to remove the padding.
<img width="327" alt="Screenshot 2023-09-20 at 1 41 53 PM" src="https://github.com/syncfusion/flutter-widgets/assets/58723574/68d217ae-9e77-49cc-a940-43afff521377">

**Comment by sfHariHaraSudhan** [comment]
Hi @anis-mansuri,

We have prepared a sample to display the specified number of [Hilo Segments](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/HiloSegment-class.html) at load time using the [autoScrollingDelta](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/autoScrollingDelta.html) and [autoScrollingMode](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/autoScrollingMode.html) properties. Additionally, we have made the remaining [Hilo Segments](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/HiloSegment-class.html) visible while scrolling the chart horizontally by setting the [zoomMode](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ZoomPanBehavior/zoomMode.html) property as [ZoomMode.x](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ZoomMode.html) in the [ZoomPanBehavior](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ZoomPanBehavior-class.html). In this sample, we have also utilized the [dataLabelSettings](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianSeries/dataLabelSettings.html) property to render the data label for the [Hilo Series](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/HiloSeries-class.html). Unfortunately, we were unable to replicate the mentioned dot behavior from our end while scrolling the chart horizontally.

However, we suspect that you have enabled the [showIndicationForSameValues](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/HiloSeries/showIndicationForSameValues.html) property in the [Hilo Series](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/HiloSeries-class.html) which renders the small line for the [Hilo Segments](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/HiloSegment-class.html) with same high and low values and so that the mentioned dot behavior might be occurred. 

Shared the Sample Browser link below regarding the [Hilo Series](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/HiloSeries-class.html) for your reference.
SB : https://flutter.syncfusion.com/#/cartesian-charts/chart-types/financial-charts/high-low-chart.

Also attached the sample and recording below for your reference. We recommend you check whether the [showIndicationForSameValues](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/HiloSeries/showIndicationForSameValues.html) property is enabled or not and also to share the sample by modifying it according to your needs to reproduce the mentioned dot behavior. With that information it will be very useful for us to provide possible solution from our end.

**How can I connect a round Container with the line, I need to remove the padding?**

To remove the padding space between the line and the round container, You can achieve the mentioned requirement based on the below mentioned ways.

1. In the [builder](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DataLabelSettings/builder.html) property of the [DataLabelSettings](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DataLabelSettings-class.html), you can wrap the Container widget within the Align Widget, and you can set the heightFactor and widthFactor as zero according to your needs. 
2. You can use the [markerSettings](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianSeries/markerSettings.html) property of the respective series instead of rendering the Container widget in the [builder](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DataLabelSettings/builder.html) property of the [DataLabelSettings](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DataLabelSettings-class.html).

Kindly refer the code snippet below:
```
class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  late List<ChartSampleData> _data;
  late ZoomPanBehavior _zoomPanBehavior;

  @override
  void initState() {
    _data = [
      ChartSampleData(x: '20/04', high: 90, low: 60),
      ChartSampleData(x: '27/04', high: 60, low: 30),
      ChartSampleData(x: '01/06', high: 20, low: 50),
      ChartSampleData(x: '12/06', high: 40, low: 10),
      ChartSampleData(x: '14/06', high: 50, low: 30),
      ChartSampleData(x: '29/06', high: 50, low: 30),
      ChartSampleData(x: '05/07', high: 60, low: 30),
      ChartSampleData(x: '10/07', high: 50, low: 20),
      ChartSampleData(x: '16/07', high: 70, low: 40),
      ChartSampleData(x: '27/07', high: 90, low: 60),
    ];
    _zoomPanBehavior = ZoomPanBehavior(
      enablePanning: true,
      zoomMode: ZoomMode.x,
    );
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SfCartesianChart(
        primaryXAxis: CategoryAxis(
          autoScrollingDelta: 5,
          autoScrollingMode: AutoScrollingMode.start,
        ),
        primaryYAxis: NumericAxis(
          anchorRangeToVisiblePoints: false,
        ),
        series: <CartesianSeries<ChartSampleData, String>>[
          HiloSeries<ChartSampleData, String>(
            dataSource: _data,
            // shows indication for the same high and low values.
            // showIndicationForSameValues: true,
            // you can uncomment the below lines to render marker.
            // color: Colors.blue,
            // markerSettings: const MarkerSettings(
            //   color: Colors.blue,
            //   isVisible: true,
            // ),
            xValueMapper: (ChartSampleData sales, int index) => sales.x,
            highValueMapper: (ChartSampleData sales, int index) => sales.high,
            lowValueMapper: (ChartSampleData sales, int index) => sales.low,
            dataLabelSettings: DataLabelSettings(
              isVisible: true,
              builder: (data, point, series, pointIndex, seriesIndex) {
                return Align(
                  heightFactor: 0,
                  widthFactor: 0,
                  child: Container(
                    height: 10,
                    width: 10,
                    decoration: const BoxDecoration(
                      color: Colors.blue,
                      shape: BoxShape.circle,
                    ),
                  ),
                );
              },
            ),
          ),
        ],
        zoomPanBehavior: _zoomPanBehavior,
      ),
    );
  }
}

class ChartSampleData {
  final String? x;
  final num? high;
  final num? low;

  ChartSampleData({
    this.x,
    this.high,
    this.low,
  });
}
```
Snapshot : 
![image](https://github.com/syncfusion/flutter-widgets/assets/105288122/41ba4d5c-1dc8-4767-a7f8-326e69c46541)

Regards,
Hari Hara Sudhan. K.
[504022.zip](https://github.com/syncfusion/flutter-widgets/files/12684358/504022.zip)
[_504022.zip](https://github.com/syncfusion/flutter-widgets/files/12684360/_504022.zip)

**Comment by anis-mansuri** [comment]
Thanks @sfHariHaraSudhan.
Implemented the demo you shared.
