### ISSUE TITLE
[SfDataGrid] Load pagination API, not using SfDataPager for pagination, but a custom pagination selector. How can I track and restore the state of checkboxes?

### ISSUE THREAD

**Issue by hardgit** [syncfusion/flutter-widgets#1421]
Hello, I have customized a pagination selector using a List. When I click on a checkBox, I use onSelectionChanged: (addedRows, removedRows) to listen to the selected rows. When I switch pages and make API requests, I try to set the checkBox state again. However, I noticed an issue where evaluateDataSource.effectiveRows is always empty. I also tried to add dataGridRows to effectiveRows in the void buildDataGridRow(List<EvaluateEntity> data, int indexStart) function. Although effectiveRows now has data, setting dataGridController.selectedRows = selectedRows does not restore the checkBox state. Can you please advise me on what to do?

onSelectionChanged：
![image](https://github.com/syncfusion/flutter-widgets/assets/31436497/658539af-5a21-462d-834f-4e9bd075ba85)

request data：
![image](https://github.com/syncfusion/flutter-widgets/assets/31436497/4fc3d353-e6c2-40ea-991d-fec38038d5b9)

void buildDataGridRow(List<EvaluateEntity> data, int indexStart) 
![image](https://github.com/syncfusion/flutter-widgets/assets/31436497/5be46c39-eca5-417b-988d-5c2bc5f52271)

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @hardgit,


Based on the provided code snippet and details, we are not entirely certain about the issue you are encountering. The [DataGridSource.effectiveRows](https://pub.dev/documentation/syncfusion_flutter_datagrid/latest/datagrid/DataGridSource/effectiveRows.html) collection is typically used to retrieve records based on sorting and filtering criteria, and these values are updated when switching between pages. Additionally, you can access actual records from the [DataGridSource.rows](https://pub.dev/documentation/syncfusion_flutter_datagrid/latest/datagrid/DataGridSource/rows.html) property.

Could you please make the necessary adjustments to the provided sample to accurately reproduce the problem? Since you are utilizing a custom paging list, providing a reproducible sample along with this information will greatly assist us in conducting a thorough investigation and delivering an appropriate solution.

**Sample Link: [Sample](https://github.com/syncfusion/flutter-widgets/files/12701309/Sample.zip)**


Regards,
Tamilarasan

**Comment by hardgit** [comment]
The problem has been resolved. Thank you for your response.
