### ISSUE TITLE
[SfCartesianChart] Time of x axis changed when legends are all toggled to not selected

### ISSUE THREAD

**Issue by komhkomh** [syncfusion/flutter-widgets#1422]
1. When legends are all toggled to not selected, the time in x axis will change.

![11](https://github.com/syncfusion/flutter-widgets/assets/65888407/0ecf1a71-ae42-4707-853a-175daaf374c6)

2. For display the regular time, I set the minmum and maximum property of  DateTimeAxis. However, the column is cut in half so that I add/subtract one month to the minmum and maximum property and set EdgeLabelPlacement.hide. This makes the first label on the x-axis a long distance from the origin of the coordinates which is displayed in Fig.1. The effect is unsatisfactory. The ideal effect is label "Jan" is placed near the origin of the coordinates.
Is there a method which can fix this? Looking forward to your reply.
Btw, when I used  DateTimeCategoryAxis and set the minmum and maximum property. When other legends is toggle to not selected, then clicked the last legend, the app was stuck.

The code is attached below. Thanks for your patience.
```
class MainApp extends StatefulWidget {
  const MainApp({super.key});

  @override
  State<MainApp> createState() => _MainAppState();
}

class _MainAppState extends State<MainApp> {
  late List<ChartSampleData> _data;
  late TrackballBehavior _trackballBehavior;

  @override
  void initState() {
    _data = <ChartSampleData>[
      ChartSampleData(DateTime(2023, 01), 50),
      ChartSampleData(DateTime(2023, 02), 60),
      ChartSampleData(DateTime(2023, 03), 20),
      ChartSampleData(DateTime(2023, 04), 10),
      ChartSampleData(DateTime(2023, 05), 30),
      ChartSampleData(DateTime(2023, 06), 40),
      ChartSampleData(DateTime(2023, 07), 80),
      ChartSampleData(DateTime(2023, 08), 90),
      ChartSampleData(DateTime(2023, 09), 70),
      ChartSampleData(DateTime(2023, 10), 50),
      ChartSampleData(DateTime(2023, 11), 50),
      ChartSampleData(DateTime(2023, 12), 50),
    ];

    _trackballBehavior = TrackballBehavior(
      enable: true,
      shouldAlwaysShow: true,
      tooltipDisplayMode: TrackballDisplayMode.groupAllPoints,
      activationMode: ActivationMode.singleTap,
    );
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: SizedBox(
            height: 400,
            width: 500,
            child: SfCartesianChart(
              primaryXAxis: DateTimeAxis(
                  intervalType: DateTimeIntervalType.months,
                  interval: 1,
                  edgeLabelPlacement: EdgeLabelPlacement.hide,
                  maximum: DateTime(
                    2024,
                    1,
                  ),
                  minimum: DateTime(2022, 12),
                  dateFormat: DateFormat.MMM()
               
                  ),
              primaryYAxis: NumericAxis(),
              enableSideBySideSeriesPlacement: false,
              legend: Legend(isVisible: true),
              series: <CartesianSeries<ChartSampleData, DateTime>>[
                ColumnSeries<ChartSampleData, DateTime>(
                  dataSource: _data,
                  xValueMapper: (ChartSampleData sales, int index) => sales.x,
                  yValueMapper: (ChartSampleData sales, int index) => sales.y,
                ),
                ColumnSeries<ChartSampleData, DateTime>(
                  dataSource: _data,
                  xValueMapper: (ChartSampleData sales, int index) => sales.x,
                  yValueMapper: (ChartSampleData sales, int index) =>
                      sales.y - Random().nextInt(10),
                ),
              ],
              trackballBehavior: _trackballBehavior,
            ),
          ),
        ),
      ),
    );
  }
}

class ChartSampleData {
  ChartSampleData(this.x, this.y);
  final DateTime x;
  final num y;
}
```

**Comment by sfHariHaraSudhan** [comment]
Hi @komhkomh,

We have analyzed your query and understand that you need to display all the axis labels from January to December without partially hiding the [column segment](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ColumnSegment-class.html) when the legend is toggled. We would like to inform you that there is no direct option to achieve this requirement using the [DateTimeAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeAxis-class.html) and the axis labels will be rendered based on their respective positions and cannot be moved as mentioned.

Also, we have tried the mentioned behavior with [DateTimeCategoryAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeCategoryAxis-class.html). By setting the [visibleMinimum](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeCategoryAxis/visibleMinimum.html) and [visibleMaximum](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeCategoryAxis/visibleMaximum.html) exactly based on the y values of the data points, the [Column Segments](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ColumnSegment-class.html) render properly without hiding, as the default value of the [labelPlacement](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeCategoryAxis/labelPlacement.html) property in [DateTimeCategoryAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeCategoryAxis-class.html) is [LabelPlacement.betweenTicks](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/LabelPlacement.html). Therefore, the axis labels render between the ticks and the [Column Segments](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ColumnSegment-class.html) render properly. But, when we toggle the legend, the x-axis axis labels will be hidden because the [DateTimeCategoryAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeCategoryAxis-class.html) is designed based on indexing. Without the series being visible, the axis labels will not be rendered.

However, you can achieve the mentioned requirement by modifying the [minimum](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeAxis/minimum.html) and [maximum](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeAxis/maximum.html) properties of the [DateTimeAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeAxis-class.html) along with the data points according to your needs. This will prevent the [Column Segments](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ColumnSegment-class.html) from being partially hidden. With this modification, the axis labels will also be rendered near the origin, and when we toggle the legend, all the axis labels will be displayed.

Kindly refer the code snippet : 
```
class MainApp extends StatefulWidget {
  const MainApp({super.key});

  @override
  State<MainApp> createState() => _MainAppState();
}

class _MainAppState extends State<MainApp> {
  late List<ChartSampleData> _data;
  late TrackballBehavior _trackballBehavior;

  @override
  void initState() {
    _data = <ChartSampleData>[
      ChartSampleData(DateTime(2023, 01, 10), 50),
      ChartSampleData(DateTime(2023, 02), 60),
      ChartSampleData(DateTime(2023, 03), 20),
      ChartSampleData(DateTime(2023, 04), 10),
      ChartSampleData(DateTime(2023, 05), 30),
      ChartSampleData(DateTime(2023, 06), 40),
      ChartSampleData(DateTime(2023, 07), 80),
      ChartSampleData(DateTime(2023, 08), 90),
      ChartSampleData(DateTime(2023, 09), 70),
      ChartSampleData(DateTime(2023, 10), 50),
      ChartSampleData(DateTime(2023, 11), 50),
      ChartSampleData(DateTime(2023, 12), 50),
    ];

    _trackballBehavior = TrackballBehavior(
      enable: true,
      shouldAlwaysShow: true,
      tooltipDisplayMode: TrackballDisplayMode.groupAllPoints,
      activationMode: ActivationMode.singleTap,
    );
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: SfCartesianChart(
            primaryXAxis: DateTimeAxis(
              intervalType: DateTimeIntervalType.months,
              interval: 1,
              labelIntersectAction: AxisLabelIntersectAction.rotate90,
              minimum: DateTime(2023, 01),
              maximum: DateTime(2023, 12, 10),
              dateFormat: DateFormat.MMM(),
            ),
            primaryYAxis: NumericAxis(),
            enableSideBySideSeriesPlacement: false,
            legend: const Legend(
              isVisible: true,
              position: LegendPosition.right,
            ),
            series: <CartesianSeries<ChartSampleData, DateTime>>[
              ColumnSeries<ChartSampleData, DateTime>(
                dataSource: _data,
                xValueMapper: (ChartSampleData sales, int index) => sales.x,
                yValueMapper: (ChartSampleData sales, int index) => sales.y,
              ),
              ColumnSeries<ChartSampleData, DateTime>(
                dataSource: _data,
                xValueMapper: (ChartSampleData sales, int index) => sales.x,
                yValueMapper: (ChartSampleData sales, int index) =>
                    sales.y - Random().nextInt(10),
              ),
            ],
            trackballBehavior: _trackballBehavior,
          ),
        ),
      ),
    );
  }
}

class ChartSampleData {
  ChartSampleData(this.x, this.y);
  final DateTime x;
  final num y;
}
```
Snapshot:

Legend Enabled:
![image](https://github.com/syncfusion/flutter-widgets/assets/105288122/a2809d47-534f-4f23-b247-7997c3f3239c)

Legend Disabled:
![image](https://github.com/syncfusion/flutter-widgets/assets/105288122/9a47815a-b7a7-425b-bc1d-d1d52c57d8e6)

If you have further queries, please get back to us.

Regards,
Hari Hara Sudhan. K.

**Comment by komhkomh** [comment]
Thanks a lot! This method worked!
