### ISSUE TITLE
SfSignaturePad, signature breaks on iOS if there is a different min and max stroke width

### ISSUE THREAD

**Issue by igbenic** [syncfusion/flutter-widgets#1448]
I have a plain:

``` dart
return Scaffold(
  appBar: AppBar(
    title: Text("Testing signing"),
  ),
  body: const Center(
    child: Column(
      children: [
        Expanded(
          child: SfSignaturePad(
            // maximumStrokeWidth: 2,
            // minimumStrokeWidth: 2,
          ),
        )
      ],
    ),
  ),
);
```

This happens on iOS:

https://github.com/syncfusion/flutter-widgets/assets/10614250/4aa803e3-aa0e-405b-b845-682ec0120002

When I enter same stroke width it works ok

**Comment by sfHariHaraSudhan** [comment]
Hi @igbenic,

We have checked the reported issue with [SfSignaturePad](https://pub.dev/documentation/syncfusion_flutter_signaturepad/latest/signaturepad/SfSignaturePad-class.html) and have reproduced it at our end. This issue is replicated with 3.10.0 and later Flutter SDK versions because Flutter Framework uses an impeller rendering engine for iOS by default. Disabling the impeller by following the steps mentioned in the below link can resolve your issue.

Link: https://docs.flutter.dev/perf/impeller#ios

Regards,
Hari Hara Sudhan. K.

**Comment by t0uh33d1** [comment]
Hi @sfHariHaraSudhan, Is there no other option to proceed with other than disabling the impeller engine?

**Comment by igbenic** [comment]
> Hi @sfHariHaraSudhan, Is there no other option to proceed with other than disabling the impeller engine?

SF will probably have some better input about that, but for me the solution was to use same min and max stroke width, then it works fine

**Comment by t0uh33d1** [comment]
> > Hi @sfHariHaraSudhan, Is there no other option to proceed with other than disabling the impeller engine?
> 
> SF will probably have some better input about that, but for me the solution was to use same min and max stroke width, then it works fine

Yeah, I had to do the same for now.

**Comment by LokeshPalani** [comment]
Hi,
 
We are happy to hear that the solution was found by yourself. If you have any further queries, please get back to us. We are always happy to assist you.
 
Regards,
Lokesh P.

**Comment by kuhnroyal** [comment]
Thanks! I am watching that issue now.
