### ISSUE TITLE
Is it possible to have custom axis?

### ISSUE THREAD

**Issue by jamontes79** [syncfusion/flutter-widgets#146]
Can I have a custom X axis where instead text they are custom widgets?

Thanks in advance

**Comment by Dharanipalani** [comment]
Hi @jamontes79,
 
Thanks for the interest in our Flutter charts. As of now, we have given options to customize our axis labels text. You can customize the axis labels dynamically by using the onAxisLabelRender callback and while tapping the axis labels you can navigate to any URL or perform any actions using the onAxisLabelTapped callback. For more information please refer to the following help documents.
 
[https://help.syncfusion.com/flutter/cartesian-charts/axis-customization#axis-label-customization](https://help.syncfusion.com/flutter/cartesian-charts/axis-customization#axis-label-customization)
[https://help.syncfusion.com/flutter/cartesian-charts/callbacks#onaxislabelrender](https://help.syncfusion.com/flutter/cartesian-charts/callbacks#onaxislabelrender)
[https://help.syncfusion.com/flutter/cartesian-charts/callbacks#onaxislabeltapped](https://help.syncfusion.com/flutter/cartesian-charts/callbacks#onaxislabeltapped)
 
We have considered your requirement for providing custom widgets for axis labels as a feature request and we logged feedback. Since it is not in our planned list we are unable to provide the specific timeline for this and you can track the status of the feature request from the below feedback link.
 
[https://www.syncfusion.com/feedback/23096](https://www.syncfusion.com/feedback/23096)
 
You can also upvote and increase the vote count, which will get high priority. Based on the counts, the feature request will get priority and will be available as soon as possible.
 
Thanks,
Dharanitharan. P
