### ISSUE TITLE
[syncfusion_flutter_pdf_viewer] Double tap to zoom also triggers onTap callback two times

### ISSUE THREAD

**Issue by abhinavsinghring** [syncfusion/flutter-widgets#1480]

**Comment by deepika134** [comment]
The reported issue **“ The onTap callback triggers when perform double tap zoom in SfPdfViewer”** has been resolved and the fix is available in our latest November 7th weekly release. Please find the Pub.dev link below,

Package link: https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/23.1.44

We thank you for your support and appreciate your patience in waiting for this release.

**Comment by abhinavsinghring** [comment]
It's working as expected now. Thank you!
