### ISSUE TITLE
Flutter Syncfusion DataGridView NumPad Key Enter Not work fine into Flutter Web

### ISSUE THREAD

**Issue by abdulrehmananwar** [syncfusion/flutter-widgets#1499]
into flutter web when i press numpad keyenter i not comes into bottom line butt by other enter key it works fine . it also work fine into windows platform with both enter keys. sharing you windows app sample which work fine by numpad enter key. required same on web by numpad enter key

https://github.com/syncfusion/flutter-widgets/assets/62530396/635a0b98-4502-4bde-953b-f29331337178

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @abdulrehmananwar,

After testing with a simple sample where the **Focus** widget was used as the parent of the **TextField** widget, we noticed that the **Enter** key event didn't register through **Focus.onKey** on the **Web** Platform.  It appears to be an issue within the framework itself. We have identified a potentially related open issue on GitHub, which suggests that the problem lies in obtaining key events through the Focus widget. Once the framework team addresses this issue, it should resolve the problem. For further details, please refer to the link provided below.

**GitHub Link: https://github.com/flutter/flutter/issues/65170**

Regards,
Tamilarasan
