### ISSUE TITLE
[syncfusion_flutter_datagrid] DateTime with minutes not working well in SfDataGrid

### ISSUE THREAD

**Issue by Trung15010802** [syncfusion/flutter-widgets#1500]
I tried to implement datetime collum but the Date Filters UI not working well, it's have duplicate date and DatePicker not working.
![image](https://github.com/syncfusion/flutter-widgets/assets/90593296/75726604-2299-4d65-b554-aca2a65a4554)

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @Trung15010802,

In our DataGrid implementation, **we have applied a display format to DateTime values shown in the CheckBox filter within the filter popup menu. When multiple date values share the same date but differ in time, our format displays only the date without the time details**. Consequently, they might appear as duplicate values, yet they are distinct due to varying times. This allows applying filters accurately based on these distinctions.

As of now, the DataGrid doesn't have support for customizing the DateTime display format in the CheckBox filter within the filter popup menu. We have considered your request as a feature. We may implement this feature in any of our upcoming releases. 

At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We are always trying to make our products better and feature requests like yours are a key part of our product growth efforts. You can also communicate with us regarding the open features any time using our Feature Report page.    

**Feedback link:  [Support for customizing the DateTime display format in the CheckBox filter within the filter pop-up menu in Flutter | Feedback Portal (syncfusion.com)](https://www.syncfusion.com/feedback/48883/support-for-customizing-the-datetime-display-format-in-the-checkbox-filter-within)**

If you have any more specifications/suggestions to the feature request, you can add it as a comment in the portal and cast your vote to make it count.   

Currently, you can achieve your desired outcome through a workaround. Set the cell type in the DataGrid to String and convert the DateTime value to a string format when loading it into the DataGrid cell. We've provided a sample demonstrating this approach for your reference. Please review the attached sample and code snippet for further clarity.

```dart
class EmployeeDataSource extends DataGridSource {
  EmployeeDataSource(this.employees) {
    buildDataGridRows(employees);
  }

  List<Employee> employees = [];

  List<DataGridRow> dataGridRows = [];

  @override
  List<DataGridRow> get rows => dataGridRows;

  void buildDataGridRows(List<Employee> employees) {
    dataGridRows = employees
        .map<DataGridRow>((e) => DataGridRow(cells: [
              DataGridCell<int>(columnName: 'ID', value: e.id),
              DataGridCell<String>(columnName: 'Name', value: e.name),
              DataGridCell<String>(
                  columnName: 'Designation', value: e.designation),
              DataGridCell<String>(columnName: 'DOJ', value: e.doj.toString()), // convert to string.
              DataGridCell<int>(columnName: 'Salary', value: e.salary),
            ]))
        .toList();
  }
…
}

class Employee {
  Employee(this.id, this.name, this.designation, this.doj, this.salary);

  final int id;
  final String name;
  final String designation;
  final DateTime doj;
  final int salary;
}

```

**Sample Link: [DataGrid-Sample](https://github.com/syncfusion/flutter-widgets/files/13510915/Sample.zip)**


Please note that by employing this workaround, the text filter option replaces the date filter in the advanced filter menu. This is a limitation inherent to this workaround.

Regards,
Tamilarasan
