### ISSUE TITLE
[syncfusion_flutter_charts] not found type in chart base

### ISSUE THREAD

**Issue by 1712916** [syncfusion/flutter-widgets#1504]
My current flutter sdk is 3.0.5 everything oke until i run my app. 

Please help me solved this error

 pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_charts-20.4.44/lib/src/chart/base/chart_base.dart:2389:44: Error: 'PointerPanZoomUpdateEvent' isn't a type.
                  onPointerPanZoomUpdate: (PointerPanZoomUpdateEvent event) {
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^
 pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_charts-20.4.44/lib/src/chart/base/chart_base.dart:2389:19: Error: No named parameter with the name 'onPointerPanZoomUpdate'.
                  onPointerPanZoomUpdate: (PointerPanZoomUpdateEvent event) {
                  ^^^^^^^^^^^^^^^^^^^^^^

**Comment by LokeshPalani** [comment]
Hi,



We would like to inform you that this is a breaking change. The mouse pad scroll zooming for the desktop platform is now handled by the onPointerPanZoomUpdate event. As a result, we have moved the mouse pad scroll zoom to the onPointerPanZoomUpdate event instead of the onPointerSignal event. 



Here is the breaking change link: https://docs.flutter.dev/release/breaking-changes/trackpad-gestures#description-of-change



To avoid this issue please upgrade the flutter SDK version to 3.3 and above.



Regards,
Lokesh Palani.
