### ISSUE TITLE
syncfusion_flutter_charts:how to scroll by position?such as : chart.scrollToPostion(x:0.2222,y:0)

### ISSUE THREAD

**Issue by TeemozZ** [syncfusion/flutter-widgets#1508]
i need to scroll by position,such as

```
onZoomEnd: (args){
 chart.scrollToPostion(x: args.currentZoomPosition,y:0);
 }
```
how can i do?

**Comment by Chairilashar99** [comment]
nda membantu

**Comment by LokeshPalani** [comment]
Hi,



We have validated your query. You can achieve your requirement by using the [onPlotAreaSwipe](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/onPlotAreaSwipe.html) property in the SfCartesianChart. By using this property, you can scroll the chart to the desired position with the [visibleMinimum](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/NumericAxis/visibleMinimum.html) and [visibleMaximum](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/NumericAxis/visibleMinimum.html) properties in the [NumericAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/NumericAxis-class.html). We have prepared a sample to swipe the chart with scrolling using the _updateAxisRangeOnSwipe function. In the updateAxisRangeOnSwipe function, we have passed the parameter [ChartSwipeDirection](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSwipeDirection.html). In that function, we have checked the condition, If the direction is [ChartSwipeDirection.end](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSwipeDirection.html#end) and the [dataSource](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianSeries/dataSource.html) is less than the [visibleMaximum](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/NumericAxis/visibleMinimum.html), we have added the visible position to show the next position when scrolling the chart from right to left to see the desired scroll position. Otherwise, it will not scroll. Else the direction is [ChartSwipeDirection.Start](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSwipeDirection.html#start) and the [visibleMinimum](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/NumericAxis/visibleMinimum.html) is greater than zero, we have reduced the visible position to show the previous position when scrolling the chart from left to right to see the desired scroll position. We have shared a code snippet and sample for your reference. You can modify the sample based on your needs. Please let us know if you need any additional details.



**Code Snippet:**

```
import 'package:flutter/material.dart';

import 'package:syncfusion_flutter_charts/charts.dart';

 

void main() {

  return runApp(_ChartApp());

}

 

class _ChartApp extends StatelessWidget {

  @override

  Widget build(BuildContext context) {

    return MaterialApp(

      theme:

          ThemeData(brightness: Brightness.light, primarySwatch: Colors.blue),

      home: const MyChart(),

    );

  }

}

 

class MyChart extends StatefulWidget {

  const MyChart({super.key});

 

  @override

  _MyChartState createState() => _MyChartState();

}

 

class _MyChartState extends State<MyChart> {

  _MyChartState();

 

  late List<ChartSampleData> chartData;

  double axisVisibleMin = 1;

  double axisVisibleMax = 3;

  bool isLoad = false;

 

  @override

  void initState() {

    chartData = <ChartSampleData>[

      ChartSampleData(0, 5),

      ChartSampleData(1, 25),

      ChartSampleData(2, 100),

      ChartSampleData(3, 75),

      ChartSampleData(4, 33),

      ChartSampleData(5, 80),

      ChartSampleData(6, 21),

      ChartSampleData(7, 77),

      ChartSampleData(8, 8),

      ChartSampleData(9, 12),

      ChartSampleData(10, 42),

      ChartSampleData(11, 70),

      ChartSampleData(12, 77),

      ChartSampleData(13, 55),

      ChartSampleData(14, 19),

      ChartSampleData(15, 66),

    ];

    super.initState();

  }

 

  @override

  Widget build(BuildContext context) {

    return Scaffold(

      body: Center(

        child: SizedBox(

          height: 500,

          width: 500,

          child: SfCartesianChart(

            primaryXAxis: NumericAxis(

              visibleMinimum: axisVisibleMin,

              visibleMaximum: axisVisibleMax,

              interval: 1,

            ),

            primaryYAxis: NumericAxis(),

            series: <ChartSeries<ChartSampleData, num>>[

              ColumnSeries<ChartSampleData, num>(

                dataSource: chartData,

                xValueMapper: (ChartSampleData sales, _) => sales.x,

                yValueMapper: (ChartSampleData sales, _) => sales.y,

              ),

            ],

            onPlotAreaSwipe: (ChartSwipeDirection direction) =>

                _updateAxisRangeWhenSwipe(direction),

          ),

        ),

      ),

    );

  }

 

  void _updateAxisRangeWhenSwipe(ChartSwipeDirection direction) {

    if (direction == ChartSwipeDirection.end &&

        (axisVisibleMax + 3.toDouble()) < chartData.length) {

      isLoad = true;

      setState(

        () {

          axisVisibleMin = axisVisibleMin + 3.toDouble();

          axisVisibleMax = axisVisibleMax + 3.toDouble();

        },

      );

    } else if (direction == ChartSwipeDirection.start &&

        (axisVisibleMin - 3.toDouble()) >= 0) {

      setState(

        () {

          axisVisibleMin = axisVisibleMin - 3.toDouble();

          axisVisibleMax = axisVisibleMax - 3.toDouble();

        },

      );

    }

  }

}

 

class ChartSampleData {

  final double x;

  final int y;

 

  ChartSampleData(this.x, this.y);

}

```
 
Regards,
Lokesh P.

[chart_523013_scrollposition.zip](https://github.com/syncfusion/flutter-widgets/files/13406340/chart_523013_scrollposition.zip)
