### ISSUE TITLE
[syncfusion_flutter_pdf] How to fix: All the fonts must be embedded in PdfConformanceLevel.a2b document

### ISSUE THREAD

**Issue by MacDeveloper1** [syncfusion/flutter-widgets#1536]
When I use a none-`none` conformance level I get the assertion error

> All the fonts must be embedded in PdfConformanceLevel.a2b document

How can I fix that? Should I actually use the conformance on creating `PdfDocument`?

**Comment by irfanajaffer** [comment]
We were unable to reproduce the reported issue when conformance level is set as PdfConformanceLevel.none. On further analysis we found that the mentioned error message, “**All the fonts must be embedded in PdfConformanceLevel.a2b document**” only occurs when the conformance level is set as PdfConformanceLevel.a2b.
If we use PdfStandardFont in PDF/A conformance, then the error message thrown is as expected. 
Since PDF/A conformance refers to adherence to the ISO standard for long-term archiving of electronic documents using the PDF format, we need to embed the font in the PDF document using PdfTrueTypeFont.

If the issue still persists, kindly provide us with a simple sample or code snippet to reproduce the issue to analyze further in this.
