### ISSUE TITLE
Seeking explanation : Gauge did not rebuild on state change

### ISSUE THREAD

**Issue by itskishankumar** [syncfusion/flutter-widgets#156]
I had 2 different guages which I had to show seperately based on a stateful value. I had wrapped the guages inside a **Widget** and used the **return** function to return the gauge, like this

```
// returning gauge based on state value
if(state1)
return gauge1
else
return gauge2

// uses marker pointer
widget gauge1() {
 return SfRadialGauge();
}

// uses needle pointer
widget gauge1() {
 return SfRadialGauge();
}
```

But this implementation gave me this error,
```
The following _TypeError was thrown building Flexible(flex: 1):
type 'NeedlePointer' is not a subtype of type 'MarkerPointer'
When the exception was thrown, this was the stack
#0      SfRadialGaugeState._needsRepaintExistingAxis
package:syncfusion_flutter_gauges/…/gauge/radial_gauge.dart:350
#1      SfRadialGaugeState._needsRepaintGauge
package:syncfusion_flutter_gauges/…/gauge/radial_gauge.dart:290
#2      SfRadialGaugeState.didUpdateWidget
package:syncfusion_flutter_gauges/…/gauge/radial_gauge.dart:182
#3      StatefulElement.update
package:flutter/…/widgets/framework.dart:4815
#4      Element.updateChild
package:flutter/…/widgets/framework.dart:3314
```

So I switched the **widget** to a **class**, and it worked fine.

```
class gauge1 extends StatelessWidget {
 @override
 Widget build(BuildContext context) {
  return SfRadialGauge();
  }
 }
```

Why was this? Can someone please explain?

**Comment by Dharanipalani** [comment]
Hi @itskishankumar,

Thanks for the interest in our Flutter gauges. Since we are unaware of your code, we unable to provide an explanation. We don't know what type you are using for **state** object and **widget** in the above-given code. So, please provide more details on it or revert us the replicating scenario in the attached sample will help us to solve your problem quicker.

sample: [G-156-gauge.zip](https://github.com/syncfusion/flutter-widgets/files/6159472/G-156-gauge.zip)


Thanks,
Dharanitharan. P
