### ISSUE TITLE
document.pages.removeAt(0); its not working null check error 

### ISSUE THREAD

**Issue by ammarghias** [syncfusion/flutter-widgets#1591]
document.pages.removeAt(0); its not working null check error

**Comment by karmegams02** [comment]
The fix for the reported issue " Null check error occurs while removing pages from specific PDF document " has been included in our weekly release v24.1.44.

 

Kindly use the following link to refer to the latest package,

[syncfusion_flutter_pdf package - All Versions (pub.dev)](https://pub.dev/packages/syncfusion_flutter_pdf/versions)
