### ISSUE TITLE
[syncfusion_flutter_pdfviewer] Can onDocumentLoadFailed returns Widget like Image?

### ISSUE THREAD

**Issue by EBBozkurt** [syncfusion/flutter-widgets#1607]
Hello Syncfusion Team,

I have a request about PDF error handling. Basically, I want an errorBuilder mechanism like in the Image Widget. Can add return Widget on `onDocumentLoadFailed` function like the Image Widget. For instance, there is a code that shows error widget when Image loading is unsuccessful. Aynı zamanda istediğim özelliğin Image widgetının doküman linki: https://api.flutter.dev/flutter/widgets/Image/errorBuilder.html

```
Image.memory(
        contentData!,
        fit: BoxFit.contain,
        errorBuilder: (context, error, stackTrace) {
          return errorWidget();
        },
      ),
```

If you return Widget (It would be nullable) on `onDocumentLoadFailed` in SfPdfViewer Widget, would be much accesible for us.

**Comment by immankumarsync** [comment]
Since, the syncfusion_flutter_pdfviewer already has the support for `onDocumentLoadFailed` callback, you can show any widget when any error occurred in loading the pdf document using the stack widget or any widget of your choice. Regrettably, we currently do not have any plans to implement this feature.
