### ISSUE TITLE
[syncfusion_flutter_calendar] Issue with calendar view pop up content views

### ISSUE THREAD

**Issue by kaseyrossanderson** [syncfusion/flutter-widgets#1612]
When you have mutliple calendar types available the user is able to click the button in mobile to open a dropdown to select their new view.

The problem is that in dark mode I'm setting the headerTextColor to a white color since my background is darker. With the way that the pop up works you are using the `headerTextColor` for the color of the text (which in my case is white). 

So since you are just showing a Container (and not setting the container to any particular color) it's defaulting to white on white.

This is your code (removed a few unnecessary items such as width logic:

```
final TextStyle style = TextStyle(color: headerTextColor, fontSize: 12);

/// For each CalendarView it adds a text widget as follows with below style
style: isSelected ? style.copyWith(color: todayColor) : style,
   
Container(
   decoration: BoxDecoration(
      color: _calendarTheme.brightness == Brightness.dark ? Colors.grey[850] : Colors.white,
   ),
   child: ListView(/* The list of Text widgets for selecting the new calendar view type */)
).

```

As you can see it's basically white on white. Is it possible that you can add a new property for handling the popup decoration? Maybe something like below:

```
SfCalendarThemeData(
   data: SfCalendarThemeData(
      viewPickerStyle: ViewPickerStyle(
         backgroundColor: myColor,
         selectedTextStyle: myPrimaryColor,
         textStyle: myTextStyle,
      ),
   ),
)
```

It would be greatly appreciated!

**Comment by IndumathiR-1995** [comment]
Hi,

Currently, we are checking this. We will validate and update to you the further details on or before January 9, 2024. We appreciate your patience until then.

Regards,
Indumathi R

**Comment by IndumathiR-1995** [comment]
Hi,

As per the shared information, we suspect your issue is “**When using the dark theme mode, dark theme doesn’t applied for allowed views popup in Flutter Calendar**”. We have prepared the simple sample and it was working fine as expected. Please find the sample from the attached link. 

If this is not your issue, please share the issue details clearly. It would be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R 


[calendartheme.zip](https://github.com/syncfusion/flutter-widgets/files/13873325/calendartheme.zip)
