### ISSUE TITLE
[syncfusion_flutter_charts] V 24.1.44 issue with combo charts on android 

### ISSUE THREAD

**Issue by ThomLen** [syncfusion/flutter-widgets#1615]
Upgraded syncfusion_flutter_charts from 23.2.7 to 24.1.44
Combo Chart from Line Carts + Column Chart is not working anymore. The Column Chart is not rendered in chart anymore. 

Downgrading to 23.2.7 fixed the issue.

This is not a long term solution for me, because of a bug in V < 23.2.7 when a combo of Line / Column / Range crashed with the Legend toggle visibility function (Type error in SfCartesianChart with Range Chart)

**Comment by Yuvaraj-Gajaraj** [comment]
We have checked the reported issue combo chart in the Android platform with line and column series, and both series are rendering properly without any issues. We weren't able to reproduce the reported issue, we are not exactly sure in what scenario the issue is replicating. So, we kindly request you to try to replicate the reported issue in the below attached test sample and revert us so that it will help us assist you in a better way.

Screenshot:
<img src='https://github.com/syncfusion/flutter-widgets/assets/61863686/e895c627-9f75-4136-92b5-2e4fe995e168' width = 300PX/>

Sample: 
[i540273.zip](https://github.com/syncfusion/flutter-widgets/files/13902755/i540273.zip)

**Comment by LavanyaGowtham2021** [comment]
Please share the requested details to proceed further on this query.
