### ISSUE TITLE
[syncfusion_flutter_xlsio] Workbook.dispose() method throws: Cannot clear an unmodifiable list

### ISSUE THREAD

**Issue by SEELELancelot** [syncfusion/flutter-widgets#1627]
https://pub.dev/packages/syncfusion_flutter_xlsio

![image](https://github.com/syncfusion/flutter-widgets/assets/36724474/277a610a-de0a-4438-b302-b33736139f8b)
![image](https://github.com/syncfusion/flutter-widgets/assets/36724474/36effd25-3a53-4cb7-8bdc-b8c65caf473a)

**Comment by mdddj** [comment]
same issius

**Comment by CoryADavis** [comment]
If you're impacted and need a workaround, you can add the package "archive" as a direct dependency, and pin it to version 3.4.9

**Comment by Kurmitha4004** [comment]
Hi @SEELELancelot  ,

We have included the fix to resolve the reported issue in our weekly Flutter release version 24.1.46. Kindly upgrade your Syncfusion packages to this new 24.1.46 version and let us know if the issue is resolved.

Flutter Package: https://pub.dev/packages/syncfusion_flutter_xlsio/versions/24.1.46

Regards,
kurmitha M.

**Comment by SEELELancelot** [comment]
Ye

**Comment by SEELELancelot** [comment]
Yes,No problem
