### ISSUE TITLE
Unable to read FDF file.

### ISSUE THREAD

**Issue by GitGud31** [syncfusion/flutter-widgets#1643]
I have an FDF file (along with the PDF version of it),[ I'm following the documentation ](https://help.syncfusion.com/flutter/pdf/working-with-forms#importing-fdf-file-to-pdf) :

```
//Loads an existing PDF document.
final PdfDocument document =
    PdfDocument(inputBytes: File('input.pdf').readAsBytesSync());

//Import the FDF into the existing form.
document.form
  .importData(File('Import.fdf').readAsBytesSync(), DataFormat.fdf);

//Save the PDF document.
File('output.pdf').writeAsBytesSync(await document.save());

```

I'm getting this error:

```
E/flutter ( 8489): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Incorrect field name.
E/flutter ( 8489): #0      PdfForm._importDataFDF.<anonymous closure> (package:syncfusion_flutter_pdf/src/pdf/implementation/forms/pdf_form.dart:353:11)
E/flutter ( 8489): #1      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
E/flutter ( 8489): #2      PdfForm._importDataFDF (package:syncfusion_flutter_pdf/src/pdf/implementation/forms/pdf_form.dart:348:11)
```

how can I fix this?

**Comment by karmegams02** [comment]
The error message “Incorrect field name” is thrown when the data in the FDF file is not associated with the PDF document. If you have any concerns, kindly provide us with the FDF file and PDF document to analyze further in this.

**Comment by irfanajaffer** [comment]
We are currently working to export the PDF into XFDF using nitro PDF. However we can able to export the PDF document using our PDF control and import and modify the form fields. 

After filling the form fields in the PDF document, it may appear empty due to the absence of the appearance dictionary. By setting the setDefaultAppearance method in PdfForm class to false, you can create the appearance dictionary. By this, the text will be visible in all PDF Viewers.

he following code sample explains how to set appearance to the PDF form fields.

```
//Loads an existing PDF document.
final PdfDocument document =
    PdfDocument(inputBytes: File('input.pdf').readAsBytesSync());

//Set the default appearance.
document.form.setDefaultAppearance(true);

//Get the loaded form field and update text.
(document.form.fields[0] as PdfTextBoxField).text = 'Updated';

//Save the PDF document.
File('output.pdf').writeAsBytesSync(await document.save());
```

**Comment by AnanthaGokulaRaman** [comment]
The FDF structure created from NitroPro software is not similar to our structure. Due to this reported behavior, we have compared and analyzed our FDF structure with that of our competitors' PDF readers (Adobe, Foxit, etc.) and confirmed that our FDF creation structures are the same. However, we have logged a feature request on our end to handle this type of FDF data structure. We do not have any immediate plans to implement this feature, but we will include it in any of our upcoming releases.

Please use the below feedback link to track the status of the feature.
https://www.syncfusion.com/feedback/51335/add-support-to-import-form-fields-in-all-valid-fdf-formats
