### ISSUE TITLE
Error in building calendar URGENT

### ISSUE THREAD

**Issue by Abdullah-Mohammed-Ali** [syncfusion/flutter-widgets#1667]
hello team, 
i had a compiling problem while running my app due to an error in the latest version of Calendar 24.2.6 the method 
    _textScaleFactor = **MediaQuery.textScalerOf(context).scale(_textScaleFactor);**

is not found 
i use flutter 3.13.9 and dart sdk 3.1.5 
I hope you fix it as soon as possible 
thanks.🙏🏻

![image](https://github.com/syncfusion/flutter-widgets/assets/32640450/333f913c-39a2-45c9-9625-7859a944e377)

**Comment by Abdelazeem777** [comment]
Same here 🥲

**Comment by Yuvaraj-Gajaraj** [comment]
In the Flutter SDK version 3.16, they have deprecated the textScaleFactor parameter. So, we have migrated our source compatible to the latest Flutter SDK version so, that you are facing the textScaler issue in your project with the old SDK version. To avoid this you can use our syncfusion_flutter_calendar and syncfusion_flutter_datepicker version from 23.2.4 and below because syncfusion_flutter_calendar depends on syncfusion_flutter_datepicker package. We have shared the related details below for your reference.

In pubspec.yaml:
```dart
syncfusion_flutter_calendar: 23.2.4
syncfusion_flutter_datepicker: 23.2.4
```

Breaking changes, https://docs.flutter.dev/release/breaking-changes/deprecate-textscalefactor

Regards,
Yuvaraj
