### ISSUE TITLE
synfusion calendar issue in parsing in latest version 24.2.6  , but working using   syncfusion_flutter_calendar: ^20.4.54

### ISSUE THREAD

**Issue by samih93** [syncfusion/flutter-widgets#1674]
i used this to covert an appointment to an event model 
@override
  EventModel? convertAppointmentToObject(
      EventModel? customData, Appointment appointment) {
    // TODO: implement convertAppointmentToObject

    String color = !appointment.color.toString().contains("(")
        ? appointment.color.withOpacity(customData!.opacity).toString()
        : getStringColorFromHex(
            appointment.color.withOpacity(customData!.opacity));

    return EventModel(
        start: appointment.startTime.toString(),
        background: color,
        end: appointment.endTime.toString(),
        title: appointment.subject,
        comment: customData.comment,
        isEvent: customData.isEvent,
        isCompleted: customData.isCompleted,
        isAllDay: appointment.isAllDay,
        opacity: customData.opacity,
        id: int.parse(appointment.id.toString()),
        recurrenceRule: appointment.recurrenceRule,
        reccurenceNote: customData.reccurenceNote,
        isReapeted: appointment.recurrenceRule != null &&
                appointment.recurrenceRule != ""
            ? true
            : false);
  }
and on tap() function  returns Class 'EventModel' has no instance getter 'notes'.
Receiver: Instance of 'EventModel'
Tried calling: notes

this is the on tap function 
 onTap: (CalendarTapDetails details) {
                if (details.targetElement == CalendarElement.appointment) {
                  EventModel eventModel = details.appointments!.first;
                  print(eventModel.reccurenceNote);
                  //print(details.date);
                  //  print(details.appointments!.first.opacity);
                  showEventDialog(eventModel, context, ref);
                }
}
return

**Comment by Mounix99** [comment]
Same to me

**Comment by Yuvaraj-Gajaraj** [comment]
We can able to replicate the reported issue at our end and we have logged a bug report for it in our feedback portal. We will fix and include the changes in our upcoming Volume 1 main release which is expected to be rolled out on 3rd week of March 2024. We will update you here once the release is rolled out and we appreciate your patience until then.

**Comment by samih93** [comment]
Thank you ,also the title of the event in daily and  weekly view not displayed , just event color without name

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @samih93 ,

We have checked the reported issue at our end and we weren't able to reproduce the reported issue, the event name is displaying properly in both the day and week view. We are not able to understand what you proposing as your requirement, we kindly request you to share more information on your requirement in detail along with screenshots or screen recordings so that it will help us assist you in a better way.

Regards,
Yuvaraj.

**Comment by samih93** [comment]
![312091966-74988fd7-8d99-4896-9ad7-861aa27cd508](https://github.com/syncfusion/flutter-widgets/assets/78031951/22331b15-edd6-4ba0-babe-d2217a5e124f)

also another issue if i click on event 
this instruction EventModel eventModel = details.appointments!.first; return an error that Class 'EventModel' has no instance getter 'notes'. and i solve it now but adding notes attribute in  class EventModel

**Comment by samih93** [comment]
event click works thank you  , but the title of event (range from to , or all day)  still not displayed

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @samih93 ,

We have checked the reported issue that the event name is not shown in the AllDay appointment in the following cases,
* Wrap the SfCalendar inside the SizedBox widget and with the minimum height and width value.
* Drag and drop the normal appointment in the AllDay appointment space.
* Directly set the isAllDay property true in the Appointment creation itself.
* Give a lengthy text to an appointment subject property.

But the reported issue is not getting replicated at our end and the appointment name is rendered properly and we are not exactly sure in what scenario the issue is replicating. So, we kindly request you to try to replicate the reported issue in the attached test sample and revert us so that it will help us assist you in a better way.

Screenshot:
![image](https://github.com/syncfusion/flutter-widgets/assets/61863686/919bd1b9-c5b8-426d-816d-1918dfd4bf5c)

Sample:
[github_1674.zip](https://github.com/syncfusion/flutter-widgets/files/14635130/github_1674.zip)

Regards,
Yuvaraj.

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket with requested details to proceed further on this.

**Comment by samih93** [comment]
it works thank you
