### ISSUE TITLE
[syncfusion_flutter_calendar ]vertical scrolling issue in timeline views 

### ISSUE THREAD

**Issue by ShivarajYadagiri** [syncfusion/flutter-widgets#1705]
When there are more meetings at the same time, in some devices I'm not able to show all appointments it takes only background color in timeline views.

![Sfcalendar](https://github.com/syncfusion/flutter-widgets/assets/150325606/4c81537a-e708-4d49-b7d2-e33837d9c589)

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @ShivarajYadagiri ,

We have checked your query at our end and as we are not able to understand what you are proposing as your requirement, we kindly request you to share us with more information on your requirement in detail along with screenshots screen recordings so that it will help us assist you in a better way.

Regards,
Yuvaraj.

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket with requested details to proceed further on this.
