### ISSUE TITLE
[syncfusion_flutter_datagrid] handlePageChange method is call multiple time when load async data.

### ISSUE THREAD

**Issue by Trung15010802** [syncfusion/flutter-widgets#1716]
As you can see, newPageIndex and oldPageIndex are 1. But handlePageChange() still calling forever

![image](https://github.com/syncfusion/flutter-widgets/assets/90593296/7c031c76-7ead-4786-8adc-434c9d5bdbb3)

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @Trung15010802,

Based on the provided code snippet, we are unable to pinpoint the exact issue you are encountering and its root cause. However, based on your implementation, we suspect that the **handlePageChangedCallBack** may be null when the new and old page indexes are the same, leading to a return of the **super method from the handlePageChange** method.

We suspect that the issue might be related to the implementation of the **DataGridSource.handlePageChange** method. When overriding this method, it is necessary to return either **`true`** or **`false`** to manage page changes effectively. In your case, where the old and new page indexes are the same, it is advisable to return false from the DataGridSource.handlePageChange method.

It's crucial to avoid calling the super method within this override. We recommend reviewing and modifying the DataGridSource.handlePageChange method to directly return true or false as needed, without invoking the super method. This adjustment may help resolve the issue you are facing.

Regards,
Tamilarasan
