### ISSUE TITLE
[syncfusion_flutter_datepicker] cellBuilder don't update when setState

### ISSUE THREAD

**Issue by bernardoveras** [syncfusion/flutter-widgets#1719]
I use logic to display a "Badge" on the calendar day if it is a busy day, however, when I update the value of my "busyDates" property, the cellBuilder component only updates when I give "CMD + S" (Saved)

<img width="597" alt="image" src="https://github.com/syncfusion/flutter-widgets/assets/56937988/1081ddf0-d439-43ef-9468-39825f93129c">

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @bernardoveras ,

We have checked the reported issue with the help of a shared code snippet and ensured the badge is rendered with the given condition and it is working fine. Unfortunately, we are not able to reproduce the reported issue as we are not exactly sure in what scenario the issue is replicating. So, we kindly request you to try to replicate the reported issue in the attached test sample and revert us so that it will help us assist you in a better way.


Screenshot:
<img src='https://github.com/syncfusion/flutter-widgets/assets/61863686/d37c6cee-04ac-40ab-a498-4d20f94e43d8' width = 200px/>



Sample: 
[github_1719.zip](https://github.com/syncfusion/flutter-widgets/files/14639631/github_1719.zip)


Regards,
Yuvaraj.
