### ISSUE TITLE
Hijri Shamsi or Jalalian Calendar support

### ISSUE THREAD

**Issue by saeed-golshan** [syncfusion/flutter-widgets#174]
Hi, 
As your widget support Hijri calendar please add support for hijri shamsi or jalalian calndar that can be found in some other libraries like:
https://pub.dev/packages/jalali_calendar
https://pub.dev/packages/persian
https://pub.dev/packages/shamsi_date
https://pub.dev/packages/persian_datetime_picker
making support can help to be more popularity for library

**Comment by Indumathi1195R** [comment]
Hi Team,

Based on the shared information, we are unable to understand your requirement will be SfCalendar or SfDateRangePicker control. If possible, can you please share your requirement with exact control? Also, we have already logged the feature requests for the “Hijri Shamsi or Jalalian Calendar support”. We will implement the Jalali and Hijri calendar feature in our upcoming 2021 Volume 2 release, which is expected to be rolled out by end of June 2021, and let you know once the release rolled out. We appreciate your patience until then.

Now, you can track the status of this report through the following Feedback link,

**Feedback link:** https://www.syncfusion.com/feedback/13023/providing-a-support-for-jalali-and-hijri-calendar-in-the-flutter-event-calendar

Also, we have logged the feature requests for Shamsi and Ghamari calendar. We will implement this feature in any of our upcoming releases.

You can also communicate with us regarding the open features any time using our Feature Report page.  

**Feedback link:** https://www.syncfusion.com/feedback/22657/providing-a-support-for-shamsi-ghamari-calendar-in-the-flutter-event-calendar

If you have any more specification/suggestions to the feature request, you can add it as a comment in the portal and cast your vote to make it count.

Regards,
Indumathi R

**Comment by saeed-golshan** [comment]
Hi again
I need implement Jalalian calendar on both of SfCalendar or SfDateRangePicker. So thanks for your responsibility and I'm so excited if I can help you for Persian translation of Month title or any part of SfCalendar and SfDateRangePicker.

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for the update.

We have logged the feature request for “**Providing a support for jalali calendar in the Flutter Date Range Picker (SfDateRangePicker)**”. We will implement this feature in any of our upcoming releases and let you once the release rolled out.

At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. We appreciate your patience until then.  
  
Thank you for requesting this feature and helping us define it. We are always trying to make our products better and feature requests like yours are a key part of our product growth efforts.  
   
We will prioritize the features every release based on the demands and we do not have an immediate plan to implement this feature since we committed with already planned work. So, this feature will be available in any of our upcoming releases.   
  
Please upvote this features to make this our priority. While this feature itself is important we will prioritize the features every release, based on the user demands. So, this feature will be available in any of our upcoming releases  
   
Feedback link: https://www.syncfusion.com/feedback/24246/providing-a-support-for-jalali-calendar-in-the-flutter-date-range-picker
   
If you have any more specification/suggestions to the feature request, you can add it as a comment in the portal and cast your vote to make it count.  

Regards,
Indumathi R
