### ISSUE TITLE
[syncfusion_flutter_datagrid] How to change header *foreground* color?

### ISSUE THREAD

**Issue by divan** [syncfusion/flutter-widgets#1747]
`SfDataGridThemeData` has `headerColor` field for setting the background color of the header.

But how to change foreground (text) color for header cells?

**Comment by abineshPalanisamy** [comment]
Hi @divan,
 
Based on the information you provided, it seems you want to change the text color of header cells. We don't provide a built-in property for this customization since the header cells are loaded from the user end. Therefore, we recommend customers to achieve this by setting the text style to the Text widget for each individual column in the GridColumn. We've attached a code snippet and a sample file for your reference. If this doesn't meet your requirements, please modify the attached sample to reproduce the issue.

- **Code snippet :**
``` dart
GridColumn(
    columnName: 'id',
    label: Container(
        padding: const EdgeInsets.all(16.0),
        alignment: Alignment.center,
        child: const Text(
           'ID',
           style: TextStyle(
            color: Colors.red,
          ),
   ))),
```

- **Sample :** 

   [SfDataGrid.zip](https://github.com/syncfusion/flutter-widgets/files/14664538/SfDataGrid.zip)

Regards,
Abinesh P
