### ISSUE TITLE
[syncfusion_flutter_charts] MajorGridLines not drawing correctly

### ISSUE THREAD

**Issue by mariodelriojimenezdam** [syncfusion/flutter-widgets#1754]
When I use a custom axis associated with a LineSeries, Grid lines aren't finished drawing with 25.1.35 version:

![Captura de pantalla 2024-03-21 082643](https://github.com/syncfusion/flutter-widgets/assets/105197514/589f3896-f3c8-431e-b8c9-b415539ca0ca)

With 23.2.7 version it works correctly, this is the code that i'm using:

Axes
![Captura de pantalla 2024-03-21 082528](https://github.com/syncfusion/flutter-widgets/assets/105197514/e2f715c6-f00e-4e00-82f4-bc0a030c6c12)

CartesianChart
![Captura de pantalla 2024-03-21 082602](https://github.com/syncfusion/flutter-widgets/assets/105197514/695d5ab4-6da5-4909-acbe-a431dc029af6)

I don't know if there is a bug or if I'm missing something...

**Comment by LokeshPalani** [comment]
Hi @mariodelriojimenezdam, 

We have validated your query and checked the reported issue. The issue is getting reproduced when the [associatedAxisName](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/associatedAxisName.html) is set in the secondary axis. As of now, you can avoid this partial gridline rendering by setting the [width](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/MajorGridLines/width.html) property to 0 in [MajorGridLines](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/MajorGridLines-class.html). We have shared a code snippet, screenshot, user guide documentation, and sample for your reference. Please let us know if you have any further needs.

We will fix the reported issue and include the changes in our weekly patch release which is expected to be rolled out on April 16, 2024. We will update you here once the release is rolled out and we appreciate your patience until then.



**UG Link,**

https://help.syncfusion.com/flutter/cartesian-charts/axis-customization#grid-lines-customization


**Code Snippet:**

``` dart
        primaryYAxis: const NumericAxis(),
        primaryXAxis: DateTimeAxis(
          dateFormat: DateFormat.yMd(),       
          ),
        axes: const <ChartAxis>[
          NumericAxis(
            majorGridLines: MajorGridLines(
              width: 0,
            ),
          ),
        ],
```

Sceenshot:

![image](https://github.com/syncfusion/flutter-widgets/assets/105289202/ab39c733-40c1-4ad9-ba8b-62cd722e475a)

Regards,
Lokesh P.

[github_1754.zip](https://github.com/syncfusion/flutter-widgets/files/14762006/github_1754.zip)

**Comment by LokeshPalani** [comment]
Hi @mariodelriojimenezdam, 

 
We would like to let you know that the reported issue is fixed and rolled out in our patch release. We kindly request you to upgrade the syncfusion_flutter_charts package to the latest version below. 

 
**Version:** https://pub.dev/packages/syncfusion_flutter_charts/versions/25.1.40  

Root cause: Gridlines rendering positions are not calculated properly with the associated axis when we map the same orientation of the axis.

If you have any further queries, please feel free to reach out to us.

 
Regards,
Lokesh P.
