### ISSUE TITLE
[syncfusion_flutter_pdfviewer] Show gray screen instead of pdf on Flutter web in deployed web app

### ISSUE THREAD

**Issue by mezplz** [syncfusion/flutter-widgets#1755]
It displayed pdf via link perfectly on local Chrome when I built my project
But then when I deploy my web app to Firebase, it shows a gray screen with this error 
HEAD https://icanhazip.com/ net::ERR_UNSAFE_REDIRECT

**Comment by immankumarsync** [comment]
@mezplz, we have tried to replicate the reported issue, but hosting a Flutter application in firebase with syncfusion_flutter_pdfviewer widget is working fine as expected.
Please find the sample link: https://sfpdfviewer-sample.web.app/

We suspect that the issue might be due to the CORS security restrictions. Kindly share the stack trace to analyze more on this issue.

**Comment by minhanh277** [comment]
These are the errors shown on console
![IMG_5733](https://github.com/syncfusion/flutter-widgets/assets/125531126/f897811b-16e2-4ae7-9b54-8abbd44c56a9)

![IMG_5735](https://github.com/syncfusion/flutter-widgets/assets/125531126/7a9deadb-375e-4fa9-986f-4734f19b0e0e)

**Comment by mezplz** [comment]
<img width="177" alt="image" src="https://github.com/syncfusion/flutter-widgets/assets/50950694/06ce8be4-6693-4413-a4a3-7022e55252c1">
<img width="421" alt="image" src="https://github.com/syncfusion/flutter-widgets/assets/50950694/eb0e0517-19fd-4715-8ac8-8e54e90133d6"> 
hi @immankumarsync  I provide some issue pictures

**Comment by mezplz** [comment]
@immankumarsync  I have just created the ticket on your support portal, thanks for your support. Hope we can figure out the problem as soon as possible.

**Comment by Deepak1799** [comment]
@mezplz , Thank you for your update
