### ISSUE TITLE
SfDateRangePicker cell hover color and cell size

### ISSUE THREAD

**Issue by EbriusQuasimodo** [syncfusion/flutter-widgets#1764]
Hi!
How to change cell hover color in date picker? Or how to remove it in order to add your own in the builder?
And how to change cell size?

Thank you in advance! :)

**Comment by harkairt** [comment]
It seems that it is currently a faded version of `selectionColor`.

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @EbriusQuasimodo ,

**Query 1: How to change the cell hover color in the date picker?**

You can able to achieve your requirement with the help of setting the selection color because the cell hover color indicates the selection color. We have shared the respective UG documentation below for your reference.

UG, https://help.syncfusion.com/flutter/daterangepicker/customizations#selection-cell-customization

**Query 2: And how to change cell size?**

Currently, we don't have an option to change the cell size in the date picker, you can only able to customize the appearance of the cell with the help of cell builder. We have shared the respective UG documentation below for your reference.

UG, https://help.syncfusion.com/flutter/daterangepicker/builders#cell-builder

Regards,
Yuvaraj.
