### ISSUE TITLE
[syncfusion_flutter_pdf] Setting Document Properties

### ISSUE THREAD

**Issue by sunilguptasg** [syncfusion/flutter-widgets#1768]
Am I missing something in the documentation? I need to set the document properties like Title, Author, Subject etc. and cannot find out how...

**Comment by jeyalakshmit** [comment]
We can set the document information properties such as Title, Author, Subject etc. Please refer to the API documentation for further details:
https://pub.dev/documentation/syncfusion_flutter_pdf/latest/pdf/PdfDocumentInformation/author.html

**Comment by sunilguptasg** [comment]
`  final Workbook workbook = Workbook();

  workbook.builtInProperties.author = userName;
  workbook.builtInProperties.title = reportName;
  workbook.builtInProperties.comments = description;
  workbook.builtInProperties.createdDate = DateTime.now();`

The PDF properties are still blank. What am I doing wrong?

**Comment by jeyalakshmit** [comment]
PDF:
We are unable to reproduce the reported issue, set the document information properties is working as expected in creation and loaded document.

```//Create a new PDF document
  PdfDocument document = PdfDocument();
  //Add a new page
  PdfPage page = document.pages.add();
  //Add PdfDocumentInformation
  document.documentInformation.author = 'Syncfusion';
  document.documentInformation.title = 'PDF';
  document.documentInformation.subject = 'PDF Creation';
  document.documentInformation.keywords = 'PDF, Syncfusion';
  document.documentInformation.creator = 'Syncfusion Software Pvt. Ltd.';
  document.documentInformation.creationDate = DateTime.now();
  document.documentInformation.modificationDate = DateTime.now();
  // document.documentInformation
  //Save the document
  File('DocumentInformation.pdf').writeAsBytesSync(document.saveSync());
  //Dispose the document
  document.dispose();
```

Output:
![MicrosoftTeams-image (4)](https://github.com/syncfusion/flutter-widgets/assets/93180080/4e7820c8-b899-4c47-87ee-fb23c6c53ec6)


Therefore, we kindly request you to share the input PDF document, complete code sample with us so that we can replicate the issue on our end. This will enable us to analyze it further and provide you with a prompt solution.

Could you please clarify whether the Excel properties are blank or the PDF properties are blank? Despite mentioning XlsIO code, you've mentioned that the PDF properties remain blank.

**Comment by sunilguptasg** [comment]
My bad - thanks, it if fine.
