### ISSUE TITLE
Offset breaks the GestureDetector in Legend

### ISSUE THREAD

**Issue by Lorenzobettega** [syncfusion/flutter-widgets#1774]
In the process of updating from version 23 to 24/25, the legend unexpectedly changed with onTapped. Upon researching, I discovered that `Offset` can interfere with the GestureDetector function. Due to this, I cannot press the button for function.

Without offset:
![IMG_6507](https://github.com/syncfusion/flutter-widgets/assets/84482292/71dceb8e-c277-4934-9aad-6a149cd0a9e8)

With offset:
![IMG_6508](https://github.com/syncfusion/flutter-widgets/assets/84482292/217e6b82-4147-4e39-aa64-d48f062d6bc7)

[syncfusion_test24 - Copia.zip](https://github.com/syncfusion/flutter-widgets/files/14792815/syncfusion_test24.-.Copia.zip)

**Comment by Lorenzobettega** [comment]
@VijayakumarMariappan do you have any updates regarding this issue?

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @Lorenzobettega ,

You can overcome and achieve your requirements with the help of using the data label builder instead of a normal data label in the legend enabled circular chart. We have shared the code snippet and screenshot below for your reference. If you have any further queries please get back to us.

```dart
DoughnutSeries<PieData, String>(
  dataLabelSettings: DataLabelSettings(
    isVisible: true,
    builder: (data, point, series, pointIndex, seriesIndex) {
      return Text('${data.y}');
    },
  ),
),
```

Screenshot:
![ScreenRecording2024-04-10at6 42 10PM-ezgif com-video-to-gif-converter (1)](https://github.com/syncfusion/flutter-widgets/assets/61863686/b08d95a9-1533-41e2-a80c-a95392bf7055)


Regards,
Yuvaraj.

**Comment by Lorenzobettega** [comment]
Thank you. I'm not sure if it's the best solution, but it has solved my problem.

**Comment by LokeshPalani** [comment]
Hi @Lorenzobettega,


We would like to let you know that the reported issue is fixed and rolled out in our patch release. We kindly request you to upgrade the syncfusion_flutter_charts package to the latest version below. 

 
 **Version:** https://pub.dev/packages/syncfusion_flutter_charts/versions/25.1.41+1


**Root cause:** Data label takes hit test even the touch position is not inside the data label.

 
If you have any further queries, please feel free to reach out to us.


Regards,
Lokesh P.
