### ISSUE TITLE
Treemap minimum weight

### ISSUE THREAD

**Issue by Andre-Coelhoo** [syncfusion/flutter-widgets#1781]
Hey everyone, I would like to know if there is a way to define a minimum weight (size). Since if I have a big weight and another small I get a rectangle too small

Best regards,
André.

**Comment by LokeshPalani** [comment]
Hi @Andre-Coelhoo,
 
We would like to inform you that the tile’s weight will be calculated based on the given values in the [wightValueMapper](https://pub.dev/documentation/syncfusion_flutter_treemap/latest/treemap/SfTreemap/weightValueMapper.html). Currently, there is no option to define the minimum weight in the [SfTreemap](https://pub.dev/documentation/syncfusion_flutter_treemap/latest/treemap/SfTreemap-class.html). This is the expected behavior of [SfTreemap](https://pub.dev/documentation/syncfusion_flutter_treemap/latest/treemap/SfTreemap-class.html).

We suggest increasing the weight of the smaller tiles to address this case. For example, if you have two tiles with weights of 1000 and 10, you can map duplicate data as 100 to 10 but show the actual value from your data source in the tooltip and label builder.


Regards,
Lokesh P.
