### ISSUE TITLE
when i used in flutter web its showing grey color screeen

### ISSUE THREAD

**Issue by Sidharth-R-07** [syncfusion/flutter-widgets#1787]
when i used pdf view in flutter see this issue
![Screenshot from 2024-04-07 10-15-04](https://github.com/syncfusion/flutter-widgets/assets/105332264/0ec6f553-b210-41c8-be0d-29265b817650)
![Screenshot from 2024-04-07 10-15-41](https://github.com/syncfusion/flutter-widgets/assets/105332264/be03ffae-a68d-4584-a773-22800e62f67a)

**Comment by immankumarsync** [comment]
Hi @Sidharth-R-07,

We tried to replicate the issue, and we tried to open the PDF document from the link that you have shared. We obtained the following error message in the browser's console screen. Please confirm us whether you too obtain the same error message.
![image](https://github.com/syncfusion/flutter-widgets/assets/93641486/0bd76171-7ec8-448b-8f2b-07818e9dfa8d)

This issue occurs due to CORS security restrictions in a web application. Please find the link to know more on this, https://help.syncfusion.com/flutter/pdf-viewer/getting-started#load-document-from-the-network

Please try to open the PDF document from other links (https://cdn.syncfusion.com/content/PDFViewer/flutter-succinctly.pdf) and check whether the PDF document is loaded properly.

Also, please ensure that you have added script reference in the index.html file.
https://help.syncfusion.com/flutter/pdf-viewer/getting-started#add-the-flutter-pdf-viewer-to-an-application

**Comment by Deepak1799** [comment]
@Sidharth-R-07 We are closing this issue since we do not have enough information to proceed further. You can reopen this anytime and share the requested details to proceed further.
