### ISSUE TITLE
[syncfusion_flutter_charts] custom intervals

### ISSUE THREAD

**Issue by Tigran-Kosemyan** [syncfusion/flutter-widgets#1797]
how to set custom intervals in numeric axis with Scale values: 0, -10, -50, -100, -200, -500, -1000, -2000, -5000, -10000, -15000
```
   primaryYAxis: NumericAxis(
                        name: "hpaAxis",
                        axisLine: AxisLine(width: 1),
                        interval: 100,
                        minimum: 0,
                        maximum: -15000,
                        opposedPosition: false,
 ),
```

**Comment by LokeshPalani** [comment]
Hi @Tigran-Kosemyan,

 

Currently, there is no direct support for custom intervals in the [NumericAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/NumericAxis-class.html). We suggest that you use the [CategoryAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CategoryAxis-class.html) in the [primaryXAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/primaryXAxis.html). By doing this, you can display the axis labels as String instead of numeric values. We have provided user guide documentation for your reference. Please let us know if you have any additional needs.

 

UG Link,

https://help.syncfusion.com/flutter/cartesian-charts/axis-types#category-axis

 

Regards,
Lokesh P.

**Comment by Tigran-Kosemyan** [comment]
> Hi @Tigran-Kosemyan,
> 
> Currently, there is no direct support for custom intervals in the [NumericAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/NumericAxis-class.html). We suggest that you use the [CategoryAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CategoryAxis-class.html) in the [primaryXAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/primaryXAxis.html). By doing this, you can display the axis labels as String instead of numeric values. We have provided user guide documentation for your reference. Please let us know if you have any additional needs.
> 
> UG Link,
> 
> https://help.syncfusion.com/flutter/cartesian-charts/axis-types#category-axis
> 
> Regards, Lokesh P.

Thank you for answer

Best regards
