### ISSUE TITLE
Scroll to top on date change [SfCalendar - CalendarView.schedule]

### ISSUE THREAD

**Issue by vgavrilovikj** [syncfusion/flutter-widgets#1802]
I made the CalendarView.schedule custom so it shows only events for one month - for example April, May, June, etc. instead of for the whole year because the items that I get from the backend are for one month only - now, that works perfectly fine.

However when I change the month from a datepicker the items are changed inside the schedule view but the list is not scrolled to top - is there any way to handle this?

Moreover - for some reason when I am on the schedule view with lots of items (60+) and I open a showModalBottomSheet() the opening of the sheet is lagging a lot.. is there a way to fix this?

**Comment by Yuvaraj-Gajaraj** [comment]
Hi,



**Query 1: However when I change the month from a datepicker the items are changed inside the schedule view but the list is not scrolled to top - is there any way to handle this?**


We have checked your query and we suspect that you can able to change the month through the date picker in SfCalendar, after navigating you can't able to scroll further. For this, we suggest you use the custom date picker and limit the date picker month view based on the available appointment date to avoid navigating to a different view.

We have prepared the workaround sample and shared it below for your reference. If you have any further queries please get back to us.

Screenshot: 
![ScreenRecording2024-04-18at9 25 12PM-ezgif com-video-to-gif-converter](https://github.com/syncfusion/flutter-widgets/assets/61863686/0f14b2c2-c2c9-4d9f-9d4a-8a7c8fbee797)


Sample: 
[i580889.zip](https://github.com/syncfusion/flutter-widgets/files/15027981/i580889.zip)


**Query 2: Moreover - for some reason when I am on the schedule view with lots of items (60+) and I open a showModalBottomSheet() the opening of the sheet is lagging a lot.. is there a way to fix this?**


We have tested the reported issue and weren't able to reproduce it at our end. as we are not exactly sure in what scenario the issue is replicating. So, we kindly request you to try to replicate the reported issue in the below attached test sample and revert us so that it will help us assist you in a better way.


Regards,
Yuvaraj.
