### ISSUE TITLE
Inquiry about Gridline Color and Width in sfdatagrid Flutter

### ISSUE THREAD

**Issue by NJashwanth** [syncfusion/flutter-widgets#1815]
I recently updated to the latest version of the sfdatagrid Flutter package and noticed a change in the gridline color and width. Previously, without any explicit customization on my part, the gridline colors were different from what I'm currently experiencing in the updated version.

In the previous version (23.x.x), the thinner gridlines provided a cleaner and less obtrusive appearance in my application. However, in the updated version, the cell borders appear thicker, which affects the overall appearance of my application.

Could you please provide guidance on how to adjust the thickness of cell borders in the updated version, particularly when using Material3? I aim to achieve the same look as in the previous version while maintaining compatibility with Material3.

**Comment by abineshPalanisamy** [comment]
Hi @NJashwanth 

Based on the information provided, it appears that the reported problem involves changes in the grid line color and StrokeWidth in the latest version of SfDataGrid for Material design. We have transitioned to new colors in SfDataGrid to align with Material 3 standards, whereas previously, we used the same colors as in Material 2. Consequently, due to the new colors in Material 3, the grid line color and width appear different.
 
To address this issue, you have the option to customize the grid line color and thickness. This can be achieved by utilizing the **SfDataGridThemeData.gridLineColor** and **SfDataGridThemeData.gridLineStrokeWidth** properties.
Please refer to the following user guide documentation links to gain a deeper understanding related to styling grid line.
 
UG  Link  - [Styling grid lines](https://help.syncfusion.com/flutter/datagrid/styles#styling-grid-lines)
 
Additionally, you can consider the code snippet below to retrieve the old gridline color.

- **Code snippet:**
```dart
SfDataGridTheme(
        data: SfDataGridThemeData(
            gridLineColor:
                // Previously used gridline color for material 3
                Theme.of(context).colorScheme.onSurface.withOpacity(0.12)),
        child: SfDataGrid(),
```

Regards,
Abinesh P

**Comment by ashok-kuvaraja** [comment]
Hi @NJashwanth,

We suspect that the reported issue has been resolved at your end. We are closing this ticket now. If you need any further assistance, you can reopen this issue. We are always happy to help you.

Regards,
Ashok K
