### ISSUE TITLE
Does it support the table‘s colspan and rowspan?

### ISSUE THREAD

**Issue by fanweiguo-tal** [syncfusion/flutter-widgets#1828]
### Use case

I want to develop  the table's colspan and rowspan,but i can‘t found  it .

### Proposal

no

**Comment by abineshPalanisamy** [comment]
Hi @fanweiguo-tal ,
 
Based on the provided information, it seems that you want to span both the columns and rows in SfDataGrid. We kindly request that you provide additional clear details regarding the expected behavior and the required scenarios on your end. Additionally, please provide reasons for requiring span support. This will greatly assist us in investigating the issue further and providing an appropriate solution as quickly as possible

Regards,
Abinesh P

**Comment by ashok-kuvaraja** [comment]
Hi @fanweiguo-tal,

We suspect that the reported issue has been resolved at your end. We're closing this issue now. if you need any further assistance, you may reopen the issue. We are always happy to help you.

Regards,
Ashok K
