### ISSUE TITLE
Donut inside a Donut Chart

### ISSUE THREAD

**Issue by Hiteshc29** [syncfusion/flutter-widgets#1830]
### Use case

<img width="409" alt="Screenshot 2024-04-25 at 11 17 16 AM" src="https://github.com/syncfusion/flutter-widgets/assets/23652725/73e7976c-f226-4876-a63a-271cc1983038">

How can we create the mentioned Donut Chart in the image? If possible please share a sample code, it would be great help. Thank you in anticipation. 

### Proposal

Mentioned in the use case

**Comment by LokeshPalani** [comment]
Hi @Hiteshc29,

You can achieve your requirements by using the [Stack](https://api.flutter.dev/flutter/widgets/Stack-class.html) widget. In the [Stack](https://api.flutter.dev/flutter/widgets/Stack-class.html) widget, you can display the two [SfCircularChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCircularChart/SfCircularChart.html) with the help of the [radius](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CircularSeries/radius.html) property in the [DoughnutSeries](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DoughnutSeries-class.html). You can display the Legend in a custom position by using the [offset](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/Legend/offset.html) property in the [Legend](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/Legend-class.html). Therefore, the Legend will be toggled, and the segment will hide only for the top of the [SfCircularChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCircularChart/SfCircularChart.html) because the top [SfCircularChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCircularChart/SfCircularChart.html) takes the interactions and does not go below the [SfCircularChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCircularChart/SfCircularChart.html). We have shared the user guide documentation link, Sample, and screenshot for your reference. You can modify the sample based on your needs.

UG Link,

https://help.syncfusion.com/flutter/circular-charts/legend#floating-legend
https://help.syncfusion.com/flutter/circular-charts/chart-types/doughnut-chart#changing-the-doughnut-size

 
Screenshot:

![image](https://github.com/syncfusion/flutter-widgets/assets/105289202/42cc89b1-d236-4e2b-be85-1f56dff9c495)

Regards,
Lokesh P.

[chart_584057.zip](https://github.com/syncfusion/flutter-widgets/files/15161661/chart_584057.zip)
