### ISSUE TITLE
Draw markers manually after the chart has been drawn without the need for a full rebuild of the chart

### ISSUE THREAD

**Issue by av4625** [syncfusion/flutter-widgets#1865]
### Use case

I'd like this feature for `SfCartesianChart` using `LineSeries`.

# Use case
When I hover on one chart I want to be able to show markers on another chart.
There are a couple of ways to already do this. One has a big performance downside and the other doesn't work for data that crosses over and has more than one data point using the same X value.

Currently you can use `onMarkerRender` to do this, but this means that you have to completely rebuild the full chart every time. This means you can't hold 60fps anymore (at least with ~1500 data points on a MacBook pro). This is how I currently do it and what can be seen in the video.

Or you can use a trackball and showByIndex to do this. This way works quite well and has got good performance as it doesn't completely rebuild the chart. The problem here is if you have more than one data point that has the same x value. Like the vertical part of the line on the left graph in the video. The trackball ends up drawing more than one marker.
Can follow here for an example of this issue: https://www.syncfusion.com/forums/188212/issues-showing-trackball-markers-how-i-want?reply=zm0s8e

https://github.com/syncfusion/flutter-widgets/assets/19472253/e3173fc8-c3de-4975-b4c6-3b62b0ea45d9

### Proposal

To do this in a more performant way I think it could be done in a few different ways.

# Option 1
`MarkerSettings` could take a list of indexes to show the markers at. Then it could have a function like `trackball.showByIndex()`, that lets you update the list of indexes that should be shown. e.g.
``` dart
// Show marker at data point index 10
markerSettings.showByIndex(<int>[10]);
// Show marker at data point index 10 and 20
markerSettings.showByIndex(<int>[10, 20]);
// Or like this and all others are removed
markerSettings.showByIndex(10);
```

# Option 2
Or `updateDataSource` could be updated to include adding and removing markers. Or have a similar function with a different name only for markers.

Having this feature would also fix another problem that I have. As you can see on the chart on the right in the video I use a trackball and the marker jumps around from line/series to line/series as the data points don't have common X values in each line/series. With this feature, I could manually decide where to draw the marker on each line/series and pick the closest X value for each line/series.

Thanks!

**Comment by LokeshPalani** [comment]
Hi ,

**Query 1: MarkerSettings could take a list of indexes to show the markers at. Then it could have a function like trackball.showByIndex(), that lets you update the list of indexes that should be shown.** 


We would like to let you know that, the trackball will rendered to a data point that is closest to the interactive position, so that when having multiple points that have the same x value it will render based on the closest point only and this is a default behavior.


**Query 2: Or updateDataSource could be updated to include adding and removing markers. Or have a similar function with a different name only for markers. Having this feature would also fix another problem that I have. As you can see on the chart on the right in the video I use a trackball and the marker jumps around from line/series to line/series as the data points don't have common X values in each line/series. With this feature, I could manually decide where to draw the marker on each line/series and pick the closest X value for each line/series.**

You can show a marker on the chart which is on the left side by extending the [TrackballBehavior](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TrackballBehavior-class.html) and creating a custom trackball. You can get the interacted data point and its index value from the [onTrackballPositionChanging](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/onTrackballPositionChanging.html) event and pass that value to the secondary chart which is on the left. In the secondary chart, disable all the override methods available in the custom trackball class. Then, you can access the controller from the [onRendererCreated](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianSeries/onRendererCreated.html) callback which has a public method [pointToPixel](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeriesController/pointToPixel.html) method, using this you can convert the data point into pixel values. After that, override the paint method in the custom trackball and paint a circle in the second chart with the help of the pixel values we found. Calling markNeedPaint in custom trackball class will help you show a marker on the second chart without rebuilding the whole chart.

In the [pixelToPoint](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeriesController/pointToPixel.html) conversion, you need to pass a data point value in this you can able to proceed in two ways, with data point and point index. 

​ Using a Data Point: Directly pass the data point value to the method, which will then return the corresponding pixel value. 
Using a Point Index: Obtain the data point value based on the point index from the second chart's data source, and then pass this value to the method to get the pixel value based on point index.

We have shared the related UG documentation below for your reference, we hope it will help you to achieve your requirements. If you have any further queries please get back to us, we are always happy to assist you.


UG,

Trackball position changing event - https://help.syncfusion.com/flutter/cartesian-charts/callbacks#ontrackballpositionchanging

onRendererCreated - https://help.syncfusion.com/flutter/cartesian-charts/callbacks#onrenderercreated-series

pointToPixel - https://help.syncfusion.com/flutter/cartesian-charts/methods#pointtopixel

Regards,
Lokesh P.

**Comment by av4625** [comment]
> We would like to let you know that, the trackball will rendered to a data point that is closest to the interactive position, so that when having multiple points that have the same x value it will render based on the closest point only and this is a default behavior.

I'm happy that this is the default behaviour, but there is some weirdness that happens that doesn't line up with this statement.
Using the example code in the community forum sometimes it draws 2 markers which means it is not only drawing the "closest" point. It does not do this all the time.
Also, if using `trackball.showByIndex(<i>)`, surely there is no "closer" point than the point at the index provided, so it should draw on that one?

Having said that, I'm happy to not use trackball in this scenario if it doesn't play nicely with multiple points with the same X value as I only want to programatically show markers. This feature request isn't asking for a change to trackball but rather a way to draw these markers programatically without requiring a full redraw of the chart (similar to how trackball does it). The nicest way I can think of is adding `showByIndex(int)` and `hide()` functions to `MarkerSettings`. This keeps it inline with other features in this library.

# Query 2
This solution sounds promising and perhaps means I don't need any new features 😊, but I think I need a little more help (sorry).
Is it this function I should override: https://github.com/syncfusion/flutter-widgets/blob/cd0b01d2bfbdf718697312a35937eb8421a7268e/packages/syncfusion_flutter_charts/lib/src/charts/behaviors/trackball.dart#L2901
Or is it this one: https://github.com/syncfusion/flutter-widgets/blob/cd0b01d2bfbdf718697312a35937eb8421a7268e/packages/syncfusion_flutter_charts/lib/src/charts/behaviors/trackball.dart#L2290

I can't find any reference to `markNeedPaint`. Could you maybe just provide an example overridden paint function that paints a marker at any random x,y or point index? I understand all the other parts like `onTrackballPositionChanging`, `onRendererCreated` and `pointToPixel`. I don't need examples how to do all that (hopefully makes it easier).

Thanks!

**Comment by av4625** [comment]
I was able to use this to make something that works for my situation. Thank you! This improved my FPS from ~15 to ~57. A great improvement!
