### ISSUE TITLE
Title: Expanding Syncfusion Table to Maximum Size When Data is Absent

### ISSUE THREAD

**Issue by EduardoYamauchi** [syncfusion/flutter-widgets#1880]
Hello,

In our system, when there is no data loaded, I would like the table to expand to fill the maximum possible size, similar to the way a widget expands. Currently, only the column headers are displayed in such cases.

Additionally, when there is some data but it does not occupy the full screen (for example, if the table can fit 10 items but we only have 2), I would still like the table to expand to the maximum possible size, including the column headers and the 2 rows. Essentially, I want the table to always fill the available space.

Is there a configuration for this? How can I achieve this behavior?

Thank you.

**Comment by abineshPalanisamy** [comment]
Hi @EduardoYamauchi ,
 
The SfDataGrid takes the width and height of its parent widget. Therefore, it occupies the space based on the parent widget's dimensions. Based on the provided details, we cannot clearly address your issue. To assist you further and better understand the problem, we kindly request that you provide additional details or a sample to replicate the expected behavior. This information will enable us to thoroughly address your request and provide an appropriate solution.
 
Regards,
Abinesh P
