### ISSUE TITLE
program to control pageing

### ISSUE THREAD

**Issue by stoneLee81** [syncfusion/flutter-widgets#189]
I have another two questions about data grid widget of paging?
1 How to use program to control paging, instead of clicking on the paging component？
2 sometimes, I don't need to show loading widget, sometime needs, can i use program to control it flexibly?

**Comment by RenugaSadagoban98** [comment]
Hi @stoneLee81,

Greetings from Syncfusion.

Please find the following response,

**How to use program to control paging, instead of clicking on the paging component？** 

You can navigate between the pages programmatically using [controller ](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpub.dev%2Fdocumentation%2Fsyncfusion_flutter_datagrid%2Flatest%2Fdatagrid%2FDataGridController-class.html&data=04%7C01%7Crenugadevi.sadagoban%40syncfusion.com%7Ceb77a99525634366c0c108d8fe672844%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C637539066307034517%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=BKvyjhVouhGe9pw%2B8dFkILTE0h0GzXOte2B45JP7AzQ%3D&reserved=0)with the following option, 
•	[nextPage](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpub.dev%2Fdocumentation%2Fsyncfusion_flutter_datagrid%2Flatest%2Fdatagrid%2FDataPagerController%2FnextPage.html&data=04%7C01%7Crenugadevi.sadagoban%40syncfusion.com%7Ceb77a99525634366c0c108d8fe672844%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C637539066307034517%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=eJheEa%2BFm8pNLc0iWXDzTo84XIfNSM4qce2DA6ciLIs%3D&reserved=0), 
•	[previousPage,](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpub.dev%2Fdocumentation%2Fsyncfusion_flutter_datagrid%2Flatest%2Fdatagrid%2FDataPagerController%2FpreviousPage.html&data=04%7C01%7Crenugadevi.sadagoban%40syncfusion.com%7Ceb77a99525634366c0c108d8fe672844%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C637539066307044510%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Mbo6Y6sUu9j0K0WtDSvSkywnjfPJvhOq6tlKBlNzUyE%3D&reserved=0) 
•	[LastPage,](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpub.dev%2Fdocumentation%2Fsyncfusion_flutter_datagrid%2Flatest%2Fdatagrid%2FDataPagerController%2FlastPage.html&data=04%7C01%7Crenugadevi.sadagoban%40syncfusion.com%7Ceb77a99525634366c0c108d8fe672844%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C637539066307044510%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=AYwYhegKKmJwW6PZWKv94G1CuZO4uxUxuOq0NiWGaZo%3D&reserved=0)
•	[nextPage](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpub.dev%2Fdocumentation%2Fsyncfusion_flutter_datagrid%2Flatest%2Fdatagrid%2FDataPagerController%2FnextPage.html&data=04%7C01%7Crenugadevi.sadagoban%40syncfusion.com%7Ceb77a99525634366c0c108d8fe672844%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C637539066307054505%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ScK3SOoIE1eSg86WBjFKMSjp8lz8WWqbJw7aHMZU%2FwU%3D&reserved=0)  
Refer following code snippets,  

```

@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: LayoutBuilder(builder: (context, constraint) {
      return Column(
        children: [
          MaterialButton(
            onPressed: () {
              controller.previousPage();
            },
            child: Text('Move Previous page'),
          ),
          SizedBox(
              height: constraint.maxHeight - 120,
              width: constraint.maxWidth,
              child: _buildDataGrid()),
          Container(
            height: 60,
            child: Align(
                alignment: Alignment.center,
                child: SfDataPager(
                  delegate: orderInfoDataSource,
                  initialPageIndex: index,
                  controller: controller,
                  pageCount: orderInfoDataSource.orders.length /
                      orderInfoDataSource.rowsPerPage,
                  direction: Axis.horizontal,
                )),
          )
        ],
      );
    }),
    );
  }
```

**sometimes, I don't need to show loading widget, sometime needs, can i use program to control it flexibly?** 

You can use onPageNavigationStrat and onPageNavigationEnd callbacks to show and hide the loading indicator when navigating between pages. 
 
You can refer to the following UG document to show and hide the loading widget, 
 
UG link: https://help.syncfusion.com/flutter/datagrid/paging#asynchronous-data-loading
