### ISSUE TITLE
Build fails on windows when I use *25.2.5

### ISSUE THREAD

**Issue by richard457** [syncfusion/flutter-widgets#1890]
### Bug description

C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(254,5): error MSB8066: Custom build for 'D:\a\flipper\flipper\apps\flipper\build\windows\x64\CMakeFiles\083e6a85e3a644d59acbf5e1be804eba\flutter_windows.dll.rule;D:\a\flipper\flipper\apps\flipper\build\windows\x64\CMakeFiles\7ea1013b22b154002d4dcfb27b53f779\flutter_assemble.rule;D:\a\flipper\flipper\apps\flipper\windows\flutter\CMakeLists.txt' exited with code 1. [D:\a\flipper\flipper\apps\flipper\build\windows\x64\flutter\flutter_assemble.vcxproj]
Build process failed.

#0      ProcessResultExtensions.exitOnError (package:msix/src/method_extensions.dart:61:7)
#1      WindowsBuild.build (package:msix/src/windows_build.dart:33:18)
<asynchronous suspension>
#2      Msix._buildMsixFiles (package:msix/msix.dart:107:31)
<asynchronous suspension>
#3      Msix._createMsix (package:msix/msix.dart:102:5)
<asynchronous suspension>
#4      Msix.create (package:msix/msix.dart:59:5)
<asynchronous suspension>
#5      main (file:***C:/Users/runneradmin/AppData/Local/Pub/Cache/hosted/pub.dev/msix-3.16.7/bin/create.dart:4:3)

### Steps to reproduce

Build fails on windows when I use *25.2.5 change all dependencies to use 25.2.5 and build windows

### Code sample

<details open><summary>Code sample</summary>

```dart
[Add your code here]
```

</details>

### Screenshots or Video

Build fails on windows when I use *25.2.5

### Stack Traces

C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(254,5): error MSB8066: Custom build for 'D:\a\flipper\flipper\apps\flipper\build\windows\x64\CMakeFiles\083e6a85e3a644d59acbf5e1be804eba\flutter_windows.dll.rule;D:\a\flipper\flipper\apps\flipper\build\windows\x64\CMakeFiles\7ea1013b22b154002d4dcfb27b53f779\flutter_assemble.rule;D:\a\flipper\flipper\apps\flipper\windows\flutter\CMakeLists.txt' exited with code 1. [D:\a\flipper\flipper\apps\flipper\build\windows\x64\flutter\flutter_assemble.vcxproj]
Build process failed.

#0      ProcessResultExtensions.exitOnError (package:msix/src/method_extensions.dart:61:7)
#1      WindowsBuild.build (package:msix/src/windows_build.dart:33:18)
<asynchronous suspension>
#2      Msix._buildMsixFiles (package:msix/msix.dart:107:31)
<asynchronous suspension>
#3      Msix._createMsix (package:msix/msix.dart:102:5)
<asynchronous suspension>
#4      Msix.create (package:msix/msix.dart:59:5)
<asynchronous suspension>
#5      main (file:***C:/Users/runneradmin/AppData/Local/Pub/Cache/hosted/pub.dev/msix-3.16.7/bin/create.dart:4:3)

### On which target platforms have you observed this bug?

Windows

### Flutter Doctor output

flutter 3.22.1

**Comment by LokeshPalani** [comment]
Hi,

 

We suspect that the mentioned exception might have occurred due to not add a final slash "/" when adding an assets folder in pubspec.yaml. We have shared details below for how to add final slash in the assets folder.

``` dart
flutter:
  assets:  
  - assets/asset_folder_name/
```

Additionally, we recommend that you check by clearing the cache using the below mentioned methods:

- Delete the build folder in the project, add the **“flutter create .”** command to run the project.
- In the Flutter terminal, add the **"flutter pub cache clean"** command to clear all the cache.
- Close the running application and then add the **"flutter clean"** command.
- Afterwards, add the **"flutter pub get"** command to get all the dependencies in the pubspec.yaml file.

 
We hope that above shared solutions will help you to resolve the issue. If you still face the mentioned exception even after clearing the cache, then kindly share with us some detailed information regarding when and where the exception occurs, along with any screenshots or recordings. With that additional information, it will be very useful for us to find a possible solution from our end.

Regards,
Lokesh P.

**Comment by richard457** [comment]
> ```dart
> asset_folder_name
> ```

But this asset_folder_name/ is a standard way of capturing the all files in folder

**Comment by richard457** [comment]
NOTE: when I downgrade package to 24* and to flutter 3.19 it works without changing anything else

**Comment by LokeshPalani** [comment]
Hi @richard457,

We have checked the reported issue for all our [Syncfusion](https://pub.dev/publishers/syncfusion.com/packages) package with the latest version, but the issue didn't get reproduced at our end. If you are still facing the same issue, please share additional information regarding the package name with version and Flutter SDK version you are using then please try to share the sample you use to reproduce the issue, it will be more helpful to us to provide a solution sooner.


Additionally, we have shared user guide documentation link for Syncfusion Compatible Package Version for your reference below. Please let us know if you need any further assistance.
 
UG Link: https://help.syncfusion.com/flutter/system-requirements#sdk-version-compatibility
 
Regards,
Lokesh P
