### ISSUE TITLE
The same appointment is displayed twice on the same day in month view.

### ISSUE THREAD

**Issue by tsumayoji1102** [syncfusion/flutter-widgets#1909]
### Bug description

When appointments count by date is over `appointmentDisplayCount` in monthSettings, same appointment is displayed twice.

In this image, `TEST3` and `工事5` are one of appointments, but their same appointment existed in same date(day of 8 and 13 are understandable.)

these days have more  appointments than length of `appointmentDisplayCount` in monthSettings.

![スクリーンショット 2024-06-06 22 45 30](https://github.com/syncfusion/flutter-widgets/assets/52852644/82a8d7c2-c901-4e73-963a-f58f33c72499)

### Steps to reproduce

1. set `appointmentDisplayCount` in monthSettings
2. add appointments which counts over the `appointmentDisplayCount` in a date
3. check the day in month view of calendar 

### Code sample

<details open><summary>Code sample</summary>

```dart
[Add your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Stack Traces

<details open><summary>Stack Traces</summary>

```dart
[Add the Stack Traces here]
```

</details>

### On which target platforms have you observed this bug?

iOS

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.6, on macOS 14.1.1 23B81 darwin-arm64, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.89.1)
[✓] Connected device (4 available)  
[✓] Network resources
```

</details>

**Comment by LokeshPalani** [comment]
Hi @tsumayoji1102,

We tried to replicate the reported issue with latest calendar version [25.2.7+1](https://pub.dev/packages/syncfusion_flutter_calendar/versions/25.2.7+1) at our end. We tried the following ways to reproduce the issue:

- We checked with the latest calendar version [25.2.7+1](https://pub.dev/packages/syncfusion_flutter_calendar/versions/25.2.7+1) to reproduce the reported issue.
- We tested by setting 5 appointments with the [appointmentDisplayCount](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/MonthViewSettings/appointmentDisplayCount.html) as 6.
- We tested by setting 5 appointments with the [appointmentDisplayCount](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/MonthViewSettings/appointmentDisplayCount.html) as 3.
- We checked in mobile, windows and web platform.

Unfortunately, we are not able to reproduce the reported issue. However, we suspect that the mentioned issue might have occurred due to duplicate appointments in your appointment list, and we recommend that you check by removing the duplicate appointments from the existing appointment list.

Additionally, we would like to let you know that by using the [appointmentDisplayCount](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/MonthViewSettings/appointmentDisplayCount.html) property of [monthViewSettings](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/SfCalendar/monthViewSettings.html) in [SfCalendar](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/SfCalendar-class.html), you can customize the number of appointments displayed in month cell only. You can’t remove or restrict the any appointment in the appointment list using this property.

UG Link: https://help.syncfusion.com/flutter/calendar/month-view#appointment-display-count

If you still face the issue, we kindly request you to try to replicate the reported issue in the below attached test sample and revert us so that it will help us assist you in a better way. 

Regards,
Lokesh P.

[gh1909.zip](https://github.com/user-attachments/files/15757047/gh1909.zip)

**Comment by tsumayoji1102** [comment]
@LokeshPalani Thank you for checking it.
After reading it, I tried to upgrade the library version of 25.2.7+1 and check them, but I found same problem.

> we suspect that the mentioned issue might have occurred due to duplicate appointments in your appointment list

When I checked it, there are not duplicated appointments.

One of way how to solve this issue temporary is to edit appointments.
if number of them per day is over the `appointmentDisplayCount`, remove the excess of them.

If you find new information about the issue, please mention me and introduce it.

**Comment by tsumayoji1102** [comment]
Hi, @PreethikaSelvam 
Just now, I create new flutter project for checking this issue and upload to github pages.
If you have a time, please check <a href="https://tsumayoji1102.github.io/ikenie_flutter/">this link</a>.
Repository is <a href="https://github.com/tsumayoji1102/ikenie_flutter">here</a>. This project is minimum to check this issue.

A day of 2024/6/16 is default (appointments length of this day and appointmentDisplayCount is equal) , but 2024/6/18 is this issue condition.

![スクリーンショット 2024-06-20 13 05 44](https://github.com/syncfusion/flutter-widgets/assets/52852644/1449f8a5-35b7-4d89-b348-d559188bee86)

**Comment by tsumayoji1102** [comment]
@PreethikaSelvam thank you for analyze my query.
I didn’t know about `isMoreAppointmentRegion`, and I understand what it is now. 
Your example code is easy to understand.

In my project, I will use this code for showing appointments of day as many as possible.
I think this issue can be solved in my project. thank you.
```
appointmentBuilder: (context, details) {
  final appointment = details.isMoreAppointmentRegion
      ? details.appointments
          .elementAt(monthAppointmentDisplayCount - 1)
      : details.appointments.first;
  return Container(
    color: appointment.color,
    child: Center(
      child: Text(
        appointment.subject,
        style: const TextStyle(color: Colors.white),
      ),
    ),
  );
},
```

**Comment by tsumayoji1102** [comment]
thank you！
