### ISSUE TITLE
Use generally accepted Dart package version numbers

### ISSUE THREAD

**Issue by mulderpf** [syncfusion/flutter-widgets#1919]
### Use case

When using different package management tools or deciding whether to upgrade a package, it is generally accepted that a major version number change, signifies that there is a potentially breaking change to be aware of.  I last had syncfusion_flutter_calendar v25.2.7.+1 and today version 26.1.35 appeared.  The previous version isn't even mentioned in the changelog, and the update to version 26 seems to be a bug fix only.  Usually major version numbers tend to be updated only with breaking changes (flutter pub / dart pub have functionality written specifically to take this into account).

### Proposal

1.  For small bug fixes, consider increasing minor version numbers instead of major version number.
2. For each version published on pub.dev, include a changelog as I have absolutely no idea what has changed and what hasn't.

**Comment by mulderpf** [comment]
I just noticed that this is still happening where major version numbers are changing, but there appears to be no breaking changes.  This breaks being able to run things like "flutter pub upgrade" as flutter sees a change from version 26.2.14 to 27.1.50 as a breaking change and won't actually update the package.  Would it be possible to update your versioning to the standard way it is done for all other flutter packages so that it works with the tooling provided, rather than always having to manually update for small changes?

**Comment by ThilipChandru** [comment]
Hi @mulderpf ,

We would like to inform you about the versioning process we are using for our Flutter widgets.

| Release Name|Version |
| ------------- | ------------- |
| Main release  | 1.1.x (Volume I)<br>  2.1.x (Volume II)  |
| Service pack release  | 1.2.x (Volume I)<br>2.2.x (Volume II)  |
|Weekly release after the main release| 1.1.x (Incremental version from the main release version)<br>1.1.x  |
|Weekly release after the service pack release|1.2.x (Incremental version from the service pack release version)<br>1.2.x |


We are conducting internal releases of the packages in order to improve stability before the final release. As a result, the main release version may not always be 1.1.0. For example, if the main release version is 1.1.37, this indicates that we have made 36 internal releases and have confirmed that version 1.1.37 is stable and ready for publication.
 
You may also notice some missing versions in the weekly releases; these follow the same procedure mentioned above.
 
Since we are following this versioning process, we are not adhering to the Flutter package versioning system, and there are currently no plans to implement it in the future.
 
Thank you for your understanding. If you have any other questions, please feel free to reach out to us.

Regards,
Thilip Chandru.
