### ISSUE TITLE
[syncfusion_flutter_pdf] Mini update in docs

### ISSUE THREAD

**Issue by Macacoazul01** [syncfusion/flutter-widgets#1921]
### Use case

on the example app for flutter web, on index.html [file](https://github.com/syncfusion/flutter-examples/blob/master/web/index.html) 

This script is added to allow the pdfs to work as expected:

```
</script>
<!-- This script installs pdf.min.js to render the PDF page as an image in the
  application and load in syncfusion_flutter_pdfviewer widget -->
<script src="//cdnjs.cloudflare.com/ajax/libs/pdf.js/2.11.338/pdf.min.js"></script>
<script type="text/javascript">
  pdfjsLib.GlobalWorkerOptions.workerSrc = "//cdnjs.cloudflare.com/ajax/libs/pdf.js/2.11.338/pdf.worker.min.js";
</script>
```

### Proposal

This should appear in the docs in the site or in the readme of the package.

Also why this package uses this version from years ago instead of a newer one?

**Comment by Macacoazul01** [comment]
this version (2.11.338) is from [Oct 2, 2021](https://github.com/mozilla/pdf.js/releases?page=3)

i'm using on my project the newer that worked without breaking everything: `2.12.313`

**Comment by immankumarsync** [comment]
Hi @Macacoazul01,
<table>
<tr>
<td>
This should appear in the docs in the site or in the readme of the package.
</td>
<td>
The UG for script references has already been added to the documentation and the readme.md file.

UG: https://help.syncfusion.com/flutter/pdf-viewer/getting-started#add-the-flutter-pdf-viewer-to-an-application

readme: https://pub.dev/packages/syncfusion_flutter_pdfviewer#web-integration
</td>
</tr>
<tr>
<td>
Also why this package uses this version from years ago instead of a newer one?</td>
<td>
We have added the minimum supported version in the documentation.
With the newer versions of pdf.js library, the below issue occurs,

```Invalid argument: Invalid array length```

when opening the document, as the document bytes will get disposed by the pdf.js library once we create the PdfJsDoc instance.

If the document bytes get disposed, the operations like text search, bookmark navigation, text selection, etc. cannot be performed.
</td>
</tr>
</table>
