### ISSUE TITLE
[SfCartesianChart] [Flutter] How to jump  programmatically to desired position?

### ISSUE THREAD

**Issue by LazyLazyCoder** [syncfusion/flutter-widgets#1924]
### Use case

Hi

I need to scroll/jump/pan (horizontally) to the desired position in FastLineSeries. I can't achieve this.
For example, I have 2000 points on the chart (Zoom enabled and zoomed, 100 points visible at a time) and I want to programmatically jump to index 1234.

I read this:
https://github.com/syncfusion/flutter-widgets/issues/1361

but PanToDirection scrolls the chart by a large and constant amount. I need to move to the desired index. Is it possible?

showByIndex works but does not automatically scroll/jump/pan the chart.

### Proposal

Add goToIndex(index) or similar

**Comment by LokeshPalani** [comment]
Hi @LazyLazyCoder,

 Currently, we do not have an option to view the specific index for the [FastLineSeries](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/FastLineSeries-class.html). However, you can achieve your outcome by using the [onRendererCreated](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/NumericAxis/onRendererCreated.html) callback in the [NumericAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/NumericAxis-class.html). This allows you to get the current visible range details using [NumericAxisController](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/NumericAxisController-class.html) to update the visible range programmatically without using set state using [rangeController](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/rangeController.html) for the [intialVisibleMinimum](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/NumericAxis/initialVisibleMinimum.html) and [initialVisibleMaximum](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/NumericAxis/initialVisibleMaximum.html) properties of [NumericAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/NumericAxis-class.html). We have prepared workaround sample to achieve your outcome for displaying the specific datapoints by tapping on the [TextButton](https://api.flutter.dev/flutter/material/TextButton-class.html). You can modify the sample based on your needs. We have shared code snippet, screen recording, user guide documentation link and sample for your reference below.

 
UG Link for rangeController in the NumericAxis: https://help.syncfusion.com/flutter/cartesian-charts/axis-customization#rangecontroller

UG Link for onRendererCreated in the NumericAxis: https://help.syncfusion.com/flutter/cartesian-charts/callbacks#onrenderercreated-axis

Code Snippet:

``` dart
late List<ChartSampleData> data;
late NumericAxis xAxis;
late NumericAxisController _numericAxisController;

RangeController rangeController = RangeController(
  start: 0,
  end: 2000,
);

@override
void initState() {
  super.initState();

  data = generateRandomData(2000);

  xAxis = NumericAxis(
    isVisible: true,
    onRendererCreated: (NumericAxisController controller) =>
        _numericAxisController = controller,
    initialVisibleMinimum: rangeController.start.toDouble(),
    initialVisibleMaximum: rangeController.end.toDouble(),
  );
}

SfCartesianChart(
  primaryXAxis: xAxis,
  primaryYAxis: const NumericAxis(),
  title: const ChartTitle(text: 'Half yearly sales analysis'),
  series: <CartesianSeries<ChartSampleData, double>>[
    FastLineSeries<ChartSampleData, double>(
      dataSource: data,
      xValueMapper: (sales, _) => sales.x,
      yValueMapper: (sales, _) => sales.y,
      name: 'Sales 0',
    ),
  ],
);

Row(
  mainAxisAlignment: MainAxisAlignment.spaceEvenly,
  children: [
    TextButton(
      onPressed: () => _setRange(0, 2000),
      child: const Text('View default range'),
    ),
    TextButton(
      onPressed: () => _setRange(1200, 1300),
      child: const Text('View range 1200 to 1300'),
    ),
  ],
);

void _setRange(double minRange, double maxRange) {
  _numericAxisController.visibleMinimum = minRange;
  _numericAxisController.visibleMaximum = maxRange;
}

```
Regards,
Lokesh P.

[_github_fastlineseries_visiblerange_chart_.zip](https://github.com/user-attachments/files/15886668/_github_fastlineseries_visiblerange_chart_.zip)

**Comment by LokeshPalani** [comment]
Hi @LazyLazyCoder,

We have ensured with 1000 data points in the [FastLineSeries](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/FastLineSeries-class.html) by setting [primaryXAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/primaryXAxis.html) and [primarYAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/primaryYAxis.html) as [NumericAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/NumericAxis-class.html) and pan the chart to view the specific data point in the [SfCartesianChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart-class.html). We did not face any performance lagging in the chart.

 

We have the following common factors that can be used to boost the performance of the chart when there is need to plot high volume data.


- Load and store the required data points in the initState method itself, and then set the [dataSource](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeries/dataSource.html) to the chart series.

- Use [NumericAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/NumericAxis-class.html) or [DateTimeAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeAxis/DateTimeAxis.html) instead of [CategoryAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CategoryAxis/CategoryAxis.html) and [DateTimeCategoryAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeCategoryAxis-class.html).
- When there are a large number of points to load in the line series, you can use [FastLineSeries](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/FastLineSeries-class.html) instead of [LineSeries](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/LineSeries-class.html).
- Instead of enabling data markers and data labels when there are a large number of data points, you can use [Trackball](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/trackballBehavior.html) to view the point information.
- Set series [animationDuration] (https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianSeries/animationDuration.html) as 0 to disable the animation while loading large number of data points.
- Use [updateDataSource](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeriesController/updateDataSource.html) method while updating dynamic data points instead of calling setState. For more details refer UG -  https://help.syncfusion.com/flutter/cartesian-charts/methods#updatedatasource.
- Use On-demand loading while rendering large data points, it can be used to load more data to the chart when the visible range reaches the end on dragging in the chart. For more details refer UG -   https://help.syncfusion.com/flutter/cartesian-charts/on-demand-loading.  
- Use [autoScrollingDelta](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/autoScrollingDelta.html) property in the  [NumericAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/NumericAxis-class.html) or [DateTimeAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeAxis/DateTimeAxis.html), to show the number of dataPoints always visible in the [SfCartesianChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart-class.html). By using this, you can view the remaining data points by setting the [enablePanning](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ZoomPanBehavior/enablePanning.html) property to true in the [ZoomPanBehavior](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ZoomPanBehavior-class.html). For more details refer UG - https://help.syncfusion.com/flutter/cartesian-charts/axis-customization#auto-scrolling.
- We have also shared the performance metrics when high volume data points are used for [FastLineSeries](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/FastLineSeries-class.html) with [NumericAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/NumericAxis-class.html) in the [SfCartesianChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart-class.html) for your reference below.


| DataPoints | Devices | Performance metrics |
|-----------------|-----------------|-----------------|
| 1 Million  | Android | 450 ms  |
| 1 Million | Web  | 800 ms |
| 1 Million  | Windows  | 400 ms  |
| 1 Million | iOS  | 260 ms |
| 1 Million  | macOS  | 400 ms  |

And we still need more details to validate the reported issue. Could you please provide the following information, which will be helpful for us to provide a solution sooner?

- What are all the features enabled in the SfCartesianChart?
- What type of axis is used in the SfCartesianChart?

If you are still facing issues after using above mentioned key points, we kindly request you to share more details regarding the specific scenario in which you encounter the issue with a screenshot or screen recording and test sample or code snippet. This will help us to assist you more effectively.

Regards,
Lokesh P.
