### ISSUE TITLE
[syncfusion_flutter_pdfviewer] UI becomes laggy when number of pages in pdf document are more

### ISSUE THREAD

**Issue by sagarkardani** [syncfusion/flutter-widgets#196]
It seems that when number of pages are less then performance is good.

But when number of pages are higher (say for example near to 500 or more) then UI becomes laggy. Zooming, scrolling etc. actions in the viewer are not responding that much fast. Besides this loaded document also slows down other UI components in that particular app.

**Comment by dillibabun** [comment]
Hi @sagarkardani ,

Greetings from Syncfusion.

We tried to reproduce the reported issue from our side, but SfPdfViewer works properly. We expect that the issue might be specific to your working environment. So, kindly share us the following details.

1. Platforms in which issue is reproduced.
2. Device RAM size.
3. flutter doctor log.
4. Input document.

These pieces of information will be helpful for us to reproduce the reported issue at our end and provide you a prompt solution at the earliest.

Regards,
Dilli babu.

**Comment by sagarkardani** [comment]
Thank you Syncfusion for investigating the point.

Below are the details...


1. Platform :
    Android (version 10)


2. Device :
    SM-N960F (android-arm64), RAM - 6 GB


3. Flutter Doctor Log :
    [√] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.17134.1488], locale en-IN)
    [√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    [√] Chrome - develop for the web
    [√] Android Studio (version 4.1.0)
    [√] VS Code (version 1.55.2)
    [√] Connected device (2 available)

    • No issues found!


4. Document :
    I have just duplicated the pages 5 times in flutter-succinctly.pdf and it becomes 645 pages.
    This document also laggs the UI.
    If there are no copyright/legal issues then I can surely upload here. Just tell me that I upload document here or not ?


Regards,
Sagar.

**Comment by dillibabun** [comment]
Hi @sagarkardani ,

Thank you for sharing us the details.

We tried to reproduce the reported issue with the provided details. But, SfPdfViewer UI doesn't become laggy. The sample application can be downloaded [here](https://www.syncfusion.com/downloads/support/directtrac/general/ze/sampleapplication-1621849900). Kindly install this APK in your device and let us know whether the issue is reproduced.

You can share the document by creating a support query in our website. The documents shared in our incidents will be maintained confidentially. Please share us the documents which will be helpful for us the provide you a prompt solution at the earliest.
https://www.syncfusion.com/support/directtrac/incidents/newincident 

Regards,
Dilli babu.

**Comment by sagarkardani** [comment]
Yes, SfPdfViewer really working fine in this sample application.

Now it seems like I should investigate further in my setup, that why this document becomes laggy with my implementation. At present I am closing the issue.

Thank you Syncfusion for quick support and assistance.

Regards,
Sagar.
