### ISSUE TITLE
[RangeSlider] cannot drag to left if start=end

### ISSUE THREAD

**Issue by narumishi** [syncfusion/flutter-widgets#197]
For `SfRangeSlider`, start thumb can only drag to points left to end,  and end thumb can only drag to right to start.

However, when **start=end**, once we click and hold the thumb icon, actually the end thumb is selected. 

So when **start=end=maxVal**, we can do nothing since end cannot move to left.

It will be helpful if whatever we select and drag, they should be able to move from minVal to maxVal.

**Comment by LakshmiRadhaKrishnan** [comment]
Hi, 
 
Greetings from Syncfusion. 
 
**Query 1 & 2:**  
when **start=end**, once we click and hold the thumb icon, actually the end thumb is selected. 
when **start=end=maxVal**, we can do nothing since end cannot move to left. 
 
We have fixed this behaviour and this change will be available in our next weekly NuGet on April 27th, 2021. 
 
**Query 3:** It will be helpful if whatever we select and drag, they should be able to move from minVal to maxVal. 
 
We have considered your request as an improvement “Allow dragging the thumbs in both directions when the start and end thumbs are in the same value”, and the status can be tracked from the feedback portal link.   
   
**Feedback:** https://www.syncfusion.com/feedback/24539/allow-dragging-the-thumbs-in-both-directions-when-the-start-and-end-thumbs-are-in   

We will prioritize the features every release based on the demands and priority. So, this feature will be available in any of our upcoming releases. 

Regards,
Lakshmi R.

**Comment by narumishi** [comment]
Thanks for your fix.
The official `RangeSlider` could be a good example, it uses dx of drag gesture to decide which point to move.
