### ISSUE TITLE
Hello, how to make the timeInterval is appear no scroll horizontal when scroll between days (i want only cells for days scroll)

### ISSUE THREAD

**Issue by NaderDiab** [syncfusion/flutter-widgets#1970]
### Use case

Hello, how to make the timeInterval is appear no scroll horizontal when scroll between days (i want only cells for days scroll)

### Proposal

![Screenshot 2024-07-09 180306](https://github.com/syncfusion/flutter-widgets/assets/69509079/4ac2698f-e6f6-4ee9-b3d6-19118298f9e2)

**Comment by LokeshPalani** [comment]
Hi @NaderDiab,

We have validated your query and attached screenshot on our end, but we are unable to understand what you are proposing as your requirement. We kindly request you to provide us with more detailed information about your requirement, along with a screen recording, so that we can assist you more effectively. Please let us know if you need any further details.

Regards,
Lokesh P.
