### ISSUE TITLE
[syncfusion_flutter_datagrid] Can't get data correctly using onCellTap with Pagig

### ISSUE THREAD

**Issue by Trung15010802** [syncfusion/flutter-widgets#2025]
### Bug description

Can't get data correctly using onCellTap with Pagination

### Steps to reproduce

1. Go to page 2
2. Tap any cell
3. Show data cell in page 1 not page 2

### Code sample

Fofllow this example but with pagination:
https://support.syncfusion.com/kb/article/11302/how-to-get-the-cell-value-when-tapping-the-cells-in-flutter-datatable-sfdatagrid

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/user-attachments/assets/55984767-1920-4c53-b007-0a190e2800a2)

</details>

### Stack Traces

.

### On which target platforms have you observed this bug?

Web

### Flutter Doctor output

.

**Comment by abineshPalanisamy** [comment]
Hi @Trung15010802 ,
 
In SfDataGrid, by default, only the rows available on a specific page are held in [DataSource.effectiveRows](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpub.dev%2Fdocumentation%2Fsyncfusion_flutter_datagrid%2Flatest%2Fdatagrid%2FDataGridSource%2FeffectiveRows.html&data=05%7C02%7Cabinesh.palanisamy%40syncfusion.com%7C937291f0bd2646256da008dcbdd16a36%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638593954351728241%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=%2FBZMnmRY9vxBwrh72dof5gR1X61hcgJISmREDgEFDgA%3D&reserved=0). To support sorting and filtering across all pages, we maintain a list of all rows in DataSource.effectiveRows. 
 
In this approach, we do not override the [handlePageChange](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpub.dev%2Fdocumentation%2Fsyncfusion_flutter_datagrid%2Flatest%2Fdatagrid%2FDataGridSource%2FhandlePageChange.html&data=05%7C02%7Cabinesh.palanisamy%40syncfusion.com%7C937291f0bd2646256da008dcbdd16a36%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638593954351736493%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=lloKo7zQnfNdOTfykZN%2B5%2FaH%2BT69w4BcS9HKkaV96v0%3D&reserved=0) method in the [DataGridSource](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpub.dev%2Fdocumentation%2Fsyncfusion_flutter_datagrid%2Flatest%2Fdatagrid%2FDataGridSource-class.html&data=05%7C02%7Cabinesh.palanisamy%40syncfusion.com%7C937291f0bd2646256da008dcbdd16a36%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638593954351743488%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=tXq04toIwRM9DvMDsJcK%2B61sFMRsxGDuF1NsXtHvo%2FE%3D&reserved=0) class. The DataGrid automatically determines the rows required for each page based on the [SfDataPager.pageCount](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpub.dev%2Fdocumentation%2Fsyncfusion_flutter_datagrid%2Flatest%2Fdatagrid%2FSfDataPager%2FpageCount.html&data=05%7C02%7Cabinesh.palanisamy%40syncfusion.com%7C937291f0bd2646256da008dcbdd16a36%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638593954351749872%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=wd%2FtbpXVombfKqDN%2FjgyWLw0%2FTVb9oygFEFd48V9wg8%3D&reserved=0), which is calculated as the total number of DataGridRows divided by SfDataPager.pageCount.
 
When using pagination, the **rowIndex** provided corresponds to the rows available on the current page. As a result, you may encounter incorrect details if you are working with a list of all rows in DataSource.effectiveRows. To achieve the expected behavior, we implemented a workaround in the sample. By using the [onPageNavigationEnd](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpub.dev%2Fdocumentation%2Fsyncfusion_flutter_datagrid%2Flatest%2Fdatagrid%2FSfDataPager%2FonPageNavigationEnd.html&data=05%7C02%7Cabinesh.palanisamy%40syncfusion.com%7C937291f0bd2646256da008dcbdd16a36%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638593954351755869%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=NBBhB77WuyihAvkMllaUEYOStoLfIQYY816T26TaKpE%3D&reserved=0) callback, which is triggered when a page navigation is successfully completed, we can obtain the respective **pageIndex**. With this, we can accurately calculate the rowIndex and retrieve the correct details when a cell is tapped.
 
We have included a sample for your reference. Please review this sample for more details and adapt it to suit your specific requirements.

- **Sample :** [SfDataGrid.zip](https://github.com/user-attachments/files/16635148/SfDataGrid.zip)

 
Regards,
Abinesh P

**Comment by ashok-kuvaraja** [comment]
Hi @Trung15010802,

We hope that the reported issue has been resolved at your end. Hence, we are closing this issue now. If you need any more help, please reopen this ticket. We are always happy to assist you.

Regards,
Ashok K
