### ISSUE TITLE
[syncfusion_flutter_charts] Display widget labels instead of text labels on different axis

### ISSUE THREAD

**Issue by vovaklh** [syncfusion/flutter-widgets#2036]
### Use case

Hi! I want to display image label insted of text label on NumericAxis based on value. For now I can display only text and change it in axisLabelFormatter. I would like to display custom labels (as image)

### Proposal

Add labelBuilder to Axis if it is possible

**Comment by ThilipChandru** [comment]
Hi,



We have analyzed your requirement at our end, and currently, we don't have direct support for disabling the [onChartInteractionMove ](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/onChartTouchInteractionMove.html)in entire charts. However, the onChartInteractionMove can be disabled for some interactive features with some restrictions. Can you please share your exact requirement with more details, It will be helpful for sharing the solution as soon as possible.

 

Regards,
S Thilip Chandru.

**Comment by ThilipChandru** [comment]
Hi @vovaklh,

we have logged the feedback to support any custom widget as chart axis labels and we are unable to provide a specific timeline for this since it is not in our volume 3 planned list but it will be available in any of our upcoming releases. You can track the status from the below feedback link. 

Feedback link: https://www.syncfusion.com/feedback/23096.

Regards,
S Thilip Chandru.

**Comment by LavanyaGowtham2021** [comment]
Since it’s an uncertain feature, I am closing this. Please follow up with the FR below.
Feedback link: https://www.syncfusion.com/feedback/23096.
