### ISSUE TITLE
Logarithmic Axis Minimum/Maximum Not Being Respected

### ISSUE THREAD

**Issue by saavy1** [syncfusion/flutter-widgets#2062]
### Bug description

When using a logarithmic axis in a Cartesian Chart, if you set the minimum and maximum values the graph still extends beyond them in both directions

### Steps to reproduce

Here is a simple project I made that repros the issue. The only important note is I am on Flutter 3.24.1 so I am using the dependency override for the package

The data points I'm passing to the Chart are within the range of both axes.

### Code sample

<details open><summary>Code sample</summary>

```dart
void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Syncfusion Flutter Charts',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SfCartesianChart(
        primaryYAxis: const NumericAxis(maximum: 30, minimum: -30),
        primaryXAxis: const LogarithmicAxis(
          anchorRangeToVisiblePoints: false,
          initialVisibleMinimum: 20,
          initialVisibleMaximum: 25000,
          minimum: 20,
          maximum: 25000,
          interval: 1,
        ),
        series: <SplineSeries<Datum, double>>[
          SplineSeries<Datum, double>(
            dataSource: const [Datum(x: 20, y: 0), Datum(x: 22000, y: 0)],
            xValueMapper: (data, _) => data.x,
            yValueMapper: (data, _) => data.y,
          )
        ],
      ),
    );
  }
}

final class Datum {
  const Datum({required this.x, required this.y});

  final double x;
  final double y;
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>
 

[image](https://github.com/user-attachments/assets/bc3266ac-3a9f-4abb-b707-36fee5367244)

[image](https://github.com/user-attachments/assets/959cf8ab-fd0d-4e52-af49-f512906d3822)

</details>

### Stack Traces

<details open><summary>Stack Traces</summary>
No stack trace necessary here, no exception

```dart
[Add the Stack Traces here]
```

</details>

### On which target platforms have you observed this bug?

Windows, Android

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.24.1, on Microsoft Windows [Version 10.0.22635.4112], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/windows-android-setup for more details.
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.11.1)
[√] Android Studio (version 2023.3)
[√] VS Code (version 1.92.2)
[√] Connected device (3 available)
[√] Network resources

! Doctor found issues in 1 category.```

</details>

**Comment by saavy1** [comment]
I went ahead and downgraded my Flutter version to 3.22.3 so I could test with the exact package from syncfusion and not the overriden one and I got the exact same results as above

**Comment by lizhuoyuan** [comment]
Do you have any solutions?
I have a similar problem, when displaying several nodes on the line, the progress is 0 and the left origin is beyond the leftmost distance.
like this:
![image](https://github.com/user-attachments/assets/f45ea7dc-1573-48b2-9463-c60f35a8160a)
The starting points don't overlap.

**Comment by Baranibharathip** [comment]
Hi @saavy1,
 
We are able to replicate the reported issue regarding logarithmic axis minimum/maximum not being respected at our end and have logged bug report for it in our feedback portal. We will fix and include the changes in our weekly patch release which is expected to be rolled out on October 15, 2024 . We will update you here once the release is rolled out and we appreciate your patience until then. You can also track the status of the bug with the feedback below.
 
Feedback link : [https://www.syncfusion.com/feedback/61535](https://www.syncfusion.com/feedback/61535/minium-and-maximum-range-are-not-updated-properly-for-log-axis)
 
Regards,
Baranibharathi P.

**Comment by natrayansf** [comment]
Hi @saavy1,

We initially logged this issue as a bug because the logarithmic axis did not appear to respect the set minimum/maximum values in the chart, based on the output observed from other axes like the [NumericAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/NumericAxis-class.html). 

After investigating the issue with our development team and reviewing the chart's behavior, we confirmed that this is not a bug, it's the expected behavior for [logarithmic scales](https://en.wikipedia.org/wiki/Logarithmic_scale). The [logarithmic scale](https://en.wikipedia.org/wiki/Logarithmic_scale) adjusts based on intervals, with a default [logBase](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/LogarithmicAxis/logBase.html) of 10, and values are rounded to the nearest logarithmic point for clearer scaling. This rounding ensures the chart remains readable and consistent, especially when dealing with a large range of numbers. For the same reason, do not have range padding support in the log axis same as the numeric axis.

For example, even with a set range of 20 to 22,000, the axis expands to show values starting from the nearest lower increment (1) and extending to the next higher increment (100,000), ensuring proper scaling and readability. 

Regards,
Natrayan

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket if you need further assistance on this.
