### ISSUE TITLE
[syncfusion_flutter_calendar] Cannot drag horizontal scrollbar in resource view (Web)

### ISSUE THREAD

**Issue by ThorinEk** [syncfusion/flutter-widgets#2070]
### Bug description

Same problem as #1912 however this is for the Web Platform. The horizontal scrollbar at the bottom of the resource calendar view can not be moved.
Package versions:
 - syncfusion_flutter_calendar: 26.2.14
 - syncfusion_flutter_core: 26.2.14

Flutter: 3.24.2

### Steps to reproduce

1. Try to drag the horizontal scrollbar

### Code sample

<details open><summary>Code sample</summary>

```dart
SfCalendar(
  controller: widget.viewModel.calendarController,
  dataSource: widget.viewModel.dataSource,
  resourceViewSettings: resourceViewSettings(constraints.maxHeight),
  minDate: DateTime.now().startOfHour,
  resourceViewHeaderBuilder: resourceViewHeaderBuilder,
  view: currentView,
  allowedViews: allowedViews,
  showNavigationArrow: true,
  showWeekNumber: true,
  weekNumberStyle: weekNumberStyle,
  showDatePickerButton: true,
  showCurrentTimeIndicator: true,
  appointmentTimeTextFormat: 'HH:mm',
  firstDayOfWeek: 1,
  showTodayButton: widget.showTodayButton,
  onTap: ontap,
 ),
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![syncfusion bug scrollbar](https://github.com/user-attachments/assets/94b6e37c-837a-4064-a876-3a0fa2fae965)

</details>

### On which target platforms have you observed this bug?

Web

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.24.2, on Microsoft Windows [Version 10.0.22631.4169], locale sv-SE)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.9.2)
[√] Android Studio (version 2023.2)
[√] VS Code (version 1.92.1)
[√] Connected device (3 available)
[√] Network resources
```

</details>

**Comment by ThilipChandru** [comment]
Hi @ThorinEk,


The reported issue has been fixed and rolled out in our Volume 3 main release. To avoid this issue, we kindly request that you upgrade the syncfusion_flutter_calendar package to the latest version below.


Calendar : [syncfusion_flutter_calendar: ^27.1.48](https://syncfusion-my.sharepoint.com/personal/thilipchandru_s_syncfusion_com/Documents/syncfusion_flutter_calendar:%20%5e27.1.48)


Root cause : The scrollPhysics is set to NeverScrollPhysics to prevent conflicts between switching the TimelineWeek view and scrolling between days within the week on mobile platforms.


Regards,
Thilip Chandru.

**Comment by ThorinEk** [comment]
Hello @ThilipChandru,
Thanks for the response and effort to resolve this, I can confirm that this is now working correctly in my web application!

Kind regards,
Gustav
