### ISSUE TITLE
Is there a way to display newly added points with animation when using the updateDataSource method of ChartSeriesController?

### ISSUE THREAD

**Issue by elethiame** [syncfusion/flutter-widgets#2087]
### Use case

I'm using the SfCartesianChart to display a live data source with the updateDataSource method, which offers great performance. However, I would like to animate the newly added points. Is there a way to achieve this, or do you have any suggestions on how to apply it?

Thanks!

### Proposal

none.

**Comment by KompelliSravanSyncfusion** [comment]
Hi elethiame,
 
Due to performance considerations, we did not provide animation support while updating data via the [updateDataSource](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeriesController/updateDataSource.html) method . So, currently, the [updateDataSource](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeriesController/updateDataSource.html) method of the [ChartSeriesController](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeriesController-class.html) does not support animations. However, you can achieve dynamic animations to add or replace data points directly by using the setState method, which will allow for animated transitions.
 
List of series supports add and replace animation.

- Line
- Column
- Bar
- Bubble
- Scatter
- StackedColumn
- StackedColumn100
- StackedBar
- StackedBar100
- Hilo
- RangeColumn
- Candle
- HiloOpenClose
- BoxAndWhisker
- Waterfall

For more details, please refer to our sample browser: [Demos & Examples of Syncfusion Flutter Widgets](https://flutter.syncfusion.com/#/cartesian-charts/series-features/animation/series-animation) . We have  also attached a sample for your reference that demonstrates how to implement this approach effectively. 

[bd_639441.zip](https://github.com/user-attachments/files/17243572/bd_639441.zip)

If you have any further queries, please get back to us. We are always happy to assist you.
 
Regards,
Kompelli Sravan Kumar.

**Comment by elethiame** [comment]
@KompelliSravanSyncfusion 
Thanks for your response.
So, if I want to update the line with a new data point using animation, I should use setState to reload the whole chart. But won't this cause a performance issue?
I will have about three lines with 1,800 points on the chart at the end.

**Comment by KompelliSravanSyncfusion** [comment]
Hi @elethiame,
 
As we mentioned in our previous update, "Due to performance considerations, we did not provide animation support while updating data via the [updateDataSource](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeriesController/updateDataSource.html) method. Currently, the [updateDataSource](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeriesController/updateDataSource.html) method of the [ChartSeriesController](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeriesController-class.html) does not support animations."
 
You are correct that using the setState method to update the line with a new data point will result in the entire chart being rebuilt. While this approach allows for animated transitions, it can lead to performance issues, particularly in scenarios like yours, with three lines and approximately 1,800 data points.
 
To optimize performance, we recommend avoiding the use of animation when loading large datasets. This can help enhance the overall responsiveness of the chart.
 
If you have any further questions or need additional assistance, please feel free to reach out.
 
Regards,
Kompelli Sravan Kumar.

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket if you need further assistance on this.
