### ISSUE TITLE
Weekly column on header

### ISSUE THREAD

**Issue by mayonetech** [syncfusion/flutter-widgets#2120]
### Use case

is possible to do something like that in flutter

<img width="713" alt="Screenshot 2024-10-10 at 22 27 40" src="https://github.com/user-attachments/assets/0080fa36-0416-4fa7-a98d-f79eccdb8f2b">

### Proposal

<img width="713" alt="Screenshot 2024-10-10 at 22 27 40" src="https://github.com/user-attachments/assets/0080fa36-0416-4fa7-a98d-f79eccdb8f2b">

**Comment by abineshPalanisamy** [comment]
Hi @mayonetech ,

Based on the images provided, we are unclear about the expected behavior on your side. To assist you further and gain a better understanding of your expectations, we kindly request that you provide any additional details and share the specific use cases related to the behavior you are seeking. This information will greatly help us investigate your query and provide a prompt and appropriate solution.
 
Regards,
Abinesh P

**Comment by ashok-kuvaraja** [comment]
Hi @mayonetech,

We suspect that the reported issue has been resolved at your end. Hence, we are closing this issue. If you need any further assistance, please reopen this. We are always happy to help.
 
Regards,
Ashok K
