### ISSUE TITLE
DateTimeAxis shows invalid dates when dataSource has no elements (empty list)

### ISSUE THREAD

**Issue by Abhijit-Revamp** [syncfusion/flutter-widgets#2140]
### Bug description

I have a ColumnSeries with primaryXAxis as DateTimeAxis
The intervalType is set to DateTimeIntervalType.days (however this has no impact)

Screen shots atached
If the "dataSource" has one or more value, the Axis labels are perfect. 
As soon as the dataSource has empty list, the label jumps to "Feb 10 to May 31"

### Steps to reproduce

1. Empty the list that is supplied to DataSource

### Code sample

<details open><summary>Code sample</summary>

```dart
SfCartesianChart(
  primaryXAxis: const DateTimeAxis(
      title: AxisTitle(text: 'Date'),
      intervalType: DateTimeIntervalType.days,
   ),

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots</summary>

Correct one:
<img width="1419" alt="image" src="https://github.com/user-attachments/assets/29097c8d-f4bc-43f2-b853-fc29ca9611a3">

With just 1 element in data - still good
<img width="1407" alt="image" src="https://github.com/user-attachments/assets/c2bea4f7-ee41-4660-8a1d-70ce0fb15697">

Invalid dates with empty data set:
<img width="1428" alt="image" src="https://github.com/user-attachments/assets/b36f4ee7-ad4f-40c5-8daf-aa4b6b919a12">

</details>

### Stack Traces

<details open><summary>Stack Traces</summary>

```dart
[Add the Stack Traces here]
```

</details>

### On which target platforms have you observed this bug?

Web

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel beta, 3.26.0-0.1.pre, on macOS 14.7 23H124 darwin-x64, locale en-IN)
    • Flutter version 3.26.0-0.1.pre on channel beta at /Volumes/Abhi-Data/FlutterDev/SDK/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee624bc4fd (5 weeks ago), 2024-09-10 17:41:06 -0500
    • Engine revision 059e4e6d8f
    • Dart version 3.6.0 (build 3.6.0-216.1.beta)
    • DevTools version 2.39.0
```

</details>

**Comment by natrayansf** [comment]
Hi @Abhijit-Revamp, 
 
We would like to let you know that the [DateTimeAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeAxis/DateTimeAxis.html) labels are calculated based on the provided data, ensuring that the axis displays relevant information. The appearance of the labels depends on the [interval](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/interval.html) and [intervalType](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeAxis/intervalType.html) set in the [DateTimeAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeAxis/DateTimeAxis.html). However, if the [dataSource](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeries/dataSource.html) is empty, the axis will display a default date range starting from 1970, such as labels from 'Feb 10 to May 31'. This is expected behavior.

If the [dataSource](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeries/dataSource.html) is empty and you would like to display a predefined range, we recommend using the [minimum](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeAxis/minimum.html) and [maximum](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeAxis/maximum.html) properties in axis. Please refer the following code snippet. 

```
SfCartesianChart(
  primaryXAxis: const DateTimeAxis(
      minimum: data.isEmpty ? DateTime(2024, 1, 1) : null;
      maximum: data.isEmpty ? DateTime(2024, 6, 31) : null;
   ),
),
```

For more details, please refer to the following UG links: 
**Date-time-intervals:** https://help.syncfusion.com/flutter/cartesian-charts/axis-types#date-time-intervals 
**Customizing axis range:** https://help.syncfusion.com/flutter/cartesian-charts/axis-types#customizing-range-1

Regards,
Natrayan

**Comment by Abhijit-Revamp** [comment]
Thanks @natrayansf
This is really simple solution.
Will close
