### ISSUE TITLE
[syncfusion_flutter_datagrid][web] Multi-Select Rows With SHIFT Does Not Work

### ISSUE THREAD

**Issue by ThorinEk** [syncfusion/flutter-widgets#2144]
### Bug description

Selecting multiple checkboxes through holding SHIFT is not working. The bug can is also affecting the [official Flutter Data Grid Demo](https://[flutter.syncfusion.com/#/datagrid/selection/checkbox-selection](https://flutter.syncfusion.com/#/datagrid/selection/checkbox-selection)), so you can reproduce the steps below:

### Steps to reproduce

1. Press a checkbox in any row except the last
2. Press and hold SHIFT
3. Press a checkbox in any row further down

Expected result: All the checkboxes in between should be selected
Actual outcome: Only the two clicked rows are selected

However, after clicking any row in the datagrid (not checkbox), then the SHIFT-select feature works after that.

### Code sample

<details open><summary>Code sample</summary>

```dart
# pubspec.yaml
dependencies:
  syncfusion_flutter_core: ^27.1.50
  syncfusion_flutter_datagrid: ^27.1.50

```

</details>

### Screenshots or Video

![image](https://github.com/user-attachments/assets/fb6fac21-e2e6-4991-b29b-f78c9dca7c10)

### Stack Traces

I will skip stacktrace since this is not a runtime exception, and is visible in the official Flutter Data Grid Demo.

### On which target platforms have you observed this bug?

Web

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.24.2, on Microsoft Windows [Version 10.0.22631.4317], locale sv-SE)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.9.2)
[√] Android Studio (version 2023.2)
[√] VS Code (version 1.92.1)
[√] Connected device (3 available)
[√] Network resources

• No issues found!
```

</details>

**Comment by abineshPalanisamy** [comment]
Hi @ThorinEk ,
 
We have checked your query at our end, and we are able to replicate that issue at our end. We have considered this as a  bug and logged a bug report regarding this in our feedback portal. We will fix the reported issue and include the changes in our upcoming weekly patch release, which is expected to be rolled out on November 05, 2024. We will let you know once released, and we appreciate your patience until then.
 
Disclaimer: Inclusion of this solution in the weekly release may change due to other factors including but not limited to QA checks and works reprioritization. 
 
Regards,
Abinesh P

**Comment by ThorinEk** [comment]
Hello @abineshPalanisamy, thank you very much for the quick response. Sounds great that you will be resolving this issue.

**Comment by abineshPalanisamy** [comment]
Hi @ThorinEk ,
 
We are glad to inform you that the reported problem has been resolved on our end. Therefore, kindly update SfDataGrid to the latest version([27.1.57](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpub.dev%2Fpackages%2Fsyncfusion_flutter_datagrid&data=05%7C02%7Cabinesh.palanisamy%40syncfusion.com%7C41173d7073724d600a5608dcf800d800%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638657929701594037%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=hnW%2BZWqaGh%2FBPEitsEmlcNKITS1cd8W5Ngof7XB1Kjs%3D&reserved=0)). 
 
**Root cause :**  In the SfDataGrid, we used framework checkboxes for the checkbox columns. The Shift key press is recognized when the DataGrid has focus. However, when tapping on a checkbox, we do not allow the focus to shift to the DataGrid, affecting the Shift-selection behavior on checkbox taps.

If you have any further queries, please don't hesitate to reach out. We are more than happy to assist you.

Regards,
Abinesh P

**Comment by ThorinEk** [comment]
Thank you very much for the quick response and fix for this issue. I can confirm that it is now working on my end!

Kind Regards,
Gustav Persson
