### ISSUE TITLE
markerTooltipBuilder on SfMaps doesn't respect widget border radius

### ISSUE THREAD

**Issue by Okiring** [syncfusion/flutter-widgets#216]
added a component under the markerTooltipBuilder and gave it a border radius. There is also no way of setting the border radius under MapTooltipSettings. Currently the markerTooltipBuilder only seems to work well with full square with no border radius.

can reproduce with the code below
![Screen Shot 2021-05-08 at 9 08 00 PM](https://user-images.githubusercontent.com/27002476/117549241-ea961800-b041-11eb-9b4b-6870e097323f.png)

result you will get
![Screen Shot 2021-05-08 at 9 07 35 PM](https://user-images.githubusercontent.com/27002476/117549255-fda8e800-b041-11eb-8e1c-ea3c95b354c2.png)

i also tried changing the settings under MapTooltipSettings but i can only set the color,strokeColor and stroke width. Provide possibility of setting the borderRadius for tooltip from MapTooltipSettings if possible.

**Comment by LakshmiRadhaKrishnan** [comment]
Hi, 
 
Greetings from Syncfusion support. 
 
You can set border radius to the tooltip using the tooltipBorderRadius property in the SfMapsThemeData instead of setting border to the widget returning from the markerTooltipBuilder. Kindly refer the below link for more details. 

**Link:** https://help.syncfusion.com/flutter/maps/tooltip#appearance-customization  
 
 
![Screenshot 2021-05-10 at 12 52 49 PM](https://user-images.githubusercontent.com/47354659/117646418-5941b580-b1a9-11eb-9aeb-c85dbfb29e58.png)

 
Please let us know if you need further assistance with this. 
 
Regards, 
Lakshmi R.

**Comment by Okiring** [comment]
Thanks...let me check..
