### ISSUE TITLE
[syncfusion_flutter_datagrid] How do i hide checkbox some lines. Thanks 

### ISSUE THREAD

**Issue by gltiennd** [syncfusion/flutter-widgets#2168]
### Use case

I have some conditions and I want to hide or change a certain view.

### Proposal

![Screenshot 2024-11-15 at 09 36 39](https://github.com/user-attachments/assets/19829998-1f8a-4a9a-80e5-d5eda4c63694)

**Comment by gltiennd** [comment]
![Uploading Screenshot 2024-11-15 at 09.36.39.png…]()

**Comment by abineshPalanisamy** [comment]
Hi @gltiennd ,
 
In SfDataGrid, there is no built-in support to disable the checkbox for a particular row as requested. The checkbox column is handled at the source level and is always rendered as the first column.
 
However, we have a workaround to achieve the desired behavior. **Instead of using the DataGrid’s checkbox column, you can create a custom checkbox column at the sample level. This way, you can disable the checkbox for specific rows based on your conditions**. We have included a sample for your reference; please review it for further details.

- Sample : [SfDataGrid.zip](https://github.com/user-attachments/files/17770403/SfDataGrid.zip)


Regards,
Abinesh P

**Comment by gltiennd** [comment]
> Xin chào ,
> 
> Trong SfDataGrid, không có hỗ trợ tích hợp để vô hiệu hóa hộp kiểm cho một hàng cụ thể theo yêu cầu. Cột hộp kiểm được xử lý ở cấp nguồn và luôn được hiển thị dưới dạng cột đầu tiên.
> 
> Tuy nhiên, chúng tôi có một cách giải quyết để đạt được hành vi mong muốn. **Thay vì sử dụng cột hộp kiểm của DataGrid, bạn có thể tạo cột hộp kiểm tùy chỉnh ở cấp mẫu. Bằng cách này, bạn có thể tắt hộp kiểm cho các hàng cụ thể dựa trên điều kiện của mình**. Chúng tôi đã bao gồm một mẫu để bạn tham khảo; Vui lòng xem lại để biết thêm chi tiết.
> 
> * Mẫu : [SfDataGrid.zip](https://github.com/user-attachments/files/17770403/SfDataGrid.zip)
> 
> Trân trọng, Abinesh P

Thanks for your quick response. can you help me handle the checkbox in the header too? please

**Comment by abineshPalanisamy** [comment]
Hi @gltiennd ,

As mentioned in the previous response, instead of using the Text widget in the [GridColumn](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpub.dev%2Fdocumentation%2Fsyncfusion_flutter_datagrid%2Flatest%2Fdatagrid%2FGridColumn-class.html&data=05%7C02%7Cabinesh.palanisamy%40syncfusion.com%7Cb27ba8aa94dc46e6ee6f08dd057821fd%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638672735711739394%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=7TE0J3P9F5hluj5s6%2Fgld3vZEovYwm0pu3gCBhPTPlU%3D&reserved=0), you should add a CheckBox widget for the checkbox column in the [GridColumn.label](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpub.dev%2Fdocumentation%2Fsyncfusion_flutter_datagrid%2Flatest%2Fdatagrid%2FGridColumn%2Flabel.html&data=05%7C02%7Cabinesh.palanisamy%40syncfusion.com%7Cb27ba8aa94dc46e6ee6f08dd057821fd%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638672735711754536%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=hSf%2BM%2BSo1UOA87r63yQ2YUJq0JP%2Brl8yVXTDaRtv9q0%3D&reserved=0). In the onChanged event, you can perform the selection action. We have included a sample for your reference; please review it for further details.

- **Sample :**  [SfDataGrid.zip](https://github.com/user-attachments/files/17775970/SfDataGrid.zip)

 
Regards,
Abinesh P

**Comment by gltiennd** [comment]
> Hi @gltiennd ,
> 
> As mentioned in the previous response, instead of using the Text widget in the [GridColumn](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpub.dev%2Fdocumentation%2Fsyncfusion_flutter_datagrid%2Flatest%2Fdatagrid%2FGridColumn-class.html&data=05%7C02%7Cabinesh.palanisamy%40syncfusion.com%7Cb27ba8aa94dc46e6ee6f08dd057821fd%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638672735711739394%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=7TE0J3P9F5hluj5s6%2Fgld3vZEovYwm0pu3gCBhPTPlU%3D&reserved=0), you should add a CheckBox widget for the checkbox column in the [GridColumn.label](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpub.dev%2Fdocumentation%2Fsyncfusion_flutter_datagrid%2Flatest%2Fdatagrid%2FGridColumn%2Flabel.html&data=05%7C02%7Cabinesh.palanisamy%40syncfusion.com%7Cb27ba8aa94dc46e6ee6f08dd057821fd%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638672735711754536%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=hSf%2BM%2BSo1UOA87r63yQ2YUJq0JP%2Brl8yVXTDaRtv9q0%3D&reserved=0). In the onChanged event, you can perform the selection action. We have included a sample for your reference; please review it for further details.
> 
> * **Sample :**  [SfDataGrid.zip](https://github.com/user-attachments/files/17775970/SfDataGrid.zip)
> 
> Regards, Abinesh P

I appreciate your quick response. It has helped me out. Thanks again.
