### ISSUE TITLE
SyncFusion DataGridView Filter Data Reset all selection

### ISSUE THREAD

**Issue by abdulrehmananwar** [syncfusion/flutter-widgets#2178]
### Use case

Please Give solution into filter search by some values not all.

### Proposal

While filtering, if I want to select only 3 specific values using the search, it sometimes selects all values instead. Please provide a solution for this issue.
https://github.com/user-attachments/assets/ff6c13c0-87db-46ce-878f-f4fb89d2d72e

**Comment by abdulrehmananwar** [comment]
Additionally Required as per image attached. 
![image](https://github.com/user-attachments/assets/55eeadf3-b011-408c-8396-e66d1bbdbe47)

**Comment by SethupathyD** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>


<p style='margin:0in;font-family:Calibri;font-size:11.0pt'>Hi abdulrehmananwar
,<br>
&nbsp;</p>

<div style='direction:ltr'>


Query | Response
-- | --
While filtering,   if I want to select only 3 specific values using the search, it sometimes   selects all values instead. Please provide a solution for this issue. | Please note that   this is the expected behavior of filtering in the Flutter DataGrid. When   filtering, all the filtered data will be selected. You need to manually   deselect the unwanted records.
Can we make column   Name on the Top of Icons. | As of now, Flutter   DataGrid does not have support to make column name on the top of icons.
Need Text Field   Editable Column. | We are a little   unclear about your requirement. Could you please confirm whether you want to   load the DataGrid with an editable column or enable edit mode by tapping a   cell in a specific column? This clarification will help us provide a more   accurate suggestion.



</div>

<p style='margin:0in;font-family:Calibri;font-size:11.0pt'>&nbsp;</p>

<p style='margin:0in;font-family:Calibri;font-size:11.0pt'>Regards,<br>
Sethupathy D.</p>


</body>

</html>

**Comment by abdulrehmananwar** [comment]
for last one question . yes on tap i want to make cell editable. which i creating on build widget. butt when i click it unselect or select the row also

**Comment by abineshPalanisamy** [comment]
Hi @abdulrehmananwar ,

Based on the details provided, in SfDataGrid, you can enable editing by tap by setting the [SfDataGrid.editingGestureType](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpub.dev%2Fdocumentation%2Fsyncfusion_flutter_datagrid%2Flatest%2Fdatagrid%2FSfDataGrid%2FeditingGestureType.html&data=05%7C02%7Cabinesh.palanisamy%40syncfusion.com%7C64da5769612e49d42f1308dd0de51e38%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638681999879521785%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=ZlHH4VBEZy4U5wagebXVrhqgufURxfTokwA2RV5XUp4%3D&reserved=0) property to tap. The cell will switch to edit mode when you tap it. However, you need to perform selection and deselection simultaneously. In SfDataGrid, when performing an editing action, you cannot simultaneously perform a selection action. This is the expected behavior on our end. Please feel free to contact us if you require any further assistance.
 
Regards,
Abinesh P

**Comment by ashok-kuvaraja** [comment]
Hi @abdulrehmananwar,

We suspect that the reported issue has been resolved at your end. Hence, we are closing this issue. If you need any further assistance, please reopen this. We are always happy to help.
 
Regards,
Ashok K
