### ISSUE TITLE
Scroll in Listview with panning and trackingball set to true

### ISSUE THREAD

**Issue by roderikpeeters** [syncfusion/flutter-widgets#219]
On my Listview I'm using 4 different SplineSeries charts. They all use panning to see old data and also a trackingball to get values from the data. Im not using zoom.

So only horizontal scrolling, but now I can't move inside my ListView to see other charts. I know that this is known and also desired behavior for the package. However I need a solution that I can still scroll down to the other charts.

Any suggestions on how to fix this?

**Comment by Dharanipalani** [comment]
Hi @roderikpeeters,

We have analyzed your query and would like to tell you that we have prohibited the scrolling purposefully for the below scenarios.

1. Crosshair or trackball enabled with a single tap as activation mode   
2. Zooming or panning enabled with modes other than the selection zooming 

We have already created feedback for this feature request, and we will try to provide this support sooner and we are not able to provide the specific timeline for this since this is not in our planned list, but you can check the status of your request at the link below, and we appreciate your patience while we work on it.

[https://www.syncfusion.com/feedback/19322](https://www.syncfusion.com/feedback/19322)

Thanks,
Dharanitharan. P
