### ISSUE TITLE
Trackball stuck on first series when in TrackballDisplayMode.groupAllPoints

### ISSUE THREAD

**Issue by petoknm** [syncfusion/flutter-widgets#224]
I have some time series that I want to display but when I enable trackball, and want to move it forward past the end of the first series, it gets stuck  on the last data point from the first series.
I use `TrackballDisplayMode.groupAllPoints`.

![screenshot](https://user-images.githubusercontent.com/5087675/117986985-67730b80-b33a-11eb-9db1-77a40dcc9ed7.png)

**Comment by Dharanipalani** [comment]
Hi @petoknm,

Greetings from the Syncfusion team. We have looked over your question and the screenshot you sent, and we would like to inform you that the trackball is displayed by locating the closest data points from the touch spot. The trackball makes to the nearest data point from the contact location rather than null points in the screenshot which having sequence of empty points. As a result, it has moved to the end of the first series, and you can use the float mode or nearest point mode to see the trackball in the appropriate data points. Refer to the [support guide](https://help.syncfusion.com/flutter/cartesian-charts/trackball-crosshair#label-display-mode) for more information.

Kindly revert us if you need any further assistance on this.

Thanks,
Dharanitharan. P
