### ISSUE TITLE
[Suggestion] Show necessary pdf security information in syncfusion_flutter_pdf plugin

### ISSUE THREAD

**Issue by brightseagit** [syncfusion/flutter-widgets#228]
Hello,
syncfusion_flutter_pdf is a great plugin but I would like to suggest some necessary features such as:

- if a file is protected or not
- If it has an owner password set or a user password set
- If the file has limited permissions
- what kind of permissions allowed and not allowed.

All this information is very crucial for anyone working with pdfs in the application so I think it would be great to have them in this plugin.

Thanks for providing this awesome plugin.

**Comment by chinnumuniyappan** [comment]
Hi @brightseagit ,

Greetings from Syncfusion.

<table>
<tr>
<td>
if a file is protected or not
</td> <td>
At present we do not have direct support to check whether the document is encrypted or not. Instead of we can get these details by using the following code.

```dart
bool isEncryptedDocument() {
  bool isEncrypted = false;
  try {
    //Load the encrypted PDF document.
    PdfDocument document =
        PdfDocument(inputBytes: File('secured.pdf').readAsBytesSync());
  } catch (exception) {
    if (exception.toString().contains('Cannot open an encrypted document.')) {
      isEncrypted = true;
    }
  }
  return isEncrypted;
}
```
</tr> <tr><td>
If it has an owner password set or a user password set
</td><td>
Please refer to the following documentation to find whether the document is encrypted using the owner or user password.
<a href="https://help.syncfusion.com/flutter/pdf/working-with-security#how-to-determine-whether-the-pdf-document-is-protected-by-user-or-owner-password">https://help.syncfusion.com/flutter/pdf/working-with-security#how-to-determine-whether-the-pdf-document-is-protected-by-user-or-owner-password</a>
</td></tr>
<tr>
<td>
If the file has limited permissions  </br> </br>
what kind of permissions allowed and not allowed.
</td>
<td>
We can get the permission details using the following <a href="https://pub.dev/documentation/syncfusion_flutter_pdf/latest/pdf/PdfPermissions-class.html">permissions</a> API available on the PdfSecurity class. Refer the below code for further details.

```dart
  //Get the document security.
  PdfSecurity security = document.security;

  //Get the permissions
  PdfPermissions permissions = security.permissions;

```
</td></tr>
</table>

Regards, 
Chinnu M

**Comment by brightseagit** [comment]
Thanks 👍 for giving this detailed reply with sample code. I would definitely try these tomorrow.
