### ISSUE TITLE
Does pdfviewer not support GestureDetector?

### ISSUE THREAD

**Issue by tomriddle7** [syncfusion/flutter-widgets#235]
```
GestureDetector(
  child: SfPdfViewer.network(
    'https://cdn.syncfusion.com/content/PDFViewer/flutter-succinctly.pdf',
    key: _pdfViewerKey,
  ),
  onTapUp: (TapUpDetails details) {
  var x = details.globalPosition.dx;
  var y = details.globalPosition.dy;
  if (x >= 0 && x <= MediaQuery.of(context).size.width / 5) {
    leftPage();
  } else if (x >= MediaQuery.of(context).size.width * 4 / 5 &&
    x <= MediaQuery.of(context).size.width) {
    rightPage();
  } else {
    setState(() => _visible = !_visible);
  }
})
```
I read this thread https://github.com/syncfusion/flutter-widgets/issues/94 and you said that By wrapping GestureDetector over SfPdfViewer widget, the user interaction in the widget can be identified.

So I made this code but it doesn't fire event expected.

Is there any solution to catch tap event?
 
Thank for your support.

**Comment by dillibabun** [comment]
Hi @tomriddle7 ,

Greetings from Syncfusion.

We are checking on this issue and suspect this to be defect. We are analyzing on this issue and will update the further details on 20 May 2021.

Regards,
Dilli babu

**Comment by dillibabun** [comment]
Hi @tomriddle7 ,

We have analyzed the reported issue with "GestureDetector over SfPdfViewer widget not working". In SfPdfViewer, we have used different gestures to detect the different tapping, panning, and zooming. As per flutter architecture, a gesture that is detected first will trigger its callback and the remaining gestures will be rejected. Since gestures inside SfPdfViewer are detected first, gestures subscribed in main.dart is not invoked. To overcome this issue, we recommended using RawGestureDetector over SfPdfViewer which is illustrated in the following codes.

`
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:syncfusion_flutter_pdfviewer/pdfviewer.dart';
void main() {
  runApp(MaterialApp(
    title: 'Syncfusion PDF Viewer Demo',
    home: HomePage(),
  ));
}
/// Represents Homepage for Navigation
class HomePage extends StatefulWidget {
  @override
  _HomePage createState() => _HomePage();
}
class _HomePage extends State<HomePage> {
  final GlobalKey<SfPdfViewerState> _pdfViewerKey = GlobalKey();
  @override
  void initState() {
    super.initState();
  }
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: const Text('Syncfusion Flutter PDF Viewer'),
          actions: <Widget>[
            IconButton(
              icon: const Icon(
                Icons.bookmark,
                color: Colors.white,
              ),
              onPressed: () {
                _pdfViewerKey.currentState?.openBookmarkView();
              },
            ),
          ],
        ),
        body: RawGestureDetector(
          gestures: {
            AllowMultipleGestureRecognizer:
            GestureRecognizerFactoryWithHandlers<
                AllowMultipleGestureRecognizer>(
                  () => AllowMultipleGestureRecognizer(),  //constructor
                  (AllowMultipleGestureRecognizer instance) {  //initializer
                instance.onTap = () => print('tap');
                instance.onTapUp = (TapUpDetails details) => print('tap up');
                instance.onTapDown = (TapDownDetails details) => print('tap down');
              },
            )
          },
          child: SfPdfViewer.asset(
            'assets/sample.pdf',
            key: _pdfViewerKey,
          ),)
    );
  }
}
///
class AllowMultipleGestureRecognizer extends TapGestureRecognizer {
  @override
  void rejectGesture(int pointer) {
    acceptGesture(pointer);
  }
}`

Regards,
Dilli babu.

**Comment by supratikkoley** [comment]
No...i tried this method but it is not responding on gestures.

**Comment by dillibabun** [comment]
Hi @supratikkoley ,

We have prepared a simple application with the above-shared code. Kindly test the [APK ](https://www.syncfusion.com/downloads/support/directtrac/general/ze/gestures-622041647)and let us know if you find any issues.

Regards,
Dilli babu.

**Comment by rodrigorafaeldamaceno** [comment]
Some update in this issue? I need get onTap event on PDF, for show actions

**Comment by pradyotprksh** [comment]
There is a way i found to disable the widget gestures is by using `AbsorbPointer` and setting the property `absorbing` as `true`.

**Comment by nerraj-droid** [comment]
Use stack like this,

Stack(
                            children: [
                              Hero(
                                tag: 'pdf-viewer',
                                child: SfPdfViewer.network(
                                  "https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf",
                                  controller: _pdfViewerController
                                ),
                              ),
                              GestureDetector(
                                onTap: () {
                                  print('olahh');
                                  _gotoViewerPage(context);
                                },
                                child: Container(
                                  color: Colors.transparent,
                                ),
                              ),
                            ],
                          )
