### ISSUE TITLE
[DateTimeCategoryAxis] ChartSeriesController.updateDataSource doesn't recalculate zoom position 

### ISSUE THREAD

**Issue by millerovv** [syncfusion/flutter-widgets#236]
Hello, Syncfusion team! 

Thank you for the great chart library and your hard work! I am currently testing syncfusion_flutter_charts in my pet project and unfortunately came upon an issue. I recently moved from `DateTimeAxis` to `DateTimeCategoryAxis` in order to hide empty candles on my chart X axis.  

I am also using the new on-demand loading feature. For showing the lazy-loaded candles on chart I update the data using `ChartSeriesController.updateDataSource` method. With DateTimeAxis everything works smoothly and the current zoom position gets recalculated after I add new indexes. On the other hand with `DateTimeCategoryAxis` zoom position somehow stays the same which results in weird behavior (see video). This is frustrating because I really needed the new axis class functionality, but now I must stop using on-demand loading because of this problem.

On-demand loading with `DateTimeAxis`
After calling  `ChartSeriesController.updateDataSource` the zoomPosition is recalculated based on new candles list that contains old+new candles:

https://user-images.githubusercontent.com/31796433/118650084-b9110f80-b7ec-11eb-9a1c-c5f6a13cb543.mov

On-demand loading with `DateTimeCategoryAxis`
After adding new loaded candles the zoom position stays at 0.0 therefore the loaded candles get skipped while also the next pagination request gets emitted:

https://user-images.githubusercontent.com/31796433/118650114-c29a7780-b7ec-11eb-8f87-570ffd4be3f9.mov

**Comment by SriramKiranSenthilkumar** [comment]
Hi @millerovv,

> Thank you for your feedback @SriramKiranSenthilkumar!
> 
> I am not sure how to run your sample project because it does not seem to contain the lib folder and main.dart file.
> Could you please check and upload the archive once again?

Sorry for the inconvenience. I have now re-uploaded the archive again. Please check the sample in the same response.

Regards,
Sriram Kiran

**Comment by millerovv** [comment]
Evidently, the problem occurs in my project due to the opposite direction of scrolling for lazy load trigger. 


I updated the main.dart file by changing the if check in `getloadMoreIndicatorBuilder` method to `direction == ChartSwipeDirection.start` and altering the `_updateData` method so it inserts the new values to the start of the chartData. 

Now this sample works just like in my project in the videos above. Here is the gist with the new version of main.dart: 

https://gist.github.com/millerovv/8edb4c03f91b9703ee47ce8616469ad4

The problem gets reproduced now. Here are the videos demonstrating the behaviors with DateTimeAxis and DateTimeCategoryAxis

https://user-images.githubusercontent.com/31796433/118974628-b5f85980-b97b-11eb-8605-063ca69bec1d.mov

https://user-images.githubusercontent.com/31796433/118974658-bc86d100-b97b-11eb-955d-5a96e7c4d5d4.mov

**Comment by SriramKiranSenthilkumar** [comment]
Hi @millerovv,

Thanks for the revert. We have analyzed your scenario with the test sample, and we are able to replicate the reported issue at our end. We have considered this as a bug and will resolve and include the fix for the reported issue in our upcoming weekly patch release which is expected to be rolled out by the middle of next week. We will update you once the release is rolled out and we appreciate your patience until then.

Regards,
Sriram Kiran

**Comment by Dharanipalani** [comment]
Hi @millerovv,

We have analyzed your scenario and like to tell you that we can achieve the expected behavior by doing the sample level alteration in the code. In the DateTime axis we stored the axis visible minimum and maximum initially in the **onActualRangeChanged** callback and after load the new data we set the old visible minimum and maximum to the new data also and hence it is showing the old visible range. In the **DateTimeCategoryAxis** also we processed the same but different behavior is due to the data and the intervals are processed based on the indices instead of the date and time, so after added the new data in the starting of the data list it shows the data in that list and hence new data shows immediately after swiping the chart. Now, we attached the altered sample and the screen-record for your reference and kindly make use of it. Here, we set the DateTime values of the indices in the callback and hence it works as expected. Please revert us if you need any further assistance on this.

Sample: [altersample.zip](https://github.com/syncfusion/flutter-widgets/files/6569623/altersample.zip)

Screen-record: https://user-images.githubusercontent.com/19763272/120180392-50348900-c229-11eb-87aa-b3cc8df50ccc.mp4

Thanks,
Dharanitharan. P

**Comment by millerovv** [comment]
Hi @Dharanipalani 

I seem to have figured it out. Thank you for your reply, that was really helpful!
