### ISSUE TITLE
Incompatibility with the test plugin

### ISSUE THREAD

**Issue by ederluca** [syncfusion/flutter-widgets#24]
Good afternoon

Guys my question is very simple is there a provision for updating the dependency used in syncfusion_flutter_corre called pedantic?

I'm asking this because version 18.3.40 is incompatible with the latest version of the test plugin so I can't get both to work as per the message below:
 
Because test> = 1.16.0-nullsafety.5 depends on pedantic> = 1.10.0-nullsafety <1.10.0 and syncfusion_flutter_core 18.3.40 depends on pedantic> = 1.9.0 <1.9.9, test> = 1.16.0- nullsafety.5 is incompatible with syncfusion_flutter_core 18.3.40.

So, because app depends on both syncfusion_flutter_core 18.3.40 and test 1.16.0-nullsafety.5, version solving failed.
pub get failed (1; So, because app depends on both syncfusion_flutter_core 18.3.40 and test 1.16.0-nullsafety.5, version solving failed.)

**Comment by SriramKiranSenthilkumar** [comment]
Hi @ederluca ,

Greetings from Syncfusion. We have analyzed your scenario and we have analyzed on your scenario and this version solving issue is due to the flutter test plugin using the presale version of the pedantic package([1.10.0-nullsafety](https://pub.dev/packages/pedantic/versions/1.10.0-nullsafety)). As we do not provide support for presale versions, we cannot update the pedantic package to its presale version. However, to overcome the reported version solving issue, kindly please add the below code in your Flutter project's _pubspec.yaml_ file.
```
dependency_overrides:
  pedantic: 1.10.0-nullsafety
```
For further reference on how to add dependency overrides for your Flutter project, please click [here](https://dart.dev/tools/pub/dependencies#dependency-overrides)

Regards,
Srirram Kiran

**Comment by FerBueroTrebino** [comment]
> Hi @ederluca ,
> 
> Greetings from Syncfusion. We have analyzed your scenario and this version solving issue is due to the flutter test plugin using the presale version of the pedantic package([1.10.0-nullsafety](https://pub.dev/packages/pedantic/versions/1.10.0-nullsafety)). As we do not provide support for presale versions, we cannot update the pedantic package to its presale version. However, to overcome the reported version solving issue, kindly please add the below code in your Flutter project's _pubspec.yaml_ file.
> 
> ```
> dependency_overrides:
>   pedantic: 1.10.0-nullsafety
> ```
> 
> For further reference on how to add dependency overrides for your Flutter project, please click [here](https://dart.dev/tools/pub/dependencies#dependency-overrides)
> 
> Regards,
> Srirram Kiran



> Hi @ederluca ,
> 
> Greetings from Syncfusion. We have analyzed your scenario and this version solving issue is due to the flutter test plugin using the presale version of the pedantic package([1.10.0-nullsafety](https://pub.dev/packages/pedantic/versions/1.10.0-nullsafety)). As we do not provide support for presale versions, we cannot update the pedantic package to its presale version. However, to overcome the reported version solving issue, kindly please add the below code in your Flutter project's _pubspec.yaml_ file.
> 
> ```
> dependency_overrides:
>   pedantic: 1.10.0-nullsafety
> ```
> 
> For further reference on how to add dependency overrides for your Flutter project, please click [here](https://dart.dev/tools/pub/dependencies#dependency-overrides)
> 
> Regards,
> Srirram Kiran

Thanks Srirram Kiran! This solve the issue for me.
