### ISSUE TITLE
Disable to select through blackout dates into syncfusion datepicker

### ISSUE THREAD

**Issue by axl0d** [syncfusion/flutter-widgets#244]
Hello syncfusion developers!
enablePastDates is a useful  property from SfDateRangePicker class, is there any property that has the same behavior for blackout dates?
maxDate or minDate are limited by a DateTime class and not a list as blackoutDates.
**visually a range of dates can be selected through a blackout day** (this seems confusing as ux)

![image](https://user-images.githubusercontent.com/28642287/119048501-ee506580-b984-11eb-8def-7ad61f59381c.png)

the use case would be an available date range and not an available date range except for some blackout days

**Comment by Indumathi1195R** [comment]
Hi,

**Regarding Query: is there any property that has the same behavior for blackout dates?**

We are unable to understand the query clearly. If possible, can you please share your issue details or requirement details clearly? It would be helpful for us to analyze and provide you a solution at the earliest.

As per the SfDateRangePicker implementation, when we select the date range over the blackout dates, picker UI looks like the attached image and it is the expected behavior of the picker. Also please find the UG documentation links for blackoutDates and enablePastDates.

**UG link:**
https://help.syncfusion.com/flutter/daterangepicker/date-restrictions#blackout-dates
https://help.syncfusion.com/flutter/daterangepicker/date-restrictions#enable-and-disable-past-dates

Also, we have a KB document for reverse of the blackout dates. Please find the KB from the following link.

**KB link:**
https://www.syncfusion.com/kb/12075/how-to-add-active-dates-in-the-flutter-date-range-picker-sfdaterangepicker

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by axl0d** [comment]
**when we select the date range over the blackout dates, picker UI looks like the attached image and it is the expected behavior of the picker.**

is there any way to disable the behavior? _if it does not exist it could be a new property so that it does not affect the current api_
if the controller found a blackout date between range selected dates, it can't forward to the next dates.
The range selected dates would be from initial date until first a found blackout date.

the logic is well implemented, but visually I get gives me to understand that I have n periods of days
**for example:**  the attached image I selected a range date from initial date 20 May until 31 May
first period: 20 May - 24 May
second period: 26 May - 27 May
third period: 29 May - 31 May

with this functionality the user should be restricted to a single period of days, in this case if I want to select the same range dates (20 May until 31 May) I will not be able to do it because the first blackout date is 25 May
the answer would be:
single period: 20 May - 24 May

**Comment by Indumathi1195R** [comment]
Hi,

We regret to inform you that as per the current implementation of the Flutter Date Range Picker unable to customize UI by mentioned requirement, also it is an expected behavior of the picker.

Regards,
Indumathi R
