### ISSUE TITLE
Run rendering of chart in separate isolate.

### ISSUE THREAD

**Issue by corteXnzt** [syncfusion/flutter-widgets#252]
Hi I'm new with flutter and I developed a BLE device updating its characteristic value every 50ms and values are rendered on graph using your wonderful library. The problem is when it updates the chart the update goes from >90ms to 1800ms. When I turn off the flutter chart delay goes down to ~60ms. 

Now being new to flutter and coming from python/c++ programming I just learned that there is no multithreading in flutter and so I must use isolate. Does rendering your graph via isolate process possible? Do you have some example ? Or some tips so I can process the BLE data as fast as possible while rendering the chart in realtime.

**Comment by Dharanipalani** [comment]
Hi @corteXnzt,

Thanks for the interest in our Flutter charts. We have analyzed your scenario and like to tell you that we did not use isolate in our source, and you can use isolate at the application level for fetching the data. Additionally, we suggest you use the FastLineSeries to experience better performance since we processed and drawn it as a single segment. Also, use the **updateDataSource** public method to update the data source of our charts instead of calling the setstate. Since in the setstate which process the whole data and the chart whereas in the **updateDataSource** method we processed only the updated data points, so it gives best performance. Refer to the below help document for further references.

[https://help.syncfusion.com/flutter/cartesian-charts/methods#updatedatasource](https://help.syncfusion.com/flutter/cartesian-charts/methods#updatedatasource)

Kindly revert us if you need any further assistance on this.

Thanks,
Dharanitharan. P

**Comment by corteXnzt** [comment]
Just an update on this, sorry for late update. Thank you Dharanitharan! I converted to FastLineSeries and I used the updateDataSource before. Later I found out that the **timers debug being printed by the debugger is not accurate**. I tested it using a timer on a separate phone and is still on time and so is still accurate. Thank you again.
