### ISSUE TITLE
syncfusion_flutter_pdf 19.1.65-beta doesn't decrease pdf size on page removal

### ISSUE THREAD

**Issue by brightseagit** [syncfusion/flutter-widgets#260]
Issue- Even after removing pages from a pdf the size of pdf still remains the same. I think the size should also be decreased accordingly.

Thanks.

**Comment by brightseagit** [comment]
Update with more info on this:-

[Sample.pdf](https://github.com/syncfusion/flutter-widgets/files/6569587/Sample.pdf) This is a sample pdf I downloaded from the web and used the adobe acrobat audit space usage tool. The results I got: 
![sample audit space usage](https://user-images.githubusercontent.com/72334435/120179608-70b01380-c228-11eb-8419-4e47400a9388.png)

[new sample.pdf](https://github.com/syncfusion/flutter-widgets/files/6569711/new.sample.pdf) Then I removed one page from the pdf using syncfusion_flutter_pdf plugin and ran the adobe acrobat audit space usage tool on it. The results I got: 
![new sample audit space usage](https://user-images.githubusercontent.com/72334435/120179808-a6ed9300-c228-11eb-99f6-2390be011389.png)

Now here what I found is that the Document Overhead increased more than double. I think there should be some way to clean up on created documents.

Thanks.

**Comment by Anand3595** [comment]
Hi @brightseagit ,

Greetings from Syncfusion. We can set PdfDocument.fileStructure.incrementalUpdate as false to restructure PDF document while saving. By default, incrementalUpdate is enabled and preserves the copy of an existing content. So that file size getting increased while saving PDF document after removed page from PDF document. We suggest you to disable PdfDocument.fileStructure.incrementalUpdate by set false to overcome this issue. Refer to the following code for further details. Kindly try this on your end and let us know whether it is achieving your requirement.


> //Load the document.
> PdfDocument document = PdfDocument(inputBytes: File('gis_succinctly.pdf').readAsBytesSync());
> //Disable incremental update by set value as false
> document.fileStructure.**incrementalUpdate = false**;
> //Remove first page of the PDF document
> document.pages.removeAt(0);
> //Save the destination document.
> List<int> bytes = document.save();

With Regards,
Anand Panchamoorthi

**Comment by brightseagit** [comment]
Thanks for this detailed solution. This has resolved my issue 👍.

**Comment by brightseagit** [comment]
Hey, I just checked that without setting incrementalUpdate to false one sample file is showing blank white pages when modified for example removing pages but as soon as I set incrementalUpdate to false it shows the document. Can you please state the reason for this behavior?

Here is the sample file - [c4611_sample_explain.pdf](https://github.com/syncfusion/flutter-widgets/files/6571517/c4611_sample_explain.pdf)

**Comment by Anand3595** [comment]
Hi @brightseagit ,

We are able to reproduce the reported issue with “PDF Document corrupted while removing page” in our end. And we will provide further validation details on 4th June 2021.

With Regards,
Anand Panchamoorthi

**Comment by Anand3595** [comment]
Hi @brightseagit ,

The reported issue with “PDF Document corrupted while removing page” has been validated and confirmed as a defect. We will include the fix in our upcoming weekly release which is planned on 15th June 2021.

The status of the bug can be track through below link: https://www.syncfusion.com/feedback/25969/pdf-document-corrupted-while-removing-page.

With Regards,
Anand Panchamoorthi

**Comment by brightseagit** [comment]
Thanks for letting me know about this.

**Comment by Anand3595** [comment]
Hi @brightseagit ,

The bug tracking link has been updated as public.

With Regards,
Anand Panchamoorthi

**Comment by Anand3595** [comment]
Hi @brightseagit ,

Thanks for your patience.

We have included the fix for an issue with “PDF Document corrupted while removing page” in our latest weekly package release with version [19.1.69-beta](https://pub.dev/packages/syncfusion_flutter_pdf/versions/19.1.69-beta).

Please let us know if you need any further assistance in this.

With Regards,
Anand Panchamoorthi

**Comment by brightseagit** [comment]
Thanks for letting me know.
I just checked and verified that 19.1.69-beta has resolved the “PDF Document corrupted while removing page” issue.
