### ISSUE TITLE
[syncfusion_flutter_charts] Display trendline equations

### ISSUE THREAD

**Issue by walsha2** [syncfusion/flutter-widgets#298]
# Feature Request 

Would it be possible to **display** the trendline equations used by the `Trendline` class **directly on the chart**? This would be a simple string annotation.
 
https://help.syncfusion.com/flutter/cartesian-charts/trendline#tooltip-for-trendline

Although it is possible for end users to do this manually and annotate the chart, it would require recreating all the math/logic in `trendlines.dart` to back out the equations that were used or how they were derived. It seems like it makes more sense for this to be a feature as part of `SfCartesianChart`.

# Example

This is similar capability to what Mircrosoft Excel would do as seen in the screenshots below:

![excel-expotential-trendline-equation](https://user-images.githubusercontent.com/53703092/124223517-79b32f80-dac9-11eb-9b70-ef707aba4af2.png)

![excel-linear-trendline-formulas](https://user-images.githubusercontent.com/53703092/124223521-7c158980-dac9-11eb-98ae-4d5499c78b87.png)

**Comment by Dharanipalani** [comment]
Hi @walsha2,

Thanks for the interest in our Flutter charts. We have analyzed your query and logged a feedback for your feature request. We cannot specify a timeline for this since this is not in our upcoming schedule, but we assure that it will be available in any of our upcoming releases. You can track the status of this feature from the below feedback link.

Feedback link: [https://www.syncfusion.com/feedback/26714](https://www.syncfusion.com/feedback/26714)

Thanks,
Dharanitharan. P

**Comment by walsha2** [comment]
@Dharanipalani @JayavigneshwaranG it looks like this has now been added as part of the most recent  `19.3.43` update:

https://pub.dev/packages/syncfusion_flutter_charts/changelog#19343---09302021

Thank you for getting to this request, much appreciated. You guys are doing a great job!
