### ISSUE TITLE
The first Stackbar doesn't look right

### ISSUE THREAD

**Issue by Lawati97** [syncfusion/flutter-widgets#303]
I have attached an image to show how it looks like
<img width="1536" alt="Screen Shot 2021-07-05 at 12 16 43 PM (2)" src="https://user-images.githubusercontent.com/37277245/124439887-02142780-dd8b-11eb-95bf-6b696485cec6.png">

**Comment by dharanidharandharmasivam** [comment]
Hi @Lawati97 ,

Thanks for your interest in our Flutter chart widget. We have analyzed your scenario, but the stacked bar looks similar to others. Since we are not aware of your exact expectation, can you please share your expected screenshot, and provide more information on how the first stacked bar differs from others. This will be helpful in providing the solution sooner.

Thanks,
Dharani.

**Comment by Lawati97** [comment]
@dharanidharandharmasivam I was expecting to have the first row bar box has the same levels as the rest so if you zoom in you would see that the first Blue box has a different hight comparing to others

**Comment by Lawati97** [comment]
@dharanidharandharmasivam Kindly note what am trying to do is that am trying to have each represent the total of some category within each month so, at the end, ill have a single row? 
I would like to confirm if that is possible or not using this package?

**Comment by Dharanipalani** [comment]
Hi @Lawati97,

We investigated your query and were unable to visualize your reported problem. We attempted to replicate your reported issue at our end by creating a sample as shown in the screenshot and zooming in. Because the stacked bar height is the same for everyone when zooming, we have attached the screen recording and sample we utilized. So, please look at this and duplicate the issue in the attached sample. Sharing a screenshot or screen recording of your problem can help us examine your situation and give you a solution faster.

Sample:  [github_294.zip](https://github.com/syncfusion/flutter-widgets/files/6783144/github_294.zip)

Screen record: https://user-images.githubusercontent.com/19763272/124893860-be265a00-dff8-11eb-9a05-da687615fa89.mp4

Thanks,
Dharanitharan. P
