### ISSUE TITLE
Text search is blocking mobile screen

### ISSUE THREAD

**Issue by boucardsb** [syncfusion/flutter-widgets#317]
Hi,

I'm in company working on a mobile app and we need a pdf viewer.
I saw the package syncfusion_flutter_pdfviewer and it does everything we need.

Only one thing is bothering us, it's the synchronous text search that feel like the application froze.
The text search feature is quite important in our project and we were wondering if it's planned to make this asynchronous.

Thanks.

**Comment by deepika134** [comment]
Hi boucardsb,

Greetings from Syncfusion.

We are unable to provide the text search as Asynchronous. We have used text search methods from Syncfusion PDF package. Since, the requested support is yet to be given in that package, we are unable to do in our widget. As an alternative, we tried to use the [Isolate.spawn]( https://api.flutter.dev/flutter/dart-isolate/Isolate/spawn.html) but, the spawn method allows static members and top-level function to make synchronous methods as asynchronous. Currently, we have no plans to implement this support and status of the feature can be tracked using following link https://www.syncfusion.com/feedback/21985/asynchronous-text-search 

You can also contact us through our [support forums](https://www.syncfusion.com/forums), [Direct-Trac](https://www.syncfusion.com/support/directtrac/), or [feedback portal]( https://www.syncfusion.com/feedback/flutter). We are always happy to assist you!

Regards,
Deepika R
