### ISSUE TITLE
SfPdfViewer.network() doesn't display the PDF in Flutter Web

### ISSUE THREAD

**Issue by saprahits** [syncfusion/flutter-widgets#318]
`Container(
                          height: 200,
                          width: 200,
                          padding: EdgeInsets.all(3),
                          decoration: BoxDecoration(
                            border: Border.all(color: Colors.blueAccent),
                            borderRadius: BorderRadius.circular(10),
                            color: Colors.white,
                          ),
                          child: SfPdfViewer.network(
                            'http://www.orimi.com/pdf-test.pdf',
                          ),
                        ),`

  syncfusion_flutter_pdfviewer: ^19.2.47-beta

**Comment by deepika134** [comment]
Hi saprahits,

Greetings from Syncfusion.

The reported issue is known issue in flutter web application. This is due to CORS security limitation in web application. Kindly refer the following flutter forum.
https://github.com/flutter/flutter/issues/51125.

On analyzing further, we found that this issue can be resolved by configure the CORS settings in the requested server or by disabling the security settings in chrome.dart as mentioned below steps:
1. Go to flutter\bin\cache and remove a file named: flutter_tools.stamp
2. Go to flutter\packages\flutter_tools\lib\src\web and open the file chrome.dart.
3. Find '--disable-extensions'.
4. Add '--disable-web-security'.

You can also contact us through our [support forums](https://www.syncfusion.com/forums), [Direct-Trac](https://www.syncfusion.com/support/directtrac/), or [feedback portal]( https://www.syncfusion.com/feedback/flutter). We are always happy to assist you!

Regards,
Deepika R

**Comment by mmustafaget** [comment]
@deepika134 after disable web security it works on local but how we can run it on LIVE SERVER?

**Comment by deepika134** [comment]
Hi mmustafaget,

We request to set the CORS in your server to access the document bytes from other servers. Kindly refer the following documentation and let us know if you need any further assistance.
https://flutter.dev/docs/development/platform-integration/web-images#cross-origin-resource-sharing-cors 

Regards,
Deepika R

**Comment by muhammedsibil** [comment]
pdf always showing loading in flutter web after released,
but it works in local run.
