### ISSUE TITLE
[syncfusion_flutter_charts] Delay when using onPointTap callback

### ISSUE THREAD

**Issue by peterstojanowski** [syncfusion/flutter-widgets#322]
Hello,

I have a question regarding the `SfCartesianChart` with `ColumnSeries`. I need to show a new page when the user taps on a single bar. I'm currently using the `onPointTap` callback to do that but it's being called after roughly a second. Is it possible to get a callback instantly or archive this in a different way? I'm not using the `onPointDoubleTap` method so there is no need to wait. 

Thanks,
Peter

**Comment by Dharanipalani** [comment]
Hi @peterstojanowski,

Thank you for the interest in our Flutter charts. We have investigated your issue and can tell you that the delay in the single tap is caused by the Flutter framework. This is used to determine whether the user is trying a double tap. By default, Flutter has a 300ms delay, thus if the user taps within 300ms, it is treated as a double tap; otherwise, it is treated as a single tap.  We have added the following link for your reference.

[https://developers.google.com/web/updates/2013/12/300ms-tap-delay-gone-away](https://developers.google.com/web/updates/2013/12/300ms-tap-delay-gone-away)

Thanks,
Dharanitharan. P

**Comment by peterstojanowski** [comment]
Hi @Dharanipalani ,

Thank you for your quick response. I understand the delay required for detecting double tap. In my case however I don't need to handle double taps thus the delay is not needed. Please compare with Flutter's `GestureDetector` widget. If the `onDoubleTap` callback is `null` then the `onTap` is fired immediately without any delay. Would be good to see this fixed in one of the next releases of `syncfusion_flutter_charts`.

Thanks,
Peter

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @peterstojanowski,

We have analyzed your query and no issues get reproduced at our end. We have tested the time duration in both the native widget and our chart both are having the same time duration to load a popup widget. The time difference is also in the microseconds, we have attached the videos that show the time duration to be taken for the shown popup.

**Native widget:**
https://user-images.githubusercontent.com/61863686/126974670-aa55edf0-69ec-4dbf-99c7-59452229c78e.mp4

**Our widget:**
https://user-images.githubusercontent.com/61863686/126974684-d1e5ef2a-d343-4809-acc5-3938532b5489.mp4
