### ISSUE TITLE
UI stops animating when removing pages from document in loop

### ISSUE THREAD

**Issue by brightseagit** [syncfusion/flutter-widgets#323]
When trying to remove pages from a pdf document in a loop using the remove functionality of "syncfusion_flutter_pdf" the ui stops or lags. I think this is happening because the plugin is performing the actions on the main thread.

Thank you.

**Comment by Anand3595** [comment]
Hi @brightseagit ,

Thanks for contacting Syncfusion support.

Our package is written natively in Dart for supporting all the platforms and its only works on the main thread (synchronously) and we do not have asynchronous support, due to the UI has been stopped animating for doing very large process. So we request you to use the Isolate to overcome issue. Please find the sample from https://www.syncfusion.com/downloads/support/directtrac/general/ze/FindTextSample1866861097 for more details.

With Regards,
Anand Panchamoorthi

**Comment by brightseagit** [comment]
You have provided a great example on how to use isolates.
Thank you.
