### ISSUE TITLE
how to set rowsPerPage dinamically

### ISSUE THREAD

**Issue by wahyu-handayani** [syncfusion/flutter-widgets#325]
I am using syncfusion_flutter_datagrid: ```19.2.46-beta``` and having 23 list of data. In each page I would like to show 5 list (```rowsPerPage: 5```), so there will be ```pageCount: 5``` (as a round of 23 devided by 5), but I do confused about the content in last page should be 3 list of data. In what property of ```SfDataPager``` that I will know the user is in last page or is there a way to set ```rowsPerPage``` dinamically (so if I am in 1st-4th page: there will be 5 list and in 5th page there will be 3 data list left). Here is part of the code:
```
SfDataPager(
      delegate: orderInfoDataSource,
      pageCount: (dataSource.length / rowsPerPage).round().toDouble(),
      onPageNavigationStart: (int x) {
        if (x == ((dataSource.length / rowsPerPage).round() - 1))
          orderInfoDataSource._rowsPerPage = dataSource.length -
              (rowsPerPage * ((dataSource.length / rowsPerPage).round() - 1));
        else
          orderInfoDataSource._rowsPerPage = rowsPerPage;
      },
    )
```

**Comment by RenugaSadagoban98** [comment]
Hi @wahyu-handayani , 
 
Greetings from Syncfusion. 
   
You can check whether the current navigated page is last page by checking the pageCount value with newPageIndex in handlePageChange method of DataGridSource. In order to load only the remaining rows from the data, just check the currently calculated end of the row index is greater than the overall length of the rows collection. If that is true, you can load only the available rows in the list. In the below sample, we have loaded 23 rows and last page shows only 3 rows.

Please refer the following code snippet,
```

class EmployeeDataSource extends DataGridSource {
  /// Creates the employee data source class with required details.
  EmployeeDataSource(this.employeeData, this.rowsPerPage) {
    buildPaginateDataGridRows();
  }

….
   @override
  Future<bool> handlePageChange(int oldPageIndex, int newPageIndex) async {
    final int startIndex = newPageIndex * rowsPerPage;
    int endIndex = startIndex + rowsPerPage;
    if (endIndex <= employeeData.length && startIndex < employeeData.length) {
      _employeeRows =
          employeeData.getRange(startIndex, endIndex).toList(growable: false);
    } else {
      if (startIndex < employeeData.length && endIndex > employeeData.length) {
        endIndex = employeeData.length;
        _employeeRows =
            employeeData.getRange(startIndex, endIndex).toList(growable: false);
      } else {
        employeeData = [];
      }
    }
```


We have prepared a sample for your reference,
Sample link:  https://www.syncfusion.com/downloads/support/directtrac/general/ze/main-89820899

Please let us know if you need any further assistance.

Regards,
Renuga devi

**Comment by wahyu-handayani** [comment]
@RenugaSadagoban98 Thank you very much for your help, that's great help for me

**Comment by RenugaSadagoban98** [comment]
Hi @wahyu-handayani , 
 
Thanks for the update. 
 
We will wait to hear from you. Please get back to us if you require further assistance from us. 
 
Regards, 
Renuga devi
