### ISSUE TITLE
[syncfusion_flutter_charts] The value is zero, but still the chart

### ISSUE THREAD

**Issue by lcm1475** [syncfusion/flutter-widgets#327]
The values of 7-12, 7-13, 7-14, 7-15 and 7-16 are all zero. My expected behavior is a straight line, but now the result is that I can't understand. Is it wrong where I set it?

![屏幕截图 2021-07-28 015347](https://user-images.githubusercontent.com/9637601/127204249-64920733-518c-4b82-8039-2235b97b1e05.png)
![屏幕截图 2021-07-28 015406](https://user-images.githubusercontent.com/9637601/127204264-ffc3709d-b4f7-4de1-beae-9543cbef29a3.png)
![屏幕截图 2021-07-28 015421](https://user-images.githubusercontent.com/9637601/127204275-c4ad0a29-905e-4b20-ab11-d5329470d048.png)
![屏幕截图 2021-07-28 015434](https://user-images.githubusercontent.com/9637601/127204284-8daf8385-61ff-4c52-9ff3-90347b67ef43.png)
![屏幕截图 2021-07-28 015446](https://user-images.githubusercontent.com/9637601/127204294-52612c05-b5b7-422e-a152-f402fda3e10f.png)
![屏幕截图 2021-07-28 015658](https://user-images.githubusercontent.com/9637601/127204302-36d86211-321c-4108-be83-366f3dbdc577.png)

**Comment by Dharanipalani** [comment]
Hi @lcm1475,

Thanks for the interest in our Flutter charts. We looked your scenario and determined that this is how the spline charts behave. Because of the control points utilized to produce the spline charts, this is the case. We reviewed this situation with our competitors and confirmed this behavior, and we have attached a screenshot for your review. We also recommend setting the spline type to monotonic to get the plat line instead of the spike, as this is how spline charts behave in other modes. Please refer to the assistance document below for further information on this.

[https://help.syncfusion.com/flutter/cartesian-charts/chart-types/spline-chart#spline-rendering-types](https://help.syncfusion.com/flutter/cartesian-charts/chart-types/spline-chart#spline-rendering-types)

Screenshot
![image](https://user-images.githubusercontent.com/19763272/127813354-3539060e-485e-4d86-8d2b-6aaca6f47d46.png)

Please revert us if you need further assistance on this.

Thanks,
Dharanitharan. P
