### ISSUE TITLE
Chart Data Positioned Incorrectly Along DateTimeAxis

### ISSUE THREAD

**Issue by nickmatthews713** [syncfusion/flutter-widgets#329]
I have created a scatterplot similar to the [sample shown in Syncfusion's documentation](https://help.syncfusion.com/flutter/cartesian-charts/chart-types/scatter-chart).

However, the data points do not line up with my DateTimeAxis...

![IMG_0048](https://user-images.githubusercontent.com/36548596/127568296-fb6a6b36-d008-4c9a-90ab-51a833efaadc.jpg)

As you can, see, more than a few points do not match the DateTime I provided. I have tried multiple workaround solutions but to no avail. Here is my code as well...

<img width="576" alt="Screen Shot 2021-07-29 at 4 18 40 PM" src="https://user-images.githubusercontent.com/36548596/127567266-2390401f-d456-4d49-8e79-87634523d676.png">
<img width="335" alt="Screen Shot 2021-07-29 at 4 18 56 PM" src="https://user-images.githubusercontent.com/36548596/127567295-8eccc71d-782a-4a8c-9706-c2927542dd5e.png">

**Comment by Dharanipalani** [comment]
Hi @nickmatthews713,

Thanks for the interest in our Flutter charts. We have analyzed your queries and produced the following responses.

**Query #1** **the data points do not line up with my DateTimeAxis...**

We have investigated the given screenshot and like to tell you that the scatter series is rendered as per expected behavior. In the chart, for between each year (2012, 2013, etc..) there is division of 12 months and so from your data for the year of 2012, the month is 10 and so it is appearing at the end of the grid line and for 2013 the month is 1 and so it is appearing at the starting of the grid line. You can see this clearly when you keep the date format as like [DateFormat.yM()](https://api.flutter.dev/flutter/intl/DateFormat/DateFormat.yM.html) which displays both month and year and easy to understand the data plotting on the chart. We have attached the screenshot below for your given data as a reference. So, series is rendered correctly based on the given data and if you want to all the data is to be exactly on the grid line then it is not possible unless your data all points the first month of the year.

Screenshot
![image](https://user-images.githubusercontent.com/19763272/127668600-5a2f6411-7faf-4462-9263-231ab41fe165.png)

**Query #2** For missing of the year 2019

By default, the chart is rendered with automatic range and thus it renders with this behavior. So, if you want to show the year 2019, then you can the [visibleMaximum](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeAxis/visibleMaximum.html) or [maximum](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeAxis/maximum.html) or also by setting the [rangePadding](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/rangePadding.html) to the additional to overcome this issue. Please see the screenshot below for your reference with additional range padding.

Screenshot:
![image](https://user-images.githubusercontent.com/19763272/127668719-e875d676-e5d0-497e-a5b2-25079987a770.png)

Please refer the below documents and the attached sample.

[https://help.syncfusion.com/flutter/cartesian-charts/axis-customization#auto-range-calculation](https://help.syncfusion.com/flutter/cartesian-charts/axis-customization#auto-range-calculation)
[https://help.syncfusion.com/flutter/cartesian-charts/axis-types#applying-padding-to-the-range](https://help.syncfusion.com/flutter/cartesian-charts/axis-types#applying-padding-to-the-range)


Sample: [scatter_datetime.zip](https://github.com/syncfusion/flutter-widgets/files/6908205/scatter_datetime.zip)

Please revert us if you need any further assistance on this.

Thanks,
Dharanitharan. P

**Comment by nickmatthews713** [comment]
Thank you for the response @Dharanipalani ! Setting the minimum attribute of the DateTimeAxis fixed my problem!
