### ISSUE TITLE
[syncfusion_flutter_charts] skip empty data

### ISSUE THREAD

**Issue by Reprevise** [syncfusion/flutter-widgets#374]
Let's say I have some data like this.

```dart
final data = <DateTime, double>{
    DateTime(2018, 1, 12): 12.0,
    DateTime(2019, 1, 13): 18.0,
    DateTime(2020, 1, 20): 9.0,
    DateTime(2020, 1, 27): 24.0,
    DateTime(2020, 4, 6): 87.0,
    DateTime(2021, 9, 12): 3.0,
    DateTime(2021, 11, 12): 90.0,
    DateTime(2021, 12, 12): 286.0,
};
```

Is there any way to make it so that the chart skips (doesn't render) the dates that's missing without me having to populate missing dates with null values?

**Comment by SriramKiranSenthilkumar** [comment]
Hi @Reprevise,

Greetings from Syncfusion. We have analyzed your scenario at our end, and we recommend that you use the **DateTimeCategoryAxis** (instead of **DateTimeAxis**) as the x-axis for your chart as it can display Date-time values in non-linear intervals which will be suitable for your case. We have also created a simple chart with the **DateTimeCategoryAxis** using the provided chart data and attached it along with the user guide link below for your reference.

Sample: 
[datetimecategory.zip](https://github.com/syncfusion/flutter-widgets/files/7195365/i342778_datetimecategory.zip)

UG: https://help.syncfusion.com/flutter/cartesian-charts/axis-types#date-time-category-axis

Please check with the attached sample and revert us if you require further assistance on this.

Regards,
Sriram Kiran

**Comment by Reprevise** [comment]
`DateTimeCategoryAxis` seemed to fix it. Thanks!
