### ISSUE TITLE
[SfDataGrid] web and desktop No named parameter with the name 'nullOk'

### ISSUE THREAD

**Issue by krisu7** [syncfusion/flutter-widgets#38]
syncfusion_flutter_datagrid-18.3.44-beta/lib/src/sfdatagrid.dart:1136:32: Error: No named parameter with the name 'nullOk'.
        MediaQuery.of(context, nullOk: true)?.textScaleFactor ?? 1.0;

**Comment by krisu7** [comment]
https://github.com/flutter/flutter/pull/68736

**Comment by NeelakandanKannan** [comment]
Hi @krisu7,

Thanks for sharing with us.

Our Syncfusion widgets are compatible with the Flutter framework's stable and beta channel. However, we will include the fix for the above issue (since it is simple changes and alternate solution is there) in our upcoming weekly pub release which scheduled on November 10th 2020.

**Comment by NeelakandanKannan** [comment]
Hi @krisu7 ,

We have resolved the error and included the changes in 2020 Volume 3 SP release (18.3.47-beta). Please update the datagrid version in pubspec.yaml as 18.3.47-beta.

**Comment by krisu7** [comment]
@NeelakandanKannan thank you! It works.
