### ISSUE TITLE
Functionalities

### ISSUE THREAD

**Issue by Sahmirzali** [syncfusion/flutter-widgets#4]
Hello. First of all thanks for this package . 

This package is support **search** text and **highlight** text ?

**Comment by SriramKiranSenthilkumar** [comment]
Hi @Sahmirzali,

Greetings from Syncfusion. We have analyzed on your query and as we are not sure of which Syncfusion Flutter widget you are using, we kindly request you to share us the more information on the Syncfusion flutter widget package you are using so that it will be helpful in providing the solutions sooner.

Regards,
Sriram Kiran

**Comment by huseynovali** [comment]
I'm using this package), i just ask you it will be support horizontal view, search and other features?

**Comment by Sahmirzali** [comment]
I'm using this package), i just ask you will it be support horizontal view, search and other features ?

**Comment by dillibabun** [comment]
Hi @Sahmirzali ,

The support for text search in SfPdfViewer widget is expected to be implemented in our upcoming 2020 Volume 4 main release. We will let you know once this feature is implemented. Until then, we can track the status of this feature in the following link
https://www.syncfusion.com/feedback/18489/support-for-text-search 

Regards,
Dilli babu.

**Comment by Sahmirzali** [comment]
@dillibabun Thanks. yes i'm using syncfusion_flutter_pdfviewer package.
