### ISSUE TITLE
getNearestChartPoints fails when one of the series has no data

### ISSUE THREAD

**Issue by rajkumar82** [syncfusion/flutter-widgets#401]
When there are more than one series plotted and if one series does not have data, then the function getNearestChartPoints fails.

this is because of 

num nearPointX = dataList[0].xValue;

**Comment by kestasb** [comment]
Is a fix coming or is there any work-around for this issue?

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @rajkumar82,

Thanks for your patience. The reported issue regarding the getNearestChartPoint method gets failed when series have no data has been fixed. Now the user interactions are working fine when the series has empty data, and the fix is rolled out in our weekly patch release. To resolve this, kindly upgrade the chart widget package to the latest version below.

https://pub.dev/packages/syncfusion_flutter_charts/versions/19.3.45+1

Regards,
Yuvaraj.
