### ISSUE TITLE
[syncfusion_flutter_charts] unusual default date formatting for minutes

### ISSUE THREAD

**Issue by ozzy91** [syncfusion/flutter-widgets#403]
I'm using a `DateTimeAxis` with autoInterval enabled (very helpful feature).
When the interval is determined as minutes or below, the formatting is very unusual. An example DateTime of 01.01.21 08:35:22 would show up as "35:22" on the axis labels.

I think in all common locales reading a time of "xx:yy" would always be interpreted as "HH:mm" or the 12 hour equivalent, so this looks broken. A better formatting would be `DateFormat.Hms()` in my opinion.

Additionally I would love to be able to provide DateFormatters for each of the DateTimeIntervalTypes. Right now I only see a way to set a global DateFormat that doesn't change with respect to the axis scale / zoom level. This would allow me to fix my initial problem if you don't agree with me on the appropriate formatting. Also a great way to customize the axis further, since your auto interval feature works really well.

**Comment by SriramKiranSenthilkumar** [comment]
Hi @ozzy91,

Greetings from Syncfusion. We have analyzed your scenario at our end, and we would like to share some information regarding the DateTimeAxis's autoInterval calculation in which we have made calculations based on the data source provided and also the value of DateTimeIntervalType provided for the axis and render the axis labels accordingly. For example, as per your case, if the axis label for DateTime value of 01.01.21 08:35:22 is getting rendered in the `DateFormat.Hms()`, then if there are more than 20 labels in the axis then the x-axis labels will get overlapped and will not be good for viewing.  So only we have kept this type of axis label formatting on auto interval calculation and provided a **dateFormat** property to format the axis labels if required. Currently, this is our default behavior.

However, we would also like to let you know that we are planning on new feature related to axis label formatting where the first date axis-label of the month will get rendered with its month name and the remaining date labels of that month will follow as such so that there will be clear view on the rendered axis labels. For example, if the axis labels in the x-axis is rendered in mm:ss format on auto interval calculation, then first hour's axis label will get rendered along with hour value like HH:mm:ss and the remaining labels of that hour will be in mm:ss format. Please check below reference screenshot regarding how the axis labels will get rendered with this feature for further reference.
![image](https://user-images.githubusercontent.com/63577117/136371438-469ead01-9bbc-47ab-b84a-ffde1cb5ea01.png)

Please revert us if you think that the above-mentioned feature will be helpful in you case so that we will check and consider this behavior has a new feature request.

Regards,
Sriram Kiran
