### ISSUE TITLE
[syncfusion_flutter_pdfviewer] Error when use SfPdfViewer.network() in web

### ISSUE THREAD

**Issue by apatheticL** [syncfusion/flutter-widgets#418]
Hi all.
I use SfPdfViewer.network()  on flutter web but it not working but show screen is gray.  it shows error like picture
my url: https://www.orimi.com/pdf-test.pdf
![image](https://user-images.githubusercontent.com/49410976/137086325-ac835b58-c9ea-4e42-b7b3-1293636e4ebb.png)

Thanks

**Comment by deepika134** [comment]
Hi apatheticL,

Greetings from Syncfusion.

The reported issue is known issue in flutter web application. This is due to CORS security limitation in web application. Kindly refer the following flutter forum.
https://github.com/flutter/flutter/issues/51125 .
On analyzing further, we found that this issue can be resolved by configure the CORS settings in the requested server or by disabling the security settings in chrome.dart as mentioned below steps:
1.Go to flutter\bin\cache and remove a file named: flutter_tools.stamp
2.Go to flutter\packages\flutter_tools\lib\src\web and open the file chrome.dart.
3.Find '--disable-extensions'.
4.Add '--disable-web-security'.

You can refer the following KB to load a PDF document from firebase storage in SfPdfViewer,
https://www.syncfusion.com/kb/12757/how-to-load-a-pdf-document-from-firebase-storage-in-syncfusion-flutter-pdfviewer 
You can also contact us through our [support forums](https://www.syncfusion.com/forums ), [Direct-Trac](https://www.syncfusion.com/support/directtrac ), or [feedback portal]( https://www.syncfusion.com/feedback/flutter ). We are always happy to assist you!


Regards,
Deepika Ravi
