### ISSUE TITLE
[Charts] selectDataPoints with overallDataPointIndex

### ISSUE THREAD

**Issue by andrea689** [syncfusion/flutter-widgets#42]
Hi, is there a way to select a data point with the index of dataSource and not with index of visible points?

Thank you.

**Comment by SriramKiranSenthilkumar** [comment]
Hi @andrea689,

Greetings from Syncfusion. We have analyzed your scenario and currently, the default behaviour in our chart is that you can only select the data points in the visible chart range using `SelectionBehavior`'s **`selectDataPoints`** public method. On further analyzing your query, we suspect that you need to select any data point outside the visible chart range and check for it by panning in the chart. Since we are not exactly sure on your requirement or use case for using the overalldataPointIndex to select the data point in the chart using the selection public method, we kindly request you to share us with more information on your requirement or scenario in detail so that it will be helpful in providing the solutions sooner.

Regards,
Sriram Kiran

**Comment by andrea689** [comment]
Yes, I want select any data point outside the visible chart range and pan the chart if needed.
Thank you!

**Comment by SriramKiranSenthilkumar** [comment]
Hi @andrea689,

Thanks for the revert. We will consider your suggestion as an improvement regarding dynamically select a data point outside the visible range with the index of the data source using **`selectDataPoints`** public method. We will implement and include this improvement in our upcoming weekly patch release which expected to be rolled out by the middle of next week. We will update you once the release is rolled out and we appreciate your patience until then.

Regards,
Sriram Kiran

**Comment by SriramKiranSenthilkumar** [comment]
Hi @andrea689,

Thanks for your patience. As we have now included the visible datapoints **`pointIndex`** and **`overallDataPointIndex`** arguments in the **`onSelectionChanged`** event in our latest weekly patch release so that you can now use these argument's values accordingly in order to process the selection of data points outside the visible chart range. So, kindly upgrade the chart widget package to the latest version below and let us know if you still have further concerns.
https://pub.dev/packages/syncfusion_flutter_charts/versions/18.3.50

Regards,
Sriram Kiran
