### ISSUE TITLE
Error: Stream has been disposed

### ISSUE THREAD

**Issue by SamarpanCoder2002** [syncfusion/flutter-widgets#423]
When I scroll it, that errors came

```
Bad state: Stream has been disposed.
An ImageStream is considered disposed once at least one listener has been added and subsequently all listeners have been removed and no handles are outstanding from the keepAlive method.
To resolve this error, maintain at least one listener on the stream, or create an ImageStreamCompleterHandle from the keepAlive method, or create a new stream for the image.
```

Hope that problem will resolved soon.

**Comment by wanzismail** [comment]
Hi @Yuvaraj-Gajaraj I was also having the same problem as mentioned above.

This issue occurs when using `syncfusion_flutter_pdfviewer` to zoom in/out on a pdf file.

**Comment by deepika134** [comment]
Hi wanzismail,

We tried to reproduce the reported issue, but the issue couldn't be reproduced on our end. For your reference, we have prepared a sample and it can be downloaded from the following link,
https://www.syncfusion.com/downloads/support/directtrac/general/ze/flutter_app_4231778733985.zip 

Kindly let us know if you are facing the reported issue with this sample. Also, please share the following details, to reproduce the reported issue on our end.
1. Platforms in which the issue is reproduced (Android, iOS, Web).
2. Device Specification.
3. Flutter Doctor log.
4. syncfusion_flutter_pdfviewer package version.
5. Flutter SDK version.

These information will be helpful for us to provide you a prompt solution at the earliest.

Regards,
Deepika Ravi
