### ISSUE TITLE
[syncfusion_flutter_pdfviewer] [Enhancement] Scrolling and panning not working after longpress

### ISSUE THREAD

**Issue by sagarkardani** [syncfusion/flutter-widgets#431]
### Current
- `enableTextSelection` is set to `false`
- finger down on screen and not moved for sometime. Afterwards scrolling and panning not working

https://user-images.githubusercontent.com/60609139/137680349-52d70877-84c8-41c6-8ca5-c5479991518c.mp4

### Enhancement
- If `enableTextSelection` is set to `true` then probably the current behaviour seems ok
- If `enableTextSelection` is set to `false` then it would be better if scrolling and panning works even after finger down on screen and not moved initially

Regards,
Sagar

**Comment by deepika134** [comment]
Hi Sagarkardani,
 
we have included the fix for this issue " Unable to pan the document when disabling the EnableTextSelection property" in our latest release, so kindly upgrade to the latest version v19.3.53 to get the issue resolved.  

Package link: https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/19.3.53-beta 
   
Regards, 
Deepika R
