### ISSUE TITLE
Deprecated API error

### ISSUE THREAD

**Issue by Erebus20058** [syncfusion/flutter-widgets#460]
Whenever I use the SyncFusion Package PDF viewer, I get an error that says:
SyncfusionFlutterPdfViewerPlugin.java uses or overrides a deprecated API.
This is the whole error:
Note: C:\Users\Erebus\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\syncfusion_flutter_pdfviewer-19.3.55-beta\android\src\main\java\com\syncfusion\flutter\pdfviewer\SyncfusionFlutterPdfViewerPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
After recompiling with Xlint:deprecation, this is the error:
C:\Users\Erebus\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\syncfusion_flutter_pdfviewer-19.3.55-beta\android\src\main\java\com\syncfusion\flutter\pdfviewer\SyncfusionFlutterPdfViewerPlugin.java:107: warning: [deprecation] getDefaultDisplay() in WindowManager has been deprecated
    Display display = wm.getDefaultDisplay();
                        ^
C:\Users\Erebus\Documents\flutter\.pub-cache\hosted\pub.dartlang.org\syncfusion_flutter_pdfviewer-19.3.55-beta\android\src\main\java\com\syncfusion\flutter\pdfviewer\SyncfusionFlutterPdfViewerPlugin.java:109: warning: [deprecation] getMetrics(DisplayMetrics) in Display has been deprecated
    display.getMetrics(metrics);
           ^
2 warnings

The app doesn't work in release state. It only works in debug mode

![Error](https://user-images.githubusercontent.com/90667519/143551221-9b601bed-b7cd-424a-8760-ebddfb672f75.PNG)
.

**Comment by FelipeSamuel** [comment]
Same problem with my project.

**Comment by dillibabu1802** [comment]
Hi @FelipeSamuel / @Erebus20058 

Thank you for contacting Syncfusion support.

We can reproduce the reported warnings at your end. We are checking on it and will update the analysis details on 1 December 2021.

Regards,
Dilli babu.

**Comment by Erebus20058** [comment]
Alright bro... Keep up the good work ❤️

**Comment by dillibabu1802** [comment]
Hi Everyone,

We will clear deprecation warnings due to display metrics in Android R SDK and included the code changes in December 1st Weekly package release which is estimated to be available on November 7, 2021, tentatively.  The status of this work can be tracked using following link.
[https://www.syncfusion.com/feedback/30826/android-clear-deprecation-warnings-due-to-display-metrics-in-android-r-sdk](https://www.syncfusion.com/feedback/30826/android-clear-deprecation-warnings-due-to-display-metrics-in-android-r-sdk)


Regards,
Dilli babu.

**Comment by deepika134** [comment]
Hi Erebus20058,

we have cleared the deprecation warnings due to display metrics in Android R SDK in our latest release, so kindly upgrade to the latest version v19.3.57.

Package link: https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/19.3.57-beta 

To run in release mode without any warnings in Flutter Stable version 2.5.3, please ensure the following changes are done in your application.

1. Provide internet access in all AndroidManifest.xml(main, profile and debug) -
`<uses-permission android:name="android.permission.INTERNET"/>
`

2. Remove the following line in AndroidManifest.xml, to resolve splash screen deprecated warnings in your sample.
```
<meta-data
  android:name="io.flutter.embedding.android.SplashScreenDrawable"
  android:resource="@drawable/launch_background"
  />

```
Regards, 
Deepika Ravi
