### ISSUE TITLE
pdf image 

### ISSUE THREAD

**Issue by IGated876** [syncfusion/flutter-widgets#47]
i realize when try to place an image it crashes when i take out the code it works fine. is there something i am missing?

PdfImage image = PdfBitmap.fromBase64String('R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7');

//Draws the image to the PDF page
page.graphics.drawImage(image, Rect.fromLTWH(pageSize.width - 30, pageSize.height - 70, 0, 0));

**Comment by Anand3595** [comment]
Hi IGated876 ,

We have validated the provided code and identified that the issue is not from the code snippet to draw an image. We are suspect the provided base64 string is for an image type GIF.  As of now, We have support to draw only JPEG and PNG images to PDF document by using flutter-pdf library. So, We suggest you to add JPEG or PNG images to PDF document instead of using GIF.

Please find the documentation for drawing PNG and JPEG image to PDF document from https://help.syncfusion.com/flutter/pdf/working-with-images.

With Regards,
Anand Panchamoorthi
