### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by JoelSuyati** [syncfusion/flutter-widgets#470]
I faced this error in the file      

radial_axis_widget.dart  ----------  line 1351

`begin = enableAnimation ? 0 : pointer.pointerInterval![0]! as double;`

**Comment by lakshmi-radhakrishnan** [comment]
Hi JoelSuyati,

We have tried to reproduce the reported scenario in SfRadialGauge with version 19.3.56 by enabling animation with all these pointers (Needle pointer, Marker pointer, Range pointer, and Widget pointer), but were unable to reproduce the mentioned exception at our end. Could you please share the snippet that you used in your application, if possible, so that we can reproduce the problem and provide solution earlier?

Regards,
Lakshmi R.
