### ISSUE TITLE
[SfCartesianChart] TrackballBehavior Tooltip is not shown on card to wide

### ISSUE THREAD

**Issue by jlnrrg** [syncfusion/flutter-widgets#476]
I use the custom builder for `TrackballBehavior`, which works like a charm.
Unfortunately on mobile the tooltip is not shown when it would break the border.
I would expect the tooltip to flow over the tooltip line if displaying is not possible otherwise.

Hereby is a video which displays the "disappearing" issue.

https://user-images.githubusercontent.com/77293597/145065420-2cb99e74-e595-4205-ae6c-8963d325e738.mp4

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @jlnrrg,

Greetings from Syncfusion. We have analyzed your query and we would like to let you know that, by default the trackball tooltip will be visible in the right side, if the tooltip exceeds the chart area in the right side the tooltip will be moved to left side. If there is no space on both sides, your tooltip may hide. So, we suspect this might be your case, to overcome this, you can reduce the text size in the tooltip and from your screenshot, we could find some space(margin) available at the left side, so you can reduce the spacing, so that the trackball tooltip will be visible. If this is not you case, get back to us with more information on your exact scenario, this will help us to provide you the solution at earlier.

Regards,
Yuvaraj.

**Comment by jlnrrg** [comment]
As you've outlined the issue is indead, that there is no space to neither side, so the tooltip hides.
My question is, if it would be possible for you to implement the function like this:
1. check if the widget can be displayed to the right side
2. check if the widget can be displayed to the left side
3. display the widget on top (over the tooltip line)

In the meantime I will try to implement an `AutoSizedText`.

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @jlnrrg,

We have analyzed your query, and we have considered this behavior as an improvement, and it will be implemented in any of our upcoming releases yet to come. We appreciate your patience until then, you can track the feature status in the below link.

Feedback: https://www.syncfusion.com/feedback/31338

Regards,
Yuvaraj.
