### ISSUE TITLE
[syncfusion_flutter_datagrid] Error when selecting all rows and switching theme colours

### ISSUE THREAD

**Issue by Shuriken97** [syncfusion/flutter-widgets#477]
Hi there! Currently I'm trying to implement light mode and dark mode for the datagrid. Currently I faced an issue when I'm selecting all rows and switching theme colours. I also passed a buildContext into the dataGridSource to detect the theme change dynamically. Below are a simple DataGridSource class code snippet that is using BuildContext to detect theme changes.

Ways to recreate the errors:
1) Pass BuildContext into dataGridSource
2) Select all rows
3) Trigger theme colour changes

Another additional question is that is there any other way to dynamically change custom widget colour in datagrid rows based on theme colour? Thanks in advance for the assistance

```
class ProductDataSource extends DataGridSource {
  ProductDataSource(this.context, {required List<Product> productData}) {
    _productData = productData
        .map<DataGridRow>((Product e) => DataGridRow(cells: <DataGridCell>[
              DataGridCell<String>(columnName: 'id', value: e.id),
              DataGridCell<String>(columnName: 'title', value: e.name),
              const DataGridCell<dynamic>(columnName: 'edit', value: ''),
            ]))
        .toList();
  }

  final int rowsPerPage = 10;
  final BuildContext context;
  List<DataGridRow> _productData = <DataGridRow>[];

  @override
  List<DataGridRow> get rows => _productData;

  @override
  DataGridRowAdapter buildRow(DataGridRow row) {
    final List<Widget> rowItem = row.getCells().map<Widget>((DataGridCell e) {
      if (e.columnName == 'edit') {
        return Container(
          alignment: Alignment.center,
          child: InkWell(
            child: SvgPicture.asset(
              'assets/icons/more.svg',
              color: Palette.handleLightDarkModeColor(context, Palette.black),
              height: 40,
              width: 40,
            ),
            onTap: () {
              print('Edit');
            },
          ),
        );
      } else if (e.columnName == 'title') {
        return Container(
          alignment: Alignment.centerLeft,
          padding: const EdgeInsets.all(10.0),
          child: Text(
            e.value.toString(),
            style: Get.textTheme.ceruleanBlueHeadline6,
            overflow: TextOverflow.ellipsis,
          ),
        );
      } else {
        return Container(
          alignment: Alignment.centerLeft,
          padding: const EdgeInsets.all(10.0),
          child: Text(
            e.value.toString(),
            style: context.textTheme.subtitle2,
          ),
        );
      }
    }).toList();

    return DataGridRowAdapter(
      color: Colors.transparent,
      cells: rowItem,
    );
  }
}

**Comment by Sangeetha-Raju** [comment]
Hi Shuriken97,

We have prepared a sample as like your requirement. We suspect that you might be recreating the DataGridSource on every time. Since you need only the Context in DataGridSource, we recommend you to maintain the DataGridSource in variable and assign it to SfDataGrid.source property. So that, DataGrid always remove the selected rows on every time when theme is changed.  When you maintain the DataGridSource in variable, DataGrid won’t refresh the DataGridRows when theme is changed. So, you can call the **DataGridSource.notifyListeners()** method to refresh the DataGridRows.

Please refer the sample from the following link.

**Sample link:** https://www.syncfusion.com/downloads/support/directtrac/general/ze/main-1634425848 

In the above sample, we have dynamically changed the text theme based on the theme color. Please check the above sample and revert us whether the provided solution meets requirement. If no, please modify the above sample based on your requirement and share the issue details. It will be helpful for us to check on it and provide you the solution at the earliest. 

Please let us know if you require any further assistance.

Regards,
Sangeetha Raju.
