### ISSUE TITLE
[syncfusion_flutter_charts]-[Area_with_empty_points]- y-value between 2 nulls is not shown.

### ISSUE THREAD

**Issue by FisherWL** [syncfusion/flutter-widgets#484]
area chart only draws when there are at least two contiguous non-null y-values.
area chart doesn't draw when a non-null y-value is between 2 null y-values.

if the y-values is a pattern of:
    num, null, num, null, num, null ...
then nothing will be shown on the area chart.

take the official example for instance,
if the chartData is changed to:
<ChartSampleData>[
      ChartSampleData(x: 2002, y: 220000000),
      ChartSampleData(x: 2003, y: null),
      ChartSampleData(x: 2004, y: 280000000),
      ChartSampleData(x: 2005, y: null),
      ChartSampleData(x: 2006, y: null),
      ChartSampleData(x: 2007, y: 250000000),
      ChartSampleData(x: 2008, y: null),
      ChartSampleData(x: 2009, y: 380000000),
      ChartSampleData(x: 2010, y: null),
      ChartSampleData(x: 2011, y: 310000000),
    ];

then nothing will be shown.

**Comment by SriramKiranSenthilkumar** [comment]
Hi @FisherWL ,

Greetings from Syncfusion. We have analyzed your query at our end, and we would like to let you know that when there are null y-values in the chart data points, then those data points are considered as gap by default by **EmptyPointSettings** feature and due to which in your case the area chart data points are only rendered as there is gap between each available y-value data points. If you want to connect those available data points omitting the null y-value data points, then you can change the **emptyPointMode** to _**drop**_ so that it will omit the null y-value data points and connect the available data points in the chart and also there are other modes available such as **_zero_**, **_gap_** (default value), and **_average_**. We have also created a sample with the help of provided chart data points and set the **emptyPointMode** to **_drop_** at connect the available data points in the chart.

sample: 
[alternateemptypoints.zip](https://github.com/syncfusion/flutter-widgets/files/7709895/sf_358978_alternateemptypoints.zip)


For further reference on EmptyPointSetting feature, please refer the user guide link below.
https://help.syncfusion.com/flutter/cartesian-charts/series-customization#empty-points

Regards,
Sriram Kiran
