### ISSUE TITLE
SfCartesianChart synchronized trackball

### ISSUE THREAD

**Issue by enfshin** [syncfusion/flutter-widgets#489]
Hey, Thanks for all your works. 
I don't know this is my problem or bug. but nowhere to ask.
![20211216_015053](https://user-images.githubusercontent.com/58045951/146245740-cb643f69-926c-4a0b-908f-391112069068.png)

Synchronized trackball is working almost fine.
I made it by following below URL.
https://www.syncfusion.com/kb/11881/how-to-synchronize-trackball-in-multiple-charts-sfcartesianchart 
I follow exactly. different is that I have 288 series for each chart and synchronized zoom. 

everythings works fine but as you can see in two tackball's datetime.
one is "12-15 14:20" and other is "12-15 14:00". it's close but not same.
every time I tapped chart. most of time two chart's synchronized trackball's X location is close but not same. 
Can you guess why?? any segesstion where to look up?

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @enfshin 

Greetings from Syncfusion. We have analyzed your query and we suspect the visible minimum and maximum in your sample are not same in both the charts due to which you might be facing the reported issue. Because in that KB we have only synchronized the trackball of the two charts based on the pixel position where we interact with the chart. So, in this case, the visible minimum, maximum and height, and width of the chart must be same then only you get the same value in the trackball tooltip.

Here we have another method called point, you can render a synchronized trackball based on the x and y value of the data points in the chart so that it will help you to show the exact value in the trackball tooltip. We have also provided the code snippet below for your reference.

Code snippet:

```dart
onTrackballPositionChanging: (TrackballArgsargs) {
trackBall1.show(args.chartPointInfo.chartDataPoint!.x,
args.chartPointInfo.chartDataPoint!.y);
        },
```

If you have any further query, please get back to us.

Regards,
Yuvaraj.
