### ISSUE TITLE
Latest update breaks SfDataGridThemeData brightness

### ISSUE THREAD

**Issue by Reprevise** [syncfusion/flutter-widgets#497]
In earlier releases, setting the `brightness` in `SfDataGridThemeData` to `Brightness.dark` would set the text color of the elements in the table to white. As of the latest release, it seems to have been broken and the cell text color is now black.

**Comment by mrtkp9993** [comment]
@Sangeetha-Raju This is not worked for my app.

**Comment by Sangeetha-Raju** [comment]
Hi @mrtkp9993,

We have provided a sample in our previous update. Can you please check whether the issue is replicating in our sample? If yes, please provide the following details, 

1.	Which Flutter channel (Stable, beta or Master) are you using? 
2.	Provide the version of DataGrid package.
3.	Issue replicating platform.

If we misunderstood anything, please modify the sample based on your requirement or provide the code snippet. It will be helpful for us to check on it and provide you the solution at the earliest.    

Regards,
Sangeetha Raju.
