### ISSUE TITLE
[syncfusion_flutter_pdfviewer] error invalid file path

### ISSUE THREAD

**Issue by BrunoAlm** [syncfusion/flutter-widgets#517]
## I got this error importing the syncfusion_flutter_pdfviewer package

[Error - 21:29:35] Request textDocument/codeAction failed.
  Message: Invalid file path
  Code: -32003 

[Error - 21:29:35] Request textDocument/colorPresentation failed.
  Message: Invalid file path
  Code: -32003 

[Error - 21:29:35] Request textDocument/documentSymbol failed.
  Message: Invalid file path
  Code: -32003 

[Error - 21:29:35] Request textDocument/codeAction failed.
  Message: Invalid file path
  Code: -32003 

[Error - 21:29:37] Request textDocument/hover failed.
  Message: Invalid file path
  Code: -32003 

[Error - 21:30:02] Request textDocument/documentSymbol failed.
  Message: Invalid file path
  Code: -32003 

# *The error goes off if I remove the import*

**Comment by deepika134** [comment]
Hi BrunoAlm,

We tried to reproduce the reported issue, but the issue couldn't be reproduced on our end. For your reference, we have prepared a sample and it can be downloaded from the following link,
https://www.syncfusion.com/downloads/support/directtrac/general/ze/flutter_app_4231778733985.zip

Kindly let us know if you are facing the reported issue with this sample. Also, please share the following details, to reproduce the reported issue on our end.
1. Platforms in which the issue is reproduced (Android, iOS, Web).
2. Device Specification.
3. Flutter Doctor log.
4. syncfusion_flutter_pdfviewer package version.
5. Flutter SDK version.

These information will be helpful for us to provide you a prompt solution at the earliest.

Regards,
Deepika Ravi

**Comment by BrunoAlm** [comment]
I've switched to flutter stable and restarted dart analysis server.
Seems to be ok now!
