### ISSUE TITLE
[syncfusion_flutter_xlsio] How to read xlsx file?

### ISSUE THREAD

**Issue by luiscarielo83** [syncfusion/flutter-widgets#523]
How to read xlsx file??

**Comment by KonduruKeerthi** [comment]
Greetings from Syncfusion.

Syncfusion Flutter XlsIO does not have support for opening existing Excel documents. We have logged a feature report for this but do not have immediate plans for implementation. You can track the status of the feature report through the following feedback link.

https://www.syncfusion.com/feedback/21974/read-excel-files-using-flutter-xlsio

Regards,
Keerthi.

**Comment by marcellocamara** [comment]
any updates? there is possible to read the content of an xlsx file ?
I've trying using another packages, without success.

**Comment by luiscarielo83** [comment]
@marcellocamara 
Hello, with "excel" dependence you can read a xlsx file.

[https://pub.dev/packages/excel](url)

Greetings

**Comment by marcellocamara** [comment]
> With "excel" dependence you can read a xlsx file.

Thanks, @luiscarielo83, but with excel I've a particular issue opened here: https://github.com/justkawal/excel/issues/350

Unfortunately, is not possible to read the content of this example xlsx:
https://servicebus2.caixa.gov.br/portaldeloterias/api/resultados/download?modalidade=Mega-Sena

**Comment by luiscarielo83** [comment]
@marcellocamara 
Maybe, you need to download the file to the device and not try to read it from the "response"

**Comment by marcellocamara** [comment]
> @marcellocamara Maybe, you need to download the file to the device and not try to read it from the "response"

@luiscarielo83 the problem is to read the content of the file, programatically.
The fact of use the bodyBytes OR create a File from the http result in the same problem. Can't reach the content.

**Comment by marcellocamara** [comment]
> Change the sheet name. No special characters, no accents, just letters.

Unfortunately this don't work. This excel file don't have special characters or accents and can't read the content too:
[Quina](https://servicebus2.caixa.gov.br/portaldeloterias/api/resultados/download?modalidade=Quina)

**Comment by luiscarielo83** [comment]
@marcellocamara 
I made a small application with your file (MAIS_MILIONARIA.xlsx) to test. It worked!
I just added the file to the "assets" directory and renamed it to the sheet.
Try it by adding the file in the assets directory or use the FilePicker option as the documentation says.

This is the code I used:

```
void _getExcelData() async {
    ByteData data = await rootBundle.load('assets/xlsx/MAIS_MILIONARIA.xlsx');
    var bytes = data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);
    var excel = Excel.decodeBytes(bytes);
    for (var table in excel.tables.keys) {
      debugPrint(table); //sheet Name
      debugPrint(excel.tables[table]?.maxColumns.toString());
      debugPrint(excel.tables[table]?.maxRows.toString());
    }
  }
```

**Comment by marcellocamara** [comment]
@luiscarielo83, thanks for this replies. You're helping a lot.
I'm still confusing about some points. I didn't get success with your example code. 

What version of flutter/dart are you using? What version of excel ?

My environment:
```dart
environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: 3.19.6
```
I'm using `excel: ^4.0.3`

I added the local file into the assets folder and the same problem is throwed: `Damaged Excel file: Corrupted Excel file.`. Don't know why. Something is wrong.

> I just added the file to the "assets" directory and renamed it to the sheet. Try it by adding the file in the assets directory 

Another point, did you tryed to get it from http request? Getting the `responde.bodyBytes` to instantiate the `Excel` variable? 
Because this is required as this url gives the file updated...
I was trying to figure out why via http request don't work and when you added into the assets worked. But I tryed local and didn't get success too hahah

Can you see my example project here, if you don't mind? It's a basic example with understading code :)
Clone it to see: 
https://github.com/marcellocamara/issues/blob/master/Flutter3Excel/lib/main.dart

Thanks 😄 

An image of my example app:
![Captura de Tela 2024-05-07 às 22 11 51](https://github.com/syncfusion/flutter-widgets/assets/18273071/988c1838-cb90-44db-bddd-f15709e024eb)

**Comment by luiscarielo83** [comment]
@marcellocamara 
Hello!

- Flutter version: 3.19.3
- Android Studio Jellyfish | 2023.3.1

----------------

- My pubspec.yaml:
<img width="358" alt="pubspec" src="https://github.com/syncfusion/flutter-widgets/assets/82050214/e6d1fc10-8fce-4bd8-a932-a318a0844236">

----------------

- No special characters, no accents, no spaces in the sheet name:
<img width="395" alt="sheet-name" src="https://github.com/syncfusion/flutter-widgets/assets/82050214/49c491aa-4819-4f17-9c1d-a8a0845d9e6b">

----------------

- Url response (postman):
<img width="1240" alt="postman-response" src="https://github.com/syncfusion/flutter-widgets/assets/82050214/f06d1565-89da-40ff-84f2-fb93b773abba">

----------------

- It works when the sheet name has no special characters, accents or spaces (fetchFromAsset):
<img width="635" alt="console" src="https://github.com/syncfusion/flutter-widgets/assets/82050214/7fb57db8-870d-46dd-89d9-0422e011826d">

----------------

Conclusion: First, you need to download and store the URL file on the device, because the "response" doesn't detect that it is an xlsx file. After downloading and storing the file, implement FilePicker to select and open the xlsx file.
And don't forget to change the name of the sheet (no special characters, no accent marks, no spaces).

I hope you can solve the problem soon. Greetings

**Comment by marcellocamara** [comment]
> Your code is fine. I did tests in both cases (assets and url) and it showed the error. 

@luiscarielo83 thanks. I didn't understand what was happening.

> What I did to make it work was change the name of the sheet (no special characters, no accents, no spaces).

Now I understood. You did make manual edit, opening the xlsx file... I'm using macOS and I don't have the software to open .xlsx files format.

> What I did to make it work was change the name of the sheet (no special characters, no accents, no spaces).

I was thinking that the name of **file** should be changed (without the special characters and accents)... I was wrong. I used my windows desktop, edited the sheet name **inside the file** and it **worked**.

But, something still don't making a sense:
[Thinks xlsx](https://servicebus2.caixa.gov.br/portaldeloterias/api/resultados/download?modalidade=Quina) file, don't have special characters, accents or spaces (Quina) and it don't works.

![quina](https://github.com/syncfusion/flutter-widgets/assets/18273071/cad78a7b-e926-4c42-b1b0-be67798c198b)

It worked only when I did the manual change to lower case:

![quina-lowercase](https://github.com/syncfusion/flutter-widgets/assets/18273071/bb54ded1-ba9a-4319-8aef-921558590544)
![Captura de Tela 2024-05-08 às 12 47 21](https://github.com/syncfusion/flutter-widgets/assets/18273071/cce70362-ddca-423e-99f7-98056ae208ae)

So, the point is: I don't think there's any possibility of doing this programatically, right?
> Try it by adding the file in the assets directory or use the FilePicker option as the documentation says.

You mentioned a way to open it with FilePicker, but I didn't understand the idea. Because I'm trying to do this programmatically, without user intervention...
I'm not an expert in reading files. To be honest, this is my second time reading a file.
But my goal is to read this file programmatically, by requesting the url (since this data is updated and does not require manual interventions).

This isn't a job or anything.
This is an open file from a Brazilian lottery that is giving me a lot of headaches with a personal hobby project hahaha

Regards from Rio de Janeiro :sunrise:

**Comment by marcellocamara** [comment]
@luiscarielo83 
Hey bro. I got it 😄 

I've forked the Excel plugin and fixed the error. Now every excel can be read with success by **local asset** AND from from the **HTTP REQUEST** 👍🏻

**Comment by luiscarielo83** [comment]
@marcellocamara 

Hello! Sorry, I've had a lot of work.
It's excellent news. How did you make it so that it could read the xml file?

**Comment by marcellocamara** [comment]
> How did you make it so that it could read the xml file?

@luiscarielo83 
I've made some changes to my specific case
Debugging and seeing the errors, fixing each step.

I've opened an issue to owner can see a better way to fix it.
Until there, I'll be using my fork.
https://github.com/justkawal/excel/compare/main...marcellocamara:excel:main

**Comment by luiscarielo83** [comment]
@marcellocamara 
Hello!
Great news! The flutter community will thank you.
Greetings.
