### ISSUE TITLE
Can't parse TextLine and TextWord messy code

### ISSUE THREAD

**Issue by blackCatDog** [syncfusion/flutter-widgets#524]
I tried to read TextLine and TextWord data, they were garbled and could not parse my PDF file. Please help me
https://drive.google.com/drive/folders/12MASizpWlNMBbEwcA6-I-f1Y7RXjjp13?usp=sharing

**Comment by blackCatDog** [comment]
![image](https://user-images.githubusercontent.com/4517330/148635346-f5f0c697-d98c-4201-b043-bd3edf2e88e4.png)
laoren5.pdf

**Comment by blackCatDog** [comment]
a29.pdf  Unable to display PDF

**Comment by blackCatDog** [comment]
a234.pdf
![image](https://user-images.githubusercontent.com/4517330/148635412-b38648b5-06d6-437b-976b-01a0cbdf25f7.png)
![image](https://user-images.githubusercontent.com/4517330/148635428-36d627ca-05c8-4c6f-b40b-747e64f2aff8.png)

**Comment by Surya-3013** [comment]
Hi @blackCatDog,

We were able to face the PDF parsing issue in a29.pdf file and the text extraction issue in laoren5.pdf file. The a234.pdf file works fine and does not cause any issue while extracting the text from it. Currently, we are analyzing the reported issue and we will update the further details on January 12th, 2022.

Regards,
Surya V

**Comment by Surya-3013** [comment]
Hi @blackCatDog ,

We have confirmed that the issue with “Runtime exception occurs while parsing and extracting the text from specific input documents” is a defect. The fix for this issue will be available in our weekly NuGet release on January 25th, 2022.

Kindly use the below feedback link to track the status of the reported bug,
https://www.syncfusion.com/feedback/31824/exception-occurs-while-parsing-and-extracting-the-text-from-specific-input

Regards,
Surya V
