### ISSUE TITLE
Bar chart show the marker

### ISSUE THREAD

**Issue by donny681** [syncfusion/flutter-widgets#529]
I want  to column chart show the marker line like below picture.I don't know how to set the widget.
![1641786240(1)](https://user-images.githubusercontent.com/16253875/148716145-3f9df216-863a-4822-8cb7-417f0f527a7d.png)

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @donny681,

Greetings from Syncfusion. We have analyzed your query and we would like to let you know that our chart has the plotBand feature, by using this you can render a line at a specific point. We have also attached the sample and KB below for your reference.

Sample: [github_529.zip](https://github.com/syncfusion/flutter-widgets/files/7838490/github_529.zip)

KB: https://www.syncfusion.com/kb/12951/how-to-render-a-line-at-a-specific-axis-value-in-cartesian-charts-sfcartesianchart 

If you need to move the line when perform user interaction, we suggest you using the trackball and disable the trackball’s tooltip like in the given below code snippet, this will show only the track line.

Code snippet:

```dart
trackballBehavior: TrackballBehavior(
    enable: true,
    tooltipSettings: InteractiveTooltip(enable: false)
)
```

Hope this will help you to achieve your requirement.

Regards,
Yuvaraj.

**Comment by donny681** [comment]
Thanks @Yuvaraj-Gajaraj ,I try your demo and find that the line cannot move to other bar when I choose the other bars , the line is alaways in the middle of the chart.
![1641827408(1)](https://user-images.githubusercontent.com/16253875/148789017-34d3e2fd-c08c-4e4b-821b-8173227d81ce.png)

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @donny681,

We have analyzed your query and we would like to let you know that the plotBand is used for rendering a line at the given position, if you want to move a line dynamically you can go for the trackball feature. Here you can move the line dynamically on the chart data point when you tapped on the plot area. So, you can use a trackball instead of plotBand to achieve your requirement. We have attached the code snippet below for your reference and we hope it will help you to achieve your requirement.

Code snippet:
```dart
trackballBehavior: TrackballBehavior(
   enable: true,
   tooltipSettings: const InteractiveTooltip(enable: false),
   activationMode: ActivationMode.singleTap,
   shouldAlwaysShow: true
),
```

However, you can update the plotBand line dynamically and we have attached a demo sample for your requirement below.

Sample: [plotBand.zip](https://github.com/syncfusion/flutter-widgets/files/7847425/plotBand.zip)


Regards,
Yuvaraj.
