### ISSUE TITLE
[syncfusion_flutter_charts] Is it possible to syncronize few charts?

### ISSUE THREAD

**Issue by theRealGetman** [syncfusion/flutter-widgets#540]
Hey
Is it possible to syncronize few charts?
This is what I mean:
1) On the screen we have 2-n charts one below another
2) They all have the same x-axis range
2) When we pinch/zoom/scroll(change range with load more) on one chart (this is only limited for x-axis), we should see same changes on other charts too

Thanks for quick response :)

**Comment by theRealGetman** [comment]
Hey @SriramKiranSenthilkumar 

Thank you for your response! Samples that you provided were really helpful and I was able to synchronize charts!
The little issue is performance, since I am using thousands of points for each chart... 

Is there any possibility to have "onRendering" callback, to make it possible to display loader, while chart is redrawing? 

Regards, 
Artem Getman

**Comment by Marismathan** [comment]
Hi @theRealGetman ,

We would like to let you know that with the previous provided sample for loadMoreIndicatorBuilder, we have already added circular progress bar to indicate the data is loading. Also we have online demo sample for this requirement.

Demo: https://flutter.syncfusion.com/#/cartesian-charts/infinite-scrolling

Can you please ensure this whether this can fulfill your requirement?

Thanks,
Marismathan G

**Comment by theRealGetman** [comment]
@Marismathan Loading indicator shows when data is fetching from the service, but is it possible to show loading indicator while points are rendering on the chart? I am using thousands of points and it takes time to draw it. And from user's perspective it looks like freezing.

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @theRealGetman,

We have analyzed your query, and we have created a simple sample to show a load indicator while data rendering, we have replaced the chart after the 1500 millisecond time period because the default animation for the series is 1500 milliseconds. We hope it will help you to achieve your requirements.

Sample: [github_540.zip](https://github.com/syncfusion/flutter-widgets/files/7990339/github_540.zip)

Regards,
Yuvaraj.
