### ISSUE TITLE
isSeriesInRow = true, shows error Null check is used on null value

### ISSUE THREAD

**Issue by MetriSomesh** [syncfusion/flutter-widgets#550]
I am developing an app currently and my data is stored in rows. I wanted a line chart which takes data from rows, but when I set isSeriesInRow=  true it shows error " Null check is used on null 
![error](https://user-images.githubusercontent.com/80524132/150960937-f19ea02d-c531-4b65-b44b-7ac9fd332d18.jpg)
![error2](https://user-images.githubusercontent.com/80524132/150960988-f3742433-de09-4075-aa0a-c29a9d70101a.jpg)
value"

**Comment by SivakumarRamya** [comment]
Hi 

We have confirmed the issue as an Exception is thrown when a chart series category label has an empty value and logged a defect report. We will include the fix for this issue in our upcoming weekly NuGet release scheduled for February 8, 2022.

You can track the status of the defect report through the following feedback link.

Track Status: https://www.syncfusion.com/feedback/32292/exception-is-thrown-when-a-chart-series-category-label-has-an-empty-value

We will let you know once the new package version is available on nuget.org.

Regards,
Ramya.

**Comment by MetriSomesh** [comment]
By opening the link it shows access denied

**Comment by SivakumarRamya** [comment]
Hi

We regret the inconvenience.
We have now resolved the issue and request you to try again and let us know if you can now track the feedback.

Regards,
Ramya.
