### ISSUE TITLE
syncfusion dataGrid update cells value by changing current cell value

### ISSUE THREAD

**Issue by abdulrehmananwar** [syncfusion/flutter-widgets#559]
i want to update amount column when i change qty column or rate column value. currently i am doing this onCellSubmit event.and after update i call  notifyListeners(); butt i want to call beginEdit fuction which not working.

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @abdulrehmananwar 

The editing will be ended when you call the **notifyListeners()** externally to update the cell data. So, instead of calling the **notifyListeners()**, just use the **notifyDataSourceListeners** method to update the specific cell. Here, we have provided the sample as per your requirement. Please refer to the below sample and code snippet,

**Code Snippet:**

``` dart
void onCellSubmit(DataGridRow dataGridRow, RowColumnIndex rowColumnIndex,
      GridColumn column) {
    final dynamic oldValue = dataGridRow
            .getCells()
            .firstWhereOrNull((DataGridCell dataGridCell) =>
                dataGridCell.columnName == column.columnName)
            ?.value ??
        '';

    final int dataRowIndex = dataGridRows.indexOf(dataGridRow);

    if (newCellValue == null || oldValue == newCellValue) {
      return;
    }
…
    //Calls all the datagrid source listeners. Call this method whenever the underlying data is added or removed.
    //If the value of the specific cell is updated,
    //call this method with RowColumnIndex argument where it refers the corresponding row and column index of the cell

    notifyDataSourceListeners(rowColumnIndex: RowColumnIndex(dataRowIndex, 4));  
  }

```

**Sample Link**: https://www.syncfusion.com/downloads/support/directtrac/general/ze/main-2119549888

We hope this helps. Please let us know if you have any questions.

Regards,
Tamilarasan
