### ISSUE TITLE
Flutter charts | Multi Touch Support

### ISSUE THREAD

**Issue by brianschardt** [syncfusion/flutter-widgets#57]
Does this library have multi touch support? e.g. touch a graph at 2 different points like the stock graph for apple stocks on the iphone

**Comment by SriramKiranSenthilkumar** [comment]
Hi @brianschardt,

Greetings from Syncfusion. We have analyzed your scenario at our end and we have created a simple sample in which we have integrated chart widget with [range selector](https://pub.dev/packages/syncfusion_flutter_sliders) widget in order to select the necessary data points in the chart by moving the range selector sliders along the chart axis range. We have attached the created sample below for your reference. Please check with the attached sample and revert us if you have further concerns. 
Sample:  [sample.zip](https://github.com/syncfusion/flutter-widgets/files/5553283/sample.zip)

We have also attached our GitHub example sample in which the range selector widget and chart widget are used to select the necessary data points in the chart.
- https://github.com/syncfusion/flutter-examples/blob/master/lib/samples/sliders/range_selector/range_selector_default_appearance.dart

Also, if you think that we have misunderstood you query then, we kindly request you to share us with more information on your requirement in detail along with example screenshots or screen recordings so that it will help provide the solutions sooner.

Regards,
Sriram Kiran
