### ISSUE TITLE
[syncfusion_flutter_xlsio] Add an option to make sheet RTL

### ISSUE THREAD

**Issue by ahmednfwela** [syncfusion/flutter-widgets#572]
an option can be added to worksheet that specifies the sheet direction (RTL/LTR), a default option can be added to the workbook too for simplicity

**Comment by SivakumarRamya** [comment]
Hi ahmednfwela,



Greetings from Syncfusion.



We have logged a feature report as RTL support in Excel using Flutter XlsIO but do not have any immediate plans to implement this feature in near future. You can track the status of the feature report through the following feedback link.



Track Status: https://www.syncfusion.com/feedback/32534/rtl-support-in-excel-using-flutter-xlsio



Regards,

Ramya.

**Comment by ahmednfwela** [comment]
comments for future PRs:
---
example implementation here:
https://github.com/justkawal/excel/blob/372468a459ac2a56261a0c0e60773e3936cd1166/lib/src/save/save_file.dart#L142

in `sheetView` XML element, set `rightToLeft` attribute to `1` or `0`

**Comment by SivakumarRamya** [comment]
Hi ahmednfwela,

Thanks for contributing the changes to the library.

We will include the fix for this enhancement on **March 1, 2022.**
You can track the status of the feature report through the following link.

Track Status: https://www.syncfusion.com/feedback/32534/rtl-support-in-excel-using-flutter-xlsio

Regards,
Ramya

**Comment by SivakumarRamya** [comment]
Hi ahmednfwela,

We appreciate your patience.

We have included the fix for the **RTL support in Excel using Flutter XlsIO** in our weekly NuGet release version **19.4.0.54**. Kindly upgrade your Syncfusion packages to this new **19.4.0.54** version.

To enable the right to left direction in the worksheet, you need to enable **Worksheet.isRightToLeft** property. Kindly try this and let us know if it works.

Regards,
Ramya.
