### ISSUE TITLE
Flutter Charts - Scrolling Doesnt work

### ISSUE THREAD

**Issue by brianschardt** [syncfusion/flutter-widgets#58]
When you try scrolling on the graph to scroll down the page, the scrolling wont work when Crosshair is enabled

```
CrosshairBehavior(
                enable: true,)
```
. Which is good for some cases, and bad for others. 
The long press activation method should allow users to easily scroll down when the crosshair has not been pressed for a long time. 

Let me know if you need any more information.

**Comment by SriramKiranSenthilkumar** [comment]
Hi @brianschardt,

Greetings from Syncfusion. We have analyzed on your scenario at our end and we would like to share some information regarding the changes related to user interaction which we have made and rolled out in our latest release. We have now prohibited scrolling gesture when user interaction enabled in the chart for better user experience. For example., say we have a simple chart with user interactions enabled such as zooming/panning, trackball, crosshair etc. and the chart is inside a scrollable widget. The old behaviour is that when the user tries to interact with the chart (say panning in the chart vertically or horizontally), then the scrolling will be performed alongside while the chart is being panned which will decrease the user experience and so, we have made some changes in our source to make the user experience better and currently, the default behaviour is that when the user interaction is enabled in the chart the scrolling will be prohibited.

Please get in touch with us if you require further assistance on this.

Regards,
Sriram Kiran

**Comment by brianschardt** [comment]
I agree that the user when navigating the graph with their finger there scrolling should be disabled, which is what you have. 
However, what i disagree with is if the activation mode is set to "longPress" that scrolling should be enabled until one has long pressed on it. Does this make sense
For an example, use Apple Stocks on IOS they do this very well.

**Comment by SriramKiranSenthilkumar** [comment]
Hi @brianschardt,

Thanks for the revert. We have analyzed your query at our end and on checking the Apple stocks application in IOS, we found that the crosshair was getting activated on the single tap itself instead of activating on long press and the scrolling was prohibited at that time. To ensure this from our side, we have also attached screen recording of the apple stock application in IOS below in which we have checked scrolling behaviour of the apple stocks chart in IOS.
Screen recording: [Screen_recording.zip](https://github.com/syncfusion/flutter-widgets/files/5564850/screenrecording.zip)


Also, to mention that, we agree with your query regarding the scrolling gesture should be enabled until the user has long pressed on the chart to activate the crosshair. However, in apple stocks chart, the crosshair is getting activated on the single tap itself thereby prohibiting scrolling in the screen as mentioned above. So, we kindly request you to share us with some competitors examples whose has this type of behaviour in their widget along with example screen recording so that we will be able to analyze on it and change the user interaction behaviour in our chart widget.

Regards,
Sriram Kiran

**Comment by jfox454** [comment]
Is there any way to override this behaviour?

I have a screen which consists of multiple charts inside a ListView - users can scroll vertically to view other charts. Each chart has user interaction (zooming and trackball) enabled. 

In the previous version users could start their vertical scroll by dragging from either the x-axis or y-axis. This is now not working and instead users can only start their vertical scroll by dragging from the legend area.
