### ISSUE TITLE
Crosshair not efffected by decimalPlaces 

### ISSUE THREAD

**Issue by RomanIvnitzki** [syncfusion/flutter-widgets#584]
![image](https://user-images.githubusercontent.com/95280630/153895818-0ad5f805-4924-4cb7-acd0-8dad9dab40a3.png)

set decimalPlaces to 0,   crosshair displays 3.

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @RomanIvnitzki,

Greetings from Syncfusion. The reported issue regarding crosshair not effected by decimal places is not reproduced at our end, we have attached the sample below which is used in the testing phase for your reference. Since the issue is not replicated, kindly get back to us by modifying the attached sample, this will be helpful in providing the solution.

Screenshot:

Crosshair with decimal place 2
![image](https://user-images.githubusercontent.com/61863686/154331869-1b59a02a-1ea5-4490-91a9-2417c2ce3c41.png)

Crosshair with decimal place 3
![image](https://user-images.githubusercontent.com/61863686/154332003-70e3c5a0-9a17-4274-8996-4d82c5569460.png)

Sample: [github_584.zip](https://github.com/syncfusion/flutter-widgets/files/8082540/github_584.zip)

Regards,
Yuvaraj.
