### ISSUE TITLE
LegendItemOverflowMode.wrap on the Legend of a SfCartesianChart is not working

### ISSUE THREAD

**Issue by kazume** [syncfusion/flutter-widgets#598]
Not sure what we're doing wrong, but setting the LegendItemOverflowMode to "wrap" has just the same effect than setting it to "none". Setting it to "scroll" works. Any known issues here?

    SfCartesianChart(
      key: UniqueKey(),
      plotAreaBorderWidth: 0.0,
      primaryXAxis: CategoryAxis(
        majorTickLines: MajorTickLines(width: 1.0),
        majorGridLines: MajorGridLines(width: 0.0),
      ),
      series: _getSeries(), // some SplineSeries
      legend: Legend(
        isVisible: true,
        itemPadding: 30.0,
        position: LegendPosition.bottom,
        overflowMode: LegendItemOverflowMode.wrap,
      ),
      tooltipBehavior: TooltipBehavior(
        enable: true,
      ),
    )

Third label missing:

<img width="321" alt="Third label missing" src="https://user-images.githubusercontent.com/15020377/155275856-dbc95fa5-ec65-4836-9730-ea420b5bb0e2.png">

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @kazume,

Greetings from Syncfusion.
We have checked the reported issue from our side and the Cartesian chart legend overflow mode property is working properly, please find the detailed explanation for the none and wrap overflow modes below.

**For none:**
Here legends are positioned automatically where most of the legends didn’t get hidden, then the position legends didn't get the scroll.

![image](https://user-images.githubusercontent.com/61863686/155298452-c61bbdb7-6190-47d7-aa76-0d63d60a8884.png)

**For wrap:**
Here legend is wrapped one by one inside a scrollable widget based on the width available in the chart.

![image](https://user-images.githubusercontent.com/61863686/155298497-08a5d2ab-4cce-4046-ae59-b6283dd2f4b5.png)

In your case legend is not wrapped because the legend item's width didn't exceed the available width, hence it is not wrapped. The wrap works only when the width of the legend items exceeds the available width.

We hope it will help you know the behavior of legend overflow modes none and wrap, if you have any further query, please get back to us.

Regards,
Yuvaraj.

**Comment by kazume** [comment]
Ok, I see where the problem is. The width of the Legend *does* exceed the available width (see attached picture), but [from the documentation](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/LegendItemOverflowMode.html), it's not clear that the wrapped Legend is put in a scrollable widget (hence I didn't even try to scroll vertically). I'll have to check how to solve this issue. In my opinion, it would be better to let the Legend expand itself downward to make it entirely visible.

<img width="336" alt="Screenshot 2022-02-23 at 11 28 09" src="https://user-images.githubusercontent.com/15020377/155302340-b1191c39-54ef-4177-8062-d4c7ec9de83d.png">

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @kazume,

Thanks for your valuable suggestions. By default, the legend occupy the space 30% of the total space in chart. if we give more space to legend, the plot area size will be reduced. And by default, the overflowMode will be LegendItemOverflowMode.scroll, in your case you can explicitly set the overflow mode as LegendItemOverflowMode.wrap so that you can view the legends properly and as you have stated kindly set the height to the legend in your application.

Thanks,
Yuvaraj

**Comment by kazume** [comment]
Hi @Yuvaraj-Gajaraj ,

thx for the quick reply and the help. I find out that setting the legend item padding to less will do the trick for our current application (because we have a maximum of 3 series only), so closing the this issue for the moment.

For the record though, I *have* set LegendItemOverflowMode explicitly to "wrap" (which is not working as expected, as stated before) and setting the height of the Chart is not an option because a) it will mess up the layout below and b) the chart proportions get distorted.
