### ISSUE TITLE
Flutter charts (web): Hiding a single LineSeries's tooltip does not work

### ISSUE THREAD

**Issue by idraper** [syncfusion/flutter-widgets#60]
I am trying to make only 1 tooltip appear on a SfCartesianChart with 2 LineSeries. I found the following solution:
https://www.syncfusion.com/forums/154846/how-to-disable-a-trackball-for-a-specific-series

However, when edited this error occurs:
```
════════ Exception caught by rendering library ═════════════════════════════════
RangeError (index): Index out of range: index should be less than 1: 1
The relevant error-causing widget was
SfCartesianChart
lib\…\pages\logging.dart:21
════════════════════════════════════════════════════════════════════════════════
```

If I change `args.chartPointInfo.label = '';` to have any non-empty string (eg `args.chartPointInfo.label = 'test';`) then it doesn't have a problem. I'm guessing that this is something related to the web version being new, but that's just a guess.

**Comment by SriramKiranSenthilkumar** [comment]
Hi @idraper,

Greetings from Syncfusion. We have analyzed your scenario at our end and we are able to replicate the reported issue regarding the trackball throwing invalid range exception in the chart when the trackball's tooltip is disabled using the **`onTrackballPositionChanging`** event in the chart. We will consider this as a bug and we ill plan and include the fix for the reported issue in our upcoming weekly patch release which is expected to be rolled out by 1st Febuary 2020. We will update you once the release is rolled out and we appreciate your patience until then.

Regards,
Sriram Kiran

**Comment by SriramKiranSenthilkumar** [comment]
Hi @idraper,

Thanks for your patience. The reported issue regarding the trackball throwing invalid range exception in the chart when the trackball's tooltip is disabled using the onTrackballPositionChanging event in the chart is now fixed and rolled out in our weekly patch release. To overcome the reported issue, kindly upgrade the chart widget package to the latest version below.
https://pub.dev/packages/syncfusion_flutter_charts/versions/18.3.52

Please get in touch with us if you would require further assistance.

Regards,
Sriram Kiran
