### ISSUE TITLE
FLUTTER-CHART - Hide values on X-Axis

### ISSUE THREAD

**Issue by brianschardt** [syncfusion/flutter-widgets#61]
This is a stock graph that is a weekly historical of a stock. On weekends there is no trading and as a result no data. The api returns series of points each trading day. It does not have data for the weekend points. How could we get the X-Axis to remove some of the values that just show the long line with no data, this way it acts more like industry standard.
Note: Using a DateTime X-Axis
e.g remove Nov 14 and Nov 15th from x axis?
![Screen Shot 2020-11-17 at 9 47 31 PM](https://user-images.githubusercontent.com/35744893/99490388-97f36300-291e-11eb-81a6-c3312c44b5a8.png)

**Comment by SriramKiranSenthilkumar** [comment]
Hi @brianschardt,

Greetings from Syncfusion. We have analyzed your scenario with provided information at our end and we have created a simple chart sample similar to the provided screenshot in which we have used the **`onAxisLabelRenderer`** callback event available in the chart to remove the x-axis labels by setting empty string for its text argument value available in the event by checking each of the axis label's DateTime value whether it is weekends or not. We have also attached the sample below for your reference. 

Sample: [sample.zip](https://github.com/syncfusion/flutter-widgets/files/5567069/sample.zip)

Please check with above-attached sample and revert us if you still have further concerns.

Regards,
Sriram Kiran

**Comment by brianschardt** [comment]
I just tried that sample. I think you are miss understanding me. 
Attached is a picture that shows in red what I expect to be removed. The x-Axis should go from Nov 12, Nov 13, Nov16, Nov 17. Just having a blank label does not solve the issue. That part of the x-Axis needs to be removed. Just like it is for apple stock charts.
![Screen Shot 2020-11-23 at 7 01 56 AM](https://user-images.githubusercontent.com/35744893/99977736-e0b17e80-2d59-11eb-9f61-b61d8506e218.png)

**Comment by SriramKiranSenthilkumar** [comment]
Hi @brianschardt,

Thanks for the revert. We have analyzed your query at our end, and we would like to share some information regarding the DateTimeAxis available in the chart. As the DateTimeAxis available in our chart widget is a linear axis i.e., the chart when gets rendered in a DateTime axis, then its axis labels will be in calculated range intervals (say from Nov 11 to Nov 17) and this is the default behaviour of the DateTimeAxis.

However, we can overcome this by using a simple workaround which is by using the category axis instead of the Date Time axis. As the category axis is a non-linear axis and it renders the axis only for the chart according to the provided x-axis values in the chart data source. So, we kindly request you to convert your date-time values to a string value and pass it to the chart so that the chart will render the axis labels only for the provided data source and thus the chart x-axis renders only for the provided DateTime string values. 

Also, we have created a simple sample in which we have created a simple chart sample in which we have converted the DateTime chart data values to string values and passed it into the chart with category axis as the x-axis. We have attached the sample below for your reference.
Sample: [workaround.zip](https://github.com/syncfusion/flutter-widgets/files/5589102/datetimecategoryaxis_workaround.zip)


Please check the above-attached sample and revert us if you still have further concerns. 
  
Also, to mention that we are planning to include a new axis type for our chart widget called the DateTimeCategoryAxis which will be highly useful for your scenario. We have already logged a feature request regarding this in our feedback portal. We will plan and include this feature in any of our upcoming releases yet to come. You can also track the status of the feature using the below feedback link. 
https://www.syncfusion.com/feedback/14083 
 
Regards, 
Sriram Kiran
