### ISSUE TITLE
syncfusion_flutter_charts: Is it possible to load graph line with 1 Million Data points?

### ISSUE THREAD

**Issue by dhaval-k-simformsolutions** [syncfusion/flutter-widgets#618]
Does syncfusion_flutter_charts provide support to load multiple graph lines (SplineSeries lines)? In my use case, each line will have around 14000 to 20000 points.

I have tried to implement it in one demo project but it's legging while initializing the graph. Also, it's legging while I try to zoom or scroll the graph content?  

Please let us know if any solutions are already available for this type of requirement.

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @dhaval-k-simformsolutions,

Loading 1million data in a chart will degrade the performance. However we suggest you use on-demand loading concept to load the required data alone. Using the loadMoreIndicatorBuilder callback to load a specified amount of data based on the demand. For updating the data dynamically, we strongly recommend the updateDataSource method instead of setState. Because in the updateDataSource method, we will process only the modified data and skips various steps like bounds calculation, processing of old data points, etc. Using these things we can improve the performance of chart in all cases like rendering wise, user interaction cases. We have provided the UG and demo sample link below for your reference.

UG: https://help.syncfusion.com/flutter/cartesian-charts/on-demand-loading
https://help.syncfusion.com/flutter/cartesian-charts/methods#updatedatasource

Demo sample: https://flutter.syncfusion.com/#/cartesian-charts/infinite-scrolling

Regards,
Yuvaraj.

**Comment by dhaval-k-simformsolutions** [comment]
@Yuvaraj-Gajaraj  Thanks for your reply but We have a requirement where we have to load all the points in a single view only... We have checked other libraries in native which provide the support for the same, Such as [SciChart](https://www.scichart.com/) & [LightingChart](https://www.arction.com/).

Please let me know if your team is have a plan to provide the support on the same so we can think about using your licence in our Product.
