### ISSUE TITLE
Performance on moving : slow movement 

### ISSUE THREAD

**Issue by chamartt** [syncfusion/flutter-widgets#62]
Hi,

I would like to use your package to restrict the number of Custom widgets (in a column) depending on the range choosen by the user.
So I used "SfRangeSlider".

Unfortunatly, I have seriously performance problem during the movement of the cursor.
Even if I only put  `onChanged: (SfRangeValues values) {
                setState(() {
                  _values = values;
                });
              },` the problem is still present.

I saw that if I show only 10 items (manually) of my Custom Widget, the problem disappear, if I show 20-30 it begins to be bad...

So the performance of the cursor moving is indirectly lied to the numbers of elements show on the same page.
It's the same with the default widget RangeSlider of Flutter.

Do you know why that is happens ?

Thank you in advance for your help !

**Comment by LakshmiRadhaKrishnan** [comment]
Hi Chamartt,

Greetings from Syncfusion.

Though we are not aware of your exact scenario, we assume that you are trying to build the whole widget tree while changing the thumb values. The onChanged will be called for every pixel changes in thumbs. Since you are calling setState inside of it, the whole stateful widget might be rebuilding and may lead to performance issues based on the number of widgets inside of it. 

As an alternative for this, you may check our SfRangeSelector widget which has an option for the deferred updating. It can be achieved by setting the SfRangeSelector.enableDeferredUpdate property and the delay in the update can be changed by setting the SfRangeSelector.deferredUpdateDelay property. Then the onChanged callback will be called only when the thumb is dragged and held for the duration specified in the deferredUpdateDelay and . However, range values are immediately updated in touch up action. 

**Video:** https://www.syncfusion.com/downloads/support/directtrac/general/ze/RangeSelector_performance1054490506.zip 
**Dart file:** https://www.syncfusion.com/downloads/support/directtrac/general/ze/main-590205294.zip 

**Code Snippet:**

`class RangeSelectorPage extends StatefulWidget {
  @override
  _RangeSelectorPageState createState() => _RangeSelectorPageState();
}

class _RangeSelectorPageState extends State<RangeSelectorPage> {
  SfRangeValues _values = SfRangeValues(0.0, 5.0);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(title: Text('Range Selector')),
        body: SingleChildScrollView(
          child: Column(
            children: [
              Padding(
                padding: EdgeInsets.only(left: 10, top: 20),
                child: SfRangeSelector(
                  min: 0.0,
                  max: 150.0,
                  interval: 30,
                  showLabels: true,
                  showTooltip: true,
                  initialValues: _values,
                  enableDeferredUpdate: true,
                  deferredUpdateDelay: 100,
                  child: Container(),
                  onChanged: (SfRangeValues newValues) {
                    setState(() {
                      _values = newValues;
                    });
                  },
                ),
              ),
              SizedBox(height: 25),
              Column(
                children: getWidget(_values.end),
              ),
            ],
          ),
        ));
  }

  List<Widget> getWidget(double count) {
    List<Widget> children = <Widget>[];
    for (int i = 0; i <= count; i++) {
      children.add(
        Padding(
          padding: EdgeInsets.only(left: 15, right: 15),
          child: Column(
            children: [
              Container(
                height: 30,
                color: Colors.blue[200],
              ),
              SizedBox(height: 5),
            ],
          ),
        ),
      );
    }

    return children;
  }
}`

Regards,
Lakshmi R.

**Comment by chamartt** [comment]
Hi Lakshmi,

Thank your for your help.
My problem was the setState call in onChanged.

Thank you also pour the tip 'enableDeferredUpdate'.

Regards.
