### ISSUE TITLE
SfDataPager: My Pagging is not in the middle

### ISSUE THREAD

**Issue by SittiphanSittisak** [syncfusion/flutter-widgets#624]
I tried to use Center for SfDataPager but It didn't work.
And how to delete margin. The picture shows a little space near border.

<img width="676" alt="sdaasdsad" src="https://user-images.githubusercontent.com/59549741/157295456-ed489c50-14e8-40e9-a5d0-013665d282de.png">

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @SittiphanSittisak,

**Query 1: I tried to use Center for SfDataPager but It didn't work.**

We suspect that you're loading the dtagrid as a child of the Container/SizedBox without setting any width. If width is not specified, we placed the data pager widget as a child of the card in the source level to cover the entire screen width. So, the center widget did not work since the data pager is laid out the entire width.

You can achieve your requirement by wrapping the data pager as a child of the Container/SizedBox then setting the width as half of the screen width from the media query. We have prepared a sample for that. Please check the following sample and code snippet,

**Code Snippet:**
```dart
SizedBox(
              width: MediaQuery.of(context).size.width / 2,
              child: SfDataPager(
                pageCount:
                    ((_employees.length / _rowsPerPage).ceil()).toDouble(),
                direction: Axis.horizontal,
                delegate: _employeeDataSource,
              ),
            )

```
**Sample Link**: https://www.syncfusion.com/downloads/support/directtrac/general/ze/sample969277960

**Query 2: How to delete margin**

We layout the data pager as a child of the Card widget, it's a panel with rounded corners. So, the default margin has always been shown, which is the behavior of the DataPager. Otherwise, do you expect us to need the data pager without the rounded corners?

Regards,
Tamilarasan

**Comment by yeleibo** [comment]
this is need to solve
