### ISSUE TITLE
Bug in documentation

### ISSUE THREAD

**Issue by obirider** [syncfusion/flutter-widgets#626]
The description of these two components is wrong:
https://pub.dev/documentation/syncfusion_flutter_datagrid/latest/datagrid/SfDataGrid/onCellSecondaryTap.html
https://pub.dev/documentation/syncfusion_flutter_datagrid/latest/datagrid/SfDataGrid/onCellLongPress.html

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @obirider,

Sorry for the inconvenience caused.

We have modified the API comments. The updated content will be published on or before March 16, 2022. We will let you know once it is published. we appreciate your patience until then.

Regards,
Tamilarasan

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @obirider,

Sorry for the inconvenience.

Due to some technical difficulties, the updated content wasn’t published in this weekly release. The updated content will be published on or before March 24, 2022. We will let you know once it is published. We appreciate your patience until then.

Regards,
Tamilarasan

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @obirider,

We would like to let you know that because of our 2022 volume 1 main release this week, we will not have a pub release for this week. The updated content will be included in our Volume 1 main release. We will let you know once it's rolled out. We appreciate your patience and understanding till then.

Regards,
Tamilarasan

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @obirider,

Thanks for your patience. 

We have updated and published the API document. Please find the updated documentation link below.

onCellLongPress: https://pub.dev/documentation/syncfusion_flutter_datagrid/latest/datagrid/SfDataGrid/onCellLongPress.html

onCellSecondaryTap: https://pub.dev/documentation/syncfusion_flutter_datagrid/latest/datagrid/SfDataGrid/onCellSecondaryTap.html


Regards,
Tamilarasan
