### ISSUE TITLE
Add BarChart yValue text tap and longPress callback

### ISSUE THREAD

**Issue by bismarabia** [syncfusion/flutter-widgets#641]
Hello, 

Is there a tap/longTap callback for yValue text? In other word, I want to handle the click and long click on the yValue text outside the bar. 

I've tried 
- BarSeries.onPointTap which handles the click only on the blue rectangle in the attached.
- SfCartesianChart.onAxisLabelTapped which handles the click on the label (left side of the chart)

<img width="340" alt="image" src="https://user-images.githubusercontent.com/16321223/159686502-fc49ee66-e6b7-4507-8c2c-8627b3e94c40.png">

What I want:
- to have a callback that handles tap and longPress on yValue text widget (pointed with arrow in the attached)
- to have SfCartesianChart.onAxisLabel**Long**Tapped attribute.
- to have BarSeries.onPoint**Long**Tap, and that would be different than TooltipBehavior.activationMode

Thank you...

**Comment by SriramKiranSenthilkumar** [comment]
Hi @bismarabia,

Greetings from Syncfusion. In order to handle tap gesture on the y-value data label text of the data point, you can use the **onDataLabelTapped** event instead of using the **onPointTap** event to achieve your scenario. Please refer the code snippet below for reference.
```
SfCartesianChart(
              onDatalabelTapped: (DataLabelTapArgs args) {
                print(args.seriesIndex);                 
              }
              // other configurations 
)
```
For further reference on **onDataLabeltapper** event please check the user guide below.
https://help.syncfusion.com/flutter/cartesian-charts/callbacks#ondatalabeltapped

Please check with the above solution and get back to us if you require further assistance.

Regards,
Sriram Kiran

**Comment by bismarabia** [comment]
That worked thank you!

one issue is, if the label is placed inside the bar (like the first one in the image) and when I click that label both **onDataLabelTapped** and **onAxisLabelTapped** are triggered. In my case, I am navigating twice to the detail screen when I click on the label inside the bar.
<img width="340" alt="image" src="https://user-images.githubusercontent.com/16321223/159686502-fc49ee66-e6b7-4507-8c2c-8627b3e94c40.png">


Is there a way to fire only **onDatalabelTapped** if I click on the label inside the BAR without firing **onAxisLabelTapped** callback?

**Comment by bismarabia** [comment]
@SriramKiranSenthilkumar any update on this?

**Comment by LavanyaGowtham2021** [comment]
Please reopen this, if you need any further assistance on this.
