### ISSUE TITLE
crash app after display barcode in pdf view.

### ISSUE THREAD

**Issue by KhanjanElsner** [syncfusion/flutter-widgets#646]
Hi,
I am converting bytes data into file and trying to display .pdf file in pdf view but when I am trying to display more than 10 barcode in pdf view my app will crash after 2-3 second. I will display barcode for 2-3 seconds and after that app will crash.

**Comment by deepika134** [comment]
Hi KhanjanElsner,

We tried to reproduce the reported issue with provided details, but the issue couldn't be reproduced on our end. For your reference, we have prepared a sample and it can be downloaded from the following link,
https://www.syncfusion.com/downloads/support/directtrac/general/ze/load_a_pdf_from_asset1666919000.zip 
Kindly let us know if you are facing the reported issue with this sample. Also, please share the following details, to reproduce the reported issue on our end.

1. Platforms in which the issue is reproduced (Android, iOS, Web, macOS).
2. Device Specification.
3. Share the issue reproducing document.
4. Flutter Doctor log.
5. syncfusion_flutter_pdfviewer package version.
6. Flutter SDK version.

This information will be helpful for us to provide you a prompt solution at the earliest.

Regards,
Deepika Ravi
