### ISSUE TITLE
[syncfusion_flutter_charts] extend chart to horizontal edges

### ISSUE THREAD

**Issue by Reprevise** [syncfusion/flutter-widgets#656]
Please allow the chart to extend to fill the horizontal margin on the sides.

![image](https://user-images.githubusercontent.com/25782944/161324294-2a289a0c-8824-4ccd-89f7-286de28d8be5.png)

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @Reprevise 

We suggest you use the [labelPlacement](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeCategoryAxis/labelPlacement.html) property in case you are using either [DateTimeCategoryAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeCategoryAxis-class.html) or [CategoryAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CategoryAxis-class.html). In these axes, by default, the labels are positioned between the ticks which is why it seems not to be filled in the side of the chart. Now you can set it to labelPlacement to [onTicks](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/LabelPlacement.html) it will help you to achieve your requirement. We have attached the code snippet and UG below for your reference.

```dart
primaryXAxis:
    DateTimeCategoryAxis(
      labelPlacement: LabelPlacement.onTicks
      ),
```

UG: https://help.syncfusion.com/flutter/cartesian-charts/axis-types#placing-labels-between-the-ticks 

Regards,
Yuvaraj.
