### ISSUE TITLE
[syncfusion_flutter_charts] GroupAllPoints do not take effect

### ISSUE THREAD

**Issue by internelp** [syncfusion/flutter-widgets#664]
After updated to version 20.1.47+1.
If the time is not exactly the same, they will not appear at the same time. Even if only by a few seconds.

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @internelp,

We suspect that the below is your case, if so, this is the expected behavior. Consider that you are having two series and having x values from 1 to 5. The first series is having all the five x and y values and in the second series, there are only four x values (x-values are 1,2,3 and 5). Now in previous versions, when you hover over the 4th x-value, the respective y value will be shown for the first series, and since the second series doesn't have the 4th value, we will be showing the nearest y-value. Recently we have changed this like if both series x-value is visible only we will show their values else, we will show what value is currently visible.

If this is not your case, kindly get back to us by modifying the attached sample, since in other cases the trackball is working fine as expected.

Sample: [i374441.zip](https://github.com/syncfusion/flutter-widgets/files/8443629/i374441.zip)

Regards,
Yuvaraj.
