### ISSUE TITLE
How to always show the label?

### ISSUE THREAD

**Issue by wrjcs** [syncfusion/flutter-widgets#669]
Hello,
I found the le label is not always show, it must be taped to show an label.

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @wrjcs,

Greetings from Syncfusion. We are not clear on your exact requirement and which widget you are using. From this GitHub issue ([670](https://github.com/syncfusion/flutter-widgets/issues/670)), we suspect that you are mentioning the chart widget. Since the query is not clear, kindly get back to us with more information on your query. You have mentioned like the labels are not shown always, from this are you mentioning x or y-axis labels or data labels. And on tapping which label do you need to show? Can you please provide more information on this and if possible share a screenshot/video for this requirement. This will be more helpful to us to provide a solution sooner.

Regards,
Yuvaraj.
