### ISSUE TITLE
Flutter Chart dataLabelMapper Miss show

### ISSUE THREAD

**Issue by gwsh** [syncfusion/flutter-widgets#67]
![image](https://user-images.githubusercontent.com/38830136/100188514-56b61100-2f25-11eb-9339-4f1050ee50e1.png)
![image](https://user-images.githubusercontent.com/38830136/100188557-6c2b3b00-2f25-11eb-94fd-ec730098223a.png)

![image](https://user-images.githubusercontent.com/38830136/100188514-56b61100-2f25-11eb-9339-4f1050ee50e1.png)

**Comment by gwsh** [comment]
![image](https://user-images.githubusercontent.com/38830136/100188631-8e24bd80-2f25-11eb-9650-f47452f81b21.png)
thank you

**Comment by SriramKiranSenthilkumar** [comment]
Hi @gwsh,

Thanks for contacting Syncfusion support. We have analyzed your scenario with the provided information at our end and we would like to share some information regarding the **`labelIntersectAction`** property of the DataLabelSettings. In order to overcome the reported issue regarding the data label not showing for certain data points in the doughnut chart, kindly please set the **`labelIntersectAction`** property as **`LabelIntersectAction.none`** which will render all the data labels of the data points in the doughnut chart. Please refer the code snippet below for further reference.
```
SfCircularChart(
     series: <CircularSeries<CountList, String>>[
          DoughnutSeries<CountList, String>(
              dataSource: <CountList>[
                CountList('1', 70, '70%'),
                CountList('2', 30, '30%'),
                CountList('3', 30, '30%'),
                CountList('4', 10, '10%'),
                CountList('5', 30, '30%'),
                CountList('6', 78, '78%'),
                CountList('7', 118, '118%'),
              ],
              xValueMapper: (CountList data, _) => data.name,
              yValueMapper: (CountList data, _) => data.count,
              dataLabelMapper: (CountList data, _) => data.rate,
              dataLabelSettings: DataLabelSettings(
                  isVisible: true,
                  // Setting label intersect action as none. The default value of this property is LabelIntersectAction.hide
                  labelIntersectAction: LabelIntersectAction.none,
                  labelPosition: ChartDataLabelPosition.outside
              )
          )
     ],
     // your configurations
)
```
**Screenshot:**
![Screenshot_20201126-112129](https://user-images.githubusercontent.com/63577117/100313633-08634980-2fdb-11eb-91c9-0d5bb9b4d076.jpg)

The sample for reference can be found below.
[sample.zip](https://github.com/syncfusion/flutter-widgets/files/5600779/sample.zip)

Please check with the above-attached sample and revert us if you still have further concerns.

Regards,
Sriram Kiran

**Comment by gwsh** [comment]
> 嗨@gwsh，
> 
> 感谢您与Syncfusion支持部门联系。我们已在最后使用提供的信息对您的方案进行了分析，并希望分享一些有关**`labelIntersectAction`**DataLabelSettings属性的信息。为了解决有关在甜甜圈图中的某些数据点未显示数据标签的报告问题，请设置**`labelIntersectAction`**属性，因为**`LabelIntersectAction.none`**该属性将呈现甜甜圈图中的数据点的所有数据标签。请参考下面的代码片段以获取更多参考。
> 
> ```
> SfCircularChart(
>      series: <CircularSeries<CountList, String>>[
>           DoughnutSeries<CountList, String>(
>               dataSource: <CountList>[
>                 CountList('1', 70, '70%'),
>                 CountList('2', 30, '30%'),
>                 CountList('3', 30, '30%'),
>                 CountList('4', 10, '10%'),
>                 CountList('5', 30, '30%'),
>                 CountList('6', 78, '78%'),
>                 CountList('7', 118, '118%'),
>               ],
>               xValueMapper: (CountList data, _) => data.name,
>               yValueMapper: (CountList data, _) => data.count,
>               dataLabelMapper: (CountList data, _) => data.rate,
>               dataLabelSettings: DataLabelSettings(
>                   isVisible: true,
>                   // Setting label intersect action as none. The default value of this property is LabelIntersectAction.hide
>                   labelIntersectAction: LabelIntersectAction.none,
>                   labelPosition: ChartDataLabelPosition.outside
>               )
>           )
>      ],
>      // your configurations
> )
> ```
> 
> **屏幕截图：**
> ![截图_20201126-112129](https://user-images.githubusercontent.com/63577117/100313633-08634980-2fdb-11eb-91c9-0d5bb9b4d076.jpg)
> 
> 供参考的样本可以在下面找到。
> [sample.zip](https://github.com/syncfusion/flutter-widgets/files/5600779/sample.zip)
> 
> 如果您还有其他疑虑，请检查上面提供的示例，并与我们联系。
> 
> 此致，
> Sriram Kiran
Thank you, it has been solved according to your plan.👍

**Comment by yashwp** [comment]
@gwsh Actually it is not working that great. Please check SS below:
![image](https://user-images.githubusercontent.com/13454790/112429106-3a56a380-8d62-11eb-899c-3f4d5d562d21.png)
