### ISSUE TITLE
[syncfusion_flutter_pdf] 'PdfName' is not a subtype of type 'PdfArray?'

### ISSUE THREAD

**Issue by EdoardoVignati** [syncfusion/flutter-widgets#674]
Version: `20.1.48-beta`

Hi, I'm running the following simple code:
```dart
final PdfDocument document =  PdfDocument(inputBytes: File('input.pdf').readAsBytesSync());
document.pages.removeAt(0);
document.dispose();
```
and this is the error:
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: type 'PdfName' is not a subtype of type 'PdfArray?' in type cast
#0      PdfBookmark._obtainDestination (package:syncfusion_flutter_pdf/src/pdf/implementation/pdf_document/outlines/pdf_outline.dart:561:29)
#1      PdfBookmark.destination (package:syncfusion_flutter_pdf/src/pdf/implementation/pdf_document/outlines/pdf_outline.dart:123:23)
#2      PdfDocumentHelper.createBookmarkDestinationDictionary (package:syncfusion_flutter_pdf/src/pdf/implementation/pdf_document/pdf_document.dart:1212:67)
#3      PdfPageCollection._removePage (package:syncfusion_flutter_pdf/src/pdf/implementation/pages/pdf_page_collection.dart:566:16)
#4      PdfPageCollection.removeAt (package:syncfusion_flutter_pdf/src/pdf/implementation/pages/pdf_page_collection.dart:223:7)
#5      _MyHomePageState._choseFile.<anonymous closure> (package:pdfkit/main.dart:52:31)
#6      List.forEach (dart:core-patch/growable_array.dart:433:8)
#7      _MyHomePageState._choseFile (package:pdfkit/main.dart:46:13)
<asynchronous suspension>
```

No problems with the PDF file. I tried to display it with `SfPdfViewer.memory(Uint8List.fromList(document.save())),` and it's perfectly working but when I try to remove a page it crashes.

In addition, is there a way to export a single page of the PDF?

Thanks

**Comment by AnanthaGokulaRaman** [comment]
Hi Edoardo,

Currently we were unable to reproduce the reported issue with the test documents from our side. To analyze further on this, kindly attach the PDF document in which this issue is reproduced.

As of now, we do not have support to import single page or page range in the Syncfusion Flutter PDF. However, you can achieve this with the help of creating existing page as template, you can refer the following link for further details, https://pub.dev/documentation/syncfusion_flutter_pdf/latest/pdf/PdfPage/createTemplate.html

Regards,
Anantha Gokula Raman J
