### ISSUE TITLE
Cartesian Charts [RangeError Exception caught by animation library] when reset [DateTimeCategoryAxis.visibleMinimum]

### ISSUE THREAD

**Issue by FisherWL** [syncfusion/flutter-widgets#686]
please see example .zip below:
[sfcharttest 2.zip](https://github.com/syncfusion/flutter-widgets/files/8535914/sfcharttest.2.zip)

when reset visible range, 
```
════════ Exception caught by animation library ═════════════════════════════════
RangeError (index): Invalid value: Valid value range is empty: -1
════════════════════════════════════════════════════════════════════════════════
```

Also, another bug is the change visible min/max functionality will be disabled after pan or pinch.

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @FisherWL ,

We have analyzed and found that you're using the old version of the chart package, this issue is already fixed and available in the latest package. So, we request you to upgrade the package to the latest version below.

Version: https://pub.dev/packages/syncfusion_flutter_charts/versions/20.1.50

Regards,
Yuvaraj.

**Comment by FisherWL** [comment]
thanks @Yuvaraj-Gajaraj 
the exception is solved after upgrading package,
however, another bug still exists ---- change visible min/max functionality will be disabled after pan or pinch.

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @FisherWL,

You have created a different issue for the visible min/max functionality, so for further information, you can track that issue.

https://github.com/syncfusion/flutter-widgets/issues/684

Regards,
Yuvaraj.
