### ISSUE TITLE
[syncfusion_flutter_charts] Is it possible to load more data with `zoomPanBehavior.panToDirection()`?

### ISSUE THREAD

**Issue by andrea689** [syncfusion/flutter-widgets#702]
Is it possible to load more data when pan chart with `zoomPanBehavior.panToDirection()`?

Also, is there any way to know if it has reach the max or min? In this way I don't show the relevant button if it has reached the end.

Thanks

**Comment by Yuvaraj-Gajaraj** [comment]
Hi Team,

Currently, we don’t have support to achieve the load more data feature in the [zoomPanBehavior.panToDirection](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ZoomPanBehavior/panToDirection.html) public method, it is only used for programmatically panning the chart widget. But we have achieved your scenario with a workaround using [onActualRangeChanged](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/onActualRangeChanged.html) callback and external events. Here you can get the visible and actual ranges of the axes. And you will use the panToDirection using the external events like button click events, etc. So, we have achieved this by having the button in the app bar and when tapping the right button updating the data when the visible maximum and actual maximum are the same using [updateDataSource](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeriesController/updateDataSource.html) method. Otherwise, it pans towards the right until the visible maximum and actual maximum are the same. We have also attached the sample below for your reference, you can modify the sample as per your requirement.

Sample: [i378041.zip](https://github.com/syncfusion/flutter-widgets/files/8631774/i378041.zip)

Regards,
Yuvaraj.
