### ISSUE TITLE
iOS crashes when opening some pdf files and then turning pages

### ISSUE THREAD

**Issue by luomo-pro** [syncfusion/flutter-widgets#704]
This problem only exists on some pdf files and only on iOS, Android is normal.
The problem can be reproduced using this simplest project.

http://us.lmdbk.com/pdf_demo.zip

I put the pdf file that will cause the crash in "assets/1.pdf"

https://user-images.githubusercontent.com/41097395/166706821-73bd77eb-143c-4bca-8186-a38f10caf89a.mp4

Here is the video of my crash, as you can see, when the pdf loaded successfully, I did a page turn, but soon the screen started to flicker continuously, then went blank, and finally crashed.
After the crash I got the following log.
Fatal error: Unexpectedly found nil while unwrapping an Optional value: file syncfusion_flutter_pdfviewer/SwiftSyncfusionFlutterPdfViewerPlugin.swift, line 154
Fatal error: Unexpectedly found nil while unwrapping an Optional value: file syncfusion_flutter_pdfviewer/SwiftSyncfusionFlutterPdfViewerPlugin.swift, line 154
* thread #5, queue = 'syncfusion_flutter_pdfviewer', stop reason = Fatal error: Unexpectedly found nil while unwrapping an Optional value
    frame #0: 0x000000019fe4ee50 libswiftCore.dylib`_swift_runtime_on_report
libswiftCore.dylib`_swift_runtime_on_report:
->  0x19fe4ee50 <+0>: ret    
libswiftCore.dylib`_swift_reportToDebugger:
    0x19fe4ee54 <+0>: b      0x19fe4ee50               ; _swift_runtime_on_report
libswiftCore.dylib`_swift_shouldReportFatalErrorsToDebugger:
    0x19fe4ee58 <+0>: adrp   x8, 327376
    0x19fe4ee5c <+4>: ldrb   w0, [x8, #0x4b0]
Target 0: (Runner) stopped.

I use the
syncfusion_flutter_pdfviewer: ^20.1.52-beta
Flutter (Channel beta, 2.13.0-0.3.pre

**Comment by deepika134** [comment]
Hi luomo-pro/ @rodrigorafaeldamaceno,

We tried to reproduce the reported issue with provided details, but the scrolling is works fine in our side without any crash. Kindly share the following details to reproduce the issue on our end,
1. Device specification
2. Issue reproducing document.

This information will be helpful for us to provide you with a prompt solution at the earliest.
Regards,
Deepika Ravi

**Comment by luomo-pro** [comment]
hi!
@deepika134
I use the
iPad air 3
iOS 14.2
This is the download address for the pdf file I used.
http://us.lmdbk.com/1.pdf
You can flip back and forth between the first 3 pages very quickly, just like I did in the video, and he will crash very quickly.

**Comment by rodrigorafaeldamaceno** [comment]
@deepika134 
iPhone 13

`The app “Runner” on @andrepaulii quit unexpectedly.
Domain: IDEDebugSessionErrorDomain
Code: 10
Failure Reason: Message from debugger: Terminated due to memory issue
User Info: {
DVTErrorCreationDateKey = “2022-05-04 13:45:45 +0000";
IDERunOperationFailingWorker = DBGLLDBLauncher;
}
Analytics Event: com.apple.dt.IDERunOperationWorkerFinished : {
“device_model” = “iPhone14,5";
“device_osBuild” = “15.4.1 (19E258)“;
“device_platform” = “com.apple.platform.iphoneos”;
“launchSession_schemeCommand” = Run;
“launchSession_state” = 2;
“launchSession_targetArch” = arm64;
“operation_duration_ms” = 66692;
“operation_errorCode” = 10;
“operation_errorDomain” = IDEDebugSessionErrorDomain;
“operation_errorWorker” = DBGLLDBLauncher;
“operation_name” = IDEiPhoneRunOperationWorkerGroup;
“param_consoleMode” = 0;
“param_debugger_attachToExtensions” = 0;
“param_debugger_attachToXPC” = 1;
“param_debugger_type” = 5;
“param_destination_isProxy” = 0;
“param_destination_platform” = “com.apple.platform.iphoneos”;
“param_diag_MainThreadChecker_stopOnIssue” = 0;
“param_diag_MallocStackLogging_enableDuringAttach” = 0;
“param_diag_MallocStackLogging_enableForXPC” = 1;
“param_diag_allowLocationSimulation” = 1;
“param_diag_gpu_frameCapture_enable” = 0;
“param_diag_gpu_shaderValidation_enable” = 0;
“param_diag_gpu_validation_enable” = 0;
“param_diag_memoryGraphOnResourceException” = 0;
“param_diag_queueDebugging_enable” = 1;
“param_diag_runtimeProfile_generate” = 0;
“param_diag_sanitizer_asan_enable” = 0;
“param_diag_sanitizer_tsan_enable” = 0;
“param_diag_sanitizer_tsan_stopOnIssue” = 0;
“param_diag_sanitizer_ubsan_stopOnIssue” = 0;
“param_diag_showNonLocalizedStrings” = 0;
“param_diag_viewDebugging_enabled” = 1;
“param_diag_viewDebugging_insertDylibOnLaunch” = 1;
“param_install_style” = 0;
“param_launcher_UID” = 2;
“param_launcher_allowDeviceSensorReplayData” = 0;
“param_launcher_kind” = 0;
“param_launcher_style” = 0;
“param_launcher_substyle” = 0;
“param_runnable_appExtensionHostRunMode” = 0;
“param_runnable_productType” = “com.apple.product-type.application”;
“param_runnable_swiftVersion” = “5.6”;
“param_runnable_type” = 2;
“param_testing_launchedForTesting” = 0;
“param_testing_suppressSimulatorApp” = 0;
“param_testing_usingCLI” = 0;
“sdk_canonicalName” = “iphoneos15.4”;
“sdk_osVersion” = “15.4”;
“sdk_variant” = iphoneos;
}`

System Information
macOS Version 12.3.1 (Build 21E258)
Xcode 13.3.1 (20103) (Build 13E500a)
Timestamp: 2022-05-04T10:45:45-03:00

**Comment by deepika134** [comment]
Hi @luomo-pro , @rodrigorafaeldamaceno ,

We are checking on the reported query and will update the further details on May 11, 2022.

Regards,
Deepika Ravi

**Comment by deepika134** [comment]
Hi @luomo-pro , @rodrigorafaeldamaceno ,

Sorry for the inconvenience.

We are still analyzing on the reported issue with high priority and will update the further details on 13 May 2022.

Regards,
Deepika Ravi

**Comment by deepika134** [comment]
Hi Everyone,

We have confirmed that the reported issue “The application will close unexpectedly when scrolling high quality PDF document on iOS device” is a defect. The issue fix will be included in our upcoming weekly release, which is estimated to be available on May 31, 2022. The status of the issue can be tracked by the following link,
https://www.syncfusion.com/feedback/34937/the-application-will-close-unexpectedly-when-scrolling-high-quality-pdf-document

Regards,
Deepika Ravi

**Comment by luomo-pro** [comment]
@deepika134
Thank you very much!
When a new version is released, I will verify that the issue is fixed correctly.

**Comment by luomo-pro** [comment]
This issue I tested already in
syncfusion_flutter_pdfviewer: ^20.1.57-beta
version is fixed.
I will close this issue.
If others still have this problem, they can submit a new issue.

**Comment by JayronKhong** [comment]
Hi, this issue still exist in version 23.2.7.
