### ISSUE TITLE
syncfusion Treemap has some Problems (include Slow rendering, not updated, etc)

### ISSUE THREAD

**Issue by intelryzen** [syncfusion/flutter-widgets#710]
![image](https://user-images.githubusercontent.com/66426612/167241329-34e026f6-a96a-46e7-9e6c-a21dc6475084.png)

I'm using your tree map plug-in well. However, there were some problems with commercializing apps using the current tree map plug-in.

Problems:
1. Symptoms of some tree map elements being obscured during update due to setstate((){})
2. Rendering is slow.
3. Symptoms of tree map data not being updated

I've created a tree map by implementing a source that fetches stock data every 7 seconds, but often some elements are not implemented and are obscured, as shown in the attached picture. It happens on the iPhone and Android, and there was no problem with my coding format.

Second, tree map rendering is very slow. In particular, if the initial rendering is very slow and more than 100 data make up the tree map element, a minimum delay of 500 ms will occur in drawing the tree map.

Third, the tree map is not updated with the normal setState((){}) method. I tried to implement the tile color to vary depending on the data, but the tree map was not updated. The widget is only updated by inserting a GlobalKey, but even this is very slow to update with the symptoms of a blinking screen.

If there's anything I'm missing about these symptoms, I'd appreciate it if you could give me tips on how to use them.

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @intelryzen,

Kindly find the response for your queries below,

**Query #1: Symptoms of some treemap elements being obscured during update due to setstate((){})**

We have tested the treemap sample by updating the stack of values every 7 seconds but no treemap element get obscured, All the elements are visible in the treemap and get updated properly.

**Query #2: Rendering is slow**

As of now, we have tested by adding more than 100 data and did not face any slow rendering issues in the treemap. We have attached the sample below which is used in the testing phase for your reference. Since we are not aware of your exact scenario in which the performance drags, kindly try to replicate with the attached sample and get back to us. This will be helpful in further analysis and provide you with the solution sooner.

**Query #3: Symptoms of treemap data not being updated**

As of now, you have to use the key for updating the treemap when adding data dynamically, this is our current behavior. So we suggest using the key for updating the data source.

Sample: [i378431.zip](https://github.com/syncfusion/flutter-widgets/files/8654318/i378431.zip)

Regards,
Yuvaraj.

**Comment by intelryzen** [comment]
Thank you for your sincere response. I released the app from my iPhone and Android Phone as your source. if the widget has a GlobalKey, the app will reflect the changes properly. However, if Widget contains a global key, the screen will blink like the attached video whenever try the setState(). The more data Widget have, the more time it takes for the widget to appear on the screen. Is there any way to solve this blinking problem?

Uploading RPReplay_Final1652171015.MP4…

**Comment by Yuvaraj-Gajaraj** [comment]
Hi Intelryzen,

We have used the [FutureBuilder](https://api.flutter.dev/flutter/widgets/FutureBuilder-class.html) in our treemaps to update the treemap elements when dynamically added data using key, this is the reason widget gets blink. This happens in the Flutter native widget too, we have wrapped the ListView widget with FutureBuilder and update the value in the [ListView](https://api.flutter.dev/flutter/widgets/ListView-class.html) by calling the setState() and assigned the new key to the key value in the button click the whole ListView get blink. We have logged the issue in Flutter GitHub page once we get a solution, we resolve this. For further information you can track the below attached issue link.

Issue link: https://github.com/flutter/flutter/issues/103810 

Regards,
Yuvaraj.

**Comment by intelryzen** [comment]
Thank you😀, and I look forward to seeing a new updated version.
