### ISSUE TITLE
Crash iOS 14

### ISSUE THREAD

**Issue by NguyenPhatBG** [syncfusion/flutter-widgets#714]
My app has crashed on release version. Please check logic code :)

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @NguyenPhatBG,

Since the provided information is not enough to replicate the reported scenario, we need the below information to proceed further. 
•	In which widget are you getting the crash
•	Did you update the data source dynamically?
•	Are you facing a crash while performing any user interaction, if so please get back to us with those user interaction cases
•	What are the properties you have used in the widget, if possible, kindly share your entire code to replicate it?

Regards,
Yuvaraj.

**Comment by LavanyaGowtham2021** [comment]
Hi @NguyenPhatBG ,

You can reopen this ticket if you still face the issue in our latest patch, and kindly share the details that we requested earlier.

Thanks,
Lavanya A.
