### ISSUE TITLE
Doughnut with center elevation is not wroking

### ISSUE THREAD

**Issue by robertoltrocha** [syncfusion/flutter-widgets#72]
Hi,
I´m trying to use the exemple in [https://help.syncfusion.com/flutter/circular-charts/chart-types](https://help.syncfusion.com/flutter/circular-charts/chart-types), but it is not working.

I changed the code 
```
annotations: <CircularChartAnnotation>[
                         CircularChartAnnotation(
                           child: Container(
                             child: PhysicalModel(
                              child: Container(),
                                shape: BoxShape.circle,
                                elevation: 10,
                                shadowColor: Colors.black,
                                color: const Color.fromRGBO(230, 230, 230, 1)))),
                                CircularChartAnnotation(
                                  child: Container(
                                  child: const Text('62%',
                                 style: TextStyle(
                                color: Color.fromRGBO(0, 0, 0, 0.5), fontSize: 25))))
                                   ],
```

to 
```
annotations: <CircularChartAnnotation>[
                         CircularChartAnnotation(
                           widget: Container(
                             child: PhysicalModel(
                              child: Container(),
                                shape: BoxShape.circle,
                                elevation: 10,
                                shadowColor: Colors.black,
                                color: const Color.fromRGBO(230, 230, 230, 1)))),
                                CircularChartAnnotation(
                                  widget: Container(
                                  child: const Text('26',
                                 style: TextStyle(
                                color: Color.fromRGBO(0, 0, 0, 0.5), fontSize: 25))))
                                   ],
```
because the **child** word is not definided. I put child=>widget.

Could you help?

![WhatsApp Image 2020-11-29 at 17 56 43](https://user-images.githubusercontent.com/30963205/100553362-69558080-326c-11eb-9ec3-b88b56c8c631.jpeg)

**Comment by SriramKiranSenthilkumar** [comment]
Hi @robertoltrocha,

Greetings from Syncfusion. We have analyzed your scenario with the provided information at our end and we would like to share some information regarding the **` height`** and **`width`** properties of the **` CircularChartAnnotation`**. In order to achieve centre elevation in the Doughnut chart, you need to set the height and width for the **` CircularChartAnnotation`**.  Also, we are sorry that in our UG documentation, the code snippet is wrong and height and width properties are also not set. We will make the necessary changes in the UG from our side as per your suggestion. Also to mention that we have created a simple doughnut chart sample similar to the provided screenshot, in which we have rendered the centre elevation with the help of **`CircularChartAnnotation`**.  Please refer the code snippet below for reference.
```
SfCircularChart(
          annotations: <CircularChartAnnotation>[
            CircularChartAnnotation(
                height: '80%', // Setting height and width for the circular chart annotation
                width: '80%',
                widget: Container(
                    child: PhysicalModel(
                        child: Container(),
                        shape: BoxShape.circle,
                        elevation: 10,
                        shadowColor: Colors.black,
                        color: const Color.fromRGBO(230, 230, 230, 1)))),
            CircularChartAnnotation(
                widget: Container(
                    child: const Text('62%',
                        style: TextStyle(
                            color: Color.fromRGBO(0, 0, 0, 0.5),
                            fontSize: 25))))
          ],
          series: <DoughnutSeries<ChartSampleData, String>>[
            DoughnutSeries<ChartSampleData, String>(
              dataSource: chartData,
              animationDuration: 0,
              dataLabelSettings: DataLabelSettings(isVisible: true),
              xValueMapper: (ChartSampleData data, _) => data.x,
              yValueMapper: (ChartSampleData data, _) => data.y,
            )
          ],
        )
```
**Screenshot :**
![Screenshot_20201130-144253](https://user-images.githubusercontent.com/63577117/100624309-52d12700-3349-11eb-99cb-a280bda214dc.jpg)

The sample for reference can be found below.
[sample.zip](https://github.com/syncfusion/flutter-widgets/files/5616618/sample.zip)

Please check with the above sample and revert us if you still have further concerns.

Regards,
Sriram Kiran

**Comment by robertoltrocha** [comment]
Hi, 
Thank you for your quick response. Your suggestion worked perfectly.

**Comment by free9ja** [comment]
Hello Syncfusion Team. I had this problem too and it took me a couple of hours to see this solution. Could you help update your documentation? Thanks,
