### ISSUE TITLE
Flutter 3 build error

### ISSUE THREAD

**Issue by LukeStanyer** [syncfusion/flutter-widgets#726]
![Screenshot 2022-05-13 at 10 45 58](https://user-images.githubusercontent.com/74783626/168257831-bb8e7b92-b6e3-4ef9-a260-6d6bfcf080e1.png)

Widget not of type inherited widget error blocking builds on Flutter 3

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @LukeStanyer,

Greetings from Syncfusion. We have already fixed the issue which occurred after upgrading the Flutter SDK version to 3.0.0. It will be rolled out in our next weekly patch release, which is expected by tomorrow, and we will update you once the patch gets rolled out. We appreciate your patience until then.

Regards,
Yuvaraj.

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @LukeStanyer,

Thanks for your patience. The issues with Flutter v3.0.0 have been fixed and rolled out in our weekly patch release. To avoid the issues, please upgrade our package to the latest version 20.1.56.

Regards,
Yuvaraj.

**Comment by diogo10** [comment]
Hi @Yuvaraj-Gajaraj, i have done the update but I still got at least issues:


../../Others/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_charts-20.1.56/lib/src/chart/base/chart_base.dart:1820:35: Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../Others/flutter/packages/flutter/lib/src/scheduler/binding.dart').
Try calling using ?. instead.
        SchedulerBinding.instance.addPostFrameCallback((_) {

**Comment by jaskiratAtNexG** [comment]
@Yuvaraj-Gajaraj any update on this???
