### ISSUE TITLE
SfDataGrid manually attached horizontal / vertical scrollController gets disposed

### ISSUE THREAD

**Issue by Elixell** [syncfusion/flutter-widgets#740]
I have some custom logic regarding the scrollControllers and I would like to manually dispose them, when i explicitly set the horizontal / vertical controllers, but  in scrollwiev_widget.dart it gets disposed internally.  I assume that, when we explicitly set any controllers we need to handle the lifycycle of that object too, like in any widget in the flutter framework.  I have some custom logic which  handles the dispose of the controllers and i would like to be able to handle it myself.

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @Elixell,

Greetings from Syncfusion.

Currently, DataGrid does not have support for disposing of the scroll controllers manually. We have considered your request as a feature. This feature will be implemented in our Volume 2 release, which is expected to be rolled out at the end of June 2022. We will let you know when this feature is implemented. You can follow up with the below feedback for further details,

Feedback Link: https://www.syncfusion.com/feedback/34990/support-to-not-dispose-the-verticalscrollcontroller-and-horizontalscrollcontroller 

Regards,
Tamilarasan

**Comment by Elixell** [comment]
Thank you very much!

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @Elixell,

Thanks for your patience. 

We are glad to announce that our Essential Studio 2022 Volume 2 Main Release **V20.2.36** is rolled out with the fix for mentioned issue and is available for download under the following link.
  
[https://www.syncfusion.com/forums/175975/essential-studio-2022-volume-2-main-release-v20-2-0-36-is-available-for-download](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.syncfusion.com%2Fforums%2F175975%2Fessential-studio-2022-volume-2-main-release-v20-2-0-36-is-available-for-download&data=05%7C01%7Ctamilarasan.paranthaman%40syncfusion.com%7C884c82e03d7943cb28a008da5b15d9c8%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C637922446653595240%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=LyrMMu5LoRIZvCHV6ZU0%2FmgamLWPfFqhdkuusnOl85U%3D&reserved=0)

We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.

Regards, 
Tamilarasan
