### ISSUE TITLE
[SfDataGrid] How to always show the sort Icon?

### ISSUE THREAD

**Issue by Wizzel1** [syncfusion/flutter-widgets#742]
What do I need to do in order to initially show the sorting icon on every column?

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @Wizzel1,

We have already considered your request “Show icon in column header cells to indicate sorting is supported” as a feature. **We planned to implement this feature only when tri-state sorting is set to true. Can you please confirm whether this meets your requirement?** If not, can you please provide more details of your requirement?

Feedback Link: [https://www.syncfusion.com/feedback/33650/support-to-show-icon-in-column-header-cells-when-tri-state-sorting-is-enabled-to](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.syncfusion.com%2Ffeedback%2F33650%2Fsupport-to-show-icon-in-column-header-cells-when-tri-state-sorting-is-enabled-to&data=05%7C01%7Ctamilarasan.paranthaman%40syncfusion.com%7C7f1da1d6319e4ae09b1208da39655084%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C637885404547824704%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=m%2B1iN8zxAdoKAXZQC4n16iizJQ6W8r%2FchTD1FpBUMx4%3D&reserved=0) 

Regards,
Tamilarasan

**Comment by Wizzel1** [comment]
Hi @Tamilarasan-Paranthaman thanks for the quick response.

I don't want to use the tri-state sorting. 

The problem is, that the sorting icon does not show by default in the column header and I was wondering why. 
Is there a setting or override that always shows this icon?

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @Wizzel1,

Thank you for your update.

Please confirm whether you want to show the unsort icon in the column headers at the initial loading itself when allow sorting is true? If sorting is applied, the ASC or DESC icons would be shown for specific column and unsort icon will be remained for other columns which are not sorted. Please check the following reference images.

**Initial loading with unsort icon:**

 
![image](https://user-images.githubusercontent.com/93904422/169972692-8f66ac6a-8689-4ce9-a3e4-819f2b4e0fbc.png)


**Ascending:**

 
![image](https://user-images.githubusercontent.com/93904422/169972736-d60f5470-26ce-42fa-9298-a2c796e861e0.png)


**Descending:**

 
![image](https://user-images.githubusercontent.com/93904422/169972758-fe1b5a6b-8c88-498f-b0bd-b9d948a3b9cf.png)


Please provide more details in case we misunderstood your requirement. It will be helpful for us to check on it and provide you the solution at the earliest.

Regards,
Tamilarasan

**Comment by Wizzel1** [comment]
@Tamilarasan-Paranthaman I want to achieve the looks from the 3rd image.

Preferably, the icon has to show in every column. 

My goal is to indicate to the user, that the column can be sorted.

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @Wizzel1,

Sorry for the inconvenience caused.

Due to some technical difficulties, we unfortunately couldn't provide the support for the “Show icon in column header cells when allow sorting is enabled to indicate sorting is supported” in the 2022 Volume 2 release. We will implement this feature in our 2022 Volume 2 SP release, which is expected to be rolled out by the mid of August 2022. We will let you know once it is published. We appreciate your patience and understanding till then.

Regards,
Tamilarasan

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @Wizzel1,

Sorry for the inconvenience caused.

Due to some technical difficulties, we unfortunately couldn't provide the support for the “Show icon in column header cells when allow sorting is enabled to indicate sorting is supported” in the 2022 Volume 2 SP release. **We will implement this feature in our 2022 Volume 3 release, which is expected to be rolled out by the end of September 2022**. We will let you know once it is published. We appreciate your patience and understanding till then.

Regards,
Tamilarasan
