### ISSUE TITLE
[DataGrid] Missing method to get row by a primary key (real_time_update)

### ISSUE THREAD

**Issue by tlvenn** [syncfusion/flutter-widgets#75]
Hi,

I am evaluating the datagrid to display stock list where values are updated in real time and where the grid is sort-able.
Given that it is currently impossible to lookup a row using a key, i have no other choices but to call `notifyListeners()` and as a result i barely manage to get 20 frames / second and the grid is really janky.

I noticed that on the react side for example a method `getRowIndexByPrimaryKey` exists which is critical to alleviate the performance issue of repainting the whole grid so i can use `notifyDataSourceListeners` with given cell(s).

The datagrid_real_time_update demo you put in place is completely cheating a real world scenario as it simply update random rows and does not bother trying to match an updated stock with its row in the datagrid...

**Comment by BalasubramaniSundaram** [comment]
Hi @tlvenn , 

Greeting from Syncfusion.

Currently, we are validating the reported issue “**SfDataGrid is repainted with each update when using notifyDataSourceListeners**” and we will validate and update you with further details on or before 10th December 2020. We appreciate your patience until then.

Regards,
Balasubramani Sundaram.

**Comment by tlvenn** [comment]
Hi @BalasubramaniSundaram ,

Thanks for your feedback and for highlighting this method that I actually missed since it is not the one being used in the real time update demo.

However the core issue is the same, I don't know the index in the grid of the stock that is being refreshed. Please keep in mind that the grid is sortable by the user and given that stocks are being updated all the time, a given stock might be at index 3 on a given tick and then at index 4 the next tick.

That is why it is so crucial that the grid provides a method to lookup the row index of a given stock using its id for example given that this piece of data does not change. That primary key should also be useful as the flutter key for the row.

**Comment by tlvenn** [comment]
Hi @BalasubramaniSundaram,

Any feedback on the above ? Thanks.

**Comment by NeelakandanKannan** [comment]
Hi @tlvenn ,

Thanks for your detailed update.

We will look onto your query and get back to you on Monday (14th December 2020).

Appreciate your patience until then.

**Comment by BalasubramaniSundaram** [comment]
Hi @tlvenn,

Thanks for your patience’s

At present we do not have support for providing the primary key for the grid cells in the datagrid and also based on the record we couldn’t do the process to find the index from the source level. 

In Datagrid, at the time of sorting only we will modify the data in DataGridSource for that we are analyzing the feasibility of providing the support to get the index based on the record on the user side itself and we will provide you the more details on or before 21st December 2020. We appreciate your patience until then.

Regards, 
Balasubramani Sundaram.

**Comment by BalasubramaniSundaram** [comment]
Hi @tlvenn , 

Thanks for your patience’s,
 
We have planned to expose the ‘indexOf’ method (parameter is the object which is used in the collection) in DataGridSource class itself to retrieve the row index from the collection. This method will return the index of a row in datagrid if the sorting is applied to datagrid. Hope, this will meet your requirement to retrieve the index. We will include the below code in our upcoming weekly pub if you don’t have any concerns in this.
 
Please refer the below code snippet,

```
@override

Widget build(BuildContext context) {
  return Scaffold(
      appBar: AppBar(
        title: Text('Retrieve Index'),
      ),
      body: Column(children: [
        FlatButton(
            onPressed: () {
              var index = _employeeDataSource.indexOf(employeeData[2]);
              //Or
              // var index = _employeeDataSource.indexOf(employeeData[random.nextInt(employeeData.length - 1)]);
              print(index);
            },
            child: Text('Get index')),
        Container(
          child: SfDataGrid(
            source: _employeeDataSource,
            selectionMode: SelectionMode.single,
            columnWidthMode: ColumnWidthMode.auto,
            allowSorting: true,
            columns: [
                   …….
                 ……
            ],
          ),
        ),
      ]));
}
```

We hope that this helps, please let us know if you would require any assistance. 
 
Regards,
Balasubramani Sundaram.

**Comment by tlvenn** [comment]
Hi @BalasubramaniSundaram,

This should work for small collections without too much impact however scanning the entire list to find a match will become very slow when the collection grows but this is a good immediate solution for whenever the number of rows or the update rate is not too big.

Long term solution would be to use something like a [SplayTreeMap](https://api.dart.dev/stable/2.10.4/dart-collection/SplayTreeMap-class.html) instead of a list to hold the `_effectiveDataSource` and add a `String getId(T data)` to the DataGridSource that will be used to build the map. We could then lookup the index / row of a given record by its id and transparently the `indexOf` method you are proposing to introduce could leverage it as well.

**Comment by NeelakandanKannan** [comment]
Hi @tlvenn ,

Thanks for your update.

We have checked the possibility to provide the map support to get the row index. But, unfortunately we can't provide this support with map type of collection due to we can easily get the row and cell information from the List and also sorting is directly performed in List. 

The primary problem is that when you call notifyListeners() or notifyDataSourceListeners(), the entire datagrid will be repainted where as if you call notifyDataSourceListeners() with specific cell, the specific cell alone will be repainted. Even though the specific cell is repainted, the performance is too low in Android platform. So, we will continue to follow the below GitHub query for framework side update,

https://github.com/flutter/flutter/issues/72451

Once we got the enough details, we will plan to refresh the entire grid or specific cell by only calling **notifyListeners()** or **notifyDataSourceListeners()**. So, there will be no need to get the row index from the underlying data.

**Comment by tlvenn** [comment]
> We have checked the possibility to provide the map support to get the row index. But, unfortunately we can't provide this support with map type of collection due to we can easily get the row and cell information from the List

Yes it's easy but it is expensive given you need to scan the whole list

> and also sorting is directly performed in List.

The `SplayTreeMap ` I mentioned is also keeping the items sorted, just like the list.

On a side note, did you end up pushing the `indexOf` method mentioned by @BalasubramaniSundaram ?

**Comment by NeelakandanKannan** [comment]
Hi @tlvenn,

We had planned to provide the **indexOf** method to get specific cell. But, we are just waiting for Flutter team's update on our bug report. Because, cell lookup even is not required if we got the enough details from them. As we mentioned, once we got the enough details or solution, we will remove the notifyDataSourceListeners(rowColumnIndex:) argument and keep the notifyDataSourceListeners() alone. You can simply call notifyDataSourceListeners() for all the CRUD operations. We will optimistically repaint whole datagrid even if you want to update single cell.
