### ISSUE TITLE
[syncfusion_flutter_sliders] Type error when VoiceOver is turned on in iOS

### ISSUE THREAD

**Issue by Okazuki** [syncfusion/flutter-widgets#750]
Hi!!  
Thanks for the great package.  
This package has been very helpful to me!  

I have an error when I set SfRangeSlider.values to a value of int with VoiceOver turned on in iOS.  

```
======== Exception caught by scheduler library =====================================================
The following _TypeError was thrown during a scheduler callback:
type 'int' is not a subtype of type 'double'

When the exception was thrown, this was the stack: 
#0      RenderBaseRangeSlider.increasedStartValue (package:syncfusion_flutter_sliders/src/range_slider_base.dart:271:35)
#1      _RenderRangeSlider.assembleSemanticsNode (package:syncfusion_flutter_sliders/src/range_slider.dart:2182:7)
#2      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3842:13)
#3      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3834:16)
#4      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3834:16)
#5      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3788:18)
#6      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3788:18)
#7      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3788:18)
#8      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3834:16)
#9      _RootSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3712:16)
#10     RenderObject._updateSemantics (package:flutter/src/rendering/object.dart:2773:25)
#11     PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1096:16)
#12     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:502:21)
#13     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
#14     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#15     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#16     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
#17     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:862:7)
(elided 4 frames from class _RawReceivePortImpl, class _Timer, and dart:async-patch)
====================================================================================================
```  

This is my configration：  
```
• Flutter (Channel stable, 2.10.1, on macOS 11.6 20G165 darwin-x64, locale ja-JP)
• Flutter version 2.10.1 at /Users/user/fvm/versions/2.10.1
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision db747aa133 (3 months ago), 2022-02-09 13:57:35 -0600
• Engine revision ab46186b24
• Dart version 2.16.1
• DevTools version 2.9.2
• iPhone11/iOS14.6
```  

Procedure：  
- Turn on VoiceOver in iOS
- Run this code  

```
void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Sample(),
    );
  }
}

class Sample extends StatelessWidget {
  const Sample({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SfRangeSlider(
        min: 0.0,
        max: 100.0,
        // Error occurs when int value is set
        values: const SfRangeValues(40, 80),
        onChanged: (dynamic value) {},
      ),
    );
  }
}
```

**Comment by sfHariHaraSudhan** [comment]
Hi @Okazuki,

We have analyzed and replicated the voice-over issue in the [SfRangeSlider](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfRangeSlider-class.html) on IOS by enabling voice-over and using the code you provided. However, it appears that the issue is not caused by enabling voice-over.

The reason for the type error is that you have passed the range [values](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfRangeSlider/values.html) as integer values instead of double values to the values property. To avoid the type error issue, we suggest using double values instead of integers for the range values.

Regards,
Hari Hara Sudhan. K

**Comment by Okazuki** [comment]
@sfHariHaraSudhan 
Thanks for doing the research.

I understand that I can pass a value of type double to SfRangeValues.
However, looking at the documentation, the constructor type is dynamic, which is causing this problem.
I think it should be a double type, not a dynamic type.

**Comment by sfHariHaraSudhan** [comment]
Hi @Okazuki,

In the [SfRangeSlider](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfRangeSlider-class.html), we can give the [SfRangeValues](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfRangeValues-class.html) as both datetime or double data type to the [values](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfRangeSlider/values.html) property, hence the datatype is declared as dynamic instead of double.

However, we are able to replicate the reported issue regarding “**Type-error-exception-was-thrown-while-passing-the-range-values-as-integer-values**” at our end and have logged bug report for it in our feedback portal. We will fix and include the changes in our weekly patch release which is expected to be rolled out on July 4, 2023. We will update you here once the release is rolled out and we appreciate your patience until then. You can also track the status of the bug using the below feedback link.
 
Feedback link: https://www.syncfusion.com/feedback/44693/type-error-exception-was-thrown-while-passing-the-range-values-as-integer-values.
 
Regards,
Hari Hara Sudhan. K.

**Comment by sfHariHaraSudhan** [comment]
Hi @Okazuki,

The reported issue regarding **Type-error-exception-was-thrown-while-passing-the-range-values-as-integer-values** has been fixed and rolled out in our Weekly patch release. Therefore, we kindly request that you upgrade the syncfusion_flutter_sliders package to the latest version below to avoid this issue.

Version:  https://pub.dev/packages/syncfusion_flutter_sliders/versions/22.1.37

Regards,
Hari Hara Sudhan. K.
