### ISSUE TITLE
Reopen #594

### ISSUE THREAD

**Issue by d-wolf** [syncfusion/flutter-widgets#754]
Ticket  #594  was closed but the problem is still present. Could you please reopen the ticket and check the example i have provided?

**Comment by sfHariHaraSudhan** [comment]
Hi @d-wolf,

We have analyzed the given sample and found the root cause of the issue is because of using the setState, as it rebuilds the whole application again, and due to this, the text, legend Icon and the series are not updated properly.

We initialize a ValueNotifier as _valueNotifier with the default text and the ValueListenableBuilder rebuilds the Text widget when the value changes, preventing a full application rebuild. When the legend icon is pressed, updating the text value triggers the ValueListenableBuilder to rebuild the Text widget, enabling proper toggling of the legend and series.

By using this approach, you can avoid using setState and achieve the desired behavior of updating the text without triggering a full rebuild of the application.

Kindly refer the code snippet below:
```
class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final ValueNotifier<String> _valueNotifier = ValueNotifier<String>('');
  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('SfCartesianChart'),
      ),
      body: series != null
          ? Column(
              children: [
                Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: ValueListenableBuilder(
                    valueListenable: _valueNotifier,
                    builder: (context, value, child) {
                      if (value == '') {
                        return Text(seriesVisibilityToString());
                      } else {
                        return Text(value.toString());
                      }
                    },
                  ),
                ),
                Expanded(
                  child: SeriesChart(series!, (index, value) {
                    series!.seriesVisibility[index] = value;
                    _valueNotifier.value = seriesVisibilityToString();
                  }),
                ),
              ],
            )
          : const Center(child: CircularProgressIndicator()),
    );
  }

  String seriesVisibilityToString() {
    _valueNotifier.value = '';
    for (var i = 0; i < series!.seriesVisibility.length; i++) {
      _valueNotifier.value += '[${i + 1}] ${series!.seriesVisibility[i]}; ';
    }
    return _valueNotifier.value;
  }
}
```

Also attached the sample below for your reference.

Regards,
Hari Hara Sudhan. K

[473879.zip](https://github.com/syncfusion/flutter-widgets/files/11787753/473879.zip)
