### ISSUE TITLE
[SfCircularChart] Add desktop support for the mouse hover in charts.

### ISSUE THREAD

**Issue by Shiryhalov** [syncfusion/flutter-widgets#755]
Hi! 
I noticed that in the CircularArea widget and in some other files you are using the `_enableMouseHover = kIsWeb` check. This is why the tooltip on the desktop doesn't appear on hover. Can you fix this please?

Found in syncfusion_flutter_charts 20.1.56.

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @Shiryhalov,

To detect the platform, we need to use the dart.io package but in pub.dev they do not recommend the dart.io usage in the packages. And we have enabled the onHover event when only the application runs on the web because the onHover event gets triggered even at tap on mobile. We have also logged the issue regarding this on the flutter GitHub page please find the link below for further information. So, as of now, we are unable to enable the onHover event in the desktop app.

GitHub: https://github.com/flutter/flutter/issues/68690

Regards,
Yuvaraj.
