### ISSUE TITLE
SfRadialGauge Not Rendering in version 2.1.57

### ISSUE THREAD

**Issue by emondd4** [syncfusion/flutter-widgets#757]
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_gauges-20.1.57/lib/src/radial_gauge/pointers/marker_pointer_renderer.dart:608:12:

Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.

 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/C:/flutter/packages/flutter/lib/src/widgets/binding.dart').
 - 
Try calling using ?. instead.
          .addPostFrameCallback((Duration duration) => markNeedsPaint());

**Comment by cmlee-danbi** [comment]
Same here

**Comment by chrisvidal** [comment]
which flutter version guys?

**Comment by cmlee-danbi** [comment]
> flutter --version
Flutter 2.10.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5464c5bac7 (5 weeks ago) • 2022-04-18 09:55:37 -0700
Engine • revision 57d3bac3dd
Tools • Dart 2.16.2 • DevTools 2.9.2

Issue occurs @ 20.0.57
In my case I just changed package version to 19.4.56, and problem solved

**Comment by chrisvidal** [comment]
had to backtrack as well to this old package version

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @emondd4,

The issue occurs due to the Flutter latest version, so we have migrated our source compatible to the latest version of Flutter. So, we suggest upgrading the Flutter version to the latest one to avoid this issue, or if you can't upgrade Flutter to the latest version use the chart(syncfusion_flutter_charts) and core(syncfusion_flutter_core) package version to 20.1.55.

syncfusion_flutter_charts: 20.1.55
syncfusion_flutter_core: 20.1.55

Regards,
Yuvaraj.
