### ISSUE TITLE
[DataGrid] SfDataGrid is repainted with each update when using notifyDataSourceListeners (Bug)

### ISSUE THREAD

**Issue by tlvenn** [syncfusion/flutter-widgets#76]
I am checking the demo with real time update which is the use case i am interested in.
Just checking the Frame rendering times highlights a significant issue with performance.

By default, the demo is set to update 100 rows every 200ms.
In that scenario, the average FPS is 15 frames / sec...

I then changed the code to only update 1 row every 200 ms and to my suprise, the FPS only jumped to 30 frames / sec.
When looking at the widget rebuild stats, I noticed that the SfDataGrid is getting repainted at each update which is not normal when using `notifyDataSourceListeners` as only the row should be updated / repainted.

![image](https://user-images.githubusercontent.com/3340262/101329192-05563c00-38ac-11eb-8087-ee301a150778.png)

**Comment by BalasubramaniSundaram** [comment]
Hi  @tlvenn,

**Query 1: SfDataGrid renderer 20 frames / second and it's janky on calling notifyListener**

Please refer to this issue report https://github.com/syncfusion/flutter-widgets/issues/76 for more details.

**Query 2:  Refreshing the row and cells** 

You can use the notifyDataSourceListeners() with respective row column index or call the DataGridController.refreshRow() method to refresh the respective row in datagrid.

Please refer to the below code snippet and UG link for your reference.

```
final DataGridController _dataGridController = DataGridController();

void _changeRows(int count) {
   _dataGridController.refreshRow(index, recalculateRowHeight: false);
}

Widget build(BuildContext context){
   return SfDataGrid(
    ….
    controller: _dataGridController,
    ….
  );
}
```

UG link: https://help.syncfusion.com/flutter/datagrid/row-height-customization#refresh-row-height-for-specific-row

Regards, 
Balasubramani Sundaram.

**Comment by BalasubramaniSundaram** [comment]
Hi @tlvenn, 

Thanks for your patience’s, 

Based on your provide details we have analyses your reported issue of ‘30Fps only jumped on updating the single row in datagrid’. From, the analysis we also get the same 30Fps in both single row and 100 rows updates when running the app on [‘Profile Mode](https://flutter.dev/docs/perf/rendering/ui-performance#diagnosing-performance-problems)’ but we couldn’t see any junk in UI and its running smoothly same way in release mode too. But in debug mode the[ asserts check](https://flutter.dev/docs/perf/rendering/ui-performance#connect-to-a-physical-device) conditions are more expense, and it will affect the UI updating figure.

In datagrid, when we are calling the notifyDataSourceListeners() with row and column index we will updating the particular cell and their child alone and we are working with high priority on analyzing and will update the further details on or before 14th December 2020. We appreciate your patience until then.

![Screen Shot 2020-12-11 at 12 07 02 AM](https://user-images.githubusercontent.com/45868997/101815334-68aecb00-3b45-11eb-907a-7f63919bc0b8.png)


Regards, 
Balasubramani Sundaram

**Comment by BalasubramaniSundaram** [comment]
Hi @tlvenn , 

We regret for the inconvenience caused.

We are still working on analysis this reported issue “SfDataGrid is repainted with each update when using notifyDataSourceListeners” with high priority. Due to its complexity taken more time than expected, we need some more time to work on this probably two more days. We will provide you the details on or before 16th December 2020. We appreciate your patience until then.

Regards, 
Balasubramani Sundaram.

**Comment by tlvenn** [comment]
Thanks for the update @BalasubramaniSundaram

**Comment by BalasubramaniSundaram** [comment]
Hi @tlvenn , 

Thanks for your patience's, 

We have analyzed a lot to increase the fps but still, we get the same result and then we reproduce the same issue in framework DataTable and simple sample too. So, we have created an issue on the framework side to know the exact causes. You can also track the status of the issue by following below bug report link. 

link: https://github.com/flutter/flutter/issues/72451

We will let you know once we get the status of the reported issue. we appreciate your patience until then.

Regards, 
Balasubramani Sundaram

**Comment by tlvenn** [comment]
That does not really explain why the SfDataGrid is getting repainted, i would expect that only the updated cells should be repainted.

As for the fps, i had a look at your report and i cant reproduce it at all...
Are you sure you are running in the profile mode ?
> https://cln.sh/kHW1M9

**Comment by BalasubramaniSundaram** [comment]
Hi @tlvenn, 
 
Thanks for your response.
 
When you are calling the notifyDataSourceListeners() with row and column index,  datagrid will update and repaint the given cell alone. We suspected the same behavior could be observed in framework too. So that, we have checked the simple application and its performance in profile mode. Fps is observed like what we experienced in datagrid also. So, we decided to log it as query to framework side and get the details about why the simple application itself taking more Fps on every time we call setState method. Based on the details provided by framework side, we might be able to know the reason behind it.
 
We have logged the query to framework side by checking the performance in profile mode. We have measured the performance in Android environment. As per your update,  your provided video shows performance testing in macOS platform`. We have checked that aspect too. The same simple sample takes 60Fps in macOS. So, we will provide all these details to framework and get the details from them. Once we got the details, we will analyze the way to improve the performance in all platforms (Android, iOS, Web and macOS).
 
Can you please confirm whether you have tested the performance in Android also for simple sample?

We have also test the Mac OS with two scenarios. In both case we get the 60Fps in

1) Updating single cell at every 200ms 

[performance_with_updating_single_row.zip](https://github.com/syncfusion/flutter-widgets/files/5709900/performance_with_updating_single_row.zip)

2) Updating the multiple row cells at every 200 ms

[perfromance_updating_multiple_row_same_time.zip](https://github.com/syncfusion/flutter-widgets/files/5709888/perfromance_updating_multiple_row_same_time.zip)


Also we have tested the same simple in macOS and android too. In MacOS we are getting 60Fps but in android its only getting 20 to 30 Fps

1) Simple sample deployed in android,

Device: Samsung S6 

| | | 
|:-------------------------:|:-------------------------:|
| ![performance_window_view](https://user-images.githubusercontent.com/45868997/102494595-e9684c80-409a-11eb-81bf-ea0cb3f2079e.gif)| ![performnace_mobile_view](https://user-images.githubusercontent.com/45868997/102494610-eff6c400-409a-11eb-803d-8428e933a986.gif)|
 
Please let us know if you have any concerns.
 
Regards,
Balasubramani Sundaram.
