### ISSUE TITLE
Build Exception

### ISSUE THREAD

**Issue by chrisvidal** [syncfusion/flutter-widgets#761]
with Flutter 2.10.2 since package version `20.1.52` in my case.

this `syncfusion_flutter_charts: ^19.4.56` is working

```

    ../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_charts-20.1.57/lib/src/chart/base/chart_base.dart:1820:35: Error: Method 'addPostFrameCallback' cannot be called on
    'SchedulerBinding?' because it is potentially null.
     - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../../Development/flutter/packages/flutter/lib/src/scheduler/binding.dart').
    Try calling using ?. instead.
            SchedulerBinding.instance.addPostFrameCallback((_) {
```

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @chrisvidal,

We have provided compatibility for the chart widget to the latest version of Flutter. So the reported issues occurred due to this. We request to upgrade the Flutter SDK version to the latest and use the latest chart package version, or if you want to stay with Flutter SDK version 2.10.2 then use the chart package version below 20.1.55 without the caret symbol (^). Also, refer to the chart's dependent widget core with the same version similar to below.

syncfusion_flutter_charts: 20.1.55
syncfusion_flutter_core: 20.1.55

Regards,
Yuvaraj.

**Comment by chrisvidal** [comment]
thanks.

but same error this time with the `syncfusion_datepicker` package that I don't even use

```


Xcode's output:
↳
    Writing result bundle at path:
        /var/folders/vr/81pvs8w52m55zkrjqhrbtwhc0000gn/T/flutter_tools.Wb7tDE/flutter_ios_build_temp_dirWjAndl/temporary_xcresult_bundle

    ../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_datepicker-20.1.57/lib/src/date_picker/date_picker.dart:8059:31: Error: Method 'addPostFrameCallback' cannot be called
    on 'SchedulerBinding?' because it is potentially null.
     - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../../Development/flutter/packages/flutter/lib/src/scheduler/binding.dart').
    Try calling using ?. instead.
        SchedulerBinding.instance.addPostFrameCallback((_) {
```

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @chrisvidal,

As we stated earlier, please use our package version below 20.1.55 but in your stack trace, you are still using the syncfusion_flutter_datepicker version as 20.1.57 is the latest one. If you want to stay with the old Flutter SDK version, you need to use our packages to use the version below 20.1.55, or did you want to use our latest package version please try to upgrade the Flutter SDK version to the latest one.

And if you have used our calendar widget, then the date picker is the dependent widget, so the package will be restored with the latest version only. So as stated earlier we suggest using a lower version.

Regards,
Yuvaraj.

**Comment by ekuleshov** [comment]
> If you want to stay with the old Flutter SDK version, you need to use our packages to use the version below 20.1.55, or did you want to use our latest package version please try to upgrade the Flutter SDK version to the latest one.

The problem is that your latest package version does not declare proper restrictions on the Flutter and Dart SDK and the old package is always listed as outdated and updatable.

Here is the recommended way to maintain backward compatibility with Flutter 2 and it doesn't add much complexity:
https://docs.flutter.dev/development/tools/sdk/release-notes/release-notes-3.0.0#your-code
