### ISSUE TITLE
SfDataPager - handlePageChange

### ISSUE THREAD

**Issue by nousath** [syncfusion/flutter-widgets#765]
HandlePageChange load twice on each page refresh 
![image](https://user-images.githubusercontent.com/25167886/170614540-d35dbf6c-1084-4eaf-a5b7-bd4ea863a7ae.png)

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @nousath,

Greetings from Syncfusion.

We are a little bit unclear about your reported query. Can you please confirm whether the handlePageChange called twice every time while navigating between the pages or called twice at initial loading alone?  It would be helpful if you provided more details about your query.

Regards,
Tamilarasan

**Comment by nousath** [comment]
Hi @Tamilarasan-Paranthaman 
thank you for your response, twice at initial loading 
each **setstate and notifyListeners** react handlePageChange

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @nousath,

We have checked your reported issue and logged this as a bug. We will include the changes in our weekly pub release which is scheduled to be rolled out on June 14, 2022. We will let you know once it gets rolled out. We appreciate your patience until then. You can follow up with the below feedback for further details, 

Feedback Link:  https://www.syncfusion.com/feedback/35277/the-handlepagechange-method-is-called-twice-on-initial-loading 

Regards,
Tamilarasan

**Comment by nousath** [comment]
thank you @Tamilarasan-Paranthaman

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @nousath,

Sorry for the inconvenience.

Due to some technical difficulties, we could not include the handlePageChange issue fix in this weekly pub release. We will include the changes in our upcoming weekly pub release which is scheduled to be rolled out on June 21, 2022. We will let you know once it is published. we appreciate your patience until then.

Regards,
Tamilarasan

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @nousath,

We would like to let you know that because of our 2022 volume 2 main release this week, we will not have a pub release for this week. The fix for the reported issue will be included in our next weekly pub release. We will let you know once it's rolled out. We appreciate your patience and understanding till then.

Regards,
Tamilarasan

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @nousath,

We are glad to inform you that the fix has been included in our weekly pub release. Please update the DataGrid package to version **20.2.39**.

We thank you for your support and appreciate your patience in waiting for this update. Please get in touch with us if you require any further assistance.

Regards,  
Tamilarasan

**Comment by marco-origam** [comment]
I'm still having this problem using the version: 26.2.10

![image](https://github.com/user-attachments/assets/d0e434b7-cae9-406c-a212-84024b5e0a4c)
