### ISSUE TITLE
CartesianChart - Data label - only show max value & min value possible?

### ISSUE THREAD

**Issue by FisherWL** [syncfusion/flutter-widgets#768]
e.g.
<img width="299" alt="WX20220528-012941@2x" src="https://user-images.githubusercontent.com/57275868/170817619-d59a0219-2c2c-4a2b-ae41-23275bdb1e9f.png">

**Comment by Marismathan** [comment]
Hi FisherWL,

Greetings from Syncfusion.We suggest that you can use the onDataLabelRender callback to render the maximum and minimum data labels of your chart. We had the data source already and we need to find the minimum and maximum values from that before rendering the chart say for example find in initState method. By using that, you can customize the rendered text in that callback. We have shared a code snippet that expresses the workaround for your scenario. And kindly go through the API link of onDataLabelRender callback in the below link too,

API link: https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/onDataLabelRender.html

`onDataLabelRender: (DataLabelRenderArgs args) {
       /// Here 100 is the maximum value and 20 is the minimum values, you can modify this based on your scenario
     if (!(args.text == '100' || args.text == '20')) {
      args.text ='';
    }
   }`

Thanks,
Marismathan G

**Comment by LavanyaGowtham2021** [comment]
Hi @FisherWL ,

You can reopen this ticket if you have any concern on the provided solution. 

Thanks,
Lavanya A.

**Comment by starfoxcom** [comment]
For those who have tried this approach, but found some issues with the cartesian chart, here are some tips to do to achieve this:
aside from `isVisible: true` in the `DataLabelSettings`, i recommend to set in the `  primaryYAxis: CategoryAxis(...` the `rangePadding` to `ChartRangePadding.additional`. Here are some examples of this without and with these changes:

Without `rangePadding`
![image](https://user-images.githubusercontent.com/29107481/189873353-83f5a973-3844-4d0a-9f94-f3ef55ded509.png)
With `rangePadding`
![image](https://user-images.githubusercontent.com/29107481/189873452-4695f49e-66b1-43a2-974f-b5b3e8a5741b.png)

Also, if you want to give a custom widget to show the label instead of using the simple `Text` from the `onDataLabelRender`, then you can use the `builder` thats on `DataLabelSettings`. Also, I recommend to use the `builder` rather than the `onDataLabelRender`, since I noticed that in some cases where the X axis data is too much, the label will not render at all, here some examples of it:
With `onDataLabelRender` on low X axis data
![image](https://user-images.githubusercontent.com/29107481/189879452-df8a083d-8790-4d89-912d-d99cc6738360.png)
With `onDataLabelRender` on high X axis data
![image](https://user-images.githubusercontent.com/29107481/189879660-20390e9b-9c70-4290-b3f9-a84f8101ac01.png)
![image](https://user-images.githubusercontent.com/29107481/189879701-da826e6e-d4be-477a-bc08-2fea428ba473.png)

With `builder` on low X axis data
![image](https://user-images.githubusercontent.com/29107481/189879959-e93e1776-405c-405c-91a0-bf64670c1cbe.png)
With `builder` on high X axis data
![image](https://user-images.githubusercontent.com/29107481/189880037-6e5e9e70-e961-4977-b374-2a55a7dd1f72.png)
![image](https://user-images.githubusercontent.com/29107481/189880068-d559d35b-2a20-4bc4-b4b4-869a27432e36.png)

Hope this info helps anyone who wants to achieve this visual with the cartesian chart, have a nice day!
