### ISSUE TITLE
Issues in Legend Color for Trendline in SplineAreaSeries

### ISSUE THREAD

**Issue by ominibyte** [syncfusion/flutter-widgets#77]
I'm using a SplineAreaSeries with `trendlines` defined as

```dart
trendlines: <Trendline>[
  Trendline(
      type: TrendlineType.movingAverage,
      color: T.current.chartColors[3],
      legendIconType: LegendIconType.circle,
      opacity: 0.8,
      name: S.current.moving_average,
      markerSettings:
          MarkerSettings(isVisible: true, shape: DataMarkerType.circle))
]
```

First, I notice that if I use `LegendIconType.verticalLine` or `LegendIconType.horizontalLine`, they only show up (dimmed) when the series is toggled off and do not show when active.

Secondly, the color on the legend for the Trendline does not take from the color defined in the Trendline. It always picks the gradient defined in the parent SplineAreaSeries unless I change the SplineAreaSeries to use color instead of gradient which I want to use.

**Comment by SriramKiranSenthilkumar** [comment]
Hi @ominibyte,

Greetings from Syncfusion. We have analyzed your queries with the provided information at our end and provided the responses below.

**Query # 1: (First, I notice that if I use LegendIconType.verticalLine or LegendIconType.horizontalLine, they only show up (dimmed) when the series is toggled off and do not show when active)**

We have analyzed the above scenario and we tried to replicate the reported issue at our end by creating a simple spline area chart sample with the legends enabled in it. Unfortunately, the trendline legend toggling was working fine at our end. To ensure from our side, we have attached below a screen recording of the working of the trendline and its series legend toggling in the chart.
[Screen_recording.zip](https://github.com/syncfusion/flutter-widgets/files/5668003/recording.zip)

 Also, if you think that we have misunderstood you query then, we kindly request you to share us with more information on your scenario in detail along with example screenshots or screen recordings and or if possible kindly try to replicate the reported issue in the attached test sample below and revert us so that it will help provide the solutions sooner. 
[test_sample.zip](https://github.com/syncfusion/flutter-widgets/files/5668026/i306387_testsample.zip)

**Query # 2 : (Secondly, the color on the legend for the Trendline does not take from the color defined in the Trendline. It always picks the gradient defined in the parent SplineAreaSeries unless I change the SplineAreaSeries to use color instead of gradient which I want to use)**

We have analyzed the above query and we are able to replicate the reported issue regarding the trendline's legend gets rendered in gradient color when defined in series at our end. We will consider this as a bug and will include the fix for the reported issue in our upcoming weekly patch release which is expected to be rolled out by the end of this month. We will update you here once the release is rolled out and we appreciate your patience until then.

Regards,
Sriram Kiran

**Comment by ominibyte** [comment]
Here is an extract from the code I'm using. I actually changed the `legendIconType` to `verticalLine` for the demonstration:

```dart
SplineAreaSeries<MoistureData, DateTime>(
                        dataSource: dataPoints,
                        xValueMapper: (MoistureData data, _) =>
                            DateTime.fromMillisecondsSinceEpoch(data.timestamp),
                        yValueMapper: (MoistureData data, _) => data.moisture,
                        trendlines: <Trendline>[
                          Trendline(
                            type: TrendlineType.movingAverage,
                            color: movingAverageColor,
                            legendIconType: LegendIconType.circle,
                            opacity: 0.8,
                            markerSettings: MarkerSettings(
                              isVisible: true,
                              shape: DataMarkerType.circle,
                              width: 5,
                              height: 5,
                            ),
                            width: 1,
                          )
                        ],
                        name: widget.title,
                        gradient: _makeGradient(widget.chartColor),
                        borderColor: widget.chartColor,
                        borderWidth: 2,
                        legendIconType: LegendIconType.verticalLine,  // This is the one not working when active
                        markerSettings: MarkerSettings(
                          isVisible: true,
                          shape: DataMarkerType.pentagon,
                        ),
                        opacity: 0.5),
```

Here's a video recording for the first part of the issue as requested:
[20201211_101425.mov.zip](https://github.com/syncfusion/flutter-widgets/files/5680015/20201211_101425.mov.zip)

If I do not set a legendIconType and use the default given for the series, It shows well. The issue only happens when I provide one. 

I created a pull request already to fix the second part of this issue.

**Comment by SriramKiranSenthilkumar** [comment]
Hi @ominibyte,

Thanks for the revert. we have analyzed your scenario with the provided information and we are able to replicate the reported issue regarding the legend icon not displaying when the legendIconType is set as verticalLine or horizontalLine and with the series colour defined as a gradient. We will consider this as a bug and will include the fix in the same weekly patch release which is expected to be rolled out by the end of this month. We will update you here once the release is rolled out and we appreciate your patience until then.

Also to mention that we will consider your suggested fix(from you pull request) while fixing the reported issue regarding the trendline's legend gets rendered in gradient colour when defined in series at our end.

Regards,
Sriram Kiran.

**Comment by Dharanipalani** [comment]
Hi @ominibyte,

Thanks for being patience. The reported issue got fixed in our latest version of flutter charts **v18.4.33**. Now the legend icon type of vertical or horizontal line shows correctly when both series is active or not and the trendline legend color issue also resolved when the gradient is applied for the series. Kindly upgrade to the latest version and it can get from below,

Latest version: [https://pub.dev/packages/syncfusion_flutter_charts/versions/18.4.33](url)

Thanks,
Dharanitharan. P
