### ISSUE TITLE
SfCartesianChart does not show the last value label on the X axis

### ISSUE THREAD

**Issue by 2020java2020** [syncfusion/flutter-widgets#779]
Hello! When I use SfCartesianChart with primaryXAxis: DateTimeCategoryAxis(), the last value label is not displayed, as shown in the screenshot. Please tell me, how to make the last value label always display. Very grateful for the help.
![Screenshot_1](https://user-images.githubusercontent.com/74665492/172637257-204fbb9a-0786-4eb3-9b42-ba070e1a0902.png)

**Comment by FisherWL** [comment]
I second that.
what's worse, it's a financial chart in my case --- meaning the latest/current date is not shown:
![WX20220608-194644](https://user-images.githubusercontent.com/57275868/172753748-b7c9cc9c-de5a-402b-a5c0-f66017b99513.png)
 (chart data is using the example in https://github.com/syncfusion/flutter-widgets/issues/774)

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @2020java2020,

Greetings from Syncfusion. We would like to let you know that the axis [interval](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/interval.html) is calculated based on the visible data points count and the available area of the chart only. And based on that interval values, the visible axis labels are rendered. For example, if there are 11 data points available, the last label will render because according to the charts, the internal interval calculation is 2. In that case, you can also use the interval property in the DateTimeCategory axis to make the last label to be rendered. Kindly get back to us if you have further queries.

Thanks,
Yuvaraj.

**Comment by LavanyaGowtham2021** [comment]
Hi @2020java2020 ,

You can reopen this ticket if you have any concern on the provided solution. 

Thanks,
Lavanya A.

**Comment by RicardoDFR** [comment]
Is there a way of getting the interval calculated by the chart axis if none is provided? Would be great because I could use it to set the maximum value of the axis to be exactly an interval, showing a value label on the end of the axis.
