### ISSUE TITLE
`SfTheme` does not get applied

### ISSUE THREAD

**Issue by ricardoboss** [syncfusion/flutter-widgets#780]
The example at https://help.syncfusion.com/flutter/themes works, but only with the `SfCartesianChart`. It doesn't work with, for example, `SfRadialGauge`. At least it doesn't on Windows 11.

I created a minimal example here: https://github.com/ricardoboss/syncfusion_theme_test

Any idea what I did wrong? Is it a bug? Do you need a `flutter doctor` output?

**Comment by Marismathan** [comment]
Hi @ricardoboss ,

Greetings from Syncfusion. We have migrated all of our Flutter widgets from [ThemeData](https://api.flutter.dev/flutter/material/ThemeData-class.html) to [ColorScheme](https://api.flutter.dev/flutter/material/ColorScheme-class.html) on [this](https://help.syncfusion.com/flutter/release-notes/v19.4.0.38) release. So we suggest you use the color scheme instead of using theme data. We have modified the sample which you have shared like that the sample which has the theme conversions using color scheme. And we have shared that sample below. Kindly go through that and get back to us if you have further queries.

Sample: [gauge_with_color_scheme.zip](https://github.com/syncfusion/flutter-widgets/files/8890485/gauge_with_color_scheme.zip)

Thanks,
Marismathan G
