### ISSUE TITLE
Live chart and onMarkerRender doesnt work together..

### ISSUE THREAD

**Issue by shaikhaman2000** [syncfusion/flutter-widgets#781]
I am working on a live chart for stock market app that basically changes every 15 seconds and adds/updates data according to current time and price. I want to show marker on the last chart data. When I am updating live chart using controller the data gets updated but onMarkerRender() function doesnt update the last chart data point and doesnt show the marker .. Any possible solution? 

`onMarkerRender: (args) {
                if (args.pointIndex! == chartData.length - 1) {
                  args.markerHeight = 7;
                  args.markerWidth = 7;
                  args.color = color;
                  args.borderColor = color.withOpacity(0.6);
                } else {
                  args.markerHeight = 0;
                  args.markerWidth = 0;
                }
              },`

I want to make a live chart this way:
![Screenshot (273)](https://user-images.githubusercontent.com/55619244/172800666-4c2648d0-78bc-41b6-975a-875b4d3d798b.png)

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @shaikhaman2000, 

Thanks for your patience. We would like to let you know that while updating the data using the [updateDataSource](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeriesController/updateDataSource.html) method the [onMarkerRender](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/onMarkerRender.html) event did not get triggered because only the latest updated data point gets affected. So, we suggest the [onCreateRenderer](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianSeries/onCreateRenderer.html) callback to customize the rendering of the series. Here you can override the rendering of series, marker, and data label of series then customize it. We have created a sample and attached it below, it updates the data using the [updateDataSource](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeriesController/updateDataSource.html) method, and we have rendered a custom marker at the last point of the series using the [drawDataMarker](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianSeriesRenderer/drawDataMarker.html) override method.

Sample: [live_update_sample.zip](https://github.com/syncfusion/flutter-widgets/files/8900084/live_update_sample.zip)

UG: https://help.syncfusion.com/flutter/cartesian-charts/callbacks#oncreaterenderer 

If you have any other queries, please get back to us.

Regards,
Yuvaraj.
