### ISSUE TITLE
The page change is incorrect after turning the device.

### ISSUE THREAD

**Issue by mr-cocos-1** [syncfusion/flutter-widgets#784]
While viewing a multi-page PDF, change the device orientation from portrait to landscape, then back to portrait, then change the PDF page with nextPage (), previousPage (), firstPage (), lastPage () , Only one or two pages before and after are displayed, but the other pages are blank.
There is no problem as long as the device is used in portrait orientation.

**Comment by mr-cocos-1** [comment]
additional information.
There was no problem with syncfusion_flutter_pdfviewer-20.1.47-beta. I have a problem after updating to 20.1.57-beta.

**Comment by deepika134** [comment]
Hi mr-cocos-1

We are validating on the reported issue and will update the further details on June 14, 2022.

Regards,
Deepika Ravi

**Comment by deepika134** [comment]
Hi mr-cocos-1,

We confirmed that the issue with "the PDF page is not rendered properly after changing the orientation" is a defect. The issue fix will be included in our main release which is estimated to be available on end of June tentatively.

The status of this issue can be tracked using following link.
https://www.syncfusion.com/feedback/30594/improve-the-scroll-fling-sensitivity-of-sfpdfviewer

Regards,
Deepika R

**Comment by mr-cocos-1** [comment]
Hello! Deepika R.

Thank you for your early investigation.  I am looking forward to the release at the end of June.

Thank you very much.

Mr-cocos-1

**Comment by deepika134** [comment]
Hi mr-cocos-1, 
 
Thank you for your patience. 
 
We have included the fix for the issue “PDF page is not rendered properly after changing the orientation” in our 2022 Volume 2 main release, so kindly upgrade to the latest version v20.2.36 to get the issue resolved.
    
Package link: https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/20.2.36-beta    
 
Regards,  
Deepika Ravi
