### ISSUE TITLE
StackedLineSeries

### ISSUE THREAD

**Issue by NVenkateshRaj** [syncfusion/flutter-widgets#790]
The value of the chart index more than 2 is pointing to the wrong values,1st two list values are mapped correctly after the 2 nd value is  mapped wrongly in X axis and Y Axis, kindly look into this

Using this list in StackedLineSeries chart:
  List<ExpenseData> getChartData() {
    final List<ExpenseData> chartData = [
      ExpenseData('Food', 0, 0, 0, 0),
      ExpenseData('Transport', 0, 45, 54, 28),
      ExpenseData('Medical', 0, 5, 20, 20),
      ExpenseData('Clothes', 0, 54, 23, 20),
      ExpenseData('Books', 0, 18, 43, 20),
      ExpenseData('Others', 0, 54, 33, 20),
    ];
    return chartData;
  }

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @NVenkateshRaj,

The [StackedLineSeries](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/StackedLineSeries-class.html) is a series where lines are stacked on top of each other. It is the default behavior of the [StackedLineSeries](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/StackedLineSeries-class.html). If you want to render a series with the exact y value, please use the [LineSeries](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/LineSeries-class.html) instead of StackedLineSeries, or else if you want to see the actual y value of the stacked line series kindly enable [dataLabelSettings](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianSeries/dataLabelSettings.html) it will show the exact value. We have attached the UG documentation below to enable the data label in series.

UG: https://help.syncfusion.com/flutter/cartesian-charts/marker-datalabel#data-label

If you have any further queries, please get back to us.

Regards,
Yuvaraj.
