### ISSUE TITLE
Error opening some pdf files

### ISSUE THREAD

**Issue by luomo-pro** [syncfusion/flutter-widgets#811]
There are some pdf can not use SfPdfViewer to normal display, will report an error.
I got the error message in onDocumentLoadFailed, it tells me "There was an error opening this document".
I also tried to open this pdf file using other software, such as edge browser, which can open and display it normally without errors.
You can download my project containing the pdf file with the error from here.
http://us.lmdbk.com/pdf_demo2.zip
I use:
syncfusion_flutter_pdfviewer: ^20.2.36-beta
Flutter Channel stable, 3.0.1
Android mobile phone: XiaoMi12 Android12

**Comment by deepika134** [comment]
Hi @luomo-pro ,

We can reproduce the reported issue on our side and will update the details on July 8, 2022.

Regards,
Deepika Ravi

**Comment by deepika134** [comment]
Hi luomo-pro,

On further analyzing, when we load the provided PDF document, we are getting the out of memory exception form Flutter plugin. We are checking on this and will update the further details on July 12, 2022.

Regards,
Deepika Ravi

**Comment by RB-93** [comment]
Any updates on this package??

Updated to the latest version but still **grey/blank screen shown when a PDF is opened**. 
This is happening for both **Browser-Web and Mobile-Web in Flutter Web**.

**Comment by RB-93** [comment]
@deepika134 

Thanks, the step mentioned above did the work, PDF files can be opened now!

**Comment by deepika134** [comment]
Hi luomo-pro,

On further analyzing, we found that getting the out of memory exception from the Flutter platform while loading the provided document. We are checking on this and will update the further details on July 21, 2022.

Regards,
Deepika Ravi

**Comment by Abhishek01039** [comment]
Hello @deepika134 
I am facing this issue on the web as well. I am using flutter 3.3.4
<img width="650" alt="image" src="https://user-images.githubusercontent.com/56479665/194612905-08ca8480-c4b4-4a56-8f2f-1821deac0351.png">

**Comment by deepika134** [comment]
Hi @Abhishek01039 ,
We tried to replicate the issue with provided details, but the PDF loaded properly without any exception in our side. We have attached the sample for your reference which can be downloaded from the attachment. If you still reproduce the reported issue in your use case, then kindly share the modified issue reproducing in sample and also, please share the following details, to reproduce the reported issue on our end.

- Platforms in which the issue is reproduced (Android, iOS, Web, macOS).
- Device Specification.
- Flutter Doctor log.
- syncfusion_flutter_pdfviewer package version.
- Flutter SDK version.
- Issue reproducing steps.
- Issue reproducing document

This information will be helpful for us to provide you a prompt solution at the earliest.

**Comment by okbye123** [comment]
This will help https://www.youtube.com/watch?v=gAUVz0U7eyA

**Comment by shubhamstrivedi** [comment]
syncfusion_flutter_pdfviewer showing hardware keyboard error in my MACOS while i'm running it on my physical device
![Uploading Screenshot 2024-04-05 at 9.12.16 AM.png…]()
