### ISSUE TITLE
Cache problem.

### ISSUE THREAD

**Issue by IvanSidiq** [syncfusion/flutter-widgets#812]
There is a problem where every time I open a pdf file, cache memory getting bigger.  
It turns out that PdfViewer creates cache each time I open the file. 
I use syncfusion_flutter_pdfviewer 20.2.36-beta .

<img width="764" alt="Screen Shot 2022-07-05 at 13 51 44" src="https://user-images.githubusercontent.com/22414849/177268017-7007a85d-3a87-4f3e-9516-102dfb594e6e.png">

I am using CacheManager to create my own cache 
*edit add link: https://pub.dev/packages/flutter_cache_manager
```Dart
Future<void> getFile(String collectionId, String bookUrl) async {
  emit(PdfCacheLoading());
  late File file;
  GetIt.I<CacheManager>().getFileFromCache(collectionId).then((value) {
    if (value != null) {
      file = value.file;

      emit(PdfCacheSuccess(file));
    } else {
      GetIt.I<CacheManager>()
          .downloadFile(getEbook(bookUrl), key: collectionId)
          .then((value) {
        file = value.file;
        emit(PdfCacheSuccess(file));
      });
    }
  });
}
```

and this is the code I use on opening pdf
```Dart
return SfPdfViewer.file(
  state.file,
  controller: controller,
  key: pdfViewerKey,
  onDocumentLoaded: (d) {
    controller.jumpToPage(startingPage);
    bookmarks = d.document.bookmarks;
  },
  onPageChanged: (p) async {
    if (userId.isNotEmpty) {
      sCubit.savePageToLocal(
          userId: userId,
          colId: collectionId,
          page: p.newPageNumber);
    }
  },
);
```

Is there a way to programmatically disable the cache?,
or is there other way to fix this? 

Thank you.

**Comment by deepika134** [comment]
Hi @IvanSidiq ,

We can reproduce the reported issue on our side and will update the details on July 12, 2022.

Regards,
Deepika Ravi

**Comment by deepika134** [comment]
Hi @IvanSidiq ,

We have confirmed that the issue “Cache memory gets bigger when you load a PDF in SfPdfViewer” is a defect and logged a defect report for this issue. The fix for the same will be included in our upcoming weekly NuGet release which is expected to be published on July 26, 2022.
The status of this issue can be tracked using the following link
https://www.syncfusion.com/feedback/36340/cache-memory-gets-bigger-when-you-load-a-pdf-in-sfpdfviewer

Regards
Deepika R

**Comment by deepika134** [comment]
Hi @IvanSidiq,

We have included the fix for this issue "Cache memory gets bigger when you load a PDF in SfPdfViewer" in our latest weekly NuGet release, so kindly upgrade to the latest version v20.2.40 to get the issue resolved. 

Package link: https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/20.2.40-beta    

Regards,
Deepika R

**Comment by IvanSidiq** [comment]
Hi @deepika134 

We would like to thank you and your team for the hard work you have put into this issue.
We have upgraded the package to the latest version and the issue is now solved.
May success always be with you.

Regards, 
Ivan Sidiq
