### ISSUE TITLE
FunnelChart Legend is reversed

### ISSUE THREAD

**Issue by AliEasy** [syncfusion/flutter-widgets#827]
Hi
My problem:
The legend list is reversed on FunnelChart: first item in legend list is related to the last (bottommost) item in funnel chart.

Any idea how to fix it

![Screenshot_20220723-152605.jpg](https://user-images.githubusercontent.com/45623453/180602233-32828466-5778-4e97-9f8b-9b315ddd5ab8.jpg)

**Comment by SriramKiranSenthilkumar** [comment]
Hi @AliEasy,

We would like to let you know that the rendering behavior of the funnel chart is that the categories or data points will get stacked from bottom to top and, thus, their corresponding legend items will be rendered accordingly.

We suggest you try a [Pyramid chart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfPyramidChart-class.html), which may meet your requirements because its data points will get stacked from top to bottom.

Please get back to us if you need further assistance with this.

Regards,
Sriram Kiran

**Comment by AliEasy** [comment]
Thanks for your reply.
In case of using Pyramid chart, how do I get the rectangle part?!

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @AliEasy,

There is no option to draw the rectangle portion in the Pyramid chart. We have created a feature request for reordering the legend items, you can track the status of the "legend reordering" feature using the following link.

Feedback: https://www.syncfusion.com/feedback/28350

Regards,
Yuvaraj.

**Comment by AliEasy** [comment]
Appreciate it

**Comment by AliEasy** [comment]
Feature is not added yet!
