### ISSUE TITLE
[syncfusion_flutter_pdfviewer] build null safety error

### ISSUE THREAD

**Issue by cheenbee** [syncfusion/flutter-widgets#833]
flutter version: 2.10.5

syncfusion_flutter_pdfviewer: ^20.2.40-beta

/usr/local/flutter/.pub-cache/hosted/pub.flutter-io.cn/syncfusion_flutter_pdfviewer-20.2.40-beta/lib/src/pdfviewer.dart:959:29: Error: Method 'addObserver' cannot be called on 'WidgetsBinding?' because it is potentially null.
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/usr/local/flutter/packages/flutter/lib/src/widgets/binding.dart').
package:flutter/…/widgets/binding.dart:1
Try calling using ?. instead.
    WidgetsBinding.instance.addObserver(this);
                            ^^^^^^^^^^^
/usr/local/flutter/.pub-cache/hosted/pub.flutter-io.cn/syncfusion_flutter_pdfviewer-20.2.40-beta/lib/src/pdfviewer.dart:1046:16: Error: Method 'clear' cannot be called on 'ImageCache?' because it is potentially null.
- 'ImageCache' is from 'package:flutter/src/painting/image_cache.dart' ('/usr/local/flutter/packages/flutter/lib/src/painting/image_cache.dart').
package:flutter/…/painting/image_cache.dart:1
Try calling using ?. instead.
    imageCache.clear();
^^^^^
/usr/local/flutter/.pub-cache/hosted/pub.flutter-io.cn/syncfusion_flutter_pdfviewer-20.2.40-beta/lib/src/pdfviewer.dart:1066:29: Error: Method 'removeObserver' cannot be called on 'WidgetsBinding?' because it is potentially null.
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/usr/local/flutter/packages/flutter/lib/src/widgets/binding.dart').
package:flutter/…/widgets/binding.dart:1
Try calling using ?. instead.
    WidgetsBinding.instance.removeObserver(this);
                            ^^^^^^^^^^^^^^

**Comment by deepika134** [comment]
Hi cheenbee,

Kindly upgrade to the latest version of Flutter SDK and Syncfusion Flutter PDFViewer to get the issue resolved. Please try this and let us know if the issue is resolved or not.

Flutter SDK setup link for the latest version: https://docs.flutter.dev/get-started/install/windows#get-the-flutter-sdk 

Syncfusion Flutter PDFViewer link for the latest version: https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/20.2.40-beta 

Regards,
Deepika Ravi
