### ISSUE TITLE
I can't custom footer widget

### ISSUE THREAD

**Issue by SunryTeang** [syncfusion/flutter-widgets#84]
i want to custom footer widget

**Comment by SriramKiranSenthilkumar** [comment]
Hi @SunryTeang,

Greetings from Syncfusion. We have analyzed your query at our end and as we are exactly sure on the query you have propsed, we kindly request you to share us with more information on which Syncfusion flutter widget you need custom footer widget so that it will be helpful in providing the solutions sooner.

Regards,
Sriram Kiran
