### ISSUE TITLE
[syncfusion_datagrid 19.4.42-beta] fit height datagrid with content

### ISSUE THREAD

**Issue by datpt11** [syncfusion/flutter-widgets#842]
I'm having a problem when the row is too small (less than 5), there will be an extra space
<img width="352" alt="Screen Shot 2022-08-06 at 16 06 30" src="https://user-images.githubusercontent.com/48908789/183242689-c3c35cc2-7560-4747-9ec0-77dcf39617cd.png">

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @datpt11,

We suspect that you are trying to autofit the row height based on the content. As per your requirement, you can achieve it by setting the **autoFitPadding** as **zero** in the **GridColumn**. It removes the default padding for the rows and the height is set based on its content. We have prepared the sample for that. Please check the following code snippet and sample.

```dart
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: const Text('Flutter SfDataGrid'),
        ),
        body: SfDataGrid(
            source: _employeeDataSource,
            onQueryRowHeight: (details) {
              return details.getIntrinsicRowHeight(details.rowIndex);
            },
            columns: [
              GridColumn(
                  columnName: 'id',
                  autoFitPadding: EdgeInsets.zero,
                  label: Container(
                      alignment: Alignment.center, child: const Text('ID'))),
              GridColumn(
                  columnName: 'name',
                  autoFitPadding: EdgeInsets.zero,
                  label: Container(
                      alignment: Alignment.center, child: const Text('Name'))),
              GridColumn(
                  columnName: 'designation',
                  autoFitPadding: EdgeInsets.zero,
                  label: Container(
                      alignment: Alignment.center,
                      child: const Text('Designation'))),
              GridColumn(
                  columnName: 'salary',
                  autoFitPadding: EdgeInsets.zero,
                  label: Container(
                      alignment: Alignment.center,
                      child: const Text('Salary'))),
            ]));
  }
}

```

Sample Link: https://www.syncfusion.com/downloads/support/directtrac/general/ze/sample-1041929070 

 
![image](https://user-images.githubusercontent.com/93904422/183414081-3df5d5c5-3054-416d-ae74-ff657f3dea0f.png)


Also, we have already provided examples in our UG documentation. Please go through this,

UG Document: https://help.syncfusion.com/flutter/datagrid/row-height-customization#fit-the-row-height-based-on-its-content 

We hope this helps. In case we misunderstood your requirement, please provide more specific or clear use case details. It will be helpful for us to check on it and provide you with the solution at the earliest.

Regards,
Tamilarasan

**Comment by datpt11** [comment]
<img width="348" alt="Screen Shot 2022-08-08 at 20 26 25" src="https://user-images.githubusercontent.com/48908789/183429300-6cdd0313-ae8c-4803-b98a-6a6f4616c19d.png">
I have 2 tables in one view, when the item is too few, there will be a space

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @datpt11,

By default, the parent height is set as the DataGrid height, and the rows will be rendered based on the height of the DataGrid. We suspect you’re loading the **DataGrid** as a child of the **Column** or **ListView** widget. In that case, the DataGrid gets a height of infinity since the Column/ ListView height is infinite. We set the DataGrid default height as 300 if the DataGrid gets the height as infinite. It's the behavior of DataGrid. If you have less than five rows, then empty space has been shown at the end of the DataGrid for the remaining height.

You can achieve your requirement by setting the **shrinkWrapRows** property to **true**. It sets the height based on the number of rows available in the DataGrid. We have prepared a sample for that. In that sample, we set the **shrinkWrapRows** to true for the **first DataGrid**. Please check the following code snippet and sample.

```dart
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Flutter SfDataGrid'),
      ),
      body: Column(
        children: [
          SfDataGrid(
              source: _employeeDataSource,
              shrinkWrapRows: true,
              columns: getColumns),
          SfDataGrid(source: _employeeDataSource, columns: getColumns),
        ],
      ),
    );
  }
}

```

Sample Link: https://www.syncfusion.com/downloads/support/directtrac/general/ze/sample846223810 

![image](https://user-images.githubusercontent.com/93904422/183610912-415cfa58-877b-4622-a454-9176b3c8de8c.png)


Also, we have already provided examples in our UG documentation. Please go through this,

UG Document: https://help.syncfusion.com/flutter/datagrid/scrolling#set-height-and-width-of-datagrid-based-on-rows-and-columns-available 

We hope this helps. Please let us know if you require any further assistance on this.

Regards,
Tamilarasan

**Comment by datpt11** [comment]
thanks for your support
