### ISSUE TITLE
How to make the prompt box display custom text

### ISSUE THREAD

**Issue by devyueyue** [syncfusion/flutter-widgets#863]
tooltipShape  ，How to display custom text

**Comment by devyueyue** [comment]
syncfusion_flutter_sliders 20.2.45

**Comment by SriramKiranSenthilkumar** [comment]
Hi @devyueyue,

Greetings from Syncfusion.
We have checked your query at our end, and we would like to let you know that to render custom text in the slider’s tooltip, you can use the [tooltipTextFormatterCallback](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfRangeSlider/tooltipTextFormatterCallback.html) available in SfSlider. We have also appended the user guide documentation for tooltipTextFormatterCallback ​below.

https://help.syncfusion.com/flutter/slider/tooltip#tooltip-text-format

Please check and get back to us if you require further assistance.

Regards,
Sriram Kiran

**Comment by devyueyue** [comment]
SfSlider(
                value: _value,
                interval: 1,
                min: 1.0,
                stepSize: 1,
                max: countList.length.toDouble(),
                showLabels: true,
                enableTooltip: true,
                shouldAlwaysShowTooltip: true,
                activeColor: CourseTheme.COLOR_3470DD,
                inactiveColor: CourseTheme.COLOR_EFF4FE,
                minorTicksPerInterval: 0,
                onChanged: (v) {
                  if (!canClick) {
                    return;
                  }
                  _bloc.mLevelMap[index] = v;
                  _bloc.allQuestionController.sink.add(_bloc.mLevelMap);
                })
                
![20220828-144819](https://user-images.githubusercontent.com/96807013/187061440-8edfdd27-f74f-4a4c-ba7d-eefa6c1de350.png)


In this effect, the text in the prompt box is not a date, but a Chinese character or an English word！

**Comment by devyueyue** [comment]
Ok, Thank you.


 How to remove the space between the left and right sides of the progress bar?

**Comment by devyueyue** [comment]
How to modify the color of the pop-up box？
![20220828-144819](https://user-images.githubusercontent.com/96807013/187067957-eb74af1b-4835-4c4d-bdff-d703a4ea2d81.png)

**Comment by SriramKiranSenthilkumar** [comment]
Hi Team,

We have checked your queries and provided the responses below.

Query 1: How to remove the space between the left and right sides of the progress bar?

We are sorry that we are not sure on what space you are proposing in your query to be removed between the left and right sides of slider. So, we kindly request you to share with us more information in detail regarding your requirement and if possible, please explain to us with an example screenshot of which space you need to remove so that it will help us assist you in a better way.

Query 2: (How to modify the color of the pop-up box?)

For modifying the style and color of the SfSlider widget, you must wrap the widget inside the [SfSliderTheme](https://pub.dev/documentation/syncfusion_flutter_core/latest/theme/SfSliderTheme-class.html) widget, and you can use the [tooltipBackgroundColor](https://pub.dev/documentation/syncfusion_flutter_core/latest/theme/SfSliderThemeData/tooltipBackgroundColor.html) property available in the [SfSliderThemeData](https://pub.dev/documentation/syncfusion_flutter_core/latest/theme/SfSliderThemeData-class.html) to modify the color of the tooltip. We have also appended the user guide documentation below for reference.

https://help.syncfusion.com/flutter/slider/tooltip#tooltip-color

Please check and get back to us if you require further assistance.

Regards,
Sriram Kiran
