### ISSUE TITLE
[syncfusion_flutter_pdfviewer] library have work lagging between scroll up and down on PDF page

### ISSUE THREAD

**Issue by kullawattana** [syncfusion/flutter-widgets#866]
When I read the file from the server, save the file to storage and use this function for reading PDF. 
```
body: SfPdfViewer.file(
        File(args.uri.toString()),
        canShowPaginationDialog: false,
        canShowScrollHead: false,
        canShowScrollStatus: false,
      ),
```
After scrolling the PDF up and down, It's lagging. I'm not sure what happened.

**Comment by deepika134** [comment]
Hi Suttipong Kullawattana,

Kindly confirm us, if you are reported this issue, when scrolling the page up and down the PDF pages takes more time to rendering in SfPdfViewer and also share the issue reproducing video.

Regards,
Deepika Ravi

**Comment by kullawattana** [comment]
I have attached the file to you for reproducing between the transition page and loading data to display PDF.  
I try to scroll quickly. I wait time to display PDF. 

https://user-images.githubusercontent.com/3391151/187368775-7b1da4a7-27f9-4eac-b4df-5dacb09be0ca.mov

**Comment by kullawattana** [comment]
And I have another issue with loading PDF. Can you adjust the PDF loading time to be faster? Because I have to wait for the PDF to finish loading for 1-2 seconds before displaying.

**Comment by kullawattana** [comment]
And I have another issue with loading PDF. Can you adjust the PDF loading time to be faster? Because I have to wait for the PDF to finish loading for 1-2 seconds before displaying.

**Comment by deepika134** [comment]
Hi @kullawattana ,

We retrieve the PDF pages from the native platform renderer and loaded those pages in our Flutter PDF Viewer only based on the virtualization, that is initially 3 pages will be rendered and on-demand scrolling rest of the pages will be rendered and this causes the delay (approx. 1 second) on displaying the pages while performing page transition. So, we couldn't reduce the time any further on displaying the pages. In this case, can we show the loading indicator until the pages are displayed in our PdfViewer so that it would be meaningful that the pages are still loading. Will this solution meet your requirement?

Regards,
Deepika Ravi
