### ISSUE TITLE
Null check operator using on null values  in synfusion pie chart 

### ISSUE THREAD

**Issue by gopibathini** [syncfusion/flutter-widgets#868]
Getting this issue not all time but at some random time 
![pie_chart_null_issue](https://user-images.githubusercontent.com/89006280/187444246-77635edc-c3fa-4e05-9383-a103be060981.PNG)

here i can see the legends and  labels  data clearly but not able to see pie chart . Pie chart showing without circle .

syncfusion version :syncfusion_flutter_charts: ^19.4.56

**Comment by sfHariHaraSudhan** [comment]
Hi @gopibathini,

Kindly check with the latest version of the [syncfusion_flutter_charts: ^21.2.10.](https://pub.dev/packages/syncfusion_flutter_charts/versions/21.2.10)
If the issue is repeated in the latest version also, kindly share us the code snippets and the data points that you have used. We suspect that you may have provided empty points to the data points, so share the required details to replicate the same exact issue. 

Regards,
Hari Hara Sudhan. K
