### ISSUE TITLE
NumericAxis maximumLabels option seems to be ignored

### ISSUE THREAD

**Issue by ominibyte** [syncfusion/flutter-widgets#88]
I want to control the maximum number of labels that shows on the Y-axis. I saw the `maximumLabels` property which I set but it does nothing at all.

So, I want to know if that is what it is supposed to do or what property can I use to achieve this?

Thanks.

**Comment by SriramKiranSenthilkumar** [comment]
Hi @ominibyte,

Greetings from Syncfusion. we have analyzed your query at our end and we would like to share some information regarding the  **maximumLabels** property of the chart axis available in our chart widget. The **maximumLabels** property can be used to customize the number of labels that needs to be present within each 100 logical pixels in an axis. For example, if your y-axis is 300 pixels long and if you set the **maximumLabels** property value as '3' then there will be a total of 9 axis label gets rendered along the y-axis. Currently, this is the default behaviour of this property. 

In order to control the number of axis labels in the chart axis, you can use the **maximum**, **minimum**, and **interval** properties of an axis as per your requirement in the chart.

For further reference on the **maximumLabels**, **maximum**, **minimum**, and **interval** properties of an axis, please check the user guide below.
- **maximumLabels** - https://help.syncfusion.com/flutter/cartesian-charts/axis-customization#maximum-number-of-labels-per-100-logical-pixels
-  **maximum** & **minimum** - https://help.syncfusion.com/flutter/cartesian-charts/axis-types#customizing-range
- **interval** - https://help.syncfusion.com/flutter/cartesian-charts/axis-types#customizing-interval

Please get in touch with us if you would require further assistance.

Regards,
Sriram Kiran
