### ISSUE TITLE
SfCartesianChart- Trackball-changing event with ActivationMode.singleTap is too sensitive

### ISSUE THREAD

**Issue by agoldm** [syncfusion/flutter-widgets#887]
Hi, 
My current chart actives trackball-changing events every single **touch** among the chart. It means that every scrolling touch on the screen where the chart appears makes the trackball appear too, and also means the trackball to appear even when the _share_ bottom sheet is on, which is unacceptable. 
The long-press option is not good for me either, because it is **too** long, and I don't know what else can be helpful for me. Any suggestions?

**Comment by SriramKiranSenthilkumar** [comment]
Hi @agoldm,

Greetings from Syncfusion.
We have validated your queries and provided the responses below.
Query - 1: **My current chart actives trackball-changing events every single touch among the charts. It means that every scrolling touch on the screen where the chart appears makes the trackball appear too.**
We have validated the above query and we would like to let you know that the trackball with activation mode set to **singleTap** will get activated when tapping down on the chart and then performing a scrolling gesture. This is the current default behaviour as the tap-down listener listens for the tap-down gesture and once the tap-down is performed it activates the trackball. For this case, we suggest using a different activation mode for the trackball.

Query - 2: **It also means the trackball to appear even when the share bottom sheet is on and the user touches the chart behind, which is unacceptable.**
We have analyzed the above query, and we are not able to understand what you have proposed in this query. So, we kindly request you to share with us more information on your requirement in detail along with example screenshots or recordings so that it will help us assist you in a better way.

Regards,
Sriram Kiran

**Comment by agoldm** [comment]
Hi @SriramKiranSenthilkumar, 
Thanks for answering and willing to help. 
I think I should be more precise.
I mean that currently I use the **singleTap** activation mode, but it is too sensitive. I don't even need to tap and the trackball appears. Touch is enough, and that's not what I need. That's why I mentioned above the **longPress** mode also because neither it nor any other activation mode is what I need. 
What I describe in query 2 is also a result of all the above.

**Comment by SriramKiranSenthilkumar** [comment]
Hi @agoldm,

We have validated your query at our end, and we would like to let you know that currently the trackball will get activated on tap down itself. This is the current default behavior of trackball and as far as we checked, there is no feasible workaround to achieve your requirement. Sorry for the inconvenience.

For your case, as mentioned earlier we suggest using a different activation mode for the trackball.

Regards,
Sriram Kiran
