### ISSUE TITLE
Update fast line series chart with array.

### ISSUE THREAD

**Issue by corteXnzt** [syncfusion/flutter-widgets#888]
Hello, I'm currently using the fast line series and update graph function. I need to render data points 1000 samples per second. The problem is the rendering is so slow. 

I received 10 int16  variables  (20 bytes)  in array format every 10ms from a BLE device.  When I turn off the graphing part I can achieve getting the samples on the stream but when I turn on the graphing part the data input receives slows down even though its on a stream which run on asynchronous as per flutter docs. 

Is their a way to update the chart with array so I wont need to do for loop adding one data points one by one? TIA

**Comment by SriramKiranSenthilkumar** [comment]
Hi @corteXnzt,

Greetings from Syncfusion.

We have validated your query at our end and we suggest you use the [updateDataSource](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeriesController/updateDataSource.html) public method with which you can process newly added, deleted or updated data points in the chart dynamically instead of processing all the data points. Based on your query we have created a simple sample in which we have added a timer which adds 10 data points per second chart data for fast line series and updated the chart using the **updateDataSource** method. we have attached the sample and user guide documentation link for **updateDataSource** method below for reference.

https://help.syncfusion.com/flutter/cartesian-charts/methods#updatedatasource


Sample - [i407349.zip](https://github.com/syncfusion/flutter-widgets/files/9598445/i407349.zip)

Also, if the above solution is not feasible at your end, then kindly please revert us with more information regarding your requirement in detail along with code snippets or samples so that it helps us assist you in a better way.

Regards,
Sriram Kiran

**Comment by corteXnzt** [comment]
Hello @SriramKiranSenthilkumar 

After going through your sample code I noticed that my code draws the graph even though the updateSource is commented out. Found out that the stream builder for ble data rebuilds the whole UI everytime a new data is received. Refactored my code and its runs smoothly at 1kHz sampling rate from BLE  with 10 values per 10ms. Thank you very much.
