### ISSUE TITLE
XAxis label not starting value from 0 index from graph's list

### ISSUE THREAD

**Issue by sagarstackapp** [syncfusion/flutter-widgets#894]
Hey, Developers

I'm using the last 14 days' data to show in a graph and my list starts from the date 7th September 2022 to 21st September 2022. But I am only getting graphs for Sep 8 to Sep 22. 

Can you please check the attached document and sort it out?

![Screenshot 2022-09-22 at 4 06 17 PM](https://user-images.githubusercontent.com/85110792/191725636-569f9ba8-cc89-4b78-a79e-bc5cae758aa4.png)

**Comment by SriramKiranSenthilkumar** [comment]
Hi Team,

Greetings from Syncfusion.
We have checked your query at our end, and we have created a simple sample by referring to the provided screenshot by adding data points from sept 7 to sept 22 and while rendering, we found that the datetime axis rendered properly at our end from Sep 7 till Sept 22. To ensure from our side, we have also attached the screenshot along with the sample used in test phase.
 
![image](https://user-images.githubusercontent.com/63577117/191939918-aa0e52ce-9093-40c9-ba68-9436aa5fe4dd.png)

So, we kindly request you to try to replicate the reported issue in the below attached sample and share with us so that it will help us assist you in a better way.

Sample - [test_sample.zip](https://github.com/syncfusion/flutter-widgets/files/9632775/i408565.zip)

Regards,
Sriram Kiran
