### ISSUE TITLE
To Image chart widget

### ISSUE THREAD

**Issue by gtuceturan** [syncfusion/flutter-widgets#918]
Hello i use page view my charts in second page and ı show this page all data charts but when ı click first page ı want to Image How can do it ?

When to image run is throws !debugNeedsPaint error and ı use with visibility false the same error

**Comment by SriramKiranSenthilkumar** [comment]
Hi @gtuceturan,

We have checked your query at our end, and we are sorry that we are not able to understand what you’re proposing as your requirement. We suspect that you are using page view with two pages and on the second page, you have all the charts then when navigating to the first page you want the charts rendered on the second page to be exported to the image and displayed on the first page. Kindly confirm whether this is your exact requirement and if not then we kindly request you to share more information on your requirement in detail along with screenshots/screen recordings so that it will help us in further analysis to assist you in a better way.
 
Regards,
Sriram Kiran

**Comment by gtuceturan** [comment]
Hello @SriramKiranSenthilkumar  yes I use Pageview and It has 4 page I use charts in 2. page but I want to show all page in first page button But I just take second page when click button  in first page I has debugNeedsPaint error

**Comment by gtuceturan** [comment]
Actuaaly ı want use chart view in pdf But I couldn't find any way 
  I use this link https://help.syncfusion.com/flutter/cartesian-charts/export-cartesian-chart

**Comment by PraveenGopalsamy** [comment]
Hi @gtuceturan ,

We have checked your query on our end. The mentioned issue was raised due to invoking the [toImage()](https://api.flutter.dev/flutter/rendering/RenderRepaintBoundary/toImage.html#:~:text=toImage%20method%20Null%20safety&text=Capture%20an%20image%20of%20the,object%2C%20multiplied%20by%20the%20pixelRatio%20.) method during the chart painting. To resolve this issue, please invoke the [toImage()](https://api.flutter.dev/flutter/rendering/RenderRepaintBoundary/toImage.html#:~:text=toImage%20method%20Null%20safety&text=Capture%20an%20image%20of%20the,object%2C%20multiplied%20by%20the%20pixelRatio%20.) method after the chart rendering using the [addPostFrameCallback()](https://api.flutter.dev/flutter/scheduler/SchedulerBinding/addPostFrameCallback.html). We have attached the sample for your reference. Please let us know if you face any issues with it. 

Also, we are validating your query "I want use chart view in pdf But I couldn't find any way" at our end and we will update further details in one business day(11 October 2022).

**Attachment:** [i411753.zip](https://github.com/syncfusion/flutter-widgets/files/9746912/i411753.zip)

Regards,
Praveen G.

**Comment by PraveenGopalsamy** [comment]
Hi @gtuceturan ,

We have created a sample for exporting the chart image as a PDF for your reference. Please check it and let us know if you face any issues with it.

We have also appended the following user guide documentation links to know more about exporting and saving images into a PDF.
* Export images to PDF - https://help.syncfusion.com/flutter/pdf/working-with-images
* Save and open PDF - https://help.syncfusion.com/flutter/pdf/getting-started#save-and-open-a-pdf-document-in-mobile

<img src="https://user-images.githubusercontent.com/83585210/195088351-b7aea161-f0b8-47b6-856f-7f3b5eca1ccc.gif" width="250">

**Attachment:** [i411753_flutter_charts_to_pdf.zip](https://github.com/syncfusion/flutter-widgets/files/9755007/i411753_flutter_charts_to_pdf.zip)

Regards,
Praveen G.

**Comment by tuceturan** [comment]
Hello @PraveenGopalsamy ,

I reviewed the code and pages in the example but You use in same page state  and your first step show two graphs page and back  first convert to pdf .

I created key for chart and use page params 

PageView(
        children: [
          OneReportBarGraphPage(key:chartKey),
         ...

but this export just when I go second page and back first page I must show the graph but I want to export pdf not show other pages.

I want to export when user open first page and click pdf I couldn't  see

**Comment by SriramKiranSenthilkumar** [comment]
Hi Team,

We have checked your query at our end, and we are sorry that we are not able to understand your exact requirement in your proposed query. So, we kindly request you to share us with more information on your requirement in detail along with code snippets, example screenshots, or screen recordings and if possible, kindly try to replicate your scenario in the below-attached sample and revert us so that it will help in further analysis in order to assist you in a better way.

Sample: [sample.zip](https://github.com/syncfusion/flutter-widgets/files/9849973/i411753_flutter_charts_to_pdf.zip)


Regards,
Sriram Kiran

**Comment by tuceturan** [comment]
https://user-images.githubusercontent.com/47599661/197505531-c4b2d4bf-f252-47a0-a489-97a690c83429.mp4



I uploaded video .

First Step click report and show 1 page  and show second page  after go back first page click pdf it runs no problem
but when I click report open first page and click pdf report imageBytes is null how can handle ? 

Soo 

When the page is opened for the first time, the result returns null when the user presses the pdf export button on the 1st page.
Problem occurs when user wants to see pdf without viewing 2nd page

**Comment by PraveenGopalsamy** [comment]
Hi @gtuceturan ,

We have analyzed your shared clip at our end and regret to say that we don't have direct support to export the chart to an image without rendering it to the screen. However, we have achieved your requirement at the sample level by referring to the following links and attached the sample for your reference.

**​Demo:**
<img src="https://user-images.githubusercontent.com/83585210/198030511-b39863e3-a7ef-499d-a6f7-965f79fd7c6b.gif" width="300">

**Reference links:**
﻿﻿* https://github.com/flutter/flutter/issues/40064#issuecomment-620081426
﻿﻿* https://stackoverflow.com/questions/55134343/renderrepaintboundary-to-image-without-adding-widget-to-screen

**Attachment :** [i411753_flutter_charts_to_pdf.zip](https://github.com/syncfusion/flutter-widgets/files/9869556/i411753_flutter_charts_to_pdf.zip)

We hope the above solution will fulfill your requirement. Please let us know if you require further assistance.

Regards,
Praveen G.

**Comment by tuceturan** [comment]
I used your like sample but its shows empty screen

**Comment by tuceturan** [comment]
You have called the graph in the same page as a function within Pageview. However, I am calling different pages within Pageview, such as calling report page 1 and report page 2 in report1 page. Is this possible?

**Comment by tuceturan** [comment]
I execute your project not showing  pdf and I applied your method in my project .There is an error Unhandled Exception: Exception: Invalid image dimensions. can you help?
