### ISSUE TITLE
gradle Exception occcured when I run the project

### ISSUE THREAD

**Issue by mohammad7hosein** [syncfusion/flutter-widgets#924]
when I run the project get this error:

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':syncfusion_flutter_pdfviewer'.
> Could not resolve all files for configuration ':syncfusion_flutter_pdfviewer:classpath'.
   > Could not find com.android.tools.build:gradle:3.5.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.5.0/gradle-3.5.0.pom
       - https://jcenter.bintray.com/com/android/tools/build/gradle/3.5.0/gradle-3.5.0.pom
     Required by:
         project :syncfusion_flutter_pdfviewer
> Failed to notify project evaluation listener.
   > Could not get unknown property 'android' for project ':syncfusion_flutter_pdfviewer' of type org.gradle.api.Project.
   > Could not get unknown property 'android' for project ':syncfusion_flutter_pdfviewer' of type org.gradle.api.Project.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 25s
Exception: Gradle task assembleDebug failed with exit code 1

what I have do?

**Comment by deepika134** [comment]
Hi @mohammad7hosein ,

We tried to reproduce the reported issue with provided details, but the syncfusion_flutter_pdfviewer is runs properly without any exception on our end. For your reference, we have prepared a sample and it can be downloaded from the following link,

https://www.syncfusion.com/downloads/support/directtrac/general/ze/sample_924-1689555942.zip

Kindly let us know if you are facing the reported issue with this sample. Also, please share the following details, to reproduce the reported issue on our end.

1. Platforms in which the issue is reproduced (Android, iOS, Web, macOS).
2. Device Specification.
3. Flutter Doctor log.
4. syncfusion_flutter_pdfviewer package version.
5. Flutter SDK version.

This information will be helpful for us to provide you a prompt solution at the earliest.

Regards,
Deepika Ravi
