### ISSUE TITLE
SfCartesianChart Big Data

### ISSUE THREAD

**Issue by tuceturan** [syncfusion/flutter-widgets#957]
Hello,

I'm using SfCartesianChart.
![Screenshot_20221104-165752 1](https://user-images.githubusercontent.com/47599661/199990608-8d674145-0698-4b83-9ec0-0124e1fd7e35.jpg)
I have 240 data 6*79 But Page is loading time so long How can fix that problem. When i use small values there is no big problem but when I use big values is take too much time and black screen My i big data is below;
[ModbusWaveeFormData.xlsx](https://github.com/syncfusion/flutter-widgets/files/9938950/ModbusWaveeFormData.xlsx)

Code :
 SfCartesianChart(
                // title: ChartTitle(text: 'Washington vs New York temperature'),
                key: keyV,
                legend: Legend(
                    isVisible: true,
                    position: LegendPosition.top,
                    textStyle: TextStyle(fontSize: 15)),

                /// API for multiple axis. It can returns the various axis to the chart.
                axes: <ChartAxis>[
                  NumericAxis(
                      title: AxisTitle(
                          text: title1, alignment: ChartAlignment.center),
                      opposedPosition: true,
                      name: 'Voltage',
                      anchorRangeToVisiblePoints: false,
                      placeLabelsNearAxisLine: true,
                      isVisible: true,
                      // majorGridLines: const MajorGridLines(width: 0),
                      labelFormat: '{value}',
                      // minimum: -400,
                      // maximum: 400,
                      interval: 100)
                ],
                primaryXAxis: NumericAxis(
                  majorGridLines: const MajorGridLines(width: 0),
                  isVisible: true,
                  crossesAt: 0,
                  placeLabelsNearAxisLine: false,
                  anchorRangeToVisiblePoints: true,
                  labelFormat: " ",
                  minorTickLines: MinorTickLines(size: 0, width: 0),
                  majorTickLines: MajorTickLines(size: 0, width: 0),
                ),
                primaryYAxis: NumericAxis(
                  title:
                      AxisTitle(text: title2, alignment: ChartAlignment.center),
                  majorGridLines: const MajorGridLines(width: 0),
                  opposedPosition: false,
                  //  minimum: -3,
                  //  maximum: 3,
                  //     interval: 1,
                  interval: 100,
                  labelFormat: '{value}',
                ),
                series: getMultipleAxisLineSeries(),
                tooltipBehavior: TooltipBehavior(enable: true),
                trackballBehavior: TrackballBehavior(
                  enable: true,
                  lineType: TrackballLineType.none,
                  activationMode: ActivationMode.singleTap,
                  // tooltipSettings: const InteractiveTooltip(canShowMarker: false),
                  markerSettings: TrackballMarkerSettings(
                    markerVisibility: TrackballVisibilityMode.visible,
                    height: 10,
                    width: 10,
                    borderWidth: 1,
                  ),
                  tooltipDisplayMode: TrackballDisplayMode.groupAllPoints,
                ),
                zoomPanBehavior: zoomPan)
				
				
 List<ChartSeries<ChartSampleData, dynamic>> getMultipleAxisLineSeries() {
    List<Color> _colorList = [
      Color.fromRGBO(155, 31, 33, 100),
      Color.fromRGBO(255, 103, 106, 100),
      Color.fromRGBO(37, 101, 39, 100),
      Color.fromRGBO(99, 196, 101, 100),
      Color.fromRGBO(55, 104, 155, 100),
      Color.fromRGBO(150, 194, 236, 100)
    ];
    //'VL1', 'VL2', 'VL3','IL1','IL2','IL3'
    //   color: ['#9B1F21', '#256527', '#37689B', '#E1676A', '#63C465','#96C2EC'],
    List<ChartSeries<ChartSampleData, dynamic>> _series = [];
    int j = 0;
    for (int i = 0; i < vaweChartData.length; i++) {
      _series.add(SplineSeries<ChartSampleData, dynamic>(
          dataSource: vaweChartData[i],
          xValueMapper: (ChartSampleData sales, _) => sales.x,
          yValueMapper: (ChartSampleData sales, _) => sales.y,
          yAxisName: 'Voltage',
          name: 'VL' + (i + 1).toString(),
          color: _colorList[j],
          selectionBehavior: SelectionBehavior(enable: true)));
      _series.add(SplineSeries<ChartSampleData, dynamic>(
          dataSource: vaweChartData[i],
          xValueMapper: (ChartSampleData sales, _) => sales.x,
          yValueMapper: (ChartSampleData sales, _) => sales.secondSeriesYValue,
          yAxisName: 'Current',
          name: 'IL' + (i + 1).toString(),
          color: _colorList[j + 1]));
      j += 2;
    }
    return _series;
  }

**Comment by LokeshPalani** [comment]
Hi @tuceturan,

We have checked your query and you can achieve your requirement by removing the [interval](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/interval.html) property from the Axis. When using low [interval](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/interval.html) with large amounts of data, the [MajorGridLines](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/MajorGridLines-class.html) are also rendered, which can cause the chart to take a long time to load. We hope that the information we have provided will resolve your issue. If getting the same issue, please get back to us. Additionally, we have shared key points to improve the performance of the chart. Please refer to them below.

The following are the key points that can be used to boost the performance of the chart when there is a need to plot high volume data.

- Load and store the required data points in the initState method itself, and then set the data points to the chart series.

- Use [NumericAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/NumericAxis-class.html) or [DateTimeAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeAxis/DateTimeAxis.html) instead of [CategoryAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CategoryAxis/CategoryAxis.html).

- When there are large number of points to load in line series, you can use [FastLineSeries](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/FastLineSeries-class.html) series instead of [LineSeries](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/LineSeries-class.html).

- Instead of enabling data markers and labels when there are large number of data points, you can use [Trackball](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/trackballBehavior.html) to view the point information.

- Set series [animationDuration](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianSeries/animationDuration.html) as 0 to disable the animation while loading large number of data points.

- Use [updateDataSource](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeriesController/updateDataSource.html) method while updating dynamic data points instead of calling setState. For more details refer ug -  https://help.syncfusion.com/flutter/cartesian-charts/methods#updatedatasource.

Use On-demand loading while rendering large data points, it can be used to load more data to the chart when the visible range reaches the end on dragging in the chart.  https://help.syncfusion.com/flutter/cartesian-charts/on-demand-loading


Regards,
Lokesh.
