### ISSUE TITLE
[syncfusion_flutter_pdf] PDFBrush not respecting transparency when exporting

### ISSUE THREAD

**Issue by theniceboy** [syncfusion/flutter-widgets#958]
When using `page.graphics.drawPath` to draw with `PdfBrushes.transparent`, the exported PDF just show a white stroke. The transparency (alpha channel) is not respected.

**Comment by theniceboy** [comment]
I saw that in 20.3.57 the update notes were: "Alpha channel is not initialized properly in transparent brush is now resolved." However the issue wasn't resolved. Was that update related to this issue? Thanks!

**Comment by irfanajaffer** [comment]
<html>
<body>
<p style="color: rgb(36, 36, 36); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: 11pt; font-family: Calibri, sans-serif; margin: 0px;">The reported "Alpha channel is not initialized properly in transparent brush" was included in Syncfusion weekly release v20.3.57.</p><p aria-hidden="true" style="color: rgb(36, 36, 36); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: 11pt; font-family: Calibri, sans-serif; margin: 0px;"> </p><p style="color: rgb(36, 36, 36); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: 11pt; font-family: Calibri, sans-serif; margin: 0px;">The transparent brush preserves the drawn path in pdf graphics with no color, this is the expected behavior for transparent brush.</p><p aria-hidden="true" style="color: rgb(36, 36, 36); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: 11pt; font-family: Calibri, sans-serif; margin: 0px;"> </p><p style="color: rgb(36, 36, 36); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: 11pt; font-family: Calibri, sans-serif; margin: 0px;">Refer the following code for reference,</p>

![image](https://user-images.githubusercontent.com/93319208/203330790-6b17adcf-78f8-475c-a8a3-909ce81ac905.png)


</body>
</html>
