### ISSUE TITLE
Datagrid - When editing a cell can't focus other textFields.

### ISSUE THREAD

**Issue by Elixell** [syncfusion/flutter-widgets#979]
Hi!

My problem is that if I am currently in a widget's **edit** mode, and trying to click another **TextField** the focus simply not traversing to the newly selected **TextField** and remains in editing mode. Tab shifting is working as expected. The selected textField will have focus but the cell regains focus immediatly. 

The issue is present for sure in windows and web.
My flutter version : Channel beta, 3.6.0-0.1.pre.

Reproducible code: https://gist.github.com/Elixell/a83f98ad75ca23b2e7c04d45c841bf0a

Thank you for your  help!

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @Elixell,

The fix for the reported issue ‘’The focus is not moved to the other widgets when DataGrid's current cell is in editing’’ has been included in the latest DataGrid version **20.3.58**. Update your DataGrid to get the issue resolved.

Pub Link: https://pub.dev/packages/syncfusion_flutter_datagrid/changelog

**Comment by Elixell** [comment]
Thank you for your fast response, it is working as intended now.

**Comment by Elixell** [comment]
Hey! It is working fine without checkboxes enabled but the same issue is back with checkboxes enabled. Reproducible using the latest 20.4.44 version.

**Comment by Elixell** [comment]
After further investigation i found that this is related to checkbox and it's intereference with the column indexes. I will file seperate issues once indentified the root cause.  I will close the issue again.
