### ISSUE TITLE
[syncfusion_flutter_charts] Legend order issue

### ISSUE THREAD

**Issue by miyazk4** [syncfusion/flutter-widgets#984]
Hello,

In my application, I am rendering Charts of multiple series.

I want to show first, the LineSeries legends, and then, the ColumnSeries legends, having the LineSeries 'above' the ColumnSeries', like the following

![imagem](https://user-images.githubusercontent.com/61757484/203032575-4e0546b5-f407-4174-976b-895c32233d31.png)

The problem here is, as mentioned, on the Legend I wanted something like: `Series 1 - Series 2 - Series 0`, but, to achieve that result, the LineSeries would appear below the ColumnSeries,

![imagem](https://user-images.githubusercontent.com/61757484/203033382-9c66c387-bec7-4b36-aeab-e13584dade88.png)

Is there any way, to achieve the same result as Image 1, but with a different order in the display of the Legend Items?

Thank you in advance.

Code source:

```dart 

 series: <CartesianSeries>[
              // Render column series
              ColumnSeries<ChartData, String>(
                  legendIconType: LegendIconType.rectangle,
                  dataSource: chartData,
                  color: Colors.blue,
                  xValueMapper: (ChartData data, _) => data.x,
                  yValueMapper: (ChartData data, _) => data.y),
              LineSeries<ChartData, String>(
                  dataSource: chartData,
                  color: Colors.red,
                  xValueMapper: (ChartData data, _) => data.x,
                  yValueMapper: (ChartData data, _) => data.y),
              LineSeries<ChartData, String>(
                  dataSource: chartData,
                  color: Colors.green,
                  xValueMapper: (ChartData data, _) => data.x,
                  yValueMapper: (ChartData data, _) => data.y1)
            ],

**Comment by SriramKiranSenthilkumar** [comment]
As per the chart behavior, the legend will be rendered based on the series order only. However, we have achieved your requirement using a workaround with the help of the legend builder feature by adding custom widgets in the place of legend items in the required order, but we cannot provide legend toggling support for the series due to legend order change. The workaround sample has been attached below for reference.
![image](https://user-images.githubusercontent.com/63577117/203531291-444c280f-414f-49e9-9a31-19e65507d0b4.png)

Sample: [i421077.zip](https://github.com/syncfusion/flutter-widgets/files/10074827/i421077.zip)
