### ISSUE TITLE
[syncfusion_flutter_charts] Scroll - zoom not working on MacOs with touchpad

### ISSUE THREAD

**Issue by theRealGetman** [syncfusion/flutter-widgets#987]
Scroll - zoom not working on flutter desktop MacOs app with touchpad, but it works with external mouse.
In the same time it works fine with touchpad on Windows laptops.

**Comment by karniv00l** [comment]
Same here on MacBook Pro M1

**Comment by Gvozdik-Darya** [comment]
Same on M1

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @theRealGetman ,

Thanks for your patience.

The reported issue regarding zooming not working on the macOS trackpad has been fixed and rolled out in our weekly patch release. To avoid this please upgrade the chart package to the latest version mentioned below.

Version: https://pub.dev/packages/syncfusion_flutter_charts/versions/20.4.43

We have also noticed the fling is not working in the current flutter due to a breaking change in the flutter framework, we have also reported the issue on the flutter GitHub page and they accept this issue. We have shared the issue link below for your reference.

Issue: https://github.com/flutter/flutter/issues/117881
