### ISSUE TITLE
[syncfusion_flutter_charts] Display LegendItem initially untoggled

### ISSUE THREAD

**Issue by miyazk4** [syncfusion/flutter-widgets#989]
My goal is to when a Chart is rendered the first time, display one of my Legend Items as 'untoggled', like this

![image](https://user-images.githubusercontent.com/61757484/203527756-8cc9855a-d83f-4b9a-b769-7de09ae2e7e5.png)

When investigating and debugging, I got this:

![image](https://user-images.githubusercontent.com/61757484/203524836-3b368fb1-04ed-4fe8-8a2e-f533ac84839a.png)

I am trying to get any information on what is doing this 'toggle' when a legend item is being tapped and, if there is any way to achieve my objective.

**Comment by LokeshPalani** [comment]
The requirement can be met by setting [isVisible](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianSeries/isVisible.html) in SplineSeries to true. When loading the chart for the first time, the respected series (isVisible: false) legend item will be toggled. You can get the Legend items information when toggled using [onLegendTapped](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/onLegendTapped.html) callback. We have shared a sample for your reference below.

**code snippet ;**

```
series: <ChartSeries<ChartSampleData, DateTime>>[
          SplineSeries<ChartSampleData, DateTime>(
            dataSource: data,
            isVisible: false,
            xValueMapper: (ChartSampleData sales, _) => sales.year,
            yValueMapper: (ChartSampleData sales, _) => sales.sales1,
          ),
```

[chart_421568.zip](https://github.com/syncfusion/flutter-widgets/files/10102448/chart_421568.zip)

**Comment by miyazk4** [comment]
> The requirement can be met by setting [isVisible](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianSeries/isVisible.html) in SplineSeries to true. When loading the chart for the first time, the respected series (isVisible: false) legend item will be toggled. You can get the Legend items information when toggled using [onLegendTapped](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/onLegendTapped.html) callback. We have shared a sample for your reference below.
> 
> **code snippet ;**
> 
> ```
> series: <ChartSeries<ChartSampleData, DateTime>>[
>           SplineSeries<ChartSampleData, DateTime>(
>             dataSource: data,
>             isVisible: false,
>             xValueMapper: (ChartSampleData sales, _) => sales.year,
>             yValueMapper: (ChartSampleData sales, _) => sales.sales1,
>           ),
> ```
> 
> [chart_421568.zip](https://github.com/syncfusion/flutter-widgets/files/10102448/chart_421568.zip)

This works in case I just render something like

```dart
legend: Legend(
                orientation: LegendItemOrientation.horizontal,
                position: LegendPosition.top,
                isVisible: true,
                itemPadding: 0,
                alignment: ChartAlignment.near,
                overflowMode: LegendItemOverflowMode.scroll,
              ),

```

But, I am creating my own Legend, using legendItemBuilder,

```dart

Widget legendItemBuilderTest(
    String name, dynamic series, dynamic point, int index) {
  var chartSeries = series as CartesianSeries;
  return Container(
    padding: const EdgeInsets.only(right: 8, bottom: 8),
    child: Row(
      mainAxisSize: MainAxisSize.min,
      mainAxisAlignment: MainAxisAlignment.start,
      children: [
        Container(
          height: 8,
          width: 8,
          decoration: BoxDecoration(
            borderRadius: (series is AreaSeries ||
                series is StackedColumnSeries ||
                series is ColumnSeries)
                ? null
                : BorderRadius.circular(4),
            color: chartSeries.isVisible ? chartSeries.color : Colors.purple,
          ),
          margin: const EdgeInsets.only(right: 8.0),
        ),
        Text('${chartSeries.legendItemText}'),
      ],
    ),
  );

```

By doing so, it renders the SplineSeries despite ```isVisible``` being set to false

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @miyazk4 ,


Your requirement has been achieved by wrapping the legend template inside the GestureDetector widget, then set the visibility of the series on its onTap event based on which legend was tapped. The data source value was then assigned based on visibility, if visibility was false, the data source value was set to be empty; otherwise, it was set to the actual data source value. We have shared the sample below for your requirement.


Screenshot:

<img width="585" alt="Screenshot 2022-12-02 at 4 51 19 PM" src="https://user-images.githubusercontent.com/61863686/205315242-9f9d4715-20b1-4938-b655-13f0af3e7aad.png">


Sample: 
[i421568.zip](https://github.com/syncfusion/flutter-widgets/files/10141870/i421568.zip)





Regards,
Yuvaraj.

**Comment by miyazk4** [comment]
> Hello,
> 
> While testing the sample provided this works.
> 
> The only issue is that, whenever I toggle a Legend Item, there is a flicker in my Chart happening.
> 
> I was reading and, the issue could probably come from the animation (which we are saying that it has a duration of 0, so I believe we can discard that)
> 
> I am aware that by calling setState, it will render whole chart again as well.
> 
> Is there any other way around this?

Also, when testing again the toggle, it sometimes appears as the Legend Item not visible, despite appearing in the Chart
![syncfusion_test2](https://user-images.githubusercontent.com/61757484/205659459-b4a7bc14-7191-4f3a-b2d8-037e651ba36a.gif)

**Comment by Yuvaraj-Gajaraj** [comment]
We already included it in our improvement regarding the flickering of the chart while toggling legend using legend builder. However, your UI appearance is the same as the default legend appearance. Default legend will work for your scenario without any issues.  Hence, we suggest using the default legend instead of the legend builder, and for the legend icon, you can use the [legendIconType](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianSeries/legendIconType.html) property in the series and set the required shape. We have shared the sample below for your reference.


**Screenshot:**

<img width="800" alt="Screenshot 2022-12-13 at 6 32 23 PM" src="https://user-images.githubusercontent.com/61863686/207325945-784fdeef-ebd0-4f7c-bff1-d9be8b5e95e4.png">

**Sample:** 
[i421568.zip](https://github.com/syncfusion/flutter-widgets/files/10218133/i421568.zip)
