### ISSUE TITLE
How to place image to specific pdf page?

### ISSUE THREAD

**Issue by teoprayoga** [syncfusion/flutter-widgets#990]
I had a problem the case is i need to place my signature to specific pdf document. like screenshot below. i tried the docs about insert image, but my signature not place in the page that i want but it show in new page.

![sign](https://user-images.githubusercontent.com/19910443/203688294-f1750c7a-7d75-4d49-ab29-6a82dff1c39d.png)

**Comment by irfanajaffer** [comment]
<html>
<body>
<p style="box-sizing: border-box; margin: 0px; font-size: 14px; font-style: inherit; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: inherit; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; color: rgb(36, 36, 36); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, system-ui, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Web&quot;, sans-serif; text-align: start; background-color: rgb(255, 255, 255);"><span style="box-sizing: border-box; font-size: 11pt; font-style: inherit; font-weight: inherit;">On analyzing your code snippet we found that the issue is with the loading Pages and also you were trying to load image as imagedata.</span></p><p style="box-sizing: border-box; margin: 0px; font-size: 14px; font-style: inherit; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: inherit; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; color: rgb(36, 36, 36); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, system-ui, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Web&quot;, sans-serif; text-align: start; background-color: rgb(255, 255, 255);"><span style="box-sizing: border-box; font-size: 11pt; font-style: inherit; font-weight: inherit;"><br style="box-sizing: border-box;"></span></p><p style="box-sizing: border-box; margin: 0px; font-size: 14px; font-style: inherit; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: inherit; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; color: rgb(36, 36, 36); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, system-ui, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Web&quot;, sans-serif; text-align: start; background-color: rgb(255, 255, 255);"><span style="box-sizing: border-box; font-size: 11pt; font-style: inherit; font-weight: inherit;">​</span><span style="box-sizing: border-box; font-size: 11pt; font-style: inherit; font-weight: inherit;">The Syncfusion Flutter PDF allows you to add, remove and load pages in a PDF document.</span></p><p style="box-sizing: border-box; margin: 0px; font-size: 14px; font-style: inherit; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: inherit; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; color: rgb(36, 36, 36); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, system-ui, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Web&quot;, sans-serif; text-align: start; background-color: rgb(255, 255, 255);"><span style="box-sizing: border-box; font-size: 11pt; font-style: inherit; font-weight: inherit;"><br style="box-sizing: border-box;"></span></p><p style="box-sizing: border-box; margin: 0px; font-size: 14px; font-style: inherit; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: inherit; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; color: rgb(36, 36, 36); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, system-ui, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Web&quot;, sans-serif; text-align: start; background-color: rgb(255, 255, 255);"><span style="box-sizing: border-box; font-size: 11pt; font-style: inherit; font-weight: inherit;">Kindly use the following code snippet to load an existing page and draw an image:</span></p><p style="box-sizing: border-box; margin: 0px; font-size: 14px; font-style: inherit; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: inherit; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; color: rgb(36, 36, 36); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, system-ui, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Web&quot;, sans-serif; text-align: start; background-color: rgb(255, 255, 255);"><span style="box-sizing: border-box; font-size: 11pt; font-style: inherit; font-weight: inherit;"><br style="box-sizing: border-box;"></span></p>

![image](https://user-images.githubusercontent.com/93319208/203794644-e10405c0-089c-48dd-9ace-c1d7c34c489d.png)



<p style="box-sizing: border-box; margin: 0px; font-size: 14px; font-style: inherit; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: inherit; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; color: rgb(36, 36, 36); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, system-ui, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Web&quot;, sans-serif; text-align: start; background-color: rgb(255, 255, 255);"><br class=" empty-paragraph" style="box-sizing: border-box;"></p><p style="box-sizing: border-box; margin: 0px; font-size: 14px; font-style: inherit; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: inherit; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; color: rgb(36, 36, 36); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, system-ui, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Web&quot;, sans-serif; text-align: start; background-color: rgb(255, 255, 255);"><span style="box-sizing: border-box; font-size: 11pt; font-style: inherit; font-weight: inherit;">Kindly refer to the following UG links to know more about pages, images, and signatures,</span></p><p style="box-sizing: border-box; margin: 0px; font-size: 14px; font-style: inherit; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: inherit; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; color: rgb(36, 36, 36); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, system-ui, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Web&quot;, sans-serif; text-align: start; background-color: rgb(255, 255, 255);"><span style="box-sizing: border-box; font-size: 11pt; font-style: inherit; font-weight: inherit;"><br style="box-sizing: border-box;"><a aria-label="Link https://help.syncfusion.com/flutter/pdf/working-with-pages" href="https://help.syncfusion.com/flutter/pdf/working-with-pages" rel="noopener noreferrer" target="_blank" tabindex="-1" class="fui-Link ___m14voj0 f3rmtva f1ern45e f1deefiw f1n71otn f1q5o8ev f1h8hb77 f1vxd6vx f1ewtqcl fyind8e f1k6fduh f1w7gpdv fk6fouc fjoy568 figsok6 f1hu3pq6 f11qmguv f19f4twv f1tyq0we f1g0x7ka fhxju0i f1qch9an f1cnd47f fqv5qza f1vmzxwi f1o700av f13mvf36 f9n3di6 f1ids18y fygtlnl f1deo86v f12x56k7 f1iescvh ftqa4ok f50u1b5 fs3pq8b f1hghxdh f1tymzes f1x7u7e9 f1cmlufx f10aw75t fsle3fq" style="box-sizing: border-box; color: rgb(79, 82, 178); text-decoration: none; background-color: transparent; user-select: auto; text-align: left; font-family: var(--fontFamilyBase); font-weight: var(--fontWeightRegular); border-style: none; cursor: pointer; display: inline; margin: 0px; padding: 0px; overflow: inherit; font-size: inherit;">https://help.syncfusion.com/flutter/pdf/working-with-pages</a><br style="box-sizing: border-box;"><a aria-label="Link https://help.syncfusion.com/flutter/pdf/working-with-images" href="https://help.syncfusion.com/flutter/pdf/working-with-images" rel="noopener noreferrer" target="_blank" tabindex="-1" class="fui-Link ___m14voj0 f3rmtva f1ern45e f1deefiw f1n71otn f1q5o8ev f1h8hb77 f1vxd6vx f1ewtqcl fyind8e f1k6fduh f1w7gpdv fk6fouc fjoy568 figsok6 f1hu3pq6 f11qmguv f19f4twv f1tyq0we f1g0x7ka fhxju0i f1qch9an f1cnd47f fqv5qza f1vmzxwi f1o700av f13mvf36 f9n3di6 f1ids18y fygtlnl f1deo86v f12x56k7 f1iescvh ftqa4ok f50u1b5 fs3pq8b f1hghxdh f1tymzes f1x7u7e9 f1cmlufx f10aw75t fsle3fq" style="box-sizing: border-box; color: rgb(79, 82, 178); text-decoration: none; background-color: transparent; user-select: auto; text-align: left; font-family: var(--fontFamilyBase); font-weight: var(--fontWeightRegular); border-style: none; cursor: pointer; display: inline; margin: 0px; padding: 0px; overflow: inherit; font-size: inherit;">https://help.syncfusion.com/flutter/pdf/working-with-images</a><br style="box-sizing: border-box;"><a aria-label="Link https://help.syncfusion.com/flutter/pdf/working-with-digital-signature" href="https://help.syncfusion.com/flutter/pdf/working-with-digital-signature" rel="noopener noreferrer" target="_blank" tabindex="-1" class="fui-Link ___m14voj0 f3rmtva f1ern45e f1deefiw f1n71otn f1q5o8ev f1h8hb77 f1vxd6vx f1ewtqcl fyind8e f1k6fduh f1w7gpdv fk6fouc fjoy568 figsok6 f1hu3pq6 f11qmguv f19f4twv f1tyq0we f1g0x7ka fhxju0i f1qch9an f1cnd47f fqv5qza f1vmzxwi f1o700av f13mvf36 f9n3di6 f1ids18y fygtlnl f1deo86v f12x56k7 f1iescvh ftqa4ok f50u1b5 fs3pq8b f1hghxdh f1tymzes f1x7u7e9 f1cmlufx f10aw75t fsle3fq" style="box-sizing: border-box; color: rgb(79, 82, 178); text-decoration: none; background-color: transparent; user-select: auto; text-align: left; font-family: var(--fontFamilyBase); font-weight: var(--fontWeightRegular); border-style: none; cursor: pointer; display: inline; margin: 0px; padding: 0px; overflow: inherit; font-size: inherit;">https://help.syncfusion.com/flutter/pdf/working-with-digital-signature</a></span></p>
</body>
</html>

**Comment by teoprayoga** [comment]
Hi thanks for help, now i can edit my specific pdf page.

but now i facing new problem. is there any correct way to detect offset when user tap pdfviewer syncfusion?
![WhatsApp Image 2022-11-29 at 08 13 25](https://user-images.githubusercontent.com/19910443/204407635-f2883cf7-4fc3-4a9e-88f6-0fa3874f1fa7.jpeg)

i tried this to detect offset:
https://github.com/syncfusion/flutter-widgets/issues/235#issuecomment-844222793

but it looks like the image below. the blue what i want, the red is the result using offset above

**Comment by deepika134** [comment]
Find the workaround to add the drawn signature on the tapped location inside the SfPdfViewer,
https://www.syncfusion.com/downloads/support/directtrac/general/ze/digitalsign312358125.zip

Steps to add the signature:

* Draw the signature in the signature pad which is present at the bottom of the page.
* Click "Add Signature" button.
* Then, you may tap on any position in the page to add the drawn signature.

Note: The tapped point will be the added signature's top-left position.

For more reference, please find the video recording of the above-mentioned steps/procedure from the following link,
https://www.syncfusion.com/downloads/support/directtrac/general/ze/signature2096460089.zip

**Achieve More**

In this example project, we have only implemented the logic of adding signature in the continuous page mode and that too only with the default zoom level (100%). By adjusting the page's DX and DY values w.r.t to the page view modes and zoom level, you could also achieve following things at the example application level,

* Adding signature at the appropriate location after zooming.
* Adding signature in the single page view mode and horizontal scrolling mode.
