### ISSUE TITLE
SfCartesianChart conflict with PageView horizontal scroll

### ISSUE THREAD

**Issue by taosimple** [syncfusion/flutter-widgets#994]
Placed SfCartesianChart into PageView, when `SfCartesianChart.TrackballBehavior.activationMode == ActivationMode.singleTap` touch on SfCartesianChart will can't horizontal scroll.
I noticed that `ActivationMode.singleTap` is not just a singleTap , if touch and move also active track ball, it useful in some scene, but can SfCartesianChart add a real single tap mode only active on single tap and not conflict with PageView?

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @taosimple ,

When the activation mode is set to singleTap, the trackball displays with the pointer down. As a result of the conflict between the chart and the PageView gesture, the chart retains the touch gesture instead of the page view while swiping to the next page.

However, You can resolve this issue by setting the trackball activation mode as [doubleTap](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TrackballBehavior/activationMode.html) or [longPress](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TrackballBehavior/activationMode.html).

For more details, please refer the following UG:

https://help.syncfusion.com/flutter/cartesian-charts/trackball-crosshair#activation-mode

Regards,
Yuvaraj.

**Comment by taosimple** [comment]
Hi @Yuvaraj-Gajaraj 
Thanks, i know what you mean, and tried doubleTap, longPress. Is it possible to provide such a single tap? like the button single click, the gesture just recognize point down and up event not move, does this avoid conflict with PageView

**Comment by LavanyaGowtham2021** [comment]
Hi @taosimple ,

Currently there is no option to do with single tap, as we shared earlier please use trackball activation mode as [doubleTap](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TrackballBehavior/activationMode.html) or [longPress](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TrackballBehavior/activationMode.html).

**Comment by LavanyaGowtham2021** [comment]
Please reopen this, if you need any further assistance on this.
